### ISSUE TITLE
Bots seem more laggy after recent updates

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#100]
Could it just be the server, or a change that was made, bots used to be incredibly smooth on the same server, but when watching newly set replays, they appear to stutter a lot more. Everything seems fine on the server D: Sorry for the constant reports

**Comment by shavitush** [comment]
try changing this line

   TeleportEntity(client, fDistance >= 75.0? vecPosition:NULL_VECTOR, vecAngles, vecVelocity);

the number 75 to something else, either lower or higher. let me know what's the best value for you. replay bots are really smooth in my server

**Comment by Technoblazed** [comment]
Tried changing both up and down, neither seems to make a difference,

**Comment by shavitush** [comment]
what's your server's cpu usage?

**Comment by Technoblazed** [comment]
15%

**Comment by Technoblazed** [comment]
https://youtu.be/_XSmDz2dOb8?t=19

**Comment by shavitush** [comment]
oh. this is because of unoptimized old code; the issue shouldn't happen for newer replays

**Comment by Technoblazed** [comment]
The code was taken 10 minutes before this was opened D:

**Comment by shavitush** [comment]
no.. i mean that the issue is because of old replays being saved with an old and unoptimized code that would really shit on the server's performance

**Comment by Technoblazed** [comment]
Yeah, but it was a new record as well

**Comment by Technoblazed** [comment]
I wiped all bots after the updated code, it's just a test server, was a completely fresh bot

**Comment by shavitush** [comment]
that's a weird behavior. i'll look into this

**Comment by Technoblazed** [comment]
Latest update helped a bit, but there's still a stutter, also doesn't appear to give all of the bots their information anymore.

e.g. -> Three bots in shavit.inc, NRM, SW, LGT - Only NRM is being given the tags and killed on spawn, the rest are acting as normal bots D:

**Comment by shavitush** [comment]
working on it

**Comment by Technoblazed** [comment]
Awesome :D

**Comment by shavitush** [comment]
let me know if it still happens

**Comment by Technoblazed** [comment]
Seemed to work fine, changed the map repeatedly, each time there would be 1 bot that isn't killed, with 0 records.

**Comment by Technoblazed** [comment]
Addition to above, when a WR is beaten, bot is respawned, and can be spectated normally, but clantag doesn't update, remains on unloaded

**Comment by shavitush** [comment]
give it a try now

**Comment by Technoblazed** [comment]
Sorry for the delayed response, but renaming works perfectly now, however the issue with the bot that isn't killed still remains  :3

**Comment by shavitush** [comment]
argh i hate csgo

in Player_Event, could you change the following line

    CreateTimer(0.10, DelayedUpdate, GetClientSerial(client), TIMER_FLAG_NO_MAPCHANGE);

To

    CreateTimer(0.50, DelayedUpdate, GetClientSerial(client), TIMER_FLAG_NO_MAPCHANGE);

**Comment by Technoblazed** [comment]
No effect

**Comment by Technoblazed** [comment]
Also, another bug I just noticed, before I reloaded this map, I set a time of 19 seconds and it's my current personal best, the bot updated its name, upon reloading the map, the record is now 34 seconds, my previous best, seems the bot didnt save o.O

**Comment by shavitush** [comment]
any error log?

**Comment by Technoblazed** [comment]
None at all

**Comment by m-yk** [comment]
try deleting the .replay file, i had something similar (can't remember exactly what happened) and doing that fixed it for me.

**Comment by Technoblazed** [comment]
I delete every record and every replay file each time I update the plugin ._.

**Comment by shavitush** [comment]
set `shavit_replay_timelimit` to 0 and tell me if it still happens

**Comment by Technoblazed** [comment]
No change, bot still doesn't overwrite the second time, PB is lower than the SR

**Comment by Technoblazed** [comment]
Ah, I see the issue, it's the name, the actual bot itself is the correct time, but the name is the old one

**Comment by shavitush** [comment]
i think i found the issue. after a map change, the bot saves and everything but the name is incorrect! could you try changing `shavit_replay_namestyle` to 0 and try again?

**Comment by Technoblazed** [comment]
Already am using 0

**Comment by shavitush** [comment]
done some testing in csgo after the recent updates, seems fine. start a new issue if it still happens please!~
