### ISSUE TITLE
Speed drops when jumping | Deathrun server

### ISSUE THREAD

**Issue by dimahail** [shavitush/bhoptimer#1002]
Hi, sorry for my bad english
I have a deathrun server, on deathrun maps, terrorists are given extra speed
Problem: Speed drops when terrorist jumping
Video:
https://www.youtube.com/watch?v=aKEJc_D2NYw

Shavit installed plugins:
core, hud, zones, wr

**Comment by kidfearless** [comment]
The timer isn't really designed for deathrun servers. As it is now you can either write a plugin to set the T's dynamic time scale to be higher using this native:
https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/include/shavit.inc#L1829
or you can use the developmental version of the timer very_good_yes and set `force_timescale` to 1 in the style config.

**Comment by Nairdaa** [comment]
This is a bhoptimer, not a deathrun timer. 

However, sv_enableautobunnyhopping 1

**Comment by Nairdaa** [comment]
Didn't notice that speed up.

**Comment by dimahail** [comment]
> This is a bhoptimer, not a deathrun timer.
> 
> However, sv_enableautobunnyhopping 1

On version 1.4 b everything worked well

**Comment by Nairdaa** [comment]
Cool, except the timer is now on version 2.6.0

So just use the 5 years old timer instead

**Comment by kidfearless** [comment]
> On version 1.4 b everything worked well

Then use that version...

**Comment by Nairdaa** [comment]
![image](https://user-images.githubusercontent.com/38843773/104267863-d296f900-5492-11eb-8bd9-6c6c6eb2e815.png)

**Comment by kidfearless** [comment]
Anyways you have 3 possible solutions to your issue, if there's nothing else then I'm going to close this issue.

**Comment by dimahail** [comment]
"or you can use the developmental version of the timer very_good_yes and set force_timescale to 1 in the style config."

can I have a link please

**Comment by Nairdaa** [comment]
He just gave it to you.

wt., 12 sty 2021, 05:15 użytkownik dimahail <notifications@github.com>
napisał:

**Comment by kidfearless** [comment]
https://github.com/shavitush/bhoptimer/tree/very_good_yes

**Comment by dimahail** [comment]
> https://github.com/shavitush/bhoptimer/tree/very_good_yes

Thank you
