### ISSUE TITLE
how do I make the sm_autobhop command enabled by default?

### ISSUE THREAD

**Issue by dimahail** [shavitush/bhoptimer#1003]
I noticed that the sm_autobhop command is disabled by default, how do I make it enabled by default?
This is very important to me

**Comment by Nairdaa** [comment]
no such cvar in this timer

**Comment by Nairdaa** [comment]
sm_autobhop 1

**Comment by Nairdaa** [comment]
it is actually enabled by default.

**Comment by dimahail** [comment]
> it is actually enabled by default.

No

**Comment by dimahail** [comment]
> sm_autobhop 1

It doesn't work that way

**Comment by Nairdaa** [comment]
> > it is actually enabled by default.
> 
> No

Yes it is. It's automatically on auto for autobhop styles due to ho wthe styles work.




> > sm_autobhop 1
> 
> It doesn't work that way

If you know better you also know how to fix your issues then.

**Comment by Nairdaa** [comment]
You're actually partially right. It's just sm_autobhop if your autobhop is disabled. You can disable/enable even if its enabled by default.

**Comment by dimahail** [comment]
As you can see, sm_autobhop is disabled by default, because if you enter sm_autobhop in the console, it will appear in the chat that sm_autobhop is enabled.
I need this option to be enabled when logging in to the server, because this option removes twitching when bhop

Video:
https://www.youtube.com/watch?v=uDYLxeff77U

**Comment by dimahail** [comment]
The video shows everything

**Comment by Nairdaa** [comment]
It's on by default, as I said, because of how the styles work. Any autobhop style will be autobhop _by default_ whenever you spawn.

**Comment by Nairdaa** [comment]
You've been told before that this timer is not made for what you're trying to accomplish. You either use it for what it's meant to be used or you disable main functionalities and search help somewhere else.

**Comment by dimahail** [comment]
The video clearly shows that the command is disabled by default. Also, when I turn it on, the twitching disappears at bhop

**Comment by dimahail** [comment]
> You've been told before that this timer is not made for what you're trying to accomplish. You either use it for what it's meant to be used or you disable main functionalities and search help somewhere else.

I don't want anything supernatural

**Comment by Nairdaa** [comment]
sv_autobunnyhopping 1 =/= sv_enablebunnyhopping 1

**Comment by dimahail** [comment]
> sv_autobunnyhopping 1 =/= sv_enablebunnyhopping 1

I have it spelled out

**Comment by Nairdaa** [comment]
idk what that means

you're doing something wrong and it's not timer related

**Comment by dimahail** [comment]
> sv_autobunnyhopping 1 =/= sv_enablebunnyhopping 1

![S1creenshot_1](https://user-images.githubusercontent.com/35889299/104277677-73a4a480-54d1-11eb-81db-bd37534de7ff.png)

**Comment by Nairdaa** [comment]
Not related to the timer at all then.

**Comment by dimahail** [comment]
I just want sm_autobhop to be enabled when connecting to the server, but it is disabled. In the video you can clearly see, friend. It can't be enabled by default, because I enable it myself in the console

**Comment by Nairdaa** [comment]
Then enable it on your own. It's not relevant to the timer at all. Your know better anyway.

**Comment by dimahail** [comment]
> Then enable it on your own. It's not relevant to the timer at all. Your know better anyway.

How does this have nothing to do with the timer if it's a function of it?

**Comment by Nairdaa** [comment]
What is it you don't understand? Your issue is not timer related.

**Comment by deadw1nter** [comment]
just simply edit the source code

**Comment by Nairdaa** [comment]
Why isn't this closed yet?
