### ISSUE TITLE
[Request] Put this into shavit-chat phrases instead

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#1008]
https://github.com/shavitush/bhoptimer/blob/very_good_yes/addons/sourcemod/scripting/shavit-chat.sp#L972

so you don't have to edit the hardcoded stuff then recompile it and just simply edit the .txt file instead

**Comment by hermansimensen** [comment]
This change would simply DESTROY the timer's ecosystem!

**Comment by rtldg** [comment]
This seems unnecessary

**Comment by Nairdaa** [comment]
I don't want that predefined text. I do realise it's every single latin alphabet leter in that sentence, but still, annoying that I have to compile the sp every time I want to change it. Also I think it's the only string that's not in phrases in the entire timer. Even the hud sections are editable inside of phrases.

**Comment by rtldg** [comment]
What are you even changing it to

**Comment by Nairdaa** [comment]
how is that relevant at all?

**Comment by Nairdaa** [comment]
I'm changing it to lorem ipsum cus im a professional. Idk, I think it's just "Test message." rn

**Comment by rtldg** [comment]
> how is that relevant at all?

it was to see if it was a cool enough string

https://github.com/shavitush/bhoptimer/commit/25f07e70e115bfb1842d1be9c85d589b54ec21fc
