### ISSUE TITLE
[After Beta?] Better Use of Scoreboard

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#101]
Maybe for after beta, but I'll suggest now anyway:

On the scoreboard:

K - Current time in seconds
A - Maps beaten in session
D - Number of maps beaten
MvPs - WRs ( Already done)
Score - Server Rank

**Comment by shavitush** [comment]
may do K/D only because the plugin is supposed to work on both CS:S and CS:GO, and as you (probably) know CS:S doesn't have assists/score

if anything, K for a negative number of seconds on the map, D for negative server rank and thats it i guess
