### ISSUE TITLE
[ Bug (?) ] Apparently you can be better than rank #1

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#1011]
shavit-chat.cfg

"ranks"         "1", as in only available for rank 1

results with
![image](https://user-images.githubusercontent.com/38843773/106347513-50df0200-62bf-11eb-8a28-057ea393687c.png)
Can't really think of a scenario where my rank is better than #1 on the server.

Tried 0-1 (says from rank 0 to rank 1 lul), 1-1, same stuff. Fix the parsing please.

**Comment by Smesh292** [comment]
Looks funny.

**Comment by rtldg** [comment]
fixed in https://github.com/shavitush/bhoptimer/commit/b19ce52efc7c9e73fe4a269ca3fef9524aaf581e and https://github.com/shavitush/bhoptimer/commit/3ca87e27c8e53aac01e84486b4587b296176c346
