### ISSUE TITLE
Segmented practice bug

### ISSUE THREAD

**Issue by friendly-hopper-685** [shavitush/bhoptimer#1023]
If you teleport to a practice checkpoint then you will stay in practice mode until restarting the timer, even if you teleport back to a segmented checkpoint. This also results in future segmented checkpoints becoming permanently marked as practice, these won't be turned back to regular checkpoints after a restart.

https://streamable.com/6kvbb2

**Comment by rtldg** [comment]
this should be fixed in https://github.com/shavitush/bhoptimer/commit/4350ca0994dce56ffabf70889860169a7fe415cb and will be in master (and next release) whenever @kidfearless updates the branch
