### ISSUE TITLE
Possibility to change menu display duration

### ISSUE THREAD

**Issue by GAMMACASE** [shavitush/bhoptimer#1024]
Currently most, if not all, menus are using 20 seconds as a default display time, which might be okay for some menus, but sometimes it's not enough, like for example menu that shows all completed maps for a specific style where you need to scroll to find the specific map you are looking for, and it's super annoying when it closes and you need to scroll again. By scrolling the menu here I mean going to next/prev page. Some convar that changes this display time for all the menus would be cool to have here.

**Comment by rtldg** [comment]
honestly, is there any reason to not use MENU_TIME_FOREVER?

**Comment by GAMMACASE** [comment]
idk why shavit decided to set it to 20 seconds, but I had 0 trouble from using MENU_TIME_FOREVER in other plugins.

**Comment by rtldg** [comment]
Decided to use 5 minutes for everything (so at least idle menus will be freed eventually) and adding a cvar seems unnecessary. https://github.com/shavitush/bhoptimer/commit/bf7f68faec0d31559ee48941556cf81e7e1342dd
