### ISSUE TITLE
version 2.6.0-1

### ISSUE THREAD

**Issue by MizzZer** [shavitush/bhoptimer#1034]
`L 03/21/2021 - 16:05:18: [SM] Exception reported: Translation string formatted incorrectly - missing at least 1 parameters (arg 6)
L 03/21/2021 - 16:05:18: [SM] Blaming: shavit/shavit-zones.smx`
`L 03/21/2021 - 16:05:09: [SM] Exception reported: Translation failed: invalid client index 1667330644 (arg 6)
L 03/21/2021 - 16:05:09: [SM] Blaming: shavit/shavit-replay.smx`
plugin `shavit/shavit-rankings.smx ([shavit] Rankings): Error detected in plugin startup (see error logs)
` it does not show any errors in the logs at all

**Comment by rtldg** [comment]
are you using any edited timer files?

**Comment by kidfearless** [comment]
Please post the full error logs.

**Comment by MizzZer** [comment]
> are you using any edited timer files?

I use everything default




> Please post the full error logs.

`L 03/21/2021 - 16:02:10: [SM] Exception reported: Translation failed: invalid client index 1667330644 (arg 6)
L 03/21/2021 - 16:02:10: [SM] Blaming: shavit/shavit-replay.smx
L 03/21/2021 - 16:02:10: [SM] Call stack trace:
L 03/21/2021 - 16:02:10: [SM]   [0] FormatEx
L 03/21/2021 - 16:02:10: [SM]   [1] Line 2796, E:\serv\1\comp1.10\shavit-replay.sp::GetTrackName
L 03/21/2021 - 16:02:10: [SM]   [2] Line 1524, E:\serv\1\comp1.10\shavit-replay.sp::FormatStyle
L 03/21/2021 - 16:02:10: [SM]   [3] Line 1546, E:\serv\1\comp1.10\shavit-replay.sp::UpdateReplayInfo
L 03/21/2021 - 16:02:10: [SM]   [4] Line 2199, E:\serv\1\comp1.10\shavit-replay.sp::DelayedUpdate

L 03/21/2021 - 16:02:45: [SM] Exception reported: Translation string formatted incorrectly - missing at least 1 parameters (arg 6)
L 03/21/2021 - 16:02:45: [SM] Blaming: shavit/shavit-zones.smx
L 03/21/2021 - 16:02:45: [SM] Call stack trace:
L 03/21/2021 - 16:02:45: [SM]   [0] FormatEx
L 03/21/2021 - 16:02:45: [SM]   [1] Line 2210, E:\serv\1\comp1.10\shavit-zones.sp::GetTrackName
L 03/21/2021 - 16:02:45: [SM]   [2] Line 1427, E:\serv\1\comp1.10\shavit-zones.sp::Command_Zones`

**Comment by MizzZer** [comment]
By the way, if you can communicate in Russian, I will be happy. For my English is lame.

**Comment by Nairdaa** [comment]
> invalid client index 1667330644 (arg 6)

wtf

anyway. make sure you are using the translations from 2.6.0 and not from the very_good_yes branch

**Comment by MizzZer** [comment]
Hmm. Apparently when I downloaded the translations in Russian, they were from the very_good_yes branch, but the author did not specify this. I'm sorry to bother you. But, !top still doesn't work

**Comment by Nairdaa** [comment]
What's the error when you do !top ?

**Comment by MizzZer** [comment]
There are simply no errors. I'm writing !top and nothing happens in the server console either.

**Comment by Nairdaa** [comment]
Then that's a cache problem and I don't know if it's caused by the changes k3n made or your client. 
The !top command is fully functional in the timer version you're referring to.

Make sure your mysql database is properly set up, that there are no errors on the actual server launch and that you're using correct files. You were using wrong translation files before so I can freely assume the issue is strictly on your end.

**Comment by MizzZer** [comment]
As a result:
Re-installed plugins
Deleted all tables from the database
Just in case, I deleted the old CFGs and configs

And at the first call, the top did not work, but as soon as the second player connected and passed the map, the top began to function.

**Comment by Nairdaa** [comment]
Yes, that's how it works. The !top won't show up unless there is something to show. If there is nothing to be drawn, the menu just won't popup, as there is a check for that. Basically, the check in human words works like "if the database is not empty draw the menu, if its empty do nothing".
