### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by catsteamoriginal** [shavitush/bhoptimer#1048]
How i change the text off the start/end zones? 
Like Start Zone/End Zone

**Comment by rtldg** [comment]
https://github.com/shavitush/bhoptimer/blob/f93a47742bf8a0063b10a1b9af47aceb9501e131/addons/sourcemod/translations/shavit-hud.phrases.txt#L7
https://github.com/shavitush/bhoptimer/blob/f93a47742bf8a0063b10a1b9af47aceb9501e131/addons/sourcemod/translations/shavit-hud.phrases.txt#L26
