### ISSUE TITLE
Hud  components not aligned

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#105]
Jump/Strafes arent aligned and it looks weird D:  

https://gyazo.com/9d31f63ce55dc4fdbb4a22038eb409a5

**Comment by Technoblazed** [comment]
Correction, only moves on styles over 8 letters long

**Comment by Nickelony** [comment]
I recommend you to swap the "Strafes: 0 (0.00)" where the "Jumps: 0" counter is.

**Comment by StrafeHack** [comment]
That won't fix it, it's the style name that pushes everything along.

I always change the HUD when I download a copy but either move everything that changes a lot of length to the right, or add if statements to change how many tabs are used depending on strlen.

**Comment by shavitush** [comment]
i really can't think of a way to fix that for long style names. if anyone has a suggestion it would be great.

**Comment by Technoblazed** [comment]
@shavitush What's planned to go in the top right? Could always have time/style at the top.

**Comment by shavitush** [comment]
times can go over 1 hour and become very long

**Comment by StrafeHack** [comment]
Can you not check the string length and then put a certain amount of \t infront of it depending?

**Comment by Technoblazed** [comment]
Or, even just as was said before

Time
Speed Style
Strafe Jump

**Comment by shavitush** [comment]
i'm pretty sure i already do it right now @StrafeHack 

    	Format(sHintText, 512, "%s\t%sStrafes: %d (%.02f)", sHintText, (strlen(gS_BhopStyles[bsStyle]) <= 6)? "\t":"", Shavit_GetStrafeCount(target), Shavit_GetSync(target));

**Comment by StrafeHack** [comment]
@shavitush 

I might be reading it wrong, but in his screenshot "Normal" is 6 chars long, and your code adds one tab if it's 6 or less, so just change it to 5 or less?

**Comment by Technoblazed** [comment]
but strafe, "No Limit" uses the version with no tab space

**Comment by StrafeHack** [comment]
"No Limit" is more than 6 chars long though, so it doesn't get the extra \t applied by this line?
(strlen(gS_BhopStyles[bsStyle]) <= 6)? "\t":""

**Comment by Nickelony** [comment]
I think this could be a very good combo:

Time | PB
Style | Jumps
Speed | Strafes

**Comment by Technoblazed** [comment]
+1

**Comment by Technoblazed** [comment]
Maybe dont even use the tab spacing, just use a | between

**Comment by shavitush** [comment]
i very disagree about using something like a |

**Comment by Nickelony** [comment]
I also disagree with that |
I just used it in my post so it looks cleaner x)
Just use

Time PB
Style Jumps
Speed Strafes

It looks much better.

**Comment by shavitush** [comment]
i found an issue with style names like Scroll as `l` is pretty small, so sometimes a `\t` wouldn't take effect..
i'll try getting the most aesthetic results from the following

```
Time (potential rank) PB (#rank)
Jumps Style
Speed Strafes (sync%)```

**Comment by Technoblazed** [comment]
Something like that would be good

**Comment by shavitush** [comment]
thoughts?

![bhop_tasku_csgo_b10000](https://cloud.githubusercontent.com/assets/3672466/17280297/6e6f3a90-5795-11e6-9a2f-090455937420.jpg)
![bhop_tasku_csgo_b10001](https://cloud.githubusercontent.com/assets/3672466/17280299/6ea8d444-5795-11e6-8b2a-5427084530fd.jpg)
![bhop_tasku_csgo_b10002](https://cloud.githubusercontent.com/assets/3672466/17280298/6ea56f98-5795-11e6-9a4b-145a98212f6f.jpg)

**Comment by Technoblazed** [comment]
Looks good

**Comment by Nickelony** [comment]
+100 THIS IS SOO BEAUTIFUL :D

**Comment by shavitush** [comment]
i'm retarded so i put it with this commit b931b26ed11219ea9f5fc23b18a5ca771ddbf399 instead
whatever, have fun :)
