### ISSUE TITLE
Warmup Time or Restart Game Causes Zones to Not Load

### ISSUE THREAD

**Issue by CustomStats** [shavitush/bhoptimer#1054]
Having a set warmuptime or doing mp_restartgame will cause the map zones to disappear when the warmup ends or when the game is restarted and will no longer load. This worked fine in the previous iteration of master, but stopped working after this most recent update to that branch. I don't know what exactly would be doing this, but having a warmuptime defined fixes a few things so it would be beneficial to have the ability set this.

Video shows what happens when mp_restartgame command is used, and the same thing happens when a warmup ends.
https://streamable.com/lzv9bi

**Comment by rtldg** [comment]
This should work fine again with [this commit](https://github.com/shavitush/bhoptimer/commit/eefaf5ebd0d3c55c6e0b1581ae1ca340bf8c143f). Let me know if it fixes it

**Comment by CustomStats** [comment]
That fixed it, thanks :)

**Comment by rtldg** [comment]
awesome :)
