### ISSUE TITLE
Invalid Handle Exceptions

### ISSUE THREAD

**Issue by CustomStats** [shavitush/bhoptimer#1055]
Most updated very_good_yes commit.
```
[SM] Exception reported: Handle e879053c is invalid (error 3)
[SM] Blaming: shavit-misc.smx
[SM] Call stack trace:
[SM]   [0] CloseHandle
[SM]   [1] Line 1475, shavit-misc.sp::DeleteCheckpointCache
[SM]   [2] Line 1427, shavit-misc.sp::DeletePersistentData
[SM]   [3] Line 591, shavit-misc.sp::OnMapStart
```
```
[SM] Exception reported: Handle e879053c is invalid (error 1)
[SM] Blaming: shavit-misc.smx
[SM] Call stack trace:
[SM]   [0] CloseHandle
[SM]   [1] Line 1475, shavit-misc.sp::DeleteCheckpointCache
[SM]   [2] Line 1427, shavit-misc.sp::DeletePersistentData
[SM]   [3] Line 537, shavit-misc.sp::Shavit_OnStyleChanged
[SM]   [5] Call_Finish
[SM]   [6] Line 1242, shavit-core.sp::CallOnStyleChanged
[SM]   [7] Line 1307, shavit-core.sp::ChangeClientStyle
[SM]   [8] Line 2812, shavit-core.sp::Command_StyleChange
```

```
[SM] Exception reported: Invalid Handle 9dc00702 (error: 3)
[SM] Blaming: shavit-misc.smx
[SM] Call stack trace:
[SM]   [0] ArrayList.Length.get
[SM]   [1] Line 1484, shavit-misc.sp::ResetCheckpointsInner
[SM]   [2] Line 1425, shavit-misc.sp::DeletePersistentData
[SM]   [3] Line 945, shavit-misc.sp::Timer_Cron
```

```
[SM] Exception reported: Invalid Handle 5a9704f4 (error: 1)
[SM] Blaming: shavit-misc.smx
[SM] Call stack trace:
[SM]   [0] ArrayList.Length.get
[SM]   [1] Line 1484, shavit-misc.sp::ResetCheckpointsInner
[SM]   [2] Line 1425, shavit-misc.sp::DeletePersistentData
[SM]   [3] Line 537, shavit-misc.sp::Shavit_OnStyleChanged
[SM]   [5] Call_Finish
[SM]   [6] Line 1242, shavit-core.sp::CallOnStyleChanged
[SM]   [7] Line 1307, shavit-core.sp::ChangeClientStyle
[SM]   [8] Line 1209, shavit-core.sp::StyleMenu_Handler
```

**Comment by CustomStats** [comment]
Tested after most recent commit and all exceptions no longer seemed to be happening. Will continue having people test it and see if there's anything else that pops up, thanks

**Comment by rtldg** [comment]
That's good to hear. Somewhere handles are getting busted but that commit was made to at least not have it break the server with spam anymore

**Comment by Septembers** [comment]
I downloaded the latest release
030 "[shavit] Core" (3.0.0) by shavit 
Title: [shavit] Miscellaneous (Miscellaneous features for shavit's bhop timer.)
  Author: shavit
  Version: 3.0.0

L 06/16/2021 - 21:17:50: [SM] Exception reported: Handle abf5118c is invalid (error 1)
L 06/16/2021 - 21:17:50: [SM] Blaming: shavit/shavit-misc.smx
L 06/16/2021 - 21:17:50: [SM] Call stack trace:
L 06/16/2021 - 21:17:50: [SM]   [0] CloseHandle
L 06/16/2021 - 21:17:50: [SM]   [1] Line 1475, C:\Users\exclu\Desktop\COMPILE 1.10\shavit-misc.sp::DeleteCheckpointCache
L 06/16/2021 - 21:17:50: [SM]   [2] Line 1426, C:\Users\exclu\Desktop\COMPILE 1.10\shavit-misc.sp::DeletePersistentData
L 06/16/2021 - 21:17:50: [SM]   [3] Line 945, C:\Users\exclu\Desktop\COMPILE 1.10\shavit-misc.sp::Timer_Cron

**Comment by CustomStats** [comment]
The Invalid Handle that includes OnMapStart seems to still be happening but haven't personally had any of the others occur again. Using master branch.

**Comment by Nairdaa** [comment]
Try the dev branch then, there were some fixes pushed since the master release

**Comment by CustomStats** [comment]
> Try the dev branch then, there were some fixes pushed since the master release

This branch is even with master.

**Comment by Nairdaa** [comment]
Lol you're right. Wth

**Comment by rtldg** [comment]
This should be fixed by https://github.com/shavitush/bhoptimer/commit/40429c6afe9d0df682621a5d10aa43df2f67c8c5 which stops handles from other player's persistent data from mixing in and causing handles to be deleted. It's in both master & very_good_yes right now so let me know if errors pop back up
