### ISSUE TITLE
[Suggestion] Make Dynamic Time/Velocity Separate Configurations

### ISSUE THREAD

**Issue by CustomStats** [shavitush/bhoptimer#1057]
The `shavit_replay_timedifference` convar enables both the dynamic time and dynamic velocity differences in the HUD, but it would be awesome to have these as separate convars so server owners can decide if they want this specific new feature (dynamic velocity), rather than having it be all or nothing.

**Comment by rtldg** [comment]
I'll add a !hud setting for velocity-difference because I forgot to do that, but I'm not sure a cvar is worth adding for it.

**Comment by rtldg** [comment]
I added a hud option for velocity different and the `shavit_hud2_default` cvar can be used to enable/disable it by default https://github.com/shavitush/bhoptimer/commit/87e64c87c7dfc4d8faec9fc1a425f1c60400ba47
