### ISSUE TITLE
Issue of random bot still spawning

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#106]
https://gyazo.com/f532335db3e226d40962d7957f0da78a

Still always one random bot that spawns with no record

**Comment by StrafeHack** [comment]
Can confirm, I have 4 styles and one will always be alive even if there is no records at all.

**Comment by shavitush** [comment]
will fix. but, you might want to disable the slowmo replay bot, it doesn't work well and i don't plan to 'fix it' as it could be used to fake runs (TAS-like)

**Comment by Technoblazed** [comment]
Yeah, just stuck all of them on while testing

**Comment by shavitush** [comment]
took me a while to figure this one ;_;
