### ISSUE TITLE
Invalid Handle

### ISSUE THREAD

**Issue by stunslave** [shavitush/bhoptimer#1060]
The errors don't really effect anything other than being spammed into console / logs. 
Which is rather annoying,

Timer Version: very_good_yes [https://github.com/shavitush/bhoptimer/tree/very_good_yes](https://github.com/shavitush/bhoptimer/tree/very_good_yes) - Latest

**Errors:**
Error Log: [errors_20210616.log](https://github.com/shavitush/bhoptimer/files/6669406/errors_20210616.log)

**Comment by Nairdaa** [comment]
I blame Nairda.

**Comment by rtldg** [comment]
This should be fixed by https://github.com/shavitush/bhoptimer/commit/40429c6afe9d0df682621a5d10aa43df2f67c8c5 which stops handles from other player's persistent data from mixing in and causing handles to be deleted. It's in both master & very_good_yes right now so let me know if errors pop back up
