### ISSUE TITLE
Console spammed with "Native is not bound"

### ISSUE THREAD

**Issue by atteure** [shavitush/bhoptimer#1062]
L 06/24/2021 - 14:55:43: [SM] Call stack trace:
L 06/24/2021 - 14:55:43: [SM]   [0] Shavit_InsideZone
L 06/24/2021 - 14:55:43: [SM]   [1] Line 1427, D:\pe\Downloads\sourcemod-1.10.0-git6499-windows(1)\addons\sourcemod\scripting\shavit-hud.sp::UpdateMainHUD
L 06/24/2021 - 14:55:43: [SM]   [2] Line 918, D:\pe\Downloads\sourcemod-1.10.0-git6499-windows(1)\addons\sourcemod\scripting\shavit-hud.sp::TriggerHUDUpdate
L 06/24/2021 - 14:55:43: [SM]   [3] Line 910, D:\pe\Downloads\sourcemod-1.10.0-git6499-windows(1)\addons\sourcemod\scripting\shavit-hud.sp::Cron
L 06/24/2021 - 14:55:43: [SM]   [4] Line 810, D:\pe\Downloads\sourcemod-1.10.0-git6499-windows(1)\addons\sourcemod\scripting\shavit-hud.sp::OnGameFrame
L 06/24/2021 - 14:55:43: [SM] Exception reported: Native is not bound
L 06/24/2021 - 14:55:44: [SM] Blaming: shavit-hud.smx

Looks like it's searching for an script... inside of someone else's download folder? Not sure what the cause of this is, but D:\pe\Downloads is definitely not my computer lol

**Comment by Nairdaa** [comment]
🤦‍♂️

**Comment by Nairdaa** [comment]
decades — Today at 18:53
@Nairda tell him to update dhooks and shit

**Comment by rtldg** [comment]
You're probably missing either DHooks2 or you need to configure the database. See if following the wiki helps https://github.com/shavitush/bhoptimer/wiki/1.-Installation-(from-source)

**Comment by atteure** [comment]
solved, apologies
