### ISSUE TITLE
cannot be cloned because it is invalid 

### ISSUE THREAD

**Issue by alispw77** [shavitush/bhoptimer#1063]
L 06/24/2021 - 22:25:02: [SM] Exception reported: Handle d4380ce3 cannot be cloned because it is invalid (error 3)
L 06/24/2021 - 22:25:02: [SM] Blaming: shavit-replay.smx
L 06/24/2021 - 22:25:02: [SM] Call stack trace:
L 06/24/2021 - 22:25:02: [SM]   [0] CloneHandle
L 06/24/2021 - 22:25:02: [SM]   [1] Line 1048, c:\Users\alien\OneDrive\Masa�st�\bhoptimer-master\addons\sourcemod\scripting\shavit-replay.sp::Native_SetReplayData
L 06/24/2021 - 22:25:02: [SM]   [3] Shavit_SetReplayData
L 06/24/2021 - 22:25:02: [SM]   [4] Line 2648, c:\Users\alien\OneDrive\Masa�st�\bhoptimer-master\addons\sourcemod\scripting\shavit-misc.sp::LoadCheckpointCache
L 06/24/2021 - 22:25:02: [SM]   [5] Line 1452, c:\Users\alien\OneDrive\Masa�st�\bhoptimer-master\addons\sourcemod\scripting\shavit-misc.sp::LoadPersistentData

**Comment by Keldraistaken** [comment]
idk if it's been solved but i've seen it a bunch of times in #timer-support-here

**Comment by alispw77** [comment]
i uploaded the latest version on my server today

**Comment by rtldg** [comment]
This should be fixed by https://github.com/shavitush/bhoptimer/commit/40429c6afe9d0df682621a5d10aa43df2f67c8c5 which stops handles from other player's persistent data from mixing in and causing handles to be deleted. It's in both master & very_good_yes right now so let me know if errors pop back up
