### ISSUE TITLE
Shavit_GetReplayFrames returns null even replay exites

### ISSUE THREAD

**Issue by bklol** [shavitush/bhoptimer#1065]
im using cows shavit ghost to show Ghost Trails but now it only works on main track,the bonus tracks did not show the Trails because cant get bonus ReplayFrames
![image](https://user-images.githubusercontent.com/54763946/125147454-fdba8680-e15d-11eb-84bb-78852e96feaf.png)
![image](https://user-images.githubusercontent.com/54763946/125147510-66096800-e15e-11eb-8f09-59884fff9044.png)

**Comment by Nairdaa** [comment]
Ask Cow to fix it. This is not a timer-related issue. Recompile the shit on your send or something.

**Comment by rtldg** [comment]
Fixed in 4a686ee4404a8f637d16d9e7dad6b4b9d21bd1bf
