### ISSUE TITLE
Style Speed Modifier Over 1.0 Causes Replay Time to Also Multiply

### ISSUE THREAD

**Issue by CustomStats** [shavitush/bhoptimer#1066]
Tested to work fine with any modifier under 1.0 but any above will result in the same thing happening. Using very_good_yes which is now even with master.

Speed modifier of "1.3"
https://streamable.com/u4sy5k
9.469 (actual time) x 1.3 (multiplier) = 12.3 (replay time)

Speed modifier of "1.0"
https://streamable.com/wumavx

**Comment by rtldg** [comment]
Try with this https://github.com/shavitush/bhoptimer/commit/71f10563a274a20a783fcdb6b9d511f42ed26f08 . Looks like the wrong style setting was used

**Comment by CustomStats** [comment]
Fixed :)

**Comment by Nairdaa** [comment]
@rtldg smh
