### ISSUE TITLE
Feature requests for 1.5b

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#107]
Spectator list, showing player ranks and for easier use of spectators, could probably integrate into planned sm_replay command

**Comment by Technoblazed** [comment]
Opacity setting for other players, instead of 255 maybe something more along 150, so they're still visible, but you can still see through them

**Comment by shavitush** [comment]
you already have a spectator list in !hud

**Comment by Technoblazed** [comment]
Spectator menu even, so it's easier to select a player to spectate, and I've seen opacity on kz servers :d

**Comment by shavitush** [comment]
some people just use !spec so they move to spectators without actually starting to spectate a specific player so i really don't see it being useful
i'll add an opacity cvar though

**Comment by Technoblazed** [comment]
Speaking of spectators, you wouldn't happen to know the csgo cvar to disable the viewing of buyouts when in spectate would you?

**Comment by shavitush** [comment]
no idea

**Comment by Technoblazed** [comment]
In the top left of the timer, would it be possible to have a -() displaying your time until you hit your personal record, or even your current rank?

**Comment by shavitush** [comment]
i'll do some tests, if it doesn't look bad, sure

**Comment by StrafeHack** [comment]
Maybe you could do what several other servers do. The "PB: 00:00.00" on the HUD will change between green and red depending on how close you are to your pb.

and usuall the "Time: 00:00.00" will do the same but for wr.

**Comment by shavitush** [comment]
i couldn't get the colored PB to work 😢
