### ISSUE TITLE
Issue with chatrank

### ISSUE THREAD

**Issue by Ashtonpjt** [shavitush/bhoptimer#1073]
I'm having an issue where it will only show one chatrank available.

(Testing for future server)

Right now it's only showing my rank for me being number 1

I should have 5 other available due to flags.

Not sure how to fix this.

**Comment by Nairdaa** [comment]
Link the chat ranks file
link the errors you have in server console

**Comment by Ashtonpjt** [comment]
[shavit-chat.txt](https://github.com/shavitush/bhoptimer/files/6988191/shavit-chat.txt)
[admins.txt](https://github.com/shavitush/bhoptimer/files/6988198/admins.txt)

got it to show all the ranks beside the ones with flags

**Comment by Ashtonpjt** [comment]
Also not that important at the moment how would i make a counter for how many times youve compelted maps? Not to knowlegble if any about sourcepawn but want to learn.

**Comment by Ashtonpjt** [comment]
Solved my issue with ranks just had some things setup wrong needed the "free"      "1" for them to show up but also still wondering about the last question

**Comment by rtldg** [comment]
`Shavit_GetClientCompletions` sounds like what you're looking for, although it requires a track and style to be provided.
https://github.com/shavitush/bhoptimer/blob/c5480e708751ad85c399ce217720fa94aad40f5e/addons/sourcemod/scripting/include/shavit.inc#L1399-L1407

Alternatively you could do a query like `select sum(completions), auth from playertimes where map = 'bhop_freedompuppies' and auth = 123123;` if you want it from every track/style or whatever

**Comment by Nairdaa** [comment]
Also not that important at the moment how would i make a counter for how many times youve compelted maps?

it's in !wr if u select the player, map completion counter is there

**Comment by Nairdaa** [comment]
lol puff ^^ nice timing

**Comment by Ashtonpjt** [comment]
![wtf](https://user-images.githubusercontent.com/88919119/129498811-3b4d3298-e1a6-4eb5-bb89-df5cc957aab4.PNG)
now running in to this issue

**Comment by Ashtonpjt** [comment]
dhook is installed was working then just stopped working

**Comment by Ashtonpjt** [comment]
fixed it had to reinstall dhook 8 times then it worked randomly

**Comment by Ashtonpjt** [comment]
nairdaa yes like that but for total completions of everymap/style to show up on the !profile page..

I use to play on a server a while back that had it

**Comment by Ashtonpjt** [comment]
also how do i disable 7 of the bonuses as I only want 1

**Comment by Ashtonpjt** [comment]
searched all the files just couldnt find anything
