### ISSUE TITLE
[Suggestion] shavit-mapchooser

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#1078]
// How many times players can choose to extend a single map (0 = block extending)
// -
// Default: "3"
// Minimum: "0.000000"
smc_mapvote_extend_limit "20"

Could add a -1 option for infinite times of extending the map till people vote otherwise to not extend. I mean I could put 999999 there as well, but hey, that's 6 bytes instead of 2, okay?

**Comment by Nairdaa** [comment]
Yes, I know that adding that -1 would result in even more bytes of the plugin itself. Meep meep.

**Comment by rtldg** [comment]
added https://github.com/shavitush/bhoptimer/commit/5cc0bd300d897b87dba084bc1427cb197f842661
