### ISSUE TITLE
(BUG) "Modify width / lenght" has no "Front edge" option?

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#109]
You can only modify the right, front and left edge. I think you accidentally removed it. :P

**Comment by StrafeHack** [comment]
There is still 6 adjusters for each point?

**Comment by shavitush** [comment]
there are supposed to be 8, yeah it's my fault i'll fix

**Comment by shavitush** [comment]
25a37ae5c9de6aac7876100df6ede6bff69009ca
