### ISSUE TITLE
Blaming: shavit-rankings.smx

### ISSUE THREAD

**Issue by Heizlin** [shavitush/bhoptimer#1093]
ranks doesn't change and maptiers doesn't save. This is what console says when i write !settier

L 11/27/2021 - 16:04:21: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/27/2021 - 16:04:21: [SM] Blaming: shavit-rankings.smx
L 11/27/2021 - 16:04:21: [SM] Call stack trace:
L 11/27/2021 - 16:04:21: [SM]   [0] Database.Query
L 11/27/2021 - 16:04:21: [SM]   [1] Line 295, D:\sourcemod-1.10.0-git6515-windows-v3.0.8\addons\sourcemod\scripting\include\shavit.inc::Database2.Query
L 11/27/2021 - 16:04:21: [SM]   [2] Line 672, D:\sourcemod-1.10.0-git6515-windows-v3.0.8\addons\sourcemod\scripting\shavit-rankings.sp::Command_SetTier

**Comment by NukoOoOoOoO** [comment]
Did you setup the database properly? Please double check it with the [instruction](https://github.com/shavitush/bhoptimer/wiki/2.1.-Configuration:-Database) and see if it still happens

**Comment by Heizlin** [comment]
i probably did something wrong because all zones is gone. Console looks like this: 
L 11/27/2021 - 18:04:55: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION veetih_bhop.GetRecordPoints does not exist

L 11/27/2021 - 17:50:45: [shavit-rankings.smx] Timer (rankings, update all points) error! Reason: FUNCTION veetih_bhop.GetWeightedPoints does not exist

my database looks like this:
	"shavit"
	{
		"driver"			"mysql"
		"host"				"myhost"
		"database"			"mydbname"
		"user"				"myuser"
		"pass"				"mypass"
	}

**Comment by akanora** [comment]
give correct rights to user so it can create functions

**Comment by Heizlin** [comment]
how? i'm not expert at database things:D

**Comment by NukoOoOoOoO** [comment]
It took me 2 seconds to find a tutorial for you on Google https://www.mysqltutorial.org/mysql-grant.aspx

**Comment by Heizlin** [comment]
ahh that link doesnt help much because i don't understand what's going on there:D i don't even know where i create new user heh

**Comment by akanora** [comment]
Contact the person who prepared your database, probably the hosting company.

**Comment by Heizlin** [comment]
i asked from hosting company about this and he said there's all permissions?

**Comment by Nairdaa** [comment]
Your company is lying, because your user doesn't have the correct auth.

**Comment by Nairdaa** [comment]
`GRANT ALL PRIVILEGES ON *.* TO 'DATABASEUSER'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;`

Delete your tables then execute the above mysql comman,, then restart the server and see if it loads fine now.

**Comment by rtldg** [comment]
If your database host hasn't granted your user the ability to create sql functions then you'll just have to disable shavit-rankings until next release. Next release will usable without sql functions as long as you set `shavit_rankings_weighting` to `1.0` but until then, yeah, you have to disable shavit-rankings or use a different db host.
