### ISSUE TITLE
240 startzone prespeed

### ISSUE THREAD

**Issue by LightBasileus** [shavitush/bhoptimer#1095]
Hello (:

I'm receiving a 240 startzone prespeed but I'm having a 260 prespeed set for the main style. I'm also receiving an issue with the jumps. It seems like their shorter than they normally would have been.

**Comment by Nairdaa** [comment]
they're*

https://forums.alliedmods.net/showthread.php?t=255298

**Comment by LightBasileus** [comment]
Thank you Dx I need the grammar lesson

**Comment by LightBasileus** [comment]
Is there anything you can do to help me with the 240 limitation thats been set on the start zone? Dx

**Comment by Nairdaa** [comment]
Literally just linked you directly to the thread that solves your problem

**Comment by LightBasileus** [comment]
No I was installing the plugin. I think its working good. My movement has still been stuck to 240 while in the start zone with a 260 prespeed set in the styles configuration. Sorry Dx

**Comment by Nairdaa** [comment]
`sm plugins list ` in your _SERVER_ console and show me the list. I bet you didn't upload the gamedata file

**Comment by Nairdaa** [comment]
Also make sure to have 

`sv_accelerate 5
sv_friction 4`
in your server config file

**Comment by LightBasileus** [comment]
"shavit - MapChooser" (1.0.4) by SlidyBat
 "Reserved Slots" (1.10.0.6528) by AlliedModders LLC
 "Sound Commands" (1.10.0.6528) by AlliedModders LLC
 "[shavit] Map Zones" (2.6.0) by shavit
 "Fun Votes" (1.10.0.6528) by AlliedModders LLC
 "[shavit] Core" (2.6.0) by shavit
 "Fun Commands" (1.10.0.6528) by AlliedModders LLC
 "[shavit] Miscellaneous" (2.6.0) by shavit
 "[shavit] Sounds" (2.6.0) by shavit
 "[shavit] World Records" (2.6.0) by shavit
"RNGFix" (1.1.2) by rio
 "Admin Menu" (1.10.0.6528) by AlliedModders LLC
 "[shavit] Rankings" (2.6.0) by shavit
 "Basic Info Triggers" (1.10.0.6528) by AlliedModders LLC
 "Client Preferences" (1.10.0.6528) by AlliedModders LLC
 "Player Commands" (1.10.0.6528) by AlliedModders LLC
 "Admin File Reader" (1.10.0.6528) by AlliedModders LLC
 "[shavit] HUD" (2.6.0) by shavit
 "[shavit] Dynamic Timelimits" (2.6.0) by shavit
 "[shavit] Player Stats" (2.6.0) by shavit
 "Anti-Flood" (1.10.0.6528) by AlliedModders LLC
"Basic Votes" (1.10.0.6528) by AlliedModders LLC
 "[shavit] Chat Processor" (2.6.0) by shavit
 "Admin Help" (1.10.0.6528) by AlliedModders LLC
 "[shavit] Replay Bot" (2.6.0) by shavit
 "Nextmap" (1.10.0.6528) by AlliedModders LLC
 "Basic Comm Control" (1.10.0.6528) by AlliedModders LLC
 "Momentum surf fix '2" (1.1.3) by GAMMA CASE
 "Basic Chat" (1.10.0.6528) by AlliedModders LLC
 "Basic Commands" (1.10.0.6528) by AlliedModders LLC
 "Basic Ban Commands" (1.10.0.6528) by AlliedModders LLC

**Comment by LightBasileus** [comment]
You're probably right

**Comment by Nairdaa** [comment]
By that list it looks like you don't even have that plugin loaded at all.

**Comment by LightBasileus** [comment]
Which one am I missing?

**Comment by Nairdaa** [comment]
The one that I linked.

**Comment by LightBasileus** [comment]
I restarted my server for the intent to double check. The plugin is in the plugins directory. Its not loading. I have now received a 196 player movement. Dx

**Comment by Nairdaa** [comment]
"it's not loading" doesn't help at all

need error logs


but I bet you still haven't uploaded the gamedata file.

**Comment by LightBasileus** [comment]
Yes, you were being right. I was not uploading the gamedata file into the gamedata directory. I was restarting my server and the sm plugin "CS:GO Movement Unlocker" (1.0) by Peace-Maker was loading. However Dx im still getting a 186 prespeed Dx

**Comment by LightBasileus** [comment]
Its not just in the start zone as it seems. It also seems to be outside of any zones.

**Comment by Nairdaa** [comment]
Already gave you the solution. I don't know what you're doing wrong.

**Comment by LightBasileus** [comment]
This was happening during one of the updates that I recall. The player movement speed was being delimited during the update until you guys were readily avaliable with the update. If its not the player movement speed unlocker, than what can i do? Dx Should i just reinstall the server from scratch?

**Comment by Nairdaa** [comment]
make sure you have the right settings in `casual_server.cfg`, your issue has nothing to do with the timer itself

**Comment by LightBasileus** [comment]
I'm using a custom gamemode configuration file. I only have the sv_accelerate, sv_friction set in there now.

**Comment by LightBasileus** [comment]
Last time i was having an issue, i was reinstalling the operating system from scratch. I was taking me a day or two but it was working shortly after that.

**Comment by Nairdaa** [comment]
Bro, without any error logs it's pretty much just blindly guessing what's wrong. If you have no errors then it's your server setup. I have no idea what you're doing ^^.

**Comment by Nairdaa** [comment]
Poke me on bhoptimer discord (an idiot sandwich) and if you got TeamViewer I could RDP and most likely fix it for you within a couple mins.

**Comment by LightBasileus** [comment]
okie, I dont have any errors. I was receiving them prior due to the gamedata file not being inserted into the gamedata directory.

**Comment by LightBasileus** [comment]
I couldn't fin your discord
