### ISSUE TITLE
[Error] Timer (WR Holder Rank table creation 0/4) SQL query failed.

### ISSUE THREAD

**Issue by evileyecc1** [shavitush/bhoptimer#1097]
Plugin Version:3.0.8

Database Version: Mysql 8.0.25

 12/22/2021 - 15:05:17: [shavit-rankings.smx] Timer (WR Holder Rank table creation 0/4) SQL query failed. Reason: Unknown column 'wrcount' in 'window order by'

**Comment by rtldg** [comment]
Until I fix the query, you can change this line
https://github.com/shavitush/bhoptimer/blob/b2a95095e788f86724ef463f9d8dfae1077c01c3/addons/sourcemod/scripting/shavit-rankings.sp#L1044
to `gB_HasSQLRANK = false;` so that error won't happen

**Comment by evileyecc1** [comment]
I will try later.Thanks

**Comment by BoomShotKapow** [comment]
This should resolve that for MySQL 8.0: https://github.com/BoomShotKapow/bhoptimer/blob/aa4b79f9a67c4baedb0870c2afd968edbf6a9be7/addons/sourcemod/scripting/shavit-rankings.sp#L1291-L1297

**Comment by rtldg** [comment]
Until the next release is out you'll have to manually make one of the changes suggested by me or BoomShot.
BoomShot's patch for it will be included in next release.
