### ISSUE TITLE
[Possible bug] Start Zone teleports to the very spawn

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#1098]
bhop_japan

https://www.youtube.com/watch?v=vjJiRK0zE0g

How to reproduce?
- Walk into startzone :J

**Comment by rtldg** [comment]
set `shavit_misc_resettargetname 0` on the map until next update. next update has https://github.com/shavitush/bhoptimer/commit/6573e0cbbc86337cc5ff275ab1d6a5bf6c59b0dc for this
