### ISSUE TITLE
Compile scripting via FTP

### ISSUE THREAD

**Issue by SeXyKiwi** [shavitush/bhoptimer#1107]
Hi,
I'm sorry if my problem isn't at the right place.
I'm setting the timer on my server, and if I made the source installation, I'm stuck because I don't know how to compile .sp files.
When I access to my server by FTP, I can't open a .exe file, so I can't compile scripts via FTP, and if I try to compile on my computer, it give me errors, ( missing files ).
I tried to install the 3.0.8 release wich is just drag and drop, without the compile step, but It doesn't work anymore.

Now, It work because I used the Evan's Bhop serv leak, but If I want to update for new versions, I just Can't, because I can't compile, or the last release don't work.
Is there a solution at my problem ?
Thanks

**Comment by akanora** [comment]
https://wiki.alliedmods.net/Compiling_SourceMod_Plugins

If you still need help Nora#1768

**Comment by SeXyKiwi** [comment]
> https://wiki.alliedmods.net/Compiling_SourceMod_Plugins
> 
> If you still need help Nora#1768 or bhoptimer's discord https://discord.gg/GZy7p3g5

You're a beast, ty so much

**Comment by rtldg** [comment]
Download sourcemod locally and drop everything in and compile locally. bhoptimer isn't missing any files it needs to compile if you drop the release in
