### ISSUE TITLE
shavit-core blaming

### ISSUE THREAD

**Issue by SKYPIXEL45** [shavitush/bhoptimer#1110]
I used the lastest version(master updated 3 days ago).

L 01/09/2022 - 22:51:23: [SM] Exception reported: Native is not bound
L 01/09/2022 - 22:51:23: [SM] Blaming: shavit-core.smx
L 01/09/2022 - 22:51:23: [SM] Call stack trace:
L 01/09/2022 - 22:51:23: [SM]   [0] SetClientEventsPaused
L 01/09/2022 - 22:51:23: [SM]   [1] Line 2827, E:\cmd\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-core.sp::DHook_ProcessMovement
L 01/09/2022 - 22:51:23: [SM] Exception reported: Native is not bound
L 01/09/2022 - 22:51:23: [SM] Blaming: shavit-core.smx
L 01/09/2022 - 22:51:23: [SM] Call stack trace:
L 01/09/2022 - 22:51:23: [SM]   [0] SetClientEventsPaused
L 01/09/2022 - 22:51:23: [SM]   [1] Line 2827, E:\cmd\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-core.sp::DHook_ProcessMovement
L 01/09/2022 - 22:51:23: [SM] Exception reported: Native is not bound
L 01/09/2022 - 22:51:23: [SM] Blaming: shavit-core.smx
L 01/09/2022 - 22:51:23: [SM] Call stack trace:
L 01/09/2022 - 22:51:23: [SM]   [0] SetClientEventsPaused
L 01/09/2022 - 22:51:23: [SM]   [1] Line 2827, E:\cmd\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-core.sp::DHook_ProcessMovement
L 01/09/2022 - 22:51:23: [SM] Exception reported: Native is not bound
L 01/09/2022 - 22:51:23: [SM] Blaming: shavit-core.smx
L 01/09/2022 - 22:51:23: [SM] Call stack trace:
L 01/09/2022 - 22:51:23: [SM]   [0] SetClientEventsPaused
L 01/09/2022 - 22:51:23: [SM]   [1] Line 2827, E:\cmd\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-core.sp::DHook_ProcessMovement
L 01/09/2022 - 22:51:23: [SM] Exception reported: Native is not bound
L 01/09/2022 - 22:51:23: [SM] Blaming: shavit-core.smx
L 01/09/2022 - 22:51:23: [SM] Call stack trace:
L 01/09/2022 - 22:51:23: [SM]   [0] SetClientEventsPaused

**Comment by Nairdaa** [comment]
Not an issue with the timer. An issue with you. Read how to install the timer again. Install dhooks, that's a requirement for the timer to work.

**Comment by SKYPIXEL45** [comment]
But I have installed Dhooks correctly, and the 3.0.8 version I used before did not have this kind of error. When I changed to the latest version, this kind of error occurred.

**Comment by Ciallo-Ani** [comment]
确保已经安装了[DHooks](https://github.com/peace-maker/DHooks2/releases)
确保你安装了最新插件之后**重启了服务器**(服务器后台输入_restart，重启地图没任何作用)
请不要直接后台输入`sm plugins reload shavit-core`，任何时候都不要重载core插件

**Comment by rtldg** [comment]
shavit-core was missing a check for eventqueuefix when using a function from eventqueuefix.

install eventqueuefix (from the master branch, not the release page) and/or make this change https://github.com/shavitush/bhoptimer/commit/ec881bbae573bb132ac80c8253c9282e52f7357a#diff-a6d6c2b4761eea8f68202daa7a99cb0b1fcd07186b000ca75e9db88a587769c5R2828-R2832
