### ISSUE TITLE
[Issue] TAS prestrafe looks like a disgusting badonkadonk

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#1113]
https://user-images.githubusercontent.com/38843773/149430636-307c5164-9800-419f-b73f-10aba89081da.mp4

Fix please so it doesn't shake like an alcoholic on delirium. Rest of the run is also an autostrafer and it doesn't shake.

**Comment by rtldg** [comment]
tbh i think it's hilarious. i'll see what can be done for it though but probably just need to save the original player angles somewhere for replay-recorder to grab

**Comment by rtldg** [comment]
https://github.com/shavitush/bhoptimer/commit/345461a838365fdcc0ca419fc87da0a36ea3b064
