### ISSUE TITLE
[BUG] Server crashes when accepting 'player_speedmod' entity input

### ISSUE THREAD

**Issue by Ciallo-Ani** [shavitush/bhoptimer#1118]
# Environment
  CSGO
  Latest Release bhoptimer v3.1.1

# Description
  My server crashes when accepting 'player_speedmod' entity input

# Steps to Reproduce
  1. Download the map [surf_fiellu](https://surfdl.net/csgo/maps/surf_fiellu.bsp.bz2)
  2. Run the map, spawn, and goto map Bonus 2.
  3. Server crashed.
  (not just this map, like surf_beyond also produce..)

# Logs
  https://pastebin.com/tvMzWh7T

# Something may properly fix this
  https://github.com/shavitush/bhoptimer/blob/dd0059f15fc3045e67325deda4552984b968ca6f/addons/sourcemod/scripting/shavit-core.sp#L2790

Change `Hook_Post` to `Hook_Pre` fixed this, but idk why.

**Comment by rtldg** [comment]
should be fixed with https://github.com/shavitush/bhoptimer/commit/0000000146955c76f2ad78096cc27f614dfddf3d
