### ISSUE TITLE
look into more prebuilt timer zone things

### ISSUE THREAD

**Issue by rtldg** [shavitush/bhoptimer#1124]
`surf_summer_ksf` has a lot of fancy trigger classnames for momentum mod and timers(?)

trigger_multiples with targetnames: `zone_b1_start`, `zone_b1_end`, `stage4_start`, `stage5_start` (etc...). `stage1_start` used as startzone? any reference to these on a website somewhere? (these might just be things that surf servers use to set the trigger as for a zone)

momentummod classname entities: `trigger_momentum_timer_start`, `trigger_momentum_timer_stage` (with `"stage" "1"` key set), `trigger_momentum_timer_stop`
https://docs.momentum-mod.org/entity/trigger_momentum_timer_start/

**Comment by sneak-it** [comment]
In surf it is *very* common for mappers to create trigger_multiple entities as premade zones. A few public surf timers are able to choose which trigger_multiple to hook, and utilize that as a zone of their choosing.

It's particularly great for ease of zoning, non-standard zone shapes, sizes, and angles, and continuity across different community servers.

**Comment by rtldg** [comment]
The momentummod classname entities are probably not created unless we use a global filters stripper cfg to modify classname=trigger_multiple & targetname=trigger_momentum_blah_blah so it doesn't really need to be a timer issue.

Since the other zones don't follow a standard naming convention it's probably a waste of time adding some sort of parsing for it and instead the trigger hooking / marking should instead be implemented. Closing this issue since #736 is already a thing.
