### ISSUE TITLE
[Issue] showkeys bug on replaybots

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#1125]
jumps on scroll styles are not being shown. It stays at 0 0 the entire replay

**Comment by rtldg** [comment]
should show scroll counts properly for bots now (excluding prop replay bots) https://github.com/shavitush/bhoptimer/commit/80e8480b7a0a94e8962e1d3da78602c703edf63d

**Comment by Nairdaa** [comment]
Will test tomorrow. Thank you for the very quick response.

czw., 24 lut 2022, 07:26 użytkownik rtldg ***@***.***>
napisał:
