### ISSUE TITLE
[Request] Use other players' checkpoints

### ISSUE THREAD

**Issue by Ciallo-Ani** [shavitush/bhoptimer#1126]
It would be useful if we can use others' checkpoints

**Comment by Nairdaa** [comment]
There is a style for that. Let me think to remember what it was called. Could perhaps steal the code from there.

**Comment by Nairdaa** [comment]
https://github.com/NukoOoOoOoO/tagteam


Thought Nuko had it done. Oh well. Maybe there is another public repository somewhere. Google "shavit" + "tagteam", and you might™ or may not find something.

**Comment by rtldg** [comment]
I don't think they mean a tagteam style. More like being able to copy and use another player's checkpoints. Maybe a menu to grab checkpoints or something.

**Comment by Nairdaa** [comment]
Yes ik xd btw thanks for that edit on nukos PR, gonna test later today

pon., 14 mar 2022, 02:59 użytkownik rtldg ***@***.***>
napisał:
