### ISSUE TITLE
[ Issue ] Checkpoints API is at fault

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#1127]
I've spent the last couple hours trying to figure out what the actual fuck was wrong with a plugin. I came to a conclusion that it's the actual API being at fault OR I'm completely misunderstanding it. 

Basically everything the error says is "hi, shavit-checkpoint.sp is at fault, go fuck yourself and figure out if it's your fault OR the actual API being at fault and you're a moron for not understanding it"

> L 03/04/2022 - 00:38:06: [SM] Exception reported: Invalid index 0 (count: 0)
> L 03/04/2022 - 00:38:06: [SM] Blaming: shavit-checkpoints.smx
> L 03/04/2022 - 00:38:06: [SM] Call stack trace:
> L 03/04/2022 - 00:38:06: [SM]   [0] ArrayList.GetArray
> L 03/04/2022 - 00:38:06: [SM]   [1] Line 1789, D:\sourcemod-1.10.0-git6528-windows\addons\sourcemod\scripting\shavit-checkpoints.sp::Native_GetCheckpoint
> L 03/04/2022 - 00:38:06: [SM]   [3] Shavit_GetCheckpoint
> L 03/04/2022 - 00:38:06: [SM]   [4] Line 525, I:\steamcmd\css\cstrike\addons\sourcemod\scripting\shavit-tagteam.sp::Shavit_OnSave
> L 03/04/2022 - 00:38:06: [SM]   [6] Call_Finish
> L 03/04/2022 - 00:38:06: [SM]   [7] Line 1422, D:\sourcemod-1.10.0-git6528-windows\addons\sourcemod\scripting\shavit-checkpoints.sp::SaveCheckpoint
> L 03/04/2022 - 00:38:06: [SM]   [8] Line 1216, D:\sourcemod-1.10.0-git6528-windows\addons\sourcemod\scripting\shavit-checkpoints.sp::MenuHandler_Checkpoints
> L 03/04/2022 - 00:38:06: [SM] Exception reported: Invalid Handle 0 (error: 4)
> L 03/04/2022 - 00:38:06: [SM] Blaming: shavit-checkpoints.smx
> L 03/04/2022 - 00:38:06: [SM] Call stack trace:
> L 03/04/2022 - 00:38:06: [SM]   [0] ArrayList.PushArray
> L 03/04/2022 - 00:38:06: [SM]   [1] Line 1445, D:\sourcemod-1.10.0-git6528-windows\addons\sourcemod\scripting\shavit-checkpoints.sp::SaveCheckpoint
> L 03/04/2022 - 00:38:06: [SM]   [2] Line 1216, D:\sourcemod-1.10.0-git6528-windows\addons\sourcemod\scripting\shavit-checkpoints.sp::MenuHandler_Checkpoints

Please hold my hand and walk me through if I'm misunderstanding something.

Actual plugin: [shavit-tagteam.zip](https://github.com/shavitush/bhoptimer/files/8181959/shavit-tagteam.zip)
Timer version: Newest release (https://github.com/shavitush/bhoptimer/releases/tag/v3.1.3)
Tears cried: 8/10

**Comment by rtldg** [comment]
Shavit_OnSave is called before the checkpoint is saved which is why GetCheckpoint doesn’t work. Arguably not very useful since there’s no forward for after the checkpoint is saved afaik but still the plugin is still using it incorrectly.

The error about the invalid handle 0 can probably be assumed to be caused by that plugin also

**Comment by rtldg** [comment]
I’ll probably look into doing the same thing I did with Shavit_OnStart (created Shavit_OnStartPre) but for OnSave

**Comment by rtldg** [comment]
Shavit_OnStart now happens after the checkpoint has saved so tagteam should be able to grab the checkpoint correctly now hopefully. https://github.com/shavitush/bhoptimer/commit/de8a82707b9fab615438844a2ea2f5ccc78957dc

You'll probably need to edit the tagteam plugin to set `cp_cache_t.iSteamID` & set `cp_cache_t.aSnapshot.bPracticeMode` to false if `cp_cache_t.aSnapshot.bTimerEnabled` and stuff like that
