### ISSUE TITLE
changing from segmented styles spams when checkpoints cvar is disabled

### ISSUE THREAD

**Issue by sh4hrazad** [shavitush/bhoptimer#1129]
when `shavit_checkpoints_checkpoints "0"`, if I change my style from segmented to other non-segmented styles, it spams "this feature is disabled" in the message box. (version 3.1.3)

I tried editing this line
https://github.com/shavitush/bhoptimer/blob/89e8f69f6abe930726c13a93a9f3a1e15f5b7ccf/addons/sourcemod/scripting/shavit-checkpoints.sp#L411
to
```sourcepawn
else if (gB_InCheckpointMenu[i] && gCV_Checkpoints.BoolValue)
```
and fixed this, but menu can't close automatically then.

**Comment by Ciallo-Ani** [comment]
ezfix, add this to your line 400 and try
```c++
if(!gCV_Checkpoints.BoolValue)
{
	return Plugin_Continue;
}
```

**Comment by Nairdaa** [comment]
that will execute rest of the code, should be Plugin_Handled; I think, no?

**Comment by Nairdaa** [comment]
I don't even see why one would use `shavit_checkpoints_checkpoints "0"` together with segmented styles, but ok xd

**Comment by rtldg** [comment]
merged in ciallo's commit for this https://github.com/shavitush/bhoptimer/commit/73601ffd0a4aacf57d1c2113d125de9ef186364f
