### ISSUE TITLE
Updated Bot Code Issues

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#113]
Probably irrelevant giving that slowmo bots should not be used, but the Slowmotion bot is now called "[SLOWMO] [SLOWMO] unloaded".

Additionally, the bot issue is still present:
https://gyazo.com/7f0bce53ba223c98bf89069dd48259c3

Could that be related to the score? That one has "0" whereas dead/alive have 1998/2000

**Comment by shavitush** [comment]
> Could that be related to the score?

yes, if there's no score, it means that some of the stuff i do didn't apply to it.. for some reason i can't replicate this at all.. if you come up with anything that might be related let me know

**Comment by Technoblazed** [comment]
Could it be OS related?

**Comment by Technoblazed** [comment]
Another update, when a new time is set, the bots arent spawning

**Comment by shavitush** [comment]
actually i probably know whats causing it
could you try running at sqlite and tell me it's fixed? (change back to mysql afterwards, just for testing!)

**Comment by Technoblazed** [comment]
Nope, didn't change anything

**Comment by Technoblazed** [comment]
Issues are resolved, as far as I can tell, doing some more testing, looks like I forgot to delete the old bot files before this lel

**Comment by Technoblazed** [comment]
Ok, so the only remaining issue, is bots not respawning when a new record is set

**Comment by shavitush** [comment]
done testing, have fun
