### ISSUE TITLE
[native bug?] Shavit_SetCheckpoint tries setting the cp to a deleted index (@param index = -1)

### ISSUE THREAD

**Issue by sh4hrazad** [shavitush/bhoptimer#1133]
(v3.1.3) happens when im trying making a plugin that lists all players' cp so that everyone could use them.
```
L 03/19/2022 - 19:05:48: [SM] Exception reported: Invalid index 3 (count: 3)
L 03/19/2022 - 19:05:48: [SM] Blaming: shavit-checkpoints.smx
L 03/19/2022 - 19:05:48: [SM] Call stack trace:
L 03/19/2022 - 19:05:48: [SM]   [0] ArrayList.SetArray
L 03/19/2022 - 19:05:48: [SM]   [1] Line 1818, D:\sourcemod-1.10.0-git6528-windows\addons\sourcemod\scripting\shavit-checkpoints.sp::Native_SetCheckpoint
L 03/19/2022 - 19:05:48: [SM]   [3] Shavit_SetCheckpoint
L 03/19/2022 - 19:05:48: [SM]   [4] Line 351, .\shavit-globalcp2.sp::SaveGlobalCheckpoint
L 03/19/2022 - 19:05:48: [SM]   [5] Line 135, .\shavit-globalcp2.sp::Command_GetCheckpoint
```
code that blames errors:
```sourcepawn
    Shavit_SetCheckpoint(client, -1, checkpoint.cpcache);
```
https://github.com/shavitush/bhoptimer/blob/b05393cf9fca682c7e959164a1ac15017c3efa3a/addons/sourcemod/scripting/shavit-checkpoints.sp#L1838-L1844

btw if i set the index to other values, it will delete the checkpoint in index-1 and overwrite the cp in the index :/

**Comment by rtldg** [comment]
can you test if doing something like this helps
```
	DeleteCheckpoint(client, position, true);
	gA_Checkpoints[client].ShiftUp(position-1);
	gA_Checkpoints[client].SetArray(position-1, cpcache);
```

**Comment by rtldg** [comment]
although, I guess it doesn't account for players not having checkpoints still

**Comment by sh4hrazad** [comment]
still
```
L 03/19/2022 - 19:23:50: [SM] Exception reported: Invalid index 3 (count: 3)
L 03/19/2022 - 19:23:52: [SM] Blaming: shavit-checkpoints-original.smx
L 03/19/2022 - 19:23:52: [SM] Call stack trace:
L 03/19/2022 - 19:23:52: [SM]   [0] ArrayList.ShiftUp
L 03/19/2022 - 19:23:52: [SM]   [1] Line 1820, .\shavit-checkpoints-original.sp::Native_SetCheckpoint
L 03/19/2022 - 19:23:52: [SM]   [3] Shavit_SetCheckpoint
L 03/19/2022 - 19:23:52: [SM]   [4] Line 351, .\shavit-globalcp2.sp::SaveGlobalCheckpoint
L 03/19/2022 - 19:23:52: [SM]   [5] Line 135, .\shavit-globalcp2.sp::Command_GetCheckpoint
```

**Comment by rtldg** [comment]
I made a commit that kind of copies the position stuff from another function. Can you check if this commit works for you https://github.com/shavitush/bhoptimer/commit/91ec294f423def449dee616f9a4f7ea0b335abda

**Comment by sh4hrazad** [comment]
It solved when `index` is not -1, 
but error still occured when `index` is -1. It's still attempting to insert the checkpoint into an unexisted index.

I tried editing this line
```sourcepawn
// shavit-checkpoints.sp line 1859
// original
    if (gA_Checkpoints[client].Length >= position)
// edited
    if (gA_Checkpoints[client].Length > position)
```
and solved.

**Comment by sh4hrazad** [comment]
another issue on `cheapCloneHandle=false`
```
L 03/19/2022 - 20:21:38: [SM] Exception reported: Handle 9d1201a3 cannot be cloned because it is invalid (error 3)
L 03/19/2022 - 20:21:38: [SM] Blaming: shavit-checkpoints.smx
L 03/19/2022 - 20:21:38: [SM] Call stack trace:
L 03/19/2022 - 20:21:38: [SM]   [0] CloneHandle
L 03/19/2022 - 20:21:38: [SM]   [1] Line 1857, .\shavit-checkpoints.sp::Native_SetCheckpoint
L 03/19/2022 - 20:21:38: [SM]   [3] Shavit_SetCheckpoint
L 03/19/2022 - 20:21:38: [SM]   [4] Line 354, .\shavit-globalcp2.sp::SaveGlobalCheckpoint
L 03/19/2022 - 20:21:38: [SM]   [5] Line 138, .\shavit-globalcp2.sp::Command_GetCheckpoint
```

**Comment by rtldg** [comment]
> It solved when `index` is not -1, but error still occured when `index` is -1. It's still attempting to insert the checkpoint into an unexisted index.
> 
> I tried editing this line
> 
> ```sourcepawn
> // shavit-checkpoints.sp line 1859
> // original
>     if (gA_Checkpoints[client].Length >= position)
> // edited
>     if (gA_Checkpoints[client].Length > position)
> ```
> 
> and solved.

Alright, I think the latest commit should now work correctly for this [9d1201a3 ](https://github.com/shavitush/bhoptimer/commit/8f59007d1d59c34c4b24c13de1c4fe207a3b20f5)

**Comment by sh4hrazad** [comment]
should only do PushArray() when `index` is -1 emm..
```
L 03/19/2022 - 20:39:13: [SM] Exception reported: Invalid index 3 (count: 3)
L 03/19/2022 - 20:39:13: [SM] Blaming: shavit-checkpoints.smx
L 03/19/2022 - 20:39:13: [SM] Call stack trace:
L 03/19/2022 - 20:39:13: [SM]   [0] ArrayList.ShiftUp
L 03/19/2022 - 20:39:13: [SM]   [1] Line 1881, .\shavit-checkpoints.sp::Native_SetCheckpoint
L 03/19/2022 - 20:39:13: [SM]   [3] Shavit_SetCheckpoint
L 03/19/2022 - 20:39:13: [SM]   [4] Line 355, .\shavit-globalcp2.sp::SaveGlobalCheckpoint
L 03/19/2022 - 20:39:13: [SM]   [5] Line 138, .\shavit-globalcp2.sp::Command_GetCheckpoint
```

**Comment by rtldg** [comment]
Shit, I forgot to add something for checking if the array has anything before shifting

**Comment by rtldg** [comment]
my brain stopped working. hopefully this solves the last of the errors https://github.com/shavitush/bhoptimer/commit/ea9a96271125659f252787840013b01e108633f5

**Comment by sh4hrazad** [comment]
It worked thx.
btw maybe could add a native called Shavit_TeleportToCheckpointCache which can teleport us to an appointed cpcache directly.

**Comment by rtldg** [comment]
> It worked thx. btw maybe could add a native called Shavit_TeleportToCheckpointCache which can teleport us to an appointed cpcache directly.

That sounds like a useful native to have. I'll look into adding it tomorrow

**Comment by rtldg** [comment]
> It worked thx. btw maybe could add a native called Shavit_TeleportToCheckpointCache which can teleport us to an appointed cpcache directly.

added `Shavit_LoadCheckpointCache` & `Shavit_SaveCheckpointCache` in https://github.com/shavitush/bhoptimer/commit/86af6ca07ba18f6c401b662159a8323fea85ad60
Let me know if there's any problems with it or you have anything you want changed

**Comment by sh4hrazad** [comment]
Nice native :D

Found a bug maybe. 
I was freezed after I loaded a checkpoint that `Shavit_SavaCheckpointCache`'d on a replaybot.

Nothing blamed in console.
code:
```sourcepawn
// save
Shavit_SaveCheckpointCache(client, checkpoint.cpcache, -1, sizeof(cp_cache_t));
```

**Comment by rtldg** [comment]
It's probably best to avoid using `-1` as the index on replay bots. `0` would probably be better.
Also it might need something before the `Shavit_SaveCheckpointCache()` like this to make sure the bot is currently replaying something: (checkpointing a central !replay bot idling could cause problems I think)
https://github.com/shavitush/bhoptimer/blob/86af6ca07ba18f6c401b662159a8323fea85ad60/addons/sourcemod/scripting/shavit-checkpoints.sp#L1402-L1413

**Comment by sh4hrazad** [comment]
No, `index  = 0` still makes me stuck in the air.
My plugin should not be able to checkpoint an idling replay bot because I write it into `Shavit_OnSave`

**Comment by rtldg** [comment]
> No, `index = 0` still makes me stuck in the air.

Hmm, not sure then. I'll test it in a bit.

> ... because I write it into `Shavit_OnSave`

You're using `Shavit_SaveCheckpointCache` inside `Shavit_OnSave`? If so then you could probably use the `Shavit_OnCheckpointCacheSaved` forward and check if `index > 0` and then save the cp_cache_t you get from that (and clone any handles you want to keep of course too)

**Comment by sh4hrazad** [comment]
> > No, `index = 0` still makes me stuck in the air.
>
>
> Hmm, not sure then. I'll test it in a bit.

wait, seems that any checkpoints that saved in spectator will make me stuck o.O


> You're using `Shavit_SaveCheckpointCache` inside `Shavit_OnSave`? If so then you could probably use the `Shavit_OnCheckpointCacheSaved` forward and check if `index > 0` and then save the cp_cache_t you get from that (and clone any handles you want to keep of course too)

ok i will have a try

**Comment by sh4hrazad** [comment]
> > You're using `Shavit_SaveCheckpointCache` inside `Shavit_OnSave`? If so then you could probably use the `Shavit_OnCheckpointCacheSaved` forward and check if `index > 0` and then save the cp_cache_t you get from that (and clone any handles you want to keep of course too)
> 
> ok i will have a try

still not, but i overwrited `cpcache.fVelocity` and solved..??
```sourcepawn
    if (IsClientObserver(client)) {
        GetEntPropVector(client, Prop_Data, "m_vecAbsVelocity", checkpoint.cpcache.fVelocity);
    }
```

**Comment by rtldg** [comment]
Oh, wait, that kind of sounds like it's calling `Shavit_SaveCheckpointCache` on a player who is in spectator instead of the player who is being spectated. You might want to copy some of the code from this function but mainly the `GetSpectatorTarget()`
https://github.com/shavitush/bhoptimer/blob/86af6ca07ba18f6c401b662159a8323fea85ad60/addons/sourcemod/scripting/shavit-checkpoints.sp#L1350-L1372

**Comment by sh4hrazad** [comment]
Maybe we could add a parameter called `target` for `Shavit_SaveCheckpointCache` to appoint a target ourselves?
I think the reason why I can't move on teleporting to a checkpoint that was saved by spectators is `target = client`
