### ISSUE TITLE
[API Request] Also call Shavit_OnDelete() on player resets their checkpoints

### ISSUE THREAD

**Issue by sh4hrazad** [shavitush/bhoptimer#1138]
Because that `deletes` checkpoints, too.

**Comment by Ciallo-Ani** [comment]
should be a new forward

**Comment by sh4hrazad** [comment]
> https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/include/shavit/checkpoints.inc#L99

I know, but I'd like to call it when we reset the checkpoint.
https://github.com/shavitush/bhoptimer/blob/ea3bd051242527268ee6bdfcf1a3011a2d6a3bcf/addons/sourcemod/scripting/shavit-checkpoints.sp#L771-L775

**Comment by Nairdaa** [comment]
That function is to delete all the checkpoints, not just one. There is no need for such native, that removes all your checkpoints. Like... what would be the use of it anyway?
