### ISSUE TITLE
Random sprites when placing first point?

### ISSUE THREAD

**Issue by StrafeHack** [shavitush/bhoptimer#114]
I'm not sure if you mean to add this but now I see the two top beams of the zone before even placing the first point...

Here they are: http://i.imgur.com/Ihzyclm.jpg

My suggestion was to just see this beam at my feat, then show the box as you walk away from the first point: http://i.imgur.com/oM4gpPL.jpg

**Comment by shavitush** [comment]
this is unintended, i actually didn't look up when i tested so i didn't see those LOL
