### ISSUE TITLE
Exception reported: Array index out-of-bounds (index 108, limit 66)

### ISSUE THREAD

**Issue by freakexeuLow** [shavitush/bhoptimer#1140]
hey and just wanted to report something...have seen the error for the first time since I use the version (Bhoptimer Version: v3.1.3) :)

L 04/14/2022 - 20:35:47: SourceMod error session started
L 04/14/2022 - 20:35:47: Info (map "bhop_xorex") (file "/home/user2/server/csgo/csgo/addons/sourcemod/logs/errors_20220414.log")
L 04/14/2022 - 20:35:47: [SM] Exception reported: Array index out-of-bounds (index 108, limit 66)
L 04/14/2022 - 20:35:47: [SM] Blaming: shavit-replay-playback.smx
L 04/14/2022 - 20:35:47: [SM] Call stack trace:
L 04/14/2022 - 20:35:47: [SM]   [1] Line 2404, C:\Users\freak\Desktop\YEP\shavit\sm 1.10\addons\sourcemod\scripting\shavit-replay-playback.sp::ReplayOnPlayerRunCmd
L 04/14/2022 - 20:35:47: [SM]   [2] Line 3547, C:\Users\freak\Desktop\YEP\shavit\sm 1.10\addons\sourcemod\scripting\shavit-replay-playback.sp::OnGameFrame
L 04/14/2022 - 20:35:47: [SM] Exception reported: Array index out-of-bounds (index 108, limit 66)

**Comment by Nairdaa** [comment]
I blame 🥑

**Comment by freakexeuLow** [comment]
> I blame 🥑

happens, he still does very good work

**Comment by rtldg** [comment]
this should be fixed by https://github.com/shavitush/bhoptimer/commit/70f29d3ca55a9f70d64f74ac9059c3cd1ab00a7a
you can grab a built shavit-replay-playback.smx with the patch in [bhoptimer-v3.1.3-2.zip](https://github.com/shavitush/bhoptimer/releases/download/v3.1.3/bhoptimer-v3.1.3-2.zip) on the releases page.
