### ISSUE TITLE
Exception reported: Invalid database Handle 0 (error: 4)

### ISSUE THREAD

**Issue by MaanKoloo** [shavitush/bhoptimer#1145]
i get this when i try to create a zone, mapzone was not created in my database but other tables yes.

`L 05/22/2022 - 08:10:36: [SM] Exception reported: Invalid database Handle 0 (error: 4)

L 05/22/2022 - 08:10:36: [SM] Blaming: shavit-zones.smx

L 05/22/2022 - 08:10:36: [SM] Call stack trace:

L 05/22/2022 - 08:10:36: [SM]   [0] Database.Query

L 05/22/2022 - 08:10:36: [SM]   [1] Line 182, D:\sourcemod-1.10.0-git6528-windows_v3.2.0\addons\sourcemod\scripting\include\shavit/core.inc::Database2.Query2

L 05/22/2022 - 08:10:36: [SM]   [2] Line 3661, D:\sourcemod-1.10.0-git6528-windows_v3.2.0\addons\sourcemod\scripting\shavit-zones.sp::InsertZone

L 05/22/2022 - 08:10:36: [SM]   [3] Line 3297, D:\sourcemod-1.10.0-git6528-windows_v3.2.0\addons\sourcemod\scripting\shavit-zones.sp::CreateZoneConfirm_Handler`

running on pterodactyl panel. using sourcemod 1.10.0 linux version

**Comment by rtldg** [comment]
Do you have your `shavit` database configured in `sourcemod/configs/databases.cfg` and is it loading?

If your database isn't configured, or if it failed to connect, the database handle can be invalid.

**Comment by MaanKoloo** [comment]
yes, I have it configured, even some tables were already created automatically in it, but mapzone could not be created

**Comment by rtldg** [comment]
you should double triple quadruple check everything on your end. try to figure out if your db is connecting or not because this error won't happen if your db connects fine. check your error logs to see if there's anything about database connections timing out or something.

**Comment by rtldg** [comment]
closing since it's been a while and there's been no response. if you have an errors to post then feel free to comment again here
