### ISSUE TITLE
[Request] print steamid as an option in the wr menus

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#1146]
when you !wr and browse through the players, could we please get an option to "print player steamid" under "player stats" or have it printed automatically into the chat when you choose "player stats"?

just so that you can get it right away and copy paste rather than having to retype manually from the menu popup

**Comment by rtldg** [comment]
I’ll add something for this so looking at a time in !wr prints the steamid. Will likely add a shavit-core native to track the last steamid printed so it doesn’t spam or print twice from shavit-stats and shavit-wr

**Comment by rtldg** [comment]
it should now do this. i'm tempted to add an array of previously printed steamids but i don't think i will for now at least. chat spammingggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
