### ISSUE TITLE
MySQL is the only supported database engine for shavit-rankings.

### ISSUE THREAD

**Issue by dowoge** [shavitush/bhoptimer#1148]
```
L 06/22/2022 - 23:42:24: [SM] Exception reported: MySQL is the only supported database engine for shavit-rankings.
L 06/22/2022 - 23:42:24: [SM] Blaming: shavit-rankings.smx
L 06/22/2022 - 23:42:24: [SM] Call stack trace:
L 06/22/2022 - 23:42:24: [SM]   [0] SetFailState
L 06/22/2022 - 23:42:24: [SM]   [1] Line 229, D:\sourcemod-1.10.0-git6528-windows_v3.2.0\addons\sourcemod\scripting\shavit-rankings.sp::Shavit_OnDatabaseLoaded
L 06/22/2022 - 23:42:24: [SM]   [3] Call_Finish
L 06/22/2022 - 23:42:24: [SM]   [4] Line 69, D:\sourcemod-1.10.0-git6528-windows_v3.2.0\addons\sourcemod\scripting\include\shavit/sql-create-tables-and-migrations.sp::RunOnDatabaseLoadedForward
L 06/22/2022 - 23:42:24: [SM]   [5] Line 245, D:\sourcemod-1.10.0-git6528-windows_v3.2.0\addons\sourcemod\scripting\include\shavit/sql-create-tables-and-migrations.sp::Trans_CreateTables_Success
```

is there any way to make it work with sqlite? im not really sure what to do

**Comment by dowoge** [comment]
will it ever be supported? assuming you said "right now" im guessing yes

**Comment by rtldg** [comment]
Yeah, it'll probably be supported. I did some work on it earlier to make some queries compatible (& to prepare for postgresql support in sourcemod 1.11). The main point recalculation queries need sqlite versions afaict though so that's the main thing left

**Comment by dowoge** [comment]
oh well thats good to know, i hope itll be compatible soon

**Comment by rtldg** [comment]
shavit-rankings should work with sqlite in the master branch now and in next release.
Using `shavit_rankings_weighting 1.0` should work fine.
Using `shavit_rankings_weighting 0.xxxx` will require using dbi.sqlite.ext{.dll,.so} Sourcemod 1.12.
