### ISSUE TITLE
[fix or remove] shavit_core_blockprejump

### ISSUE THREAD

**Issue by Uronic** [shavitush/bhoptimer#1151]
// Prevents jumping in the start zone.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
shavit_core_blockprejump "0"

This causes issues with players not being able to jump if no zones exist if enabled. Plus it is pretty useless I think since there is this setting already:
// Stop prespeeding in the start zone?
// 0 - Disabled, fully allow prespeeding.
// 1 - Limit relatively to prestrafelimit.
// 2 - Block bunnyhopping in startzone.
// 3 - Limit to prestrafelimit and block bunnyhopping.
// 4 - Limit to prestrafelimit but allow prespeeding. Combine with shavit_core_nozaxisspeed 1 for SourceCode timer's behavior.
// 5 - Limit horizontal speed to prestrafe but allow prespeeding.
// -
// Default: "2"
// Minimum: "0.000000"
// Maximum: "5.000000"
shavit_misc_prespeed "3"

**Comment by rtldg** [comment]
> This causes issues with players not being able to jump if no zones exist if enabled.

Wasn't able to reproduce this on a map without zones.

> Plus it is pretty useless I think since there is this setting already (`shavit_misc_prespeed`):

True, but I'll leave it since someone might want to keep using it. It's disabled by default currently so new servers shouldn't run into problems with it anyway.
