### ISSUE TITLE
Mapchooser has issues with workshop maps when getting maps straight from DB

### ISSUE THREAD

**Issue by Uronic** [shavitush/bhoptimer#1152]
When you choose the setting to get the map names for the mapchooser from the DB confirmed by maps folder, and the maps are workshop maps or I guess maps that are in subfolders, it will show the whole path instead of just the map name.

**Comment by rtldg** [comment]
![image](https://user-images.githubusercontent.com/55846624/178277783-3e87affb-6442-4056-b7e2-064084c203c8.png)
can't reproduce. what version is your shavit-mapchooser and do you perhaps have multiple mapchooser plugins loaded?
