### ISSUE TITLE
Gains too low

### ISSUE THREAD

**Issue by OstoraSiraj** [shavitush/bhoptimer#1153]
Hello, i switched from opentimer to this for my bhop maps testings but i am having a problem
when playing on normal with autobhop on, my gains are too low, i checked the config but eveything seems fine (accelerate 5, airaccelerate 1000, ...)
i provided 2 videos to compare, the 1st is from my lan server, the 2nd is EUFrag which also uses this timer afaik.
https://streamable.com/tv5z14
https://streamable.com/40p9ib

**Comment by rtldg** [comment]
CSS bhop servers are 99% 100 tick these days. Testing with 66 tick gives me similar results as your video. It's likely you're missing the extension that CSS servers need to change the tickrate.

Grab tickrate_enabler from here and then add `-tickrate 100` to your srcds launch options.

**Comment by rtldg** [comment]
forgot link https://github.com/daemon32/tickrate_enabler/releases/tag/0.5

**Comment by OstoraSiraj** [comment]
Thanks, i didn't know that tikrate has to do with this
