### ISSUE TITLE
!admin Timer commands disappeared

### ISSUE THREAD

**Issue by SKYPIXEL45** [shavitush/bhoptimer#1154]
![image](https://user-images.githubusercontent.com/78598338/179334688-07aca01d-dfd4-47c4-aaf0-00156c4574f7.png)
(timer version:3.3.1) And the console doesn't report any errors

**Comment by rtldg** [comment]
did you figure out what the problem was?

**Comment by SKYPIXEL45** [comment]
Yeah,I don't know if it's a coincidence, but after encountering this problem I tried to find it in the commits. 
When I directly change the version like this: 3.3.0-4 → 3.3.1, the option of "Timer Commands" disappears. 
When I changed the version like this: 3.3.0-4 → fb42a370fe3ed28130f8bea0ff4cd82d6e191d94 → 3.3.1 
,"Timer Commands" appeared .
