### ISSUE TITLE
!czone settings cant be saved

### ISSUE THREAD

**Issue by SKYPIXEL45** [shavitush/bhoptimer#1155]
I use !czone to edit the zone, it will return to the default settings when I rejoin the server. How to enable my server to save !czone settings?(the "!hud" settings can be saved normally)

**Comment by Nairdaa** [comment]
Because the hud settings are saved by SM in clientprefs, while the zones are stored in a database. Set your database up properly.

**Comment by rtldg** [comment]
The czone settings are stored in clientprefs/cookies too so they're not doing anything wrong. I think the sqlite clientprefs db now hates the non-unicode-compatible cookie string I did. Haven't been able to test more yet

**Comment by SKYPIXEL45** [comment]
![image](https://user-images.githubusercontent.com/78598338/179886043-4c9a82d4-acf8-4d87-a760-afe4ef3ec6c9.png)
I used navicat to query sm_cookies, and there is no record of shavit_czone....emmm, is this my problem?

**Comment by rtldg** [comment]
This should be fixed in https://github.com/shavitush/bhoptimer/commit/1e7459a6c4da93a0082d67053949e5076b17ca51
I'll make a release later today that includes it
