### ISSUE TITLE
sm_profile/sm_rank etc. targetting bots

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#116]
These commands shouldn't be able to target bots, if you use sm_profile etc. and there's a bot with that name on the server, the client is unable to target the user D:

**Comment by shavitush** [comment]
i can't change it

**Comment by StrafeHack** [comment]
@shavitush 
You can, the FindTarget stock has a bool to toggle bot targeting, it's the 3rd arg I believe.

**Comment by StrafeHack** [comment]
I usually put WRName in the team tag and style - time in the name if that helps give you any ideas.

**Comment by shavitush** [comment]
i think it won't be the best for css
