### ISSUE TITLE
How to turn TIMEDIFFERENCE in hud (IN REAL TIME)

### ISSUE THREAD

**Issue by lllLORD2000lll** [shavitush/bhoptimer#1166]
I did this before, but now it doesn't work. After a certain update, it stopped working.

**Comment by Nairdaa** [comment]
https://github.com/shavitush/bhoptimer#readme

**Comment by lllLORD2000lll** [comment]
> https://github.com/shavitush/bhoptimer#readme

I wouldn't be asking if that information was there.

**Comment by NukoOoOoOoO** [comment]
>- [sm_closestpos](https://github.com/rtldg/sm_closestpos)
C++ extension to efficiently find the closest replay position for calculating time-difference and velocity-difference.

**Comment by Nairdaa** [comment]
> Author

You literally just did.

**Comment by Nairdaa** [comment]
Thank Nuko for being kind and actually holding your hand to help you with your "issue", that you'd have found on your own if that info was there.

**Comment by lllLORD2000lll** [comment]
Solution: works  only shavit_hud_timedifference "1" and only in cvar force

**Comment by Nairdaa** [comment]
That's not a solution. That's just misleading and you're using an outdated version of the timer. It literally says in the change log of 3.0.0 "shavit_hud_timedifference renamed to shavit_replay_timedifference"

**Comment by Nairdaa** [comment]
Use the updated version of the timer and the correct convars to avoid such problems and misleading people reading the issues for further reference.

**Comment by lllLORD2000lll** [comment]
> That's not a solution. That's just misleading and you're using an outdated version of the timer. It literally says in the change log of 3.0.0 "shavit_hud_timedifference renamed to shavit_replay_timedifference"

Previously, this cvar included lagging behind WR anywhere on the map. What value does cvar shavit_replay_timedifference take initially? And has its principle of operation changed?

**Comment by lllLORD2000lll** [comment]
![image](https://user-images.githubusercontent.com/60987370/184437439-a5a9bcf5-8b47-460a-aa8d-6c4b6f00e1ba.png)
It looked like this

**Comment by Nairdaa** [comment]
plugin.shavit-replay-recorder.cfg

**Comment by rtldg** [comment]
> Previously, this cvar included lagging behind WR anywhere on the map.

It still does that.

> What value does cvar shavit_replay_timedifference take initially?

It was changed to a default of `1`

> And has its principle of operation changed?

No

**Comment by rtldg** [comment]
> plugin.shavit-replay-recorder.cfg

plugin.shavit-replay-playback.cfg

**Comment by Nairdaa** [comment]
in b4 he asks where those are located

**Comment by rtldg** [comment]
Going to close this.
Check for timedifference cvars in the `cfg/sourcemod/plugin.shavit-*.cfg` files if you want to enable it.
`sm_closestpos` can be useful too of course.
And you might have to enable it in `!hud` if it's not shown.
