### ISSUE TITLE
shavit_stats_use_mapchooser not compatible with workshop maps

### ISSUE THREAD

**Issue by Uronic** [shavitush/bhoptimer#1168]
When setting shavit_stats_use_mapchooser to 1 on a server using workshop maps, the map count does not show in !profile

**Comment by rtldg** [comment]
I think it's due to shavit-mapchooser storing the maps StringMap (`Shavit_GetMapsStringMap`) with the full map name (`workshop/123123/map`). I'll make it use the stripped/display version.
AFAIK there's no other plugins using `Shavit_GetMapsStringMap` so this should be fine to change

**Comment by rtldg** [comment]
Pretty sure this should work but reopen and let me know if it doesn't
