### ISSUE TITLE
[Bug] Mapchooser 

### ISSUE THREAD

**Issue by FinnTR** [shavitush/bhoptimer#1178]
When the maps uploaded from the workshop come out in the map voting, sometimes map doesnt change and the current map remains forever. For example workshop/1291055080/bhop_oceanic
smc_maplist_type "1" btw

**Comment by rtldg** [comment]
I just checked and I couldn't reproduce with that map specifically though. (rtving to and using !map)
Does it switch to oceanic when you rtv or use !map?

I know that it can fail to switch if a map is corrupted or invalid for the current game.
I think I've seen it fail with a fine map file though, but if it's just a case of oceanic for you then you could try redownloading the bsp... however workshop addons are redownloaded. I don't really know how tbh but I assume deleting the .bsp might make it reextract or redownload.

**Comment by FinnTR** [comment]
The problem is not in the map file, I can open it manually with sm_map. RTV only occurs this problem with workshop maps.

**Comment by rtldg** [comment]
I'm not having any problems with rtving to workshop maps so I don't know what to suggest.
I *can* get map changing to break if I switch to an invalid map first though so I added some code to prevent invalid maps in some places in shavit-mapchooser
