### ISSUE TITLE
New hud suggestions/issues

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#118]
https://gyazo.com/e4aa83a96b81af4ba0909595d694e308

Time flickers between 0.0 and 0.1 when moving inside the startzone.

When completing maps, timer looks like:

https://gyazo.com/371009dd61a7976fd5f1c59f0bb4c8f2

However would look better if it kept the starting timer, just with "Stopped" instead of 0.0

**Comment by shavitush** [comment]
enable zonehud to get rid of the first one and i highly disagree about having "timer: stopped" for an actual stopped timer

**Comment by Technoblazed** [comment]
Zonehud is ugly as hell though, seems like just a patch over an issue.

**Comment by shavitush** [comment]
feel free to modify it and send a pull request then
