### ISSUE TITLE
[Timer] You cannot add/edit/delete non-sql zones.

### ISSUE THREAD

**Issue by worthless175** [shavitush/bhoptimer#1183]
I just download last release and can't add zones

**Comment by rtldg** [comment]
Check what your `shavit_zones_usesql` cvar is set to in `cfg/sourcemod/plugin.shavit-zones.cfg` as that's what causes that message.
You should set it to `1`. Using `0` for it is intended for usage with standardized zone collections, which aren't too readily available right now.

**Comment by worthless175** [comment]
It fixed, thanks
