### ISSUE TITLE
Strafe count on blocked keys style.

### ISSUE THREAD

**Issue by Sqwanes** [shavitush/bhoptimer#119]
When holding a blocked key (e.g: holding A on W-Only or holding W on Sideways) and jumping at the same time the strafe count go crazy with big numbers.
Cant record a video of this right now /:

**Comment by StrafeHack** [comment]
Yeah sync should really just be completely disabled on single key styles.

**Comment by shavitush** [comment]
solved strafes 59143259370c89882cbc300642e86d69639998b0
i'll add a style property that counts sync (default on normal/scroll/400vel etc) today or tomorrow

**Comment by StrafeHack** [comment]
Awesome idea
