### ISSUE TITLE
Auto-Bhop not working

### ISSUE THREAD

**Issue by lay295** [shavitush/bhoptimer#12]
Hey man just compiled the latest version you have and noticed that auto-bhop doesn't work in the latest version. It spams this error many times in my error logs

[SM] Plugin encountered error 21: Native is not bound
[SM] Native "Shavit_InsideZone" reported: 
[SM] Displaying call stack trace for plugin "shavit-core.smx":
[SM]   [0]  Line 748, C:\Users\fizzo\AppData\Roaming\spedit\sourcepawn\configs\latest_snapshot\shavit-core.sp::OnPlayerRunCmd()

Old versions work fine, or would something be wrong on my end?

**Comment by shavitush** [comment]
Try updating SourceMod (and MetaMod: Source) to the latest stable
snapshots, please report back!

**Comment by lay295** [comment]
Huh... well that did it, my sourcemod wasn't that old though so I didn't think that was the problem. Thanks!
