### ISSUE TITLE
[Bug] strafe style

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#1212]
Even tho there is a freestyle zone, your speed will still be limited to the maximum prestrafe speed.

**Comment by rtldg** [comment]
Freestyle zones are for things like sideways to allow blocked keys.
Use Custom Speed Limit zones if you want to change the speed of somewhere for styles like `_strafe` and `400vel`

**Comment by Nairdaa** [comment]
Still doesn't work.

**Comment by Nairdaa** [comment]
I've tested out with Freestyle, Custom speed limit, easyhop. No go.

**Comment by Nairdaa** [comment]
Just doesn't work with _strafe. Work with any other style.

**Comment by rtldg** [comment]
I misunderstood and also forgot that the `_strafe` style uses `"bunnyhopping" "0"` / `sv_enablebunnyhopping`. I don't really like using the zones to make styles possible when they wouldn't/shouldn't be but fuck it. I could make it a flag that you'd have to toggle on the Custom Speed Limit zones but I think I will just make them replicate `sv_enablebunnyhopping 1` to the client.
