### ISSUE TITLE
add SSJ

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#122]
height, end speed, speed gain and to reset everything when speed is 0

**Comment by Nickelony** [comment]
Is this is something like Fastrun (2k speed on 1st jump) or CrazySpeed (+250 speed per jump) from cs 1.6?

**Comment by shavitush** [comment]
just chat output, like that:

```[Timer] Jump: 6 | Speed: 456 | Speed Δ: 255 | Height Δ: 1 | Gain: 50.52%```
