### ISSUE TITLE
shavit_misc_scoreboard "1" Doesn't appear to be working

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#125]
shavit_misc_scoreboard "1" doesn't seem to be working, no changes to the scoreboard D:

**Comment by shavitush** [comment]
error logs?

**Comment by shavitush** [comment]
this is how it should look btw

![de_nuke0006](https://cloud.githubusercontent.com/assets/3672466/17344006/2efe27ca-5909-11e6-9b7b-04d07ae39360.jpg)

**Comment by Technoblazed** [comment]
No error logs, kills stays at 0, deaths at 0, and score at -50

**Comment by shavitush** [comment]
kills should stay at 0 in csgo but score should change so sorting will take effect. score should be -50 if your PB on the map is 50 seconds
i guess deaths are buggy in csgo, maybe a different netprop is needed.. i'll look into it later

**Comment by shavitush** [comment]
what is the output of `sm_rank`?

**Comment by Technoblazed** [comment]
Updated the code again, seems to be working normally again now, apologies
