### ISSUE TITLE
Running !glock on ct/!usp on t doesn't work

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#126]

**Comment by shavitush** [comment]
i hate valve

**Comment by Technoblazed** [comment]
`L 08/02/2016 - 15:01:04: [SM] Exception reported: Entity -1 (-1) is invalid
L 08/02/2016 - 15:01:04: [SM] Blaming: shavit-misc.smx()
L 08/02/2016 - 15:01:04: [SM] Call stack trace:
L 08/02/2016 - 15:01:04: [SM]   [0] GetEntProp
L 08/02/2016 - 15:01:04: [SM]   [1] Line 760, C:\Users\anthony\Desktop\bhop\shavit-misc.sp::SetWeaponAmmo()
L 08/02/2016 - 15:01:04: [SM]   [2] Line 752, C:\Users\anthony\Desktop\bhop\shavit-misc.sp::Command_Weapon()
L 08/02/2016 - 15:01:07: [SM] Exception reported: Entity -1 (-1) is invalid
L 08/02/2016 - 15:01:07: [SM] Blaming: shavit-misc.smx()
L 08/02/2016 - 15:01:07: [SM] Call stack trace:
L 08/02/2016 - 15:01:07: [SM]   [0] GetEntProp
L 08/02/2016 - 15:01:07: [SM]   [1] Line 760, C:\Users\anthony\Desktop\bhop\shavit-misc.sp::SetWeaponAmmo()
L 08/02/2016 - 15:01:07: [SM]   [2] Line 752, C:\Users\anthony\Desktop\bhop\shavit-misc.sp::Command_Weapon()
L 08/02/2016 - 15:01:10: [SM] Exception reported: Entity -1 (-1) is invalid
L 08/02/2016 - 15:01:10: [SM] Blaming: shavit-misc.smx()
L 08/02/2016 - 15:01:10: [SM] Call stack trace:
L 08/02/2016 - 15:01:10: [SM]   [0] GetEntProp
L 08/02/2016 - 15:01:10: [SM]   [1] Line 760, C:\Users\anthony\Desktop\bhop\shavit-misc.sp::SetWeaponAmmo()
L 08/02/2016 - 15:01:10: [SM]   [2] Line 752, C:\Users\anthony\Desktop\bhop\shavit-misc.sp::Command_Weapon()
L 08/02/2016 - 15:01:14: [SM] Exception reported: Entity -1 (-1) is invalid
L 08/02/2016 - 15:01:14: [SM] Blaming: shavit-misc.smx()
L 08/02/2016 - 15:01:14: [SM] Call stack trace:
L 08/02/2016 - 15:01:14: [SM]   [0] GetEntProp
L 08/02/2016 - 15:01:14: [SM]   [1] Line 760, C:\Users\anthony\Desktop\bhop\shavit-misc.sp::SetWeaponAmmo()
L 08/02/2016 - 15:01:14: [SM]   [2] Line 752, C:\Users\anthony\Desktop\bhop\shavit-misc.sp::Command_Weapon()
L 08/02/2016 - 15:01:18: [SM] Exception reported: Entity -1 (-1) is invalid
L 08/02/2016 - 15:01:18: [SM] Blaming: shavit-misc.smx()
L 08/02/2016 - 15:01:18: [SM] Call stack trace:
L 08/02/2016 - 15:01:18: [SM]   [0] GetEntProp
L 08/02/2016 - 15:01:18: [SM]   [1] Line 760, C:\Users\anthony\Desktop\bhop\shavit-misc.sp::SetWeaponAmmo()
L 08/02/2016 - 15:01:18: [SM]   [2] Line 752, C:\Users\anthony\Desktop\bhop\shavit-misc.sp::Command_Weapon()`

**Comment by shavitush** [comment]
thanks for error log
