### ISSUE TITLE
Bot issue back again

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#128]
https://gyazo.com/15e67b2e04c9c316b778044f76e5a977

Looks like it's back again, the bot is actually playing a record, but it's giving it the name of an unranked bot :D

**Comment by shavitush** [comment]
do you by any chance have a replay file but not a WR in the server?

**Comment by shavitush** [comment]
actually what i've done was totally wrong, it's fixed now. it only affected servers using the old style names (like yours)

**Comment by Technoblazed** [comment]
Still an issue

**Comment by shavitush** [comment]
i'm unable to replicate this issue with both sqlite/mysql
does it happen with the default naming style?

**Comment by Technoblazed** [comment]
Default works fine, just when the alternative is used

**Comment by shavitush** [comment]
finally
