### ISSUE TITLE
Problem with webinterface

### ISSUE THREAD

**Issue by PtxDK** [shavitush/bhoptimer#13]
Fatal error: Call to a member function close() on boolean in timer.php on line 159

**Comment by shavitush** [comment]
This error should happen only if the prepared query was not sent.  
Did you change config.php?

**Comment by PtxDK** [comment]
Yes. I am using pretty much the same things as in my databases.cfg from sourcemod.

I am convinced that it connects to the database.

**Comment by shavitush** [comment]
I'll push a commit to `timer.php` that should fix it.  
Reopen this issue if it doesn't fix please!

**Comment by PtxDK** [comment]
I might be doing something wrong here..

My databasetable 'playertimes' looks like: http://prntscr.com/ab0p88

Then I look at bhop.php in the browser i get: http://prntscr.com/ab0q8n (Which would make one believe that it's connected)

But then I click show results on fx. bhop_forest, i get no results
http://prntscr.com/ab0qv8

**Comment by shavitush** [comment]
Can you set your PHP to report every error?

**Comment by PtxDK** [comment]
My Php.ini already has:
error_reporting = E_ALL & ~E_DEPICATED & ~E_STRICT
display_errors = On
display_startup_errors = Off
log_errors = On

In my log i have not found any related errors, I can PM you a gist with the complete log if you wish, but only 'missing file' errors(me trying to view not existing files) and 'ssl' warnnings is present.

Also no new errors goes into the log then i try to view timer.php with the map-query.

**Comment by shavitush** [comment]
Understood.  
I will rewrite the whole web interface and also implement some generic bootstrappy design and then reopen the issue so you can start testing again.
