### ISSUE TITLE
add bonus timer

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#133]
Checklist:

- [x] Database migration (add `track` integer to zones table).
- [x] Zone setup, toggle bonus/main track from zone setup menu.
- [x] Insert bonus zones to database.
- [x] Cache zone bonus status, load them from database.
- [x] Draw bonus zones too.
- [x] Bonus zone deletion.
- [x] Add natives where needed.
- [x] HUD integration for CS:S. I need someone else to do the CS:GO part, as I don't play CS:GO.
- [x] `sm_b`, etc
- [x] Database migration (add `track` integer to records table).
- [x] `sm_bwr`, etc
- [x] Separate the leaderboards arrays.
- [x] Insert bonus records to database, separated from main records,
- [x] Figure out how to implement replay bots.
- [x] Menus, record deletion etc.

**Comment by StrafeHack** [comment]
Will there be support for multiple bonuses on 1 map?

**Comment by shavitush** [comment]
probably not

**Comment by shavitush** [comment]
btw are bonus replays for the default style needed?

**Comment by StrafeHack** [comment]
Uhm, I was under the impression you would do replays for every style...

But that would probably require !replay first otherwise servers will be overloaded with bots

**Comment by shavitush** [comment]
i feel like bonus replays per style would just cause massive disk space usage

**Comment by StrafeHack** [comment]
Do you mean to store the replays would use too much space?

**Comment by shavitush** [comment]
both that and bonus replays for every style wouldn't really be needed as the default style will already show the WR route

**Comment by StrafeHack** [comment]
True, I agree.

But as this timer already has a lot of user preference options I would like to see a cvar to enable all bonus replays or just the default style, maybe even an all off option.

**Comment by Technoblazed** [comment]
What about doing the same thing that you did with the REPLAY function in shavit.inc, just create a bonus one as well. Easier to manage and makes it up for the server owners. Although default would probably be the only used one.

**Comment by StrafeHack** [comment]
True that could work, just might be a bit messy if there's one of those to enable bonuses on that style aswell.

**Comment by Technoblazed** [comment]
People like customizable, what can I say \o/ @StrafeHack

**Comment by shavitush** [comment]
decided i might just try to implement a system of tracks where you can just add them from a config file; example

```
"Tracks"
{
	"0"
	{
		"name"		"Main"
		"wr"		"wr; worldrecord; worldrecords"
	}

	"1"
	{
		"name"		"Bonus #1"
		"wr"		"bwr; bonuswr"
	}

	"2"
	{
		"name"		"Bonus #2"
		"wr"		"bwr2; bonuswr2"
	}
}
```

anyone in? or should i just do main/bonus like bTimes?

**Comment by Nickelony** [comment]
I think 1 bonus track is enough. More bonuses could confuse players and I've never seen any bhop / speedrun map with more than 1 bonus stage.

**Comment by Technoblazed** [comment]
I have bhop maps with 4 o.O

**Comment by Technoblazed** [comment]
Would the tracks have reverse compatibility with zones already created, or a system in place to convert zones to a track?

**Comment by shavitush** [comment]
Going to start the work on this today. Added a checklist to OP.

**Comment by shavitush** [comment]
Going to start work on this now.

Keep in mind that I'll only implement 2 hardcoded tracks (bonus timer), because to be fair, you never need more than 2 for a bhop server.

However, it won't be so hardcoded to 2 like I did with normal/sideways styles at the first versions of this timer. It won't be too hard to add your own tracks but I won't support the addition of more, because maintaining more code isn't easy.

**Comment by strafe** [comment]
Will #402 be finished before this and will that option be available for bonus bots too?

**Comment by shavitush** [comment]
I doubt it, I'm almost done (see #435).
And yes, #402 will have bonuses too when finished.
