### ISSUE TITLE
SCP shavit-chat error

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#135]
L 08/03/2016 - 15:35:19: [SM] Exception reported: Invalid field "params" for message "CCSUsrMsg_SayText2"
L 08/03/2016 - 15:35:19: [SM] Blaming: simple-chatprocessor.smx()
L 08/03/2016 - 15:35:19: [SM] Call stack trace:
L 08/03/2016 - 15:35:19: [SM]   [0] PbReadString
L 08/03/2016 - 15:35:19: [SM]   [1] Line 353, C:\Users\anthony\Desktop\JoshOG\Sourcemod\addons\sourcemod\scripting\simple-chatprocessor.sp::OnSayText2()
L 08/03/2016 - 15:35:27: Error log file session closed.

Probably a dumb version of SCP that I downloaded, any ideas?

**Comment by shavitush** [comment]
can you attach the error?

**Comment by Technoblazed** [comment]
Yeah, hit enter by accident lol

**Comment by shavitush** [comment]
it's an issue with SCP i'm 100% sure

**Comment by Technoblazed** [comment]
Mind if I ask where you got your scp from?

**Comment by shavitush** [comment]
https://bitbucket.org/minimoney1/simple-chat-processor

i simply edited the scp.inc file i provided in my repository to work with the transitional syntax

**Comment by Technoblazed** [comment]
Same error using your scp file, I wonder what's going on

**Comment by shavitush** [comment]
quite weird.. try leaving a reply in simple chat processor (redux)'s thread

**Comment by Technoblazed** [comment]
Your scp works over both games ye? D:

**Comment by shavitush** [comment]
it's just an include file so yeah
