### ISSUE TITLE
Tier issue?

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#136]
I'll explain it as it happened:

#### Player Connect
 [OG] bhop_at_night_csgo is rated tier 1.
#### Player Type
Techno : test
#### !rank
 [OG] Techno is unranked.
#### /setpoints (Was checking what to use)
Usage: sm_setpoints <time in seconds> <points>
#### /setpoints 60 1000
Set 1000.0 points for 1:00.0.
#### /rank (1/0?)
 [OG] Techno is ranked 1 out of 0 with 7564.31 points.
#### This was spammed \/
 [OG] bhop_at_night_csgo is rated tier 1.
 [OG] bhop_at_night_csgo is rated tier 1.
 [OG] bhop_at_night_csgo is rated tier 1.
 [OG] bhop_at_night_csgo is rated tier 1.
 [OG] bhop_at_night_csgo is rated tier 1.
 [OG] bhop_at_night_csgo is rated tier 1.

**Comment by shavitush** [comment]
after reconnecting, does it become '1 out of 1'?

**Comment by Technoblazed** [comment]
Yea, after reconnect, goes to 1 of 1

**Comment by shavitush** [comment]
yeah it's fine then; i'll make it instantly update when i finish implementing the new points algorithm
