### ISSUE TITLE
Player opacity doesn't appear to work ,no error logs

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#137]

**Comment by shavitush** [comment]
```
#include <sourcemod>

public void OnPluginStart()
{
	RegConsoleCmd("sm_test", Command_Test);
}

public Action Command_Test(int client, int args)
{
	char[] sClass = new char[32];
	GetEntityNetClass(client, sClass, 32);
	
	ReplyToCommand(client, "%s", sClass);
	
	return Plugin_Handled;
}
```

would be appreciated to get the output of this command in csgo

**Comment by StrafeHack** [comment]
>CCSPlayer

**Comment by shavitush** [comment]
@StrafeHack thanks

@Technoblazed 
shavit-misc

```
if(gCV_PlayerOpacity.IntValue != -1 && FindSendPropInfo("CCSPlayer", "m_nRenderFX") != -1)
```
>>
```
if(gCV_PlayerOpacity.IntValue != -1)
```

does it work?

**Comment by Technoblazed** [comment]
Nope

**Comment by shavitush** [comment]
it might be just unavailable for csgo, i'll check it later

**Comment by Technoblazed** [comment]
KZ Timer definitely uses it, I'll take a look into it

**Comment by StrafeHack** [comment]
@shavitush does this have nothing to do with it or was Mitchell wrong?
>– Added a convar (sv_disable_immunity_alpha) that when set, allows mods to handle their own alpha on players.

**Comment by shavitush** [comment]
gotcha, i'll add it to the readme! @Technoblazed
