### ISSUE TITLE
SSJ Gain should become loss

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#138]
[OG] Jump: 18 | Speed: 434 | Speed Δ: -49 | Gain: 92.83%

I feel like with that being a change of -49, that it's not a gain

**Comment by shavitush** [comment]
actually no, it's not a bug. gain is in relation to the 1st jump (usually 250 speed or so)

**Comment by Technoblazed** [comment]
Ah, thanks for clearing that out :D
