### ISSUE TITLE
shavit_core_timernozone doesn't work.

### ISSUE THREAD

**Issue by StrafeHack** [shavitush/bhoptimer#139]
I'm pretty sure I'm not doing anything wrong, this cvar has never worked for me even with the newest version I have just downloaded.

Restarted the server with both 0 and 1 and on completely unzoned maps with no records, replays or anything using sm_r starts the timer.

**Comment by Technoblazed** [comment]
Oh, if a map has an end zone but no start zone, not that it should, if you do !r in the end zone, you get a 0.0001s record

**Comment by StrafeHack** [comment]
Yeah tbh, this shouldn't even really be a cvar, it should be locked off but I guess someone someday might want to turn it off.

**Comment by shavitush** [comment]
my fault, will fix it soon

**Comment by shavitush** [comment]
d06f82e56cb5ae5ed126c0b50af23b4ad56a9bce
