### ISSUE TITLE
!profile Ideas (csgo)

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#142]
```
Player: Techno [U:1:181992512] (*1*)
Country: United Kingdom (*2*)

Rank: 5/10000 (20000) (*3*)
Points: 105000 (*4*)

Map Completion: 70/301 (23%) (*5*)
1 - View completed maps (*6*)
2 - View uncompleted maps (*7*)
Bonus Completion: 120/200 (60%) (*8*)
3 - View completed bonuses (*9*)
4 - View uncompleted bonus (*10*)

Map WRs: 43 (*11*)
Bonus WRs: 5 (*12*)

0 - Close (*13*)
```
---------------------------------------------------------------------
1. Latest playername and Steam3 ID.
2. Country.
3. Server Rank. - 5 = Your rank, 10000 = Total ranked players, 20000 = Total players even without ranks
4. Server Points.
5. Map Completion with % of completed maps.
6. Displays the current !profile page and allows the user to select styles.
7. Displays the current !profile page, however automatically goes to uncompleted maps.
8. Basically the same as 5
9. Basically the same as 6.
10. Basically the same as 7.
11. Display "Normal" map WRs.
12. Display "Normal" bonus WRs.
13. Close the panel.

**Comment by shavitush** [comment]
won't implement 'last online' but ok
