### ISSUE TITLE
modules detect the wrong game

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#146]
![730_screenshots_20160804192632_1](https://cloud.githubusercontent.com/assets/3672466/17413065/6b8dd1a6-5a88-11e6-85eb-101b82f4623b.jpg)

example in chat where the plugin tries to use the css rrggbb colors instead of \x02

goal: remove use of this stupid native and just cache GetEngineVersion() on every module start

**Comment by shavitush** [comment]
also time formatting is missing the minus for negative time above -60

**Comment by StrafeHack** [comment]
Maybe just do GetGameFolderName

The engine way seems cleaner but if it causes this many problems then maybe not.

**Comment by shavitush** [comment]
AFAIK GetGameFolderName is deprecated and GetEngineVersion() should be used instead

**Comment by shavitush** [comment]
i'm pretty sure it's just the other modules being called before shavit-core, maybe due to them being in a subdirectory or something
