### ISSUE TITLE
!profile Further Suggestions

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#149]
- (%) next to completed maps.
- Perhaps putting the style options under another aspect of the menu, "Map Information" etc.

**Comment by shavitush** [comment]
> Perhaps putting the style options under another aspect of the menu, "Map Information" etc.

too much of navigation in menus, sorry

i'll do percentages though

**Comment by StrafeHack** [comment]
@shavitush How come you won't add last online?

**Comment by shavitush** [comment]
The way shavit-stats works right now requires you to use a command and target someone else to open the menu to begin with. To do that, the target user has to be online.
This is subject to change (and will before beta is over) after I will implement a native like `Shavit_OpenStatsMenu(const char[] name, const char[] authid);` which will probably be called from a shavit-wr submenu.

Last online would require logging the last online time, which I didn't do yet (I really don't know why..); it will also be added eventually.

**Comment by StrafeHack** [comment]
Good to know, thanks for the detail

**Comment by shavitush** [comment]
How good is this?

![hl2_2016-08-05_05-04-05](https://cloud.githubusercontent.com/assets/3672466/17424183/109eeebe-5aca-11e6-9bc7-29f7e2344f7a.png)

**Comment by Technoblazed** [comment]
I like it, but steam3 that far down looks out of place

**Comment by shavitush** [comment]
![hl2_2016-08-05_05-07-01](https://cloud.githubusercontent.com/assets/3672466/17424225/7a508eb2-5aca-11e6-8542-7dea1f70163d.png)

**Comment by Technoblazed** [comment]
SeemsGood

**Comment by shavitush** [comment]
Working on `Shavit_GetWRCount(int client)` and will push this pretty big update!
