### ISSUE TITLE
BOTs should be added to the game only if there is available replay.

### ISSUE THREAD

**Issue by Sqwanes** [shavitush/bhoptimer#150]
title^^ Could be nice to see this added,because sometimes you see this :
http://images.akamai.steamusercontent.com/ugc/264969860603648041/E238C5E20EF46AFBD921505C408F44C52D925CCD/ :laughing:

**Comment by StrafeHack** [comment]
Meh, you're better off getting a plugin that dissolves / removes ragdolls because you will still get those bodies when players suicide.

**Comment by shavitush** [comment]
https://forums.alliedmods.net/showthread.php?t=71084
