### ISSUE TITLE
Bot Features

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#151]
To do list had a cvar to set a specified amount of bots and do !replay to spawn one in for the replay, did you change your mind D:

Also a few other things:

- Displaying bot strafes and strafe sync if appropriate.

**Comment by shavitush** [comment]
> To do list had a cvar to set a specified amount of bots and do !replay to spawn one in for the replay, did you change your mind D:

Yeah, according to many CS:S players, they disliked bTimes v2 and also really hated the idea of !replay, TAS and this kind of stuff in a bhop server so I decided to just not do them

> Displaying bot strafes and strafe sync if appropriate.

I don't think it's possible with the current replaying plugin

**Comment by Technoblazed** [comment]
Welp, time to kick some bots then.
