### ISSUE TITLE
Use a different system so the players name is always up to date.

### ISSUE THREAD

**Issue by StrafeHack** [shavitush/bhoptimer#155]
Can we use a player id system or something similar so players names in the top menu and GetWRName are their last connected name rather than whatever it was when they got the record.

Or is there an easier way

**Comment by shavitush** [comment]
it already does it

**Comment by StrafeHack** [comment]
Uh since when? I haven't tested it in a while tbh but it didn't before

**Comment by shavitush** [comment]
since the public release of the timer :s

![firefox_2016-08-08_06-49-19](https://cloud.githubusercontent.com/assets/3672466/17468820/4a9c2a98-5d34-11e6-9c2e-0ca258cf6f29.png)

**Comment by StrafeHack** [comment]
Hmm ok my bad :) I will go test the way I think I did it before but you can close it for now, sorry :\

**Comment by shavitush** [comment]
you probably confused it between the bot names, which i also fixed

**Comment by StrafeHack** [comment]
Well before you added the 2 different bot style names I just improvised mine and used getwrname and put it in the bots clantag and it never updated (im pretty sure not 100% though)
