### ISSUE TITLE
Server crashing after joining a team

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#156]
My server is crashing after installing the timer. It happens right after joining a team. There are no errors with the plugins, everything works fine, but the server is crashing after 4 seconds of playing. The only error I get is: 
**** WARNING: Watchdog timer exceeded, aborting!

What doest it mean?

**Comment by Fastmancz** [comment]
You must use in your SRCDS start command **-nowatchdog**

**Comment by Nickelony** [comment]
The problem is that I didn't use this command before and it worked perfectly fine, also my hosting doesn't support modifying the SRCDS start command :(

**Comment by shavitush** [comment]
Please provide an [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703&) crash log!

**Comment by Fastmancz** [comment]
**** WARNING: Watchdog timer exceeded, aborting!
This is problem, when 1 CPU is full loaded, then SRCDS server crash. You must add in your SRCDS start command **-nowatchdog**. It can not be otherwise resolved. Contact your hosting.

**Comment by Technoblazed** [comment]
Contact your hosting, what are your server specs?

**Comment by Nickelony** [comment]
Ok that's it. Close.

**Comment by shavitush** [comment]
Friendly reminder: you can close it yourself
