### ISSUE TITLE
Start zone not loaded after restart server.

### ISSUE THREAD

**Issue by Fastmancz** [shavitush/bhoptimer#157]
Hello,

In new version shavit-zones is problem with Start zone, when i restart server, then Start zone not loaded. But in MySQL database is saved.

Thanks for reply.

**Comment by shavitush** [comment]
Error logs?

**Comment by Fastmancz** [comment]
Nothing, when i change map after restart server, then Start zone loaded on all maps.

**Comment by Technoblazed** [comment]
So it's fixed?

**Comment by Fastmancz** [comment]
No.

**Comment by Technoblazed** [comment]
So, just to check, this is using the latest sourcecode, zones disappear when you reload the server, and there's no sourcemod error log files at all?

**Comment by Fastmancz** [comment]
I have latest version Sourcemod and Bhoptimer, but my problem not solved. In error log is nothing.

**Comment by Technoblazed** [comment]
And in your mysql/sqlite database, are the zones for the map there

**Comment by Fastmancz** [comment]
Yes. In my database is all.

**Comment by Technoblazed** [comment]
That's really strange, is it a public server?

**Comment by shavitush** [comment]
output of `sm version` please

**Comment by Fastmancz** [comment]
SourceMod Version Information:
    SourceMod Version: 1.8.0.5925
    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.5925)
    SourcePawn API: v1 = 4, v2 = 11
    Compiled on: Aug  2 2016 13:15:54
    Built from: https://github.com/alliedmodders/sourcemod/commit/e787a05
    Build ID: 5925:e787a05
    http://www.sourcemod.net/

**Comment by shavitush** [comment]
#161
