### ISSUE TITLE
Ranking System not show

### ISSUE THREAD

**Issue by KeksKartoffe** [shavitush/bhoptimer#160]
I have installed all plugins but no ranks are shown. Its enabled in cfg and Mysql is working.

**Comment by shavitush** [comment]
error logs? maybe you use the default config?

**Comment by Technoblazed** [comment]
In advance, I bet the default version of SCP that you're using is spewing an error about invalid parameters.

**Comment by KeksKartoffe** [comment]
http://capacity-gaming.de/errors_20160812.log

**Comment by shavitush** [comment]
Download and compile the version hosted on GitHub, I'm not going to support old versions.

**Comment by KeksKartoffe** [comment]
Can i use the old Webinterface for the new version?

**Comment by shavitush** [comment]
not sure why would you want to, but it *should* work

**Comment by KeksKartoffe** [comment]
With The Old Database Sry ^^

**Comment by shavitush** [comment]
database migrations automatically apply when you update the plugins

**Comment by KeksKartoffe** [comment]
ok thy for help :D

**Comment by KeksKartoffe** [comment]
Can you add me on skype? Need Help :D

**Comment by shavitush** [comment]
no

**Comment by KeksKartoffe** [comment]
ok. I installed the newest Version but same error: no ranks are shown

**Comment by shavitush** [comment]
error logs

**Comment by KeksKartoffe** [comment]
L 08/12/2016 - 18:42:22: [shavit-wr.smx] Timer (WR forwards cache update) SQL query failed. Reason: Unknown column 'u.name' in 'field list'
L 08/12/2016 - 18:42:22: [shavit-wr.smx] Timer (WR sideways cache update) SQL query failed. Reason: Unknown column 'u.name' in 'field list'
L 08/12/2016 - 18:43:43: [shavit-core.smx] Timer error! Failed to insert "KeksKartoffel|Capacity-Gaming.de"'s data to the table. Reason: Unknown column 'auth' in 'field list'

**Comment by KeksKartoffe** [comment]
more errors are not there

**Comment by AzaZPPL** [comment]
You are missing columns in your database. Stop your server. Rename your current database to `name_bak` and create a new database with your original database name. Start your server and let it create the tables on the newly created database. Compare differences and add tables you are missing. Always use the latest version that's on github.
