### ISSUE TITLE
Fix teleport lagging (replay bots)

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#164]

**Comment by shavitush** [comment]
confirmed to only happen in cs:s.

so far happens in bhop_eazy_v2, kz_bhop_yonkoma and kz_bhop_skodna

**Comment by shavitush** [comment]
okay i actually have no idea how to fix this issue without removing this part:

```
(GetVectorDistance(vecCurrentPosition, vecPosition) >= 50.0)? vecPosition:NULL_VECTOR
```

because teleports won't really work. ideas will be appreciated

**Comment by shavitush** [comment]
A solution I thought about is to hook teleports with DHooks, block them and manually teleport the bot. We'll see how well I can execute this idea!

**Comment by shavitush** [comment]
implemented a better solution as the bot can duck and everything now

**Comment by shavitush** [comment]
teleports are solved but bots dont get teleported at the first frames at all; i'll try to implement the 'block `trigger_teleport`s with dhooks' solution and fallback to teleporting on big distances back

**Comment by StrafeHack** [comment]
@shavitush do the current solution record weapon switching and attacks for not?

**Comment by shavitush** [comment]
I didn't test weapon switching.. but - it recorded everything the HUD key display shows and attacks (shooting and USP silencer).
Could you test it?

**Comment by StrafeHack** [comment]
Yeah I'll test it in a bit or tomorrow and post here

**Comment by shavitush** [comment]
Not sure what I've done but tested again and the teleporting issue is solved!

**Comment by Technoblazed** [comment]
Lol
