### ISSUE TITLE
Add Sideways sync

### ISSUE THREAD

**Issue by StrafeHack** [shavitush/bhoptimer#169]
I know it seems pretty useless but it just feels like lacking since css servers have it, if it's no crazy works I think it might be best to add a STYLE_MEASURESWSYNC

**Comment by shavitush** [comment]
alright but i just started being addicted to cs:s kz/bhop again so development might lag behind

**Comment by shavitush** [comment]
tested with SW, HSW, W-Only, D-Only and it works fine

**Comment by Technoblazed** [comment]
What about just normal?

**Comment by shavitush** [comment]
works fine, i just listed the additional styles that it works for now
