### ISSUE TITLE
Apologies, gave partly outdated error log.

### ISSUE THREAD

**Issue by ooinic** [shavitush/bhoptimer#173]
Hey shavit sorry about the previous post, my admin did give read permissions to the server and also installed dynamic, the error log is as follows:

--error spam--

**Comment by shavitush** [comment]
that's not your whole error log, sorry

shut down the server, delete the error logs, turn your server on and when you see the error log pop up turn it off and **attach** it here

**Comment by ooinic** [comment]
Alright, my apologies.

`L 08/19/2016 - 13:21:12: SourceMod error session started

L 08/19/2016 - 13:21:12: Info (map "bhop_japan") (file "errors_20160819.log")
L 08/19/2016 - 13:21:12: [CLIENTPREFS] [1049]: Unknown database 'clientprefs-sqlite'
L 08/19/2016 - 13:21:20: [CLIENTPREFS] [1049]: Unknown database 'clientprefs-sqlite'
L 08/19/2016 - 13:21:23: [SM] Unable to load plugin "shavit-chat.smx": Native "GetMessageFlags" was not found
L 08/19/2016 - 13:21:23: [SM] Exception reported: Cannot open "configs/shavit-prefix.txt". Make sure this file exists and that the server has read permissions to it.
L 08/19/2016 - 13:21:23: [SM] Blaming: shavit-rankings.smx()
L 08/19/2016 - 13:21:23: [SM] Call stack trace:
L 08/19/2016 - 13:21:23: [SM]   [0] SetFailState
L 08/19/2016 - 13:21:23: [SM]   [1] Line 930, C:\TCAFiles\Users\admin\4\csgo\addons\sourcemod\scripting\shavit-rankings.sp::SQL_SetPrefix()
L 08/19/2016 - 13:21:23: [SM]   [2] Line 127, C:\TCAFiles\Users\admin\4\csgo\addons\sourcemod\scripting\shavit-rankings.sp::OnPluginStart()
L 08/19/2016 - 13:21:23: [SM] Unable to load plugin "shavit-rankings.smx": Error detected in plugin startup (see error logs)
L 08/19/2016 - 13:21:24: [store.smx] Gifts! isn't installed or failed to load. Gifts support will be disabled. Please install Gifts. (http://forums.alliedmods.net/showthread.php?t=175185)
L 08/19/2016 - 13:21:24: [store.smx] Simple Chat Processor isn't installed or failed to load. SCP support will be disabled. (http://forums.alliedmods.net/showthread.php?t=198501)
L 08/19/2016 - 13:21:37: [CLIENTPREFS] [1049]: Unknown database 'clientprefs-sqlite'
L 08/19/2016 - 13:21:37: [SM] Exception reported: Cannot open "configs/shavit-sounds.cfg". Make sure this file exists and that the server has read permissions to it.
L 08/19/2016 - 13:21:37: [SM] Blaming: shavit-sounds.smx()
L 08/19/2016 - 13:21:37: [SM] Call stack trace:
L 08/19/2016 - 13:21:37: [SM]   [0] SetFailState
L 08/19/2016 - 13:21:37: [SM]   [1] Line 81, C:\TCAFiles\Users\admin\4\csgo\addons\sourcemod\scripting\shavit-sounds.sp::OnMapStart()
L 08/19/2016 - 13:21:48: [SM] Exception reported: Script execution timed out
L 08/19/2016 - 13:21:48: [SM] Blaming: store.smx()
L 08/19/2016 - 13:21:48: [SM] Call stack trace:
L 08/19/2016 - 13:21:48: [SM]   [1] Line 448, C:\Users\Computer\Desktop\Projects\store-plugin\addons\sourcemod\scripting\include\string.inc::FindCharInString()
L 08/19/2016 - 13:21:48: [SM]   [2] Line 660, C:\Users\Computer\Desktop\Projects\store-plugin\addons\sourcemod\scripting\include\zephstocks.inc::Downloader_AddFileToDownloadsTable()
L 08/19/2016 - 13:21:48: [SM]   [3] Line 82, store/playerskins.sp::PlayerSkins_OnMapStart()
L 08/19/2016 - 13:21:48: [SM]   [5] Call_Finish
L 08/19/2016 - 13:21:48: [SM]   [6] Line 663, C:\Users\Computer\Desktop\Projects\store-plugin\addons\sourcemod\scripting\store.sp::OnMapStart()
L 08/19/2016 - 13:21:51: [CLIENTPREFS] [1049]: Unknown database 'clientprefs-sqlite'
L 08/19/2016 - 13:22:46: [store.smx] Database connection is lost or not yet initialized.
L 08/19/2016 - 13:22:46: [store.smx] Database connection is lost or not yet initialized.
L 08/19/2016 - 13:22:46: [CLIENTPREFS] [1049]: Unknown database 'clientprefs-sqlite'
L 08/19/2016 - 13:22:48: Error log file session closed.
L 08/19/2016 - 13:22:51: SourceMod error session started
L 08/19/2016 - 13:22:51: Info (map "bhop_japan") (file "errors_20160819.log")
L 08/19/2016 - 13:22:51: [SM] Exception reported: Cannot open "configs/shavit-sounds.cfg". Make sure this file exists and that the server has read permissions to it.
L 08/19/2016 - 13:22:51: [SM] Blaming: shavit-sounds.smx()
L 08/19/2016 - 13:22:51: [SM] Call stack trace:
L 08/19/2016 - 13:22:51: [SM]   [0] SetFailState
L 08/19/2016 - 13:22:51: [SM]   [1] Line 81, C:\TCAFiles\Users\admin\4\csgo\addons\sourcemod\scripting\shavit-sounds.sp::OnMapStart()
L 08/19/2016 - 13:22:51: [SM] Exception reported: Failed to connect to SQL database. Error: [1044]: Access denied for user ''@'localhost' to database 'sourcemod-local'
L 08/19/2016 - 13:22:51: [SM] Blaming: store.smx()
L 08/19/2016 - 13:22:51: [SM] Call stack trace:
L 08/19/2016 - 13:22:51: [SM]   [0] SetFailState
L 08/19/2016 - 13:22:51: [SM]   [1] Line 2173, C:\Users\Computer\Desktop\Projects\store-plugin\addons\sourcemod\scripting\store.sp::SQLCallback_Connect()
L 08/19/2016 - 13:22:51: [SM] Exception reported: Plugin not runnable
`

**Comment by Technoblazed** [comment]
Firstly, it seems like you haven't uploaded the /configs/ directory provided with the download and that you haven't configured your databases.cfg

**Comment by shavitush** [comment]
@Technoblazed `databases.cfg` configuration isn't a must anymore

@ooinic you also forgot to download Simple Chat Processor.
I see you have errors from so many plugins; you should really follow installation instructions. We, the developers write them for a reason.
