### ISSUE TITLE
Rewrite every bitflag condition in the code

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#177]
Currently I do bitflag conditions like that for example:

    if(buttons & IN_JUMP)

What I found out recently is that something like this:

    bool a = bit & flag;
    int b = bit & flag;

`a` will be a tag mismatch, while `b` will be a value above 0 (considering `flag` is actually active) - which is bad. SourcePawn will just 'convert' `int` to `bool` on-the-fly. 0 is `false` and everything else is `true`. So it works inside conditions but is absolutely not the way I'm supposed to write code.

I didn't check the way SourcePawn handles it, but my _assumption_ is that at runtime, lower values will process faster (I never verified it - it's probably incorrect but that's what my weird logic tells me) and dealing with 0 and 1 is better than dealing with 0 and 1024 or some huge number.

So using something like `(bit & flag) > 0` will be correct, while `bit & flag` isn't. So I'm going to rewrite all bitflag conditions to be like that.

The example I provided should be done like the following then:

    if(buttons & IN_JUMP > 0)

So far everything works but it's a bad habit as other languages will throw compilation errors and hopefully my code could be used in the future so developers can also learn from it

**Note**: This is very low priority and is minor.

**Comment by StrafeHack** [comment]
What is the actual benefit of this:
```
if(buttons & IN_JUMP > 0)
	blah
else
	blah
```
Over just doing it normally like:
```
if(buttons & IN_JUMP)
	blah
else
	blah
```

**Comment by shavitush** [comment]
Correct syntax in every language; it's just SourcePawn not throwing errors tag mismatch in the second example for some reason

**Comment by shavitush** [comment]
Untested but shouldn't start issues. If it does, file anything ASAP
