### ISSUE TITLE
Hello not sure what im doing wrong maybe i am puting the config file where i shouldn't

### ISSUE THREAD

**Issue by Death101** [shavitush/bhoptimer#181]
http://pastebin.com/N6kn1E6k

**Comment by Technoblazed** [comment]
```
L 08/26/2016 - 14:17:14: [SM] Unable to load plugin "shavit-chat.smx": Could not find required plugin "dynamic"```
Your server does not have [Dynamic](https://forums.alliedmods.net/showthread.php?t=270519) installed.

```
L 08/26/2016 - 14:17:14: [SM] Error parsing gameconfig file "e:\csgo\server\csgo\addons\sourcemod\gamedata\shavit.games.txt":
```

You have not uploaded the "gamedata" directory to the correct location on your server, if at all.

**Comment by Death101** [comment]
That fixed that error but another one pops up http://pastebin.com/vyEVZHeG also where am i sopose to put web server ?

**Comment by Death101** [comment]
btw i did every step in that instruction i still get the error above

**Comment by Death101** [comment]
ok its working now tank you
