### ISSUE TITLE
Start zone spam

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#186]
shavit_core_blockprejump "1"
shavit_misc_prespeed "3"

When you jump in the start zone, the "Bhopping is not allowed in the start zone message" is posted in the chat for each time you jump about 20 times.

**Comment by shavitush** [comment]
cannot replicate
do you have the timer in a subfolder?

**Comment by Technoblazed** [comment]
Nope, just setup the server from scratch, seems to be whenever it's set to shavit_core_blockprejump "1"

**Comment by shavitush** [comment]
super weird.. i still can't replicate it though so i'm not sure how to fix it :(

**Comment by Technoblazed** [comment]
Even with shavit_core_blockprejump "0" set to 0, still being blocked when trying to jump out of the start zone o.O

**Comment by Technoblazed** [comment]
Yeah, you can't jump out of the start zones anymore

**Comment by shavitush** [comment]
I think I fixed it, I'll push the commit in a moment

**Comment by shavitush** [comment]
Try now

**Comment by Technoblazed** [comment]
Now shavit_core_blockprejump has no effect whatsoever, you are always forced down to the ground and spammed

**Comment by shavitush** [comment]
i still fail to replicate this bug so i still can't really help, sorry

**Comment by Technoblazed** [comment]
Could it just be GO related?

**Comment by shavitush** [comment]
i doubt; i'll do csgo testing tomorrow i guess

**Comment by Nickelony** [comment]
When you leave the start zone and jump back to it, you can bhop in it as much as you want. It also blocks prejump, which shouldn't be a think since there is another cvar for it.

**Comment by shavitush** [comment]
Can you try now?

**Comment by Technoblazed** [comment]
Cant even get a server to start anymore, so unable to check.

**Comment by shavitush** [comment]
Is it caused by my plugin?

**Comment by Technoblazed** [comment]
Don't think so, theres no logs at all being generated so ill probably just wipe and restart :D

**Comment by shavitush** [comment]
Can replicate the issue
