### ISSUE TITLE
(After release) Challenges / racing / duels / 1v1

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#187]
Like in DR.API's timer, it would be nice to see 1v1 challenges in your plugin and maybe mix them with a points betting system.

Edit: Those typos. My english still sucks. :/

**Comment by Technoblazed** [comment]
If this actually becomes a thing, make sure challenge points stay separate from normal map points.

**Comment by rtldg** [comment]
this seems to be a thing already with https://github.com/EvanIMK/Shavit-Race
imo the points betting is out of scope of the bhoptimer repo
