### ISSUE TITLE
Can't drop any weapons.

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#188]
Your plugin disallows dropping ANY weapon. This makes the weapon cleanup completely useless. Maybe add a cvar to enable dropping?

**Comment by Technoblazed** [comment]
Unrepeatable

**Comment by Nickelony** [comment]
My plugin list: http://pastebin.com/raw/7f7Bw2cd

**Comment by Technoblazed** [comment]
mp_drop_knife enable 1
mp_death_drop_gun

**Comment by Nickelony** [comment]
For some reason mp_death_drop_gun was 0 on my server, my bad.
