### ISSUE TITLE
Remove SSJ

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#189]
Use this instead https://forums.alliedmods.net/showthread.php?t=287039

**Comment by Technoblazed** [comment]
Replacement no longer works.

**Comment by shavitush** [comment]
i guess i need to fix the csgo crashes and add it as some extra module or something

**Comment by dominovr** [comment]
The issue was caused by the PrintColorText() function, I just replaced it with multicolours' CPrintToChat() and it worked. https://github.com/dominovr/ssj

**Comment by shavitush** [comment]
guess that solves it!
