### ISSUE TITLE
No knife/weapon command

### ISSUE THREAD

**Issue by On3TwO** [shavitush/bhoptimer#190]
Im not sure if this is already implemented, if so how to do it, but adding a command to remove both weapon and knife would be a good thing, or even pressing you're drop weapon command drops both your knife and gun

**Comment by Technoblazed** [comment]
(CSGO)

Just push your drop key twice with the cvars:

mp_drop_knife_enable 1
mp_death_drop_gun 1

set?

**Comment by On3TwO** [comment]
i have them set, it just doesnt remove the weapons from the floor,

**Comment by Technoblazed** [comment]
shavit_misc_noweapondrops "1"

**Comment by On3TwO** [comment]
ty for help // sorry if it was a waste of time

**Comment by Technoblazed** [comment]
Close your issue and we're gucci
