### ISSUE TITLE
Force FPS above 60 on players

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#191]
it's quite known that scroll can be abused with certain fps_max values, or even with FPS limiting software like FRAPS or whatsoever, so I need to find a solution that will not submit times if packets per second from players are below 60

**Comment by shavitush** [comment]
Haven't realized this cvar exists: `sv_competitive_minspec`

Marking as invalid.

**Comment by strafe** [comment]
@shavitush doesn't that just limit your fps_max value to 60 minimum? Pretty sure programs like Dxtory can still force your fps below that amount.

**Comment by shavitush** [comment]
It does, but those programs won't give you stable FPS therefore the crouchjump method won't be as effective.
