### ISSUE TITLE
Make replay bots have the names of their "players"

### ISSUE THREAD

**Issue by Massta** [shavitush/bhoptimer#192]
So this is my first time actually doing something on github, not really sure if this is the right place or the right thing to post here so please bear with me.

I recently started hosting a bhop server and - thanks to shavitush - I also have a great timer plugin.
Now there are some features lacking IMO, one of which is named bots. A friend (who's hosting another server with the same plugin) told me, the bots do have that feature but since the latest update it got lost?
Not sure about the accuracy of these information, but it is slighly annoying that the bots are named after styles, and not after players.
![20160905023221_1](https://cloud.githubusercontent.com/assets/13764328/18234845/0acfcaf8-7311-11e6-9121-fff3379b4296.jpg)

**Comment by Technoblazed** [comment]
```
// Replay bot naming style
// 0 - [SHORT STYLE] <TIME> - PLAYER NAME
// 1 - LONG STYLE - <TIME>
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
shavit_replay_namestyle "1"
```

**Comment by shavitush** [comment]
As @Technoblazed mentioned, set the name style to 0 and it'll be fine.
Hopefully soon I'll make it more customizable when I push the new styles config, where you could do something like `[{STYLE}] {NAME} - {TIME}` to your own likings :)

**Comment by Massta** [comment]
test

**Comment by Massta** [comment]
This config file seems to be missing on my ftp server for some reason, really weird.
Thanks for answering so quickly!

**Comment by Technoblazed** [comment]
If the plugin started correctly, it should be located in /csgo/cfg/plugin.shavit-replay.cfg

**Comment by Massta** [comment]
The file existed on my ftp server, but it was missing the shavit_replay_namestyle command section ._.
I added it, now everything works. Thanks again and sorry for posting irrelevant questions.

**Comment by Technoblazed** [comment]
You should delete your cfg files when you update, it won't auto add the cvars
