### ISSUE TITLE
Replay bots

### ISSUE THREAD

**Issue by nknm** [shavitush/bhoptimer#195]
I was thinking about opening a server with your timer and I'm planning on adding more styles with replay bots but the bots would take too much space in the server, could you make something like a bot for auto and a bot for every other style

**Comment by Technoblazed** [comment]
If this were to be a thing, it'd be far easier to have the !replay feature, somebody has done it, so just look around for the code and try implementing. As far as I'm aware shavit wasn't looking into a feature for it ass css people disagreed.

**Comment by nknm** [comment]
Well I feel like that feature would be great I don't understand why would css players disagree.
I personally don't enjoy having 30 bots in the server its a pain to find ppl in spectate mode and takes too many slots in the server. I'd say it's a considerably feature tho, but I'll look around and see if I can find anything thnx :)

**Comment by nknm** [comment]
okay now I know why css players don't want that. Because on css bots don't take players slots like they do on csgo

**Comment by shavitush** [comment]
they actually do fill up the server in css too

@Technoblazed i actually started doing some changes in the replay plugin as you can see and hopefully i'll implement !replay either before beta is over or after

**Comment by Technoblazed** [comment]
:d

**Comment by Technoblazed** [comment]
Love you :D

**Comment by Technoblazed** [comment]
Until something like  this is implemented, is it possible to have another style config, that records the .rec, but does not spawn the bot in.

Currently it is "noreplay", maybe this could be changed into "noreplay" and "nobot"

**Comment by shavitush** [comment]
Added, toggle with `shavit_replay_centralbot`. Use with !replay.
