### ISSUE TITLE
When changing Style

### ISSUE THREAD

**Issue by BernardinoSousa** [shavitush/bhoptimer#197]
Could you make a convar to change between teleport to startzone or stoptimer because in my server the startzone far away from spawnkiller. So for me its better with stoptimer

Sry if its on the wrong section im new on github

Thank You for your great work.

**Comment by Technoblazed** [comment]
This doesn't really seem to have a purpose other than for a course server, as it's a bhop timer. Probably wouldn't be that large of a thing to try and code in yourself.

**Comment by shavitush** [comment]
'bhoptimer'

'BHOPtimer'

BHOP
