### ISSUE TITLE
Checking when players are all dead to kill bots

### ISSUE THREAD

**Issue by BernardinoSousa** [shavitush/bhoptimer#198]
Im server owner of a course server so i need when all players are dead to kill bots and check the first player on join team because i want bots in the same team that players are because of course maps that have only one team

Sry if its on the wrong section im new on github

Thank You for your great work.

**Comment by Nickelony** [comment]
Just disable the bots if you don't need them.

**Comment by shavitush** [comment]
don't use replay bots in a course server cmon
