### ISSUE TITLE
sm_tier <mapname> always returns the current map tier

### ISSUE THREAD

**Issue by Massta** [shavitush/bhoptimer#200]
I first thought that bug only occured after setting the tier of a map, but apparently the !tier <mapname> command always returns the current map tier value, and not the one you were asking for.

**Comment by Technoblazed** [comment]
That's the point of it, it displays the current map tier, this is more of a feature request, than a bug?

**Comment by Technoblazed** [comment]
As in you're requesting 
```
sm_tier <mapname>
```

**Comment by Massta** [comment]
I guess I expressed myself poorly.
Let's say you are on bhop_sina_csgo, which has the tier 6. Now you want to know what tier bhop_eazy_csgo has, so you write !tier eazy, which will also return 6 (even though it's 1!)

>  [Timer] bhop_eazy_csgo is rated tier 6.0.

**Comment by Technoblazed** [comment]
Okay, I see the issue now, just let shavit take a look at it in the morning, I might even take a look now. :D

**Comment by Massta** [comment]
I really like that you guys are so motivated. Could I add you for 1-2 quick questions, or does Github have a pm system? D:

**Comment by Technoblazed** [comment]
http://steamcommunity.com/id/Technoblazed

**Comment by Technoblazed** [comment]
@shavitush shavit-rankings.sp, line 554-563, gF_MapTier is not being redefined, so is still using the current map tier. I would've done a PR but I know how you like your syntax', should just be a simple case of a new float and getting the tier from the table :D

**Comment by shavitush** [comment]
yea but i need to re-do the whole rankings plugin anyways
