### ISSUE TITLE
Godmode

### ISSUE THREAD

**Issue by Zelost** [shavitush/bhoptimer#201]
```
shavit_misc_godmode "3"
Enable godmode for players? 
0 - Disabled
1 - Only prevent fall/world damage.
2 - Only prevent damage from other players.
3 - Full godmode.
```
Option "2" - doesn't seem to working... Players still able to kill each others...
P.S. Sorry for my english...

**Comment by shavitush** [comment]
cannot replicate

just set it to 3, i can't think of a situation where 2 is needed

**Comment by live4net** [comment]
Got same error.

I Add to shavit0misc:

public Action OnTakeDamage(int victim, int attacker)
{
        PrintToChatAll("%d attack %d", attacker, victim);
}


When other player attack me, game print to chat:
178208 attack 4
