### ISSUE TITLE
chat error

### ISSUE THREAD

**Issue by mrkos9i4ok** [shavitush/bhoptimer#202]
L 09/08/2016 - 00:11:56: [SM] Exception reported: Array index is out of bounds
L 09/08/2016 - 00:11:56: [SM] Blaming: shavit-chat.smx()
L 09/08/2016 - 00:11:56: [SM] Call stack trace:
L 09/08/2016 - 00:11:56: [SM]   [1] Line 203, shavit-chat.sp::LoadChatCache()
L 09/08/2016 - 00:11:56: [SM]   [2] Line 812, shavit-chat.sp::Player_Spawn()

**Comment by shavitush** [comment]
attach your shavit-chat.cfg please

**Comment by mrkos9i4ok** [comment]
`"Chat"
{
    "[U:1:327104892]" // my steamid for example, use steamid3
    {
        "prefix"        "{green}/dev/"
        "name"          "{default}{team}{clan}{name}"
		"clantag"		"Владелец"
    }

    "-1" // lookup is due, shouldn't happen unless there's some error!
    {
        "rank_from"     "-1"
        "rank_to"       "-1"

        "prefix"        ""
        "name"          "{team}{name}"
        "message"       "{message}"
    }

    "0" // unranked
    {
        "rank_from"     "0"
        "rank_to"       "0"

        "prefix"        "[Unranked]"
        "name"          "{team}{name}"
        "message"       "{message}"
    }

    "1"
    {
        "rank_from"     "1"
        "rank_to"       "1"

        "prefix"        "{green}ONE TRUE GOD"
        "name"          "{clan}{team}{name}"
    }

    "2"
    {
        "rank_from"     "2"
        "rank_to"       "2"

        "prefix"        "LEGENDARY"
        "name"          "{name}"
    }

    "3"
    {
        "rank_from"     "3"
        "rank_to"       "3"

        "prefix"        "HERO"
        "name"          "{team}{name}"
    }

    "4"
    {
        "rank_from"     "4"
        "rank_to"       "infinity"

        "prefix"        "scrub!"
    }
}`

**Comment by shavitush** [comment]
I'll work on it soon, thanks for reporting

**Comment by shavitush** [comment]
Will do this in #436 as I'm rewriting the whole thing.
