### ISSUE TITLE
Add commands for style changes

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#203]
Dependent on configuration from the styles config (#178), will allow delimiters and ignore spaces.

Example:

    "command" "scr; scroll; l ;  le; legit"

Will create the commands `sm_scr`, `sm_scroll`, `sm_l`, `sm_le` and `sm_legit` which will change to the style we define.

**Comment by Technoblazed** [comment]
@shavitush This is done :D

**Comment by shavitush** [comment]
oh right LOL
