### ISSUE TITLE
When i can upload the plugin ?

### ISSUE THREAD

**Issue by BernardinoSousa** [shavitush/bhoptimer#207]
Sry for the wrong section but i dont know where section to put.

When i can upload the plugin to my server without clearing database ? 1.6 version ?
This because will be boring to players playing on server and seeing all the time records deleted

**Comment by Technoblazed** [comment]
You can upload it right now, everything works retroactively so it won't matter.

**Comment by shavitush** [comment]
Basically what @Technoblazed said. I recommend waiting a bit before you do it, I'm about to push the new styles configuration, tons of optimizations and I will also allow reloading of `shavit-core` while the server is running, stay tuned :)
