### ISSUE TITLE
Native "Shavit_GetTimer" reported: Plugin owning this native is currently paused.

### ISSUE THREAD

**Issue by Mldx** [shavitush/bhoptimer#21]
First 100 lines of error in console: https://gist.github.com/anonymous/e745a4e02af0b5935e94
"sm plugins list":http://puu.sh/nTYox/acc15063f7.png

**Comment by shavitush** [comment]
> 1.4b

Recompile the files using this tutorial: https://youtu.be/4a1bt6fbVrk

**Comment by Mldx** [comment]
After using the new files, i get these messages: http://puu.sh/nU1UH/e1325c997f.png

**Comment by shavitush** [comment]
Please, for the love of god, to the following and attach the error log afterwards:
Shut down your CS:GO server.
Go to addons/sourcemod/logs/ and delete every file that its name starts with "error_".
Start your server again, when you start seeing error being spammed in the console, shut down the server and attach the error log by drag-dropping it into the text box below my comment.

**Comment by Mldx** [comment]
[errors_20160326.log.txt](https://github.com/shavitush/bhoptimer/files/190262/errors_20160326.log.txt)

**Comment by shavitush** [comment]
`L 03/26/2016 - 00:04:27: [SM] Native "SetFailState" reported: Timer startup failed. Reason: [2003]: Can't connect to MySQL server on 'localhost' (10061)`

There we go. Do you have a local MySQL server running? The plugin cannot be used without one.

**Comment by Mldx** [comment]
It seems like my local MySQL database didn't really work.
I created a database using cpanel for my website, and that one worked.

All is good now.

**Comment by shavitush** [comment]
Glad I helped :smile:

**Comment by vadiks2003** [comment]
didn't help me for me. When i join in server (WHEN I JOIN) i got much errors moving like hacking nasa 
![default](https://cloud.githubusercontent.com/assets/16243254/14930408/6a9cc4f4-0e6c-11e6-98c4-aea8967af78e.png)
помоги блять

**Comment by vadiks2003** [comment]
стоп

**Comment by shavitush** [comment]
I don't speak Russian.

By the way, compile the timer locally, on your own PC. Follow this tutorial step by step: https://youtu.be/4a1bt6fbVrk

**Comment by vadiks2003** [comment]
Nice. now i got "gc connection established for server version 326, instance idx 1"

**Comment by vadiks2003** [comment]
wait, its not because of this plugin, its something with my ip
