### ISSUE TITLE
Can't load any styles

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#210]
I think your plugin is not reading shavit-styles.cfg because when I go to my server, all I get is "Nothing." in styles.

Here's my shavit-styles.cfg: http://pastebin.com/raw/NA5vTkp6

**Comment by Technoblazed** [comment]
Any error logs?

**Comment by Technoblazed** [comment]
Also, what on earth is "CheatEngine"

**Comment by shavitush** [comment]
absolutely can't replicate. set the permissions (CHMOD) of the file to 777, you might have permissions issues

**Comment by Nickelony** [comment]
No error logs.
Permissions didn't help :/

The plugin can't even read shavit-zones.cfg, but shavit-chat.cfg can be read...

CheatEngine - It was a cheat for CS 1.6 that could slow down your CS 1.6 client and you could record fake demos for YouTube showing your "skill". It's just Halftime + Slow.

**Comment by Technoblazed** [comment]
@Nickelony Did you update your dynamic?

**Comment by Nickelony** [comment]
@Technoblazed  No I didn't. I'll give it a try, wait.

**Comment by shavitush** [comment]
Dynamic's latest update fixed keyvalues, it'll work

**Comment by Technoblazed** [comment]
Did I do something right for once :o

**Comment by Nickelony** [comment]
Styles work now. Thx :)

I'll update the plugin and tell you if shavit-zones.cfg works

**Comment by Technoblazed** [comment]
:^)

**Comment by Nickelony** [comment]
Everything works fine now. Thx :D
