### ISSUE TITLE
Cvars for zone sprite RGB colors

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#211]
Title says it all.

**Comment by shavitush** [comment]
will implement to config files as i know how to handle config loading properly now :)

**Comment by Technoblazed** [comment]
Using dynamic right?

**Comment by shavitush** [comment]
yea

**Comment by Technoblazed** [comment]
Dude, you're like sanic today.

**Comment by shavitush** [comment]
that's what i'm aiming for :^)
