### ISSUE TITLE
Use github-pages for a good looking website

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#213]
Also either buy a domain for it or use `bhop.online` for a `timer` subdomain

**Comment by Technoblazed** [comment]
Website for the timer?

**Comment by shavitush** [comment]
yeah, something like https://shavitush.github.io/bhopstats/

**Comment by Technoblazed** [comment]
Clean, straightforward, :D and new milestone, this looks promising.

**Comment by PaxPlay** [comment]
Read into github pages a bit and made [this](https://paxplay.github.io/bhoptimer/) ([repo](https://github.com/PaxPlay/bhoptimer/tree/gh-pages)) using the caiman theme.
I'm not very experienced in web development so the html and css might look a bit messy but ¯\_(ツ)_/¯.
Tell me if you like it and I'll start adding content to it.

**Comment by shavitush** [comment]
Lazily done. I'm clueless about how to use the new GitHub pages so I just did it in markdown under the `gh-pages` branch. If you know how to make it look better I'm down for pull requests.
