### ISSUE TITLE
zones + misc don`t move

### ISSUE THREAD

**Issue by mrkos9i4ok** [shavitush/bhoptimer#214]
When including The plugin misc , you can not move at the resurrection .
Ubiravesh it, all the rules .

Same with zones.
When i go into the zone itself , you can not move.

**Comment by shavitush** [comment]
you're probably outdated
if possible, ask someone to translate russian -> russian please

**Comment by mrkos9i4ok** [comment]
When the plug-in of misc is included, it is impossible to move in general.
At shutdown everything normally works.

Too most with zones.
At in an entrance to a zone, it is impossible to move.

**Comment by Nickelony** [comment]
Maybe you have the same problem as I had with dynamic. Try to download the newest version here: https://github.com/ntoxin66/Dynamic

**Comment by mrkos9i4ok** [comment]
Thanks, has helped.

**Comment by mrkos9i4ok** [comment]
Again appears.

**Comment by mrkos9i4ok** [comment]
https://www.youtube.com/watch?v=Hxs-nhcP9Uc&feature=youtu.be

**Comment by shavitush** [comment]
set the style gravity to 1.0
