### ISSUE TITLE
Styles+End zone

### ISSUE THREAD

**Issue by mrkos9i4ok** [shavitush/bhoptimer#219]
If to change style on a end zone, then to be set up a new record over time 0.0.

**Comment by Technoblazed** [comment]
That only happens if you have no start zone.

**Comment by mrkos9i4ok** [comment]
The lie, zone of start costs. But all the same so occurs.

**Comment by mrkos9i4ok** [comment]
And, when you write! r, is just nullified the timer and on republic doesn't throw, + so it is possible to bagat a record.

**Comment by shavitush** [comment]
Honestly, I don't understand what you write.. If possible - get someone to write English for you or use your native language and I'll ask Russian friends to translate it for me :/

**Comment by Technoblazed** [comment]
Are you using google translate by any chance?

**Comment by mrkos9i4ok** [comment]
xD http://www.translate.ru/

Ну вот по-русски:
Когда меняешь стиль на зоне финиша,то ставится новый рекорд с временем 0.0.
А ещё,когда пишешь !r, то просто обнуляется таймер,а на респ не кидает, + так багать можно рекорд.

**Comment by shavitush** [comment]
now it makes more sense lol, I'll check it

**Comment by shavitush** [comment]
cant replicate https://www.youtube.com/watch?v=3HuRJ5Ym_U0&feature=youtu.be

**Comment by mrkos9i4ok** [comment]
https://www.youtube.com/watch?v=Hxs-nhcP9Uc&feature=youtu.be

**Comment by shavitush** [comment]
any errors?

**Comment by mrkos9i4ok** [comment]
L 09/11/2016 - 14:34:43: [SM] Exception reported: Divide by zero
L 09/11/2016 - 14:34:43: [SM] Blaming: shavit-core.smx()
L 09/11/2016 - 14:34:43: [SM] Call stack trace:
L 09/11/2016 - 14:34:43: [SM]   [1] Line 1342, shavit-core.sp::OnPlayerRunCmd()
???

**Comment by shavitush** [comment]
Considering this is line 1342, I think something is wrong with the version on your computer..

```sp
float fSpeed_New = (SquareRoot(Pow(fSpeed[0], 2.0) + Pow(fSpeed[1], 2.0)));

if(fSpeed_New > 0.0)
{
	float fScale = view_as<float>(gA_StyleSettings[gBS_Style[client]][fVelocityLimit]) / fSpeed_New; // <<<< this line

	PrintToChat(client, "%.02f / %.02f = %.02f", gA_StyleSettings[gBS_Style[client]][fVelocityLimit], fSpeed_New, gA_StyleSettings[gBS_Style[client]][fVelocityLimit] / fSpeed_New);

	if(fScale < 1.0)
	{
		ScaleVector(fSpeed, fScale);
		TeleportEntity(client, NULL_VECTOR, NULL_VECTOR, fSpeed);
	}
}```

**Comment by mrkos9i4ok** [comment]
1341:
```
		float fSpeed_New = SquareRoot(Pow(fSpeed[0], 2.0) + Pow(fSpeed[1], 2.0));
		float fScale = gA_StyleSettings[gBS_Style[client]][fVelocityLimit] / fSpeed_New;

		if(fScale < 1.0)
		{
			ScaleVector(fSpeed, fScale);

			TeleportEntity(client, NULL_VECTOR, NULL_VECTOR, fSpeed);
		}
```

**Comment by shavitush** [comment]
I'm not sure if you noticed, but the code you have is old

**Comment by Technoblazed** [comment]
Download the latest code, update your requirements, and recompile.

**Comment by Technoblazed** [comment]
@shavitush , interested in Updater support after beta?

**Comment by shavitush** [comment]
not really, i want everything to be opt-in

**Comment by mrkos9i4ok** [comment]
latest code)))
https://www.youtube.com/watch?v=H0xf0gEH9lY&feature=youtu.be

**Comment by shavitush** [comment]
Can anyone else check if it also happens to them? I can't replicate..

**Comment by Technoblazed** [comment]
Didn't happen for me

**Comment by mrkos9i4ok** [comment]
an what that in a config at me, or because of my bhop?

**Comment by Nickelony** [comment]
Didn't happen to me either.
