### ISSUE TITLE
Custom spawnpoint position

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#223]
e.g I want to spawn the player in the top left corner, not in the center of the zone. Could be a usefull feature, but you can do it after beta if you want.

**Comment by Kryptanyte** [comment]
@shavitush I've already got this about half done right now, can make a pull request in an hour or two to add this feature.

**Comment by shavitush** [comment]
@Kryptanyte sure! Make sure you add a cvar and follow the structure of the current code

**Comment by Kryptanyte** [comment]
Having some trouble with my test server atm, gunna take a bit longer haha.

**Comment by Nickelony** [comment]
When will this be finally added? :o

**Comment by shavitush** [comment]
i kinda left a comment on the pull request, it's not left out :)

**Comment by Kryptanyte** [comment]
Oh hey, sorry I had to deal with a drama of reinstalling windows, didn't actually see that comment until now o.o. I'll fix it up tomorrow. Sorry for the major delay

**Comment by shavitush** [comment]
Solved withiin #261.
