### ISSUE TITLE
style gravity

### ISSUE THREAD

**Issue by m-yk** [shavitush/bhoptimer#224]
In the new shavit-styles.cfg, if "gravity" is set to "0" you are unable to move at all, set to 1.0 for normal. (have only tested on normal)

**Comment by shavitush** [comment]
Make sure it's 0.0 and not 0, I had no issues in CS:S but I also assume it's fine in CS:GO

**Comment by Nickelony** [comment]
Same here, The zone is invisible and when you jump out of it you can't move.

**Comment by shavitush** [comment]
I'll update my CS:GO server and check ten

**Comment by shavitush** [comment]
Make sure you also update the gravity in the config to 1.0
