### ISSUE TITLE
Invisible zones

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#226]
For some reason all zones are invisible... I didn't change anything in the shavit-zones.cfg. Do i have to add something or comment something?

**Comment by mrkos9i4ok** [comment]
plugin.shavit-zones.cfg

`shavit_zones_usecustomsprite "0"`

**Comment by Technoblazed** [comment]
@mrkos9i4ok That wouldn't fix the issue, in most cases, you actually want _usecustomsprite to be 1, as they look a lot better that way.

**Comment by mrkos9i4ok** [comment]
At me they aren't visible too, downloading helps nothing else.

**Comment by shavitush** [comment]
upload the materials/ from the repository to your server, also add them to your fastdl server

**Comment by Nickelony** [comment]
still invisible

**Comment by Nickelony** [comment]
The zones are still invisible ._.

**Comment by shavitush** [comment]
if it's really bad, rollback to an older version until i fix it (sorry)

**Comment by shavitush** [comment]
Do you get any errors logged?

**Comment by Nickelony** [comment]
no errors at all

**Comment by shavitush** [comment]
Can you try with the newest files?

**Comment by Nickelony** [comment]
works fine :)

**Comment by shavitush** [comment]
🎉
