### ISSUE TITLE
Timer (zone refresh) SQL query failed.

### ISSUE THREAD

**Issue by Skyline23** [shavitush/bhoptimer#23]
[shavit-zones.smx] Timer (zone refresh) SQL query failed. Reason: Table 'bhop.mapzones' doesn't exist.

need help

**Comment by Skyline23** [comment]
L 04/20/2016 - 18:02:13: [shavit-zones.smx] Timer (zones module) error! Map zones' table creation failed. Reason: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

**Comment by shavitush** [comment]
Did you locally compile the .sp files from this repository?

**Comment by Skyline23** [comment]
yes

**Comment by shavitush** [comment]
Could you change the value of `shavit_core_sqlprefix` in cfg/sourcemod/plugin.shavit-core.cfg to something else and try again?

**Comment by Skyline23** [comment]
the same

**Comment by shavitush** [comment]
Alright, set `shavit_core_sqlprefix` to the default value and for now run this query on your database.

```sql
CREATE TABLE IF NOT EXISTS `mapzones` (`id` INT AUTO_INCREMENT, `map` VARCHAR(128), `type` INT, `corner1_x` FLOAT, `corner1_y` FLOAT, `corner1_z` FLOAT, `corner2_x` FLOAT, `corner2_y` FLOAT, `corner2_z` FLOAT, `rot_ang` FLOAT NOT NULL default 0, `fix1_x` FLOAT NOT NULL default 0, `fix1_y` FLOAT NOT NULL default 0, `fix2_x` FLOAT NOT NULL default 0, `fix2_y` FLOAT NOT NULL default 0, PRIMARY KEY (`id`));```

As I'm not sure what is the cause of it for now.

**Comment by Skyline23** [comment]
still have the error.but i dont mind it, thank you for your help.

**Comment by shavitush** [comment]
Just wanted to tell you that I attempted to fix this issue because I found the cause.

Could you try to recompile the whole timer and try again?

**Comment by Skyline23** [comment]
Ha,no more error.

**Comment by Skyline23** [comment]
[shavit-replay] Line 147 `CS_SetClientContributionScore(gI_ReplayBotClient[i], 2000)`
it doesn't work in cs:s.

**Comment by shavitush** [comment]
Pushed an update to shavit-replay.sp

**Comment by Skyline23** [comment]
Could you make a wait time before start replaying?

sorry for troubling you so much ;)

**Comment by shavitush** [comment]
Will be added on next update I guess :)

**Comment by shavitush** [comment]
Done! Need anything else?

**Comment by Skyline23** [comment]
No more,Thank you so much!

**Comment by shavitush** [comment]
Delete `cfg/sourcemod/plugin.shavit-misc.cfg`  
Delete `cfg/sourcemod/plugin.shavit-zones.cfg`

Reconfigure them, there are new cvars

**Comment by Skyline23** [comment]
https://youtu.be/g624HOe119Q

**Comment by shavitush** [comment]
I have actually had a similar issue with zones not loading, give it another try after recompiling everything.

Do you have any error logs?

**Comment by Skyline23** [comment]
No....

**Comment by shavitush** [comment]
Alright I'll take a look when I get home (2 days)

**Comment by shavitush** [comment]
So I didn't understand exactly what your issue was, I tested it in-game and now I see!

I fixed it. I even added a new cvar, but the default setting will work.
