### ISSUE TITLE
Trying to update from 1.4b to 1.5 causes errors

### ISSUE THREAD

**Issue by outlassn** [shavitush/bhoptimer#236]
Hello, today I tried to update the bhop timer to 1.5 from 1.4b -

I have ended up getting this spammed in my SCRDS.exe

 09/12/2016 - 18:00:56: [SM] Blaming: shavit-misc.smx() L 09/12/2016 - 18:00:56: [SM] Call stack trace: L 09/12/2016 - 18:00:56: [SM]   [1] Shavit_InsideZone L 09/12/2016 - 18:00:56: [SM]   [2] Line 496, D:\CSGO Server\Bhop\CSGO\csgo\addons\sourcemod\scripting - Copy\shavit-misc.sp::OnPlayerRunCmd() L 09/12/2016 - 18:00:56: [SM] Exception reported: Native is not bound L 09/12/2016 - 18:00:56: [SM] Blaming: shavit-misc.smx()

I tried an older version, then that gave me bots that kept killing themselves...

For now I will stay on 1.4, but if anyone knows what's going on, please help me out :)

**Comment by shavitush** [comment]
Could you update your whole error log?

**Comment by shavitush** [comment]
addons/sourcemod/logs

**Comment by outlassn** [comment]
http://pastebin.com/VbFPk63e

It continues to loop. I have the old version running flawlessly btw.

**Comment by shavitush** [comment]
+ Install [Dynamic](https://github.com/ntoxin66/Dynamic/archive/master.zip)
+ Remove KZTimer, update SourceMod, update Metamod: Source, delete dhooks-test
+ Optionally also delete stamm and install [Gifts](http://forums.alliedmods.net/showthread.php?t=175185) to get rid of more error spams :)

**Comment by outlassn** [comment]
The bots are now constantly killing each other...

**Comment by Gucccii** [comment]
mp_ignore_round_win_conditions should fix it

**Comment by Nickelony** [comment]
The zones are invisible cuz of a known bug that will be fixed soon. 
The bots are normal, you just need to get a WR so the bots come back alive.

**Comment by outlassn** [comment]
Any way to prevent them from killing themselves as of currently?

Don't want to go through the pain to get a WR for badges in every mode xd

**Comment by Nickelony** [comment]
Just use the replay bot for the styles you want. You don't have to have them in every style.
The bots must stay dead until there is a record set for that style, but I don't see any problems with that.

**Comment by outlassn** [comment]
Any chance I could set the bots to only appear after the WR is made?

**Comment by Technoblazed** [comment]
@outlassn remove any auto respawn cvars you have set, i.e. mp_respawn_ct etc.

**Comment by outlassn** [comment]
Wouldnt that make me not respawn when I use kill in console?

**Comment by Technoblazed** [comment]
The plugin allows you to respawn by default.

**Comment by Technoblazed** [comment]
I think its something like, mp_Respawn_on_death_ct and t

**Comment by Technoblazed** [comment]
To 0

**Comment by outlassn** [comment]
Yep, Did that, now its working flawlessly! Thanks :)

BTW, how does the ranking work?

**Comment by Technoblazed** [comment]
Ranking system is broken at the minute, and being recoded. But all ranks will work retroactively.

**Comment by outlassn** [comment]
Aight, thank you! 

Damn, I love this community :p actually helpful :+1:

**Comment by Technoblazed** [comment]
:^)

**Comment by shavitush** [comment]
For some reason zones don't show up in CS:GO, I'll try to figure out why soon (see #226)

**Comment by Technoblazed** [comment]
@outlassn remember, rankings are being rewritten ;)

**Comment by outlassn** [comment]
writing comments after closed the topic ;o

whitchcraft

**Comment by Nickelony** [comment]
If you want to disable the replay for a specific style you must add ""noreplay" 1" for the style in shavit-styles.cfg

**Comment by outlassn** [comment]
Would that mean I could enable replay for modes such as lowgrav and slowmo?

**Comment by Technoblazed** [comment]
Slowmo doesn't support bots due to replay speed

**Comment by outlassn** [comment]
Ah ok thanks

**Comment by outlassn** [comment]
@shavitush Thank you for fixing the zones :) Major props 💯
