### ISSUE TITLE
Shavit_hud not compatible with ShowKeys plugin

### ISSUE THREAD

**Issue by outlassn** [shavitush/bhoptimer#238]
Hey, I tried to add the ShowKeys plugin today, and found that it is not compatible.

L 09/13/2016 - 13:25:24: [SM] Exception reported: Could not send a usermessage
L 09/13/2016 - 13:25:24: [SM] Blaming: shavit-hud.smx()
L 09/13/2016 - 13:25:24: [SM] Call stack trace:
L 09/13/2016 - 13:25:24: [SM]   [0] PrintHintText
L 09/13/2016 - 13:25:24: [SM]   [1] Line 576, D:\CSGO Server\Bhop\CSGO\csgo\addons\sourcemod\scripting - Copy\shavit-hud.sp::UpdateHUD()
L 09/13/2016 - 13:25:24: [SM]   [2] Line 339, D:\CSGO Server\Bhop\CSGO\csgo\addons\sourcemod\scripting - Copy\shavit-hud.sp::TriggerHUDUpdate()
L 09/13/2016 - 13:25:24: [SM]   [3] Line 331, D:\CSGO Server\Bhop\CSGO\csgo\addons\sourcemod\scripting - Copy\shavit-hud.sp::UpdateHUD_Timer()
L 09/13/2016 - 13:25:24: [SM] Exception reported: Could not send a usermessage
L 09/13/2016 - 13:25:24: [SM] Blaming: shavit-hud.smx()

If you could add a !keys to make it extend the hud and show or put it below / above the chat, it would be a cool addition- If there is somehow a way to fix it to be compatible with the ShowKeys plugin, that would also be amazing.

Thanks in advance

(If you require the exact showkeys version I can give that)

**Comment by shavitush** [comment]
Use !hud - there's already an existing key display in the plugin

**Comment by outlassn** [comment]
Will do when I get home, didnt realize there already was :P 

Thanks again :)

**Comment by outlassn** [comment]
Hey, It works nicely but is there any way you could include that in the center hud? or like let us choose to put in center? also, it doesnt work with the bots.

**Comment by shavitush** [comment]
The timer's purpose isn't to be a strafe-hack/bhopscript detector, sorry
You can use my [bhopstats](https://github.com/shavitush/bhopstats) API for something like a Macrodox inspired anti-cheat
___

And 100% sync isn't really possible on long maps AFAIK (but very possible on short maps like bhop_mp_stairs_hq) - you could make a 10 liner plugin to ban/warn for that (let me know if you can't achieve that)

**Comment by outlassn** [comment]
I have 0 coding knowlage, I could probably change the SMAC Spinbot detector .cp code to change to "Antistrafe" as SMAC thinks that you are spinbotting if you use strafehacks, but I know that you can bypass this. (Had to ban a few people the other day)- If you could make a super simple plugin to ban/warn (maybe if you win 1 map with 100% it will warn then if you win 3 maps with 100% it will ban), it would be greatly appreciated.

**Comment by StrafeHack** [comment]
U2M, Aimware and Unity all do not get 100% sync on shavit's timer so honestly there is no point.

**Comment by outlassn** [comment]
Are you sure? Yesterday people were completing maps in INSANE speeds with 100% strafe - spamming "FRUX0CHEATS" and "AIMWARE" in chat...

lul

**Comment by StrafeHack** [comment]
Thanks.

I haven't actually used aimware in ages so I maybe wrong. But the point is if you add that people will find a way around it by either using a setting that does not give 100% or by toggling it.

**Comment by Technoblazed** [comment]
This is exactly why shavit's anti cheat is private, because the second you show what you detect, people get around it

**Comment by outlassn** [comment]
How much does it cost? I'll consider it

**Comment by shavitush** [comment]
i didn't sell plugins for ages, especially not anti-cheats (the one @Technoblazed mentioned is simply a rewrite of macrodox, nothing against strafehacks)
