### ISSUE TITLE
sql issues

### ISSUE THREAD

**Issue by altax** [shavitush/bhoptimer#24]
Hey, I have some errors during starting the server:

> L 05/17/2016 - 20:19:35: [shavit-zones.smx] Timer (zone refresh) SQL query failed. Reason: Table 'kartex_shavit.mapzones' doesn't exist
> L 05/17/2016 - 20:19:35: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Table 'kartex_shavit.playertimes' doesn't exist
> UTIL_GetListenServerHost() called from a dedicated server or single-player game.
> PutClientInServer: no info_player_start on level
> L 05/17/2016 - 20:19:38: [shavit-core.smx] Timer error! Failed to insert "rest in peace."'s data to the table. Reason: Table 'kartex_shavit.users' doesn't exist
> L 05/17/2016 - 20:19:38: [shavit-wr.smx] Timer (PB cache update) SQL query failed. Reason: Table 'kartex_shavit.playertimes' doesn't exist

what should I do?

**Comment by shavitush** [comment]
Which version of my timer do you use?

**Comment by altax** [comment]
i just downloaded your *zip archive from the main repository - https://github.com/shavitush/bhoptimer

**Comment by shavitush** [comment]
Can you attach your databases.cfg file?

**Comment by altax** [comment]
Yeah, sure. Something went wrong, i cant attach the file. So i post it here.

```
"Databases"
{
	"driver_default"		"mysql"
	
	// When specifying "host", you may use an IP address, a hostname, or a socket file path
	
	"default"
	{
		"driver"			"default"
		"host"				"localhost"
		"database"			"sourcemod"
		"user"				"root"
		"pass"				""
		//"timeout"			"0"
		//"port"			"0"
	}
	
	"shavit"
{
    "driver" "mysql"
    "host" "db1.myarena.ru"
    "database" "kartex_shavit"
    "user" "kartex_shavit"
    "pass" "test"
}

	"storage-local"
	{
		"driver"			"sqlite"
		"database"			"sourcemod-local"
	}

	"clientprefs"
	{
		"driver"			"sqlite"
		"host"				"localhost"
		"database"			"clientprefs-sqlite"
		"user"				"root"
		"pass"				""
		//"timeout"			"0"
		//"port"			"0"
	}
}
```

**Comment by shavitush** [comment]
Yeah my timer doesn't really support external databases yet. I don't mind working on it soon though.

I'll keep the issue open for a while until I fix it.

**Comment by altax** [comment]
So your plugin won't work for me at the moment? I just don't want to use external bhop plugins such as Zipcore, cksurf e.t.c

**Comment by shavitush** [comment]
For now sadly it won't.

If you want a temporary fix, run the following queries on your MySQL server and restart the CS server:
```
CREATE TABLE IF NOT EXISTS `playertimes` (`id` INT NOT NULL AUTO_INCREMENT, `auth` VARCHAR(32), `map` VARCHAR(128), `time` FLOAT, `jumps` VARCHAR(32), `style` VARCHAR(32), `date` DATE, PRIMARY KEY (`id`));
CREATE TABLE IF NOT EXISTS `mapzones` (`id` INT AUTO_INCREMENT, `map` VARCHAR(128), `type` INT, `corner1_x` FLOAT, `corner1_y` FLOAT, `corner1_z` FLOAT, `corner2_x` FLOAT, `corner2_y` FLOAT, `corner2_z` FLOAT, `rot_ang` FLOAT NOT NULL default 0, `fix1_x` FLOAT NOT NULL default 0, `fix1_y` FLOAT NOT NULL default 0, `fix2_x` FLOAT NOT NULL default 0, `fix2_y` FLOAT NOT NULL default 0, PRIMARY KEY (`id`));```

**Comment by altax** [comment]
sorry for the long answer. There were some problems. Anyway, I don't have full perms to add SQL queries.

There is a problem, when i'm trying to add first query:

` #1142 - CREATE command denied to user 'kartex_shavit'@'localhost' for table 'playertimes'`


and the same second query: 

`#1142 - CREATE command denied to user 'kartex_shavit'@'localhost' for table 'mapzones' `

So what should i do there? The technical support told me that I need to remove the extra requests. Leave only a request to create a table and add data in them.

I'll appreciate your answer, Thanks.

**Comment by shavitush** [comment]
That makes more sense. The `kartex_shavit` MySQL user has no permissions to create tables, which is totally not fine - the timer cannot function with just one table.

You will have to make your GSP create those tables for you, as your MySQL user is limited by permissions.

**Comment by altax** [comment]
..This is totally sad.

I don't know what a GSP is and more don't know how to create it.

I spent too much time and effort to configure your plugin, but whatever I tried to do, everything takes me to a dead end.

So, can you explain me, how to solve the problem and what GSP is? .. 

most likely I won't be able to have full access to the database.

**Comment by shavitush** [comment]
GSP is an acronym for 'Game Server Provider', in your case it's MyArena.

**Comment by altax** [comment]
Ok, thank you! I'll let them know about this problem.

**Comment by shavitush** [comment]
Sure. Please update me if you experience more issues!

**Comment by altax** [comment]
Alright. I did it. Everything seems good. But I still have a couple of questions.

1) Do you have rank stats for your plugin? If Yes how it works?
2) Is it possible to play music when a player beat the record?
3) The start and finish zones on the maps need to be installed manually? quite a lot of work.

**Comment by shavitush** [comment]
1) Not yet.
2) If you're running CS:S, ofir753 made a module which can be found in the AlliedModders thread. It will do that. For CS:GO, I will be making one soon.
3) Yes, AFAIK there's no possible way for a plugin to detect the start or finish areas of maps.

**Comment by altax** [comment]
I just see you wrote:

> I've already made that plugin but it's private, if you wanna purchase it PM me. It supports the timer you0 linked to.

Would it be possible to see the rank from you? very-very useful function.

P.S No, I'm running CS:GO server. I'll be waiting for your update then.

**Comment by shavitush** [comment]
I've lost my old hard drive. For now I won't be making 'private plugins' and the whole timer project is fully open-source, so expect the ranks somewhat around July/August.

**Comment by altax** [comment]
ok so, I noticed that when I press CTRL, speed is sharply restricted to 200/xx units. On the other servers, I haven't noticed this.

and can I somehow change the speed of the movement at the start? just accelerate to 250 units when I'm bhopping?

**Comment by shavitush** [comment]
I can't understand the question, sorry

**Comment by altax** [comment]
its just my level of engeng below the Mariana trench. I'll try to rephrase.

when I press ctrl while bhopping, my speed of the movement is often reduced to 200. I really don't understand why this is happening. In the zipcore plugin, i didn't notice this bug/or what is this.

And the second question is, how to set a maximum movement speed to 250 units at the start zone? When I trying to bhopping at the start zone it says:

> bhopping in the start zone is not allowed

I need to set the maximum speed of movement while bhop to 250 units in the start zone.

my apologies for my engeng :-)

**Comment by shavitush** [comment]
`sm_cvar sv_airaccelerate 2000` in gamemode_\*_server.cfg (replace \* with your gamemode)

```
// Stop prespeed in startzone? 
// 0 - Disabled
// 1 - Limit 280 speed.
// 2 - Block bhopping in startzone
// 3 - Limit 280 speed and block bhopping in startzone.
// -
// Default: "3"
shavit_misc_prespeed "1"
```
\^ Set to 1 and [modify line 273 of shavit-misc](https://github.com/shavitush/bhoptimer/blob/master/scripting/shavit-misc.sp#L273) if you need it to be anything else than 280.

A cvar for custom prespeed speed (or per-style setting) will be added soon.

**Comment by altax** [comment]
biggest thanks, dude! you've created a really great plugin!

> **Keep up the good work!**
