### ISSUE TITLE
Prespeed

### ISSUE THREAD

**Issue by Rostu13** [shavitush/bhoptimer#241]
can u help me? I have the same problems with server. I cannt bot replay and preesped is 260 max.  Bots whith dont have replay always die

**Comment by Sqwanes** [comment]
I will assume you are talking about this:
If dead bots keep respawning try this: mp_respawn_on_death_t 0 , mp_respawn_on_death_ct 0
This plugin should enable prestrafe in csgo: https://forums.alliedmods.net/showthread.php?p=2248506

**Comment by shavitush** [comment]
Prespeed is maxed at 260 because CS:GO limits it. Use the plugin @Sqwanes linked.
Disable the respawn settings, any auto-respawn plugin and CS:GO's warmup.

btw this is totally a general CS:GO question and not related to my timer.
