### ISSUE TITLE
Just updated server to new CSGO version (mlg crouch version) and have errors again :/

### ISSUE THREAD

**Issue by outlassn** [shavitush/bhoptimer#245]
Hey shavit and the github community,

Im getting 
L 09/18/2016 - 16:31:07: [SM] Plugin encountered error 21: Native is not bound
L 09/18/2016 - 16:31:07: [SM] Native "Shavit_InsideZone" reported:
L 09/18/2016 - 16:31:07: [SM] Displaying call stack trace for plugin "shavit-misc.smx":
L 09/18/2016 - 16:31:07: [SM]   [0]  Line 496, D:\CSGO Server\Bhop\CSGO\csgo\addons\sourcemod\scripting - Copy\shavit-misc.sp::OnPlayerRunCmd()
spammed ever since I updated to the new CSGO version. Any help will be greatly wanted.

-outlassn

**Comment by Technoblazed** [comment]
csgo ded

**Comment by Technoblazed** [comment]
move to css :^)

**Comment by outlassn** [comment]
Nah dude I got the old version working, csgo bhop is perfectly fine for me :)

**Comment by Technoblazed** [comment]
I quit cs until double jumping is removed \o/

**Comment by outlassn** [comment]
Honestly its not that bad but ay, your choice :+1:

**Comment by Technoblazed** [comment]
I can cheat kz maps, can cheat bhop maps :|

**Comment by outlassn** [comment]
True that, anyway @shavitush if you know why this keeps happening, please inform me :)

**Comment by outlassn** [comment]
Now am getting 

L 09/18/2016 - 17:31:12: [SM] Native "Shavit_GetBhopStyle" reported: Plugin owning this native is currently paused.
L 09/18/2016 - 17:31:12: [SM] Displaying call stack trace for plugin "shavit-misc.smx":
L 09/18/2016 - 17:31:12: [SM]   [0]  Line 434, D:\CSGO Server\Bhop\CSGO\csgo\addons\sourcemod\scripting - Copy\shavit-misc.sp::DHook_GetMaxPlayerSpeed()

**Comment by outlassn** [comment]
After ~40 min of csgo bhop, its giving me a massive headache from the new bug. Gonna try CSS. @Technoblazed

**Comment by shavitush** [comment]
Hehe; we still want to take care of the issue though!
Can you attack the beginning of the log file please after restarting the server and deleting the existing log?

**Comment by outlassn** [comment]
I just made a HUGE mistake and perma-deleted my sourcemod folder... ;_; gonna try to re-make it in a bit. Maybe it will clear up when I do- Give me a few hours :P

**Comment by outlassn** [comment]
Guys, Any idea why I can bhop well in CS:GO but cant bhop for shit in CS:S?

**Comment by Technoblazed** [comment]
Er, howso?

**Comment by outlassn** [comment]
I think I just had to get used to it, Look like in CS:S you cant do super sharp turns and expect it to keep your speed.

**Comment by Technoblazed** [comment]
Did you use a movement unlocker on your csgo server?

**Comment by outlassn** [comment]
What's that??

**Comment by Technoblazed** [comment]
CSGO has a movement unlocker plugin, that allows more accurate strafing simulator to CSS. Basically, you can actually strafe... https://forums.alliedmods.net/showthread.php?t=255298

**Comment by outlassn** [comment]
Nononono I'm saying in CS:S i can't seem to strafe. I can strafe just fine in csgo  ;)

**Comment by Technoblazed** [comment]
You'll find 99% of servers use it.

**Comment by outlassn** [comment]
I think i'm to blame as I only started bhopping when CS:GO came out. Never bhopped on CS:S before. Dunno it's movement.

**Comment by outlassn** [comment]
Just re-made my sourcemod folder and everything is working in CS:GO. I give up on CS:S it's too troublesome. I proudly say SCRDS is the most annoying program to work with Q_Q

Also RIP bhop_arcane_csgo- map broken thanks to update

**Comment by shavitush** [comment]
Glad it works :)

**Comment by outlassn** [comment]
Hey @shavitush do you think a plugin will fix the crouch issue or do we have to wait for an statement from Valve? I hope its fixable and people are working on it. Its a serious issue as some maps are being destroyed time-wise ATM and others are being RTV'd immediately because they are simply not possible anymore ;_;

**Comment by Technoblazed** [comment]
Valve said they'd add cvars for it, but ya know. Valve.

**Comment by outlassn** [comment]
Valve. "We will add cvars"

HL3 RELEASES

"csgo update cvars for game breaking bug added"

**Comment by Technoblazed** [comment]
It's not game breaking, they're not responsible for surfing/bhopping etc. | If the community complains enough, it's get fixed.

**Comment by outlassn** [comment]
That's true but if they really neglect it, Valve will see atleast 10% decline in players (I hope there are that many of our kind atleast)

**Comment by Technoblazed** [comment]
GO is a dying game.

**Comment by outlassn** [comment]
That's true, but I wonder if Valve will take initiative and push GO back up to the top or make a new CS game.

**Comment by Technoblazed** [comment]
Well, Source 2 is done, so they're just drying GO out.
