### ISSUE TITLE
Replace rank tag with admin tag

### ISSUE THREAD

**Issue by thedudeguy1** [shavitush/bhoptimer#246]
I'm not sure if there is a way to do this but a great feature would be a cvar that a server owner could set where if a player is an admin and, for example, the server is using admin tags from [this plugin](https://forums.alliedmods.net/showthread.php?t=186695), (paired with [this plugin](https://forums.alliedmods.net/showpost.php?p=2271350&postcount=1047) for CS:GO color support) they could have the cvar control whether the rank (and/or chat colors) are replaced by their own admin tag/colors (another option could be to have the admin tag shown after their bhop rank).

**Comment by Technoblazed** [comment]
https://github.com/shavitush/bhoptimer/issues/117 - It'd be doable with the new chat processor that is being used, however the CS:GO color support plugin you linked, wouldn't be needed as a chat processor is already in use.

**Comment by shavitush** [comment]
Custom Chat Colors isn't usable for CS:GO.

**Comment by thedudeguy1** [comment]
@shavitush I'm using it without issue. The plugin can be used with CS:GO but with minimal colors. When used with [this](https://forums.alliedmods.net/showpost.php?p=2271350&postcount=1047) it supports many colors in CS:GO. Either way, it was simply an example. Nothing about the mentioned plugins needs to be implemented. I was only suggesting that a player's admin status could be checked and if a certain cvar was in place, that person would have their admin tag show instead of their rank. This should be possible without interaction with Custom Chat Colors by simply not appending a rank and letting Custom Chat Colors append the tag.

**Comment by Technoblazed** [comment]
@thedudeguy1 by many colors, you mean the default 16 allowed in csgo? o.O

```
new String:CTag[][] = {
	"{01}", //White
	"{02}",
	"{03}",
	"{04}",
	"{05}",
	"{06}",
	"{07}",
	"{08}",
	"{09}",
	"{0A}",
	"{0B}",
	"{0C}",
	"{0D}",
	"{0E}",
	"{0F}",
	"{10}"
};
```

**Comment by thedudeguy1** [comment]
@Technoblazed Yest that's what I meant. I said many as a comparison to only having the three colors that Custom Chat Colors allows.

**Comment by Technoblazed** [comment]
CCC is insanely outdated, and very rarely used.

**Comment by thedudeguy1** [comment]
@Technoblazed I still use it because I haven't actually gone out and found any other plugins like this one. Additionally CCC hasn't had any problems so I haven't needed to change. But back to the topic, all I was suggesting is that if a player has certain flags, it would be nice to have the admin tag assigned by CCC show after the person's rank and before their name. If this isn't possible, then maybe an option can be set to have no rank show at all and let CCC do as it pleases.

**Comment by Technoblazed** [comment]
The chat processor used in shavit's plugin will do the job, it's doable, and not that much work :)

**Comment by thedudeguy1** [comment]
That's what I was hoping for. Maybe this could be an enhancement implemented in 1.5b or the next version.

**Comment by shavitush** [comment]
just use this https://forums.alliedmods.net/showthread.php?t=286913

**Comment by thedudeguy1** [comment]
@shavitush Should I replace [my current chat proccesor](https://forums.alliedmods.net/showthread.php?t=198501) with [that](https://forums.alliedmods.net/showthread.php?t=286913)? Can I simply remove the old chat processor and the new one will work out of the box or do my plugins that rely on the old version need to be rewritten to use the new processor?

**Comment by shavitush** [comment]
My plugin works fine with the new chat processor. As you can see, the requirements section of my timer lists the new one as a requirement for `shavit-chat`.

**Comment by thedudeguy1** [comment]
What would you recommend that I do to have my admin's tags visible and not overwritten by their rank? Would I just have to disable ranks?

**Comment by shavitush** [comment]
Implemented into the new `shavit-chat`, see !cchelp.

**Comment by michaelrw10** [comment]
I havent seen how one can add ranks to players chat tags.. am i missing something? I see where you can add a custom name, but not a rank chat tag that is based on the players current ranking.

**Comment by shavitush** [comment]
@michaelrw10 no, it's not implemented yet as rankings aren't finished.
