### ISSUE TITLE
Replay bots issue

### ISSUE THREAD

**Issue by Zelost** [shavitush/bhoptimer#249]
For some reason there are no bots (or only 1 of all available styles) for certain maps only... Any ideas?
Last version of timer.
P.S. No errors at all...

**Comment by shavitush** [comment]
are you lacking server slots? or.. the map may be missing spawn spots and `shavit-misc` couldn't spawn them for some reason
try updating sourcemod

**Comment by Zelost** [comment]
48 slots, team limits plugin.
Forgot to tell - its a totally random issue... Sometimes bots works fine, othertimes not...
Problem appeared since last updates... Replay worked fine before...
P.S. Sorry for my english...
Also odd, cause bot_quota = 5, with no bots at all ><

**Comment by shavitush** [comment]
i can't really replicate this, sorry.
guess we have to wait until someone knows why it happens to you

**Comment by Zelost** [comment]
Well, ok. Not a big problem, but still kinda odd cause it's worked  fine before... Mb I need to delete all the records and replays\refresh DB... Also I found that glitch appears only when there are some players on the server. I thought they may take bot's slots, but only for certain maps? It's more and more ridiculous...

**Comment by shavitush** [comment]
does `bot_quota mode normal` in your server config solve it?

**Comment by del6597** [comment]
Do you have a .nav file for the associated maps? I've had issues with getting bots to spawn when there is no .nav file.

**Comment by Zelost** [comment]
Shavit, I don't solve it yet... And it's "fill" for me. Mb that's the reason! I will try use normal one, than tell u if its working!
Del6597, there are nav files, created by base.nav

**Comment by Zelost** [comment]
Okay, I found a reason of my issue.  Teamlimits plugin, which also creates infinity spawn points does not affect bots... After adding a manual spawn points via "spawn tools 7" - bots are working. Odd, cause shavit_misc_createspawnpoints was set to 32...
Thanks everyone for help...
