### ISSUE TITLE
Start Zone - Very difficult to move

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#25]
When moving through the start zone, you appear to have 10 speed and tons of  jittery movement, makes it incredibly hard to move out of the start zone.

Latest Plugin Code,
SourceMod 1.7.3-dev+5303,

**Comment by shavitush** [comment]
I fixed it! Make sure your `plugin.shavit-misc.cfg` file has `shavit_misc_prespeedlimit` set to 250 and above.

**Comment by Technoblazed** [comment]
Thanks, it's set to shavit_misc_prespeedlimit "320.00". Recompiled to the latest code but still has the same issue D:

**Comment by shavitush** [comment]
Try doing the following:
1. Turn off your CS server.
2. Delete `cfg/sourcemod/plugin.shavit-misc.cfg`.
3. Turn the server on.
4. Modify `plugin.shavit-misc.cfg` to be however you want it.
5. Restart the server - don't reload the plugin.

Please report back!

**Comment by Technoblazed** [comment]
Seems to be resolved now, just needed a restart rather than a map change, thanks for the help :D Looking forward to using this plugin over our old timer, the second the ranking module is done in your next build, this will be straight on .

**Comment by Technoblazed** [comment]
Where's the best place for suggestions, on the allied modders forum?

**Comment by shavitush** [comment]
I'd prefer to have them in AM yeah
