### ISSUE TITLE
Why dont appear nothing in webserver ? 

### ISSUE THREAD

**Issue by BernardinoSousa** [shavitush/bhoptimer#251]
http://ptrunners.net/recordes/

**Comment by Weeeishy** [comment]
I'm having the same issue, but that's probably because the database is being hosted in another box.

**Comment by Technoblazed** [comment]
With the webserver, that wouldn't make a difference, without this guys actual php logs, can't determine any issue

**Comment by Weeeishy** [comment]
I have no error_log in that directory, otherwise I would've posted it earlier.

**Comment by Technoblazed** [comment]
For your page, enable php errors, just add it to the top of the page code

**Comment by shavitush** [comment]
/var/log/nginx/error.log

**Comment by Technoblazed** [comment]
Shavit, most plebs still use Apache because it's the first thing to appear on Google

**Comment by shavitush** [comment]
oh right

**Comment by AzaZPPL** [comment]
`/var/log/httpd/error.log`
or
`/var/log/apache2/error.log`

**Comment by mrkos9i4ok** [comment]
use
define('USES_RANKINGS', '0');

**Comment by Weeeishy** [comment]
Thank you @mrkos9i4ok 

It works fine for me now.
