### ISSUE TITLE
Rewrite web interface

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#252]
The project is not dead! Development is slow, I know - but I'm a bit busy irl :(

Anyways: I've got an idea to rewrite the web interface and make it work as a simple and functional website.
## Features:
- [ ] Some kind of automatic configurations. Maybe cache styles names to database and show on website?
- [ ] Player profiles - avatar, rank, list of records (sorted by points), a page per style and personal recent activities.
- [ ] Player leaderboards
- [ ] Recent rank 1 records across the server.
- [ ] Map specific leaderboards.
- [ ] Light/dark theme, or use the one by @Technoblazed if we go with Bootstrap again.

To be done by myself.

**Comment by Technoblazed** [comment]
Hey shavit, would you be interested/mind if I did some of this for you? Planned on doing it anyway and just removes something else of your list. I know you put `To be done by myself` but ya know.

**Comment by shavitush** [comment]
sure! let me know how it goes :)

**Comment by Technoblazed** [comment]
Will do!

**Comment by shavitush** [comment]
Update: Dropped this. Not really necessary and I figured out no one really uses it.
