### ISSUE TITLE
Cvar shavit_misc_prespeed don't work(

### ISSUE THREAD

**Issue by T1MOXA** [shavitush/bhoptimer#253]
I have "**shavit_misc_prespeed 1**" but I can't jump in the start zone.

**Comment by shavitush** [comment]
shavit_core_blockprejump 0

**Comment by T1MOXA** [comment]
Thank you. Helped :)

**Comment by T1MOXA** [comment]
I have another problem, I can't change the value of "sv_airaccelerate". It is always "1000". I tried using server.cfg and console but it didn't yield results.

**Comment by Technoblazed** [comment]
Check your shavit_misc config file, it can also be set per style in the styles config as well

**Comment by T1MOXA** [comment]
Thx
