### ISSUE TITLE
[Question] Styles

### ISSUE THREAD

**Issue by Nevvy** [shavitush/bhoptimer#254]
Hi
How can i restrict selected styles to ADMFLAG?

**Comment by Technoblazed** [comment]
You can't within the current code, that doesn't seem like something people would need. Mind if I ask what you're using it for?

**Comment by Nevvy** [comment]
@Technoblazed 
I'd like to create a special style for admins and i want show it on www page.

**Comment by Technoblazed** [comment]
What sort of special style

**Comment by Nevvy** [comment]
Edited slow mo with enabled rank but only for admins

**Comment by Technoblazed** [comment]
I guess it could be done using the new styles layout, but I don't have the time to do it for you, and I really don't see it as a necessary aspect :/

**Comment by Nevvy** [comment]
@Technoblazed np, I'd like ask 2 u for 1 more thing
Where i can disable gravity check in zones?
For example when i'm using sm_gravity @me 0.3 in zone and i want left it i have normal gravity

**Comment by Technoblazed** [comment]
Gravity is a style option, check your styles config

**Comment by Nevvy** [comment]
@Technoblazed 
Thank u very much

**Comment by shavitush** [comment]
no and wont be added ever
