### ISSUE TITLE
mp_ignore_round_win_conditions doesn't work properly?

### ISSUE THREAD

**Issue by T1MOXA** [shavitush/bhoptimer#255]
If the value is mp_ignore_round_win_conditions 1, the round will not end. 
And if you put 0 the round will restart if the player dies, or leaves the team.

**Comment by shavitush** [comment]
what's wrong..?

**Comment by Technoblazed** [comment]
If you set an mp_roundtime, and an mp_timelimit, the round will end.

**Comment by T1MOXA** [comment]
These values are already there. mp_roundtime 60 and mp_timelimit 60

**Comment by Gucccii** [comment]
Yeah it's really broken. I used a force round end plugin to get it to work when I still used the timer. Hopefully that will solve it.

**Comment by shavitush** [comment]
This plugin should be used if you want map rotations on an endless-round server: https://forums.alliedmods.net/showthread.php?p=2245847
