### ISSUE TITLE
!invis as alias for !hide

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#262]
!invis (or /invis) was used on cs 1.6 bhop / speedrun servers and still tons of people are using this command for some reason. Maybe add it to the plugin?

**Comment by shavitush** [comment]
I don't think it's necessary, I mean - I've never seen !invis being used ever

Might want to just use this:

```sp
#include <sourcemod>

#pragma semicolon 1
#pragma newdecls required

public void OnPluginStart()
{
	RegConsoleCmd("sm_invis", Command_Invis, "Alias for sm_hide.");
}

public Action Command_Invis(int client, int args)
{
	FakeClientCommand(client, "sm_hide");
	
	return Plugin_Handled;
}
```
