### ISSUE TITLE
Steamworks Replacement

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#264]
Steamworks shouldn't be necessary, from my current message plugin:

```
if(StrContains(sText, "{SERVERIP}") != -1)
       {
         int ips[4];
         int ip = GetConVarInt(FindConVar("hostip"));
         int port = GetConVarInt(FindConVar("hostport"));
         ips[0] = (ip >> 24) & 0x000000FF;
         ips[1] = (ip >> 16) & 0x000000FF;
         ips[2] = (ip >> 8) & 0x000000FF;
         ips[3] = ip & 0x000000FF;
         Format(sBuffer, sizeof(sBuffer), "%d.%d.%d.%d:%d", ips[0], ips[1], ips[2], ips[3],port);
         ReplaceString(sText, sizeof(sText), "{SERVERIP}", sBuffer);
       }
```

**Comment by shavitush** [comment]
Sadly if you use a different `-ip 0.0.0.0` value than public one, `hostip` will report an incorrect one

SteamWorks is reliable for this usage

**Comment by Nickelony** [comment]
I think it's useless since you can just type your IP as a text xD

**Comment by Technoblazed** [comment]
It's a nice thing to have for some people, if you don't wanna use {serverip}, don't install steamworks. Simples :D

**Comment by shavitush** [comment]
yeah, `{serverip}` will only work if you have steamworks installed - but it isn't a requirement!

**Comment by StrafeHack** [comment]
I must agree with Nickelony having the server ip as a variable doesn't make much sense, no player is going to remember your numerical IP... and if they really want it they can just use status or the browser at any time.

You should just type in your dns if you have one manually.

**Comment by Technoblazed** [comment]
It's an optional feature? If you don't want it don't use it lol
