### ISSUE TITLE
[Question] Disable teleport for TT

### ISSUE THREAD

**Issue by Nevvy** [shavitush/bhoptimer#265]
Hi, How can i disable teleport to zone for TT?
I'd like 2 keep it for CT but not for TT.
It's annoying on deathrun gamemode
2nd option is keep shavit_zones_teleporttostart "1" but players can cheat time on timer with !style command

**Comment by Technoblazed** [comment]
Don't mean to come off rude, but:

`CS:S/CS:GO bhop timer`
`bhop`

Again, features that will never be added.

**Comment by Nevvy** [comment]
@Technoblazed i know, 
btw this is not a feature request  but question.
I'd like 2 know how can i disable it or where i must remove it in .sp

**Comment by Nevvy** [comment]
Anyway it's kinda a bug
Change !style in a run should stop timer to prevent cheating a time when shavit_zones_teleporttostart is 0

**Comment by shavitush** [comment]
i can't replicate this in my servers at all
both CS:S/CS:GO, it just doesn't happen

**Comment by Nevvy** [comment]
Ill try send u video today. Now I'm at work

**Comment by shavitush** [comment]
Was a bit hard to understand what you mean, sorry

**Comment by Nevvy** [comment]
https://www.youtube.com/watch?v=dFNcZ-ZF_Bs&feature=youtu.be

**Comment by Nickelony** [comment]
Nope, it's gone :)
