### ISSUE TITLE
HUD x2

### ISSUE THREAD

**Issue by Rostu13** [shavitush/bhoptimer#267]
Hi Shavit. Since the shavit-hud has changed with this theme https://github.com/shavitush/bhoptimer/issues/242. And would like to change to #define HUD_DEFAULT (HUD_MASTER | HUD_CENTER | HUD_ZONEHUD | HUD_OBSERVE | HUD_TOPLEFT | HUD_SYNC | HUD_2DVEL). But when I put the plugin is recompiled the remains of old with the spec list and key overlay

sorry google translation

**Comment by shavitush** [comment]
those are the default settings, tell your players to use !hud and choose whatever they want
