### ISSUE TITLE
Extend `sm_wr` and `sm_bwr`'s arguments

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#268]
regular maps: (CS:S)
`sm_wr _ml` won't work,  
`sm_wr bhop_ml` will

workshop: (CS:GO)
`sm_wr bhop_ml_csgo` won't work
`sm_wr workshop/535916493/bhop_ml_csgo` will

so my plan is to load zoned maps into an array and make `sm_wr` or `sm_bwr` perform a lookup from this array; or simply use mysql's `LIKE` clause

we'll see how it goes :)

**Comment by Technoblazed** [comment]
If you can, wanna run an exact match before a LIKE. From a surf plugin I use, say you have a map called surf_me, searching for that would bring up surf_mellow etc

**Comment by shavitush** [comment]
that was my intention!
