### ISSUE TITLE
Bot shooting

### ISSUE THREAD

**Issue by nknm** [shavitush/bhoptimer#269]
I don't know if anyone asked about this before but is there an option / command to make the bot stop because its annoying in small maps when the wr was done shooting for some reason to hear the bot shooting.
Also i'd like to suggest making that u don't hear other ppls steps nor gun shots if that was invented already or if there is any plugin to do that i'd appreciate the information !

**Comment by Technoblazed** [comment]
Just write a tiny plugin to hook the sound if the client is a bot

**Comment by nknm** [comment]
that would be an option but i actually want to bots to not shoot if that was possible to disable bcuz it looks kinda bad in replays imo.

**Comment by shavitush** [comment]
i won't change it because runs on maps like exodus or badges will look horrible
if it's a big deal, edit the following two lines in shavit-replay to be like the one below them

    gA_Frames[style].Set(i, view_as<int>(aReplayData[5]), 5);
    gA_Frames[style].Set(i, (iStrings == 6)? StringToInt(sExplodedLine[5]):0, 5);

\>>>

    gA_Frames[style].Set(i, 0, 5);
