### ISSUE TITLE
Mismatched zone names in shavit-zones.cfg

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#272]
The "NoLimit" zone name for color changing is swapped with the "Teleport" zone. You should re-check all the names imo. ^_^

**Comment by shavitush** [comment]
![image](https://cloud.githubusercontent.com/assets/3672466/19211366/4ed630b0-8d43-11e6-93b4-f35fcc08580c.png)

![image](https://cloud.githubusercontent.com/assets/3672466/19211369/528c2da4-8d43-11e6-9f95-3c343dd1fce2.png)

i'm confused

**Comment by Nickelony** [comment]
Just change the Teleport zone color to red, and the NoLimit zone to green, place them in-game and you'll see what I mean.

**Comment by shavitush** [comment]
i'm pretty sure that every zone that has support for multiples of them will experience this issue then

**Comment by shavitush** [comment]
This fix is a temporary fix, I apparently handled freestyle zones the wrong way, the whole time.. Will hopefully take care of it soon when I rework the zones plugin

**Comment by shavitush** [comment]
Will be fully fixed when I rework zones, won't work on the current version for a while so I don't have to fix issues that I rewrite the code of anyways, sorry.
