### ISSUE TITLE
Bots not showing records on some maps?

### ISSUE THREAD

**Issue by thorel64** [shavitush/bhoptimer#273]
Was my error

**Comment by Nickelony** [comment]
Try to delete the unloaded records in your MySQL and pass the map again.

**Comment by shavitush** [comment]
addons/sourcemod/data/replaybot/

**Comment by thorel64** [comment]
Oh christ, when i uninstalled sourcemod after the recent bug with the latest update of csgo it removed all the records replays omg

**Comment by Technoblazed** [comment]
You didn't need to completely remove sourcemod with the latest update...you literally had to update the csgo/css bin file...
