### ISSUE TITLE
Zones don't load fast

### ISSUE THREAD

**Issue by Gucccii** [shavitush/bhoptimer#274]
As the titles says my map zones don't load right when the map is started. It probably takes around a minute / two minutes for the map zones to appear and become active. During the first one to two minutes of the round it says " [Timer] Your timer will not start as a start zone for the map is not defined". Would this be caused by my MYSQL database not updating fast enough to pull the information onto the game server. Or is there an option i'm not seeing. Thank you

**Comment by Nickelony** [comment]
Can't replicate. 100% a MySQL problem.

**Comment by shavitush** [comment]
you should use either a local mysql server or sqlite
