### ISSUE TITLE
Nc without stoping timer.

### ISSUE THREAD

**Issue by nknm** [shavitush/bhoptimer#275]
so basically you can noclip inside the start zones and the timer doest stop and ur "pre speed" is arround 1500 speed bcuz u get that boost from noclip. I'm using an older version idk if you noticed and fixed the bug already.

**Comment by nknm** [comment]
Also in some maps like bhop_downdowndown when u fall in some places u just fly out of the spawn and the timer resets to 0 sec and u can keep the speed

**Comment by shavitush** [comment]
upgrade to 1.5
