### ISSUE TITLE
Holding spacebar while in Start Zone makes your character hover.

### ISSUE THREAD

**Issue by outlassn** [shavitush/bhoptimer#281]
Title should expain it, Just go to start zone and hold down space.

**Comment by Nickelony** [comment]
can't replicate.

**Comment by outlassn** [comment]
For real? I'll take a video of it later if I have time

**Comment by Nevvy** [comment]
+1
If u have "players cant jump in startzone" character is "floating"

**Comment by nknm** [comment]
That is because sv_autobunnyhopping 1, i think, also u can just press the space bar and do auto if server has sv_autobunnyhopping 1 idk if shavit noticed already.

**Comment by shavitush** [comment]
i noticed it and the purpose of having it built into the timer is purely so you get it enabled for auto styles, and disabled for scroll styles

**Comment by shavitush** [comment]
i can replicate this ingame but it can't be fixed, due to the autobhop being caused by client prediction
you'll have to either deal with it or disable blockprejump, sorry
