### ISSUE TITLE
add "sv_maxvelocity" per style setting?

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#282]
Would be a very useful feature imo.

I'm not sure if it's possible, but you already did "sv_airaccelerate" per style.

**Comment by Technoblazed** [comment]
```
"velocity_limit"	"0.0" // velocity limit: set to 0.0 for unlimited, 400.00 for 400vel styles etc
```

**Comment by Nickelony** [comment]
It doesn't work like that. sv_maxvelocity doesn't allow you to go over the limit and "velocity_limit" stops you after landing.

**Comment by shavitush** [comment]
will cause lag, don't think it's possible :/
