### ISSUE TITLE
Bug update?

### ISSUE THREAD

**Issue by Rostu13** [shavitush/bhoptimer#283]
Hello shavit.  I downloaded the latest version of your timer. But there is no !End. Take a look yourself : 1 http://s45.radikal.ru/i107/1610/8c/66bafe0047b6.png and 2 http://s017.radikal.ru/i400/1610/75/68953988fdc3.png

**Comment by Nickelony** [comment]
Check if shavit_zones_teleporttoend is set to 1.
BTW nice links. For some reason I got a android virus on my Windows Phone. XD

**Comment by Rostu13** [comment]
In shavit-zones.sp I do not have this code. And when I removed all of the folder cfg nothing there as well as the code

**Comment by shavitush** [comment]
Use either imgur.com or hosting images, or drag them here. I'm not clicking these shady links.

Anyways, set `shavit_zones_teleporttoend` to 1

**Comment by Rostu13** [comment]
I do not see the script in shavit-zones . http://imgur.com/a/XBqVq

**Comment by Technoblazed** [comment]
You just took a screenshot of part of the code, what you have there are changes, follow the numbers on the left hand side. See how it skips? Regardless, sm_end comes under shavit-core: https://github.com/shavitush/bhoptimer/blob/master/scripting/shavit-core.sp#L233

**Comment by Rostu13** [comment]
I'm talking about something that is not generated shavit_zones_teleporttoend. (CFG all deleted them all again generated.)

**Comment by Technoblazed** [comment]
`shavit_zones_teleporttoend` isn't a valid command?

```
public Action Command_TeleportEnd(int client, int args)
{
	if(!IsValidClient(client))
	{
		return Plugin_Handled;
	}

	if(gB_Zones && Shavit_ZoneExists(Zone_End))
	{
		Shavit_StopTimer(client);
		Call_StartForward(gH_Forwards_OnEnd);
		Call_PushCell(client);
		Call_Finish();
	}

	else
	{
		Shavit_PrintToChat(client, "You %scan't%s teleport as an end zone for the map is not defined.", gS_ChatStrings[sMessageWarning], gS_ChatStrings[sMessageText]);
	}

	return Plugin_Handled;
}
```
Is the response of !end, if you have an end zone on the map, it will work.

**Comment by Rostu13** [comment]
Maybe something I do not understand. Probably not a lot of silly. But the video can help you: https://www.youtube.com/watch?v=71lJTizCeqw&feature=youtu.be

**Comment by Technoblazed** [comment]
`shavit_zones_teleporttoend` is NOT a cvar. If you add an end zone to your map, you will be able to use !end.

**Comment by Rostu13** [comment]
And unless this team is not for on / off commands !End. I need to turn it off

**Comment by shavitush** [comment]
@Technoblazed it will be a cvar when I merge #280.
@Rostu13 either ask someone to translate Russian > English for you (not automated translation!), write Russian or don't write at all. Try reading your own comments and realize how impossible it is to understand you.

**Comment by Rostu13** [comment]
Попробую написать на русском. Не создается cvar в shavit-zones и это видно по видео. Все что мне нужно это отключить команду !end.

**Comment by shavitush** [comment]
Apply the commits from #280 and you will have `shavit_zones_teleporttoend` as a valid cvar.
