### ISSUE TITLE
Zone Glitch

### ISSUE THREAD

**Issue by Nevvy** [shavitush/bhoptimer#284]
Hi shavit
1. We can only create 1 glitch zone or its bug?
2. Missing "red" paraments in shavit-zones

> 		"Teleport"
> 		{
> 			"visible"	"0"
> 			"green"		"200"
> 			"blue"		"0"
> 		}

**Comment by Technoblazed** [comment]
You could always make a PR to fix the second thing :^)

**Comment by shavitush** [comment]
1. it's intended, will be changed when i remake the new zones plugin
2. it's not missing, if it's not included, then the default value is 255
