### ISSUE TITLE
Noclip through zones and keep timer.

### ISSUE THREAD

**Issue by nknm** [shavitush/bhoptimer#286]
its sort of what the title means i recorded with csgo demos. I'll add it to this post

https://mega.nz/#!qpRQybRD!BOA3NK54G0dTpGG-shF02tem75l39ZF7Z6pwloMgTf4

Idk if u accept mega files if u dont tell how else can i send this.

I'll explain what happens. Basically if you noclip to a certain trigger and cross the startzones without jumping u'll slide through it and keep some of your speed and also reset the timer.

**Comment by shavitush** [comment]
youtube

**Comment by nknm** [comment]
https://youtu.be/FH4KhksuYt4
ther you go

**Comment by shavitush** [comment]
upload your cfg/sourcemod folder

**Comment by shavitush** [comment]
(not to mega please)

**Comment by nknm** [comment]
[sourcemod.zip](https://github.com/shavitush/bhoptimer/files/542883/sourcemod.zip)

**Comment by nknm** [comment]
its here, uploaded through the github

**Comment by thorel64** [comment]
@nknm sorry for this bud but howd you get ssj to work? i get constant crashes on my end! would mean alot to get some help, using alkatraz one

**Comment by Zelost** [comment]
You just don't have any speed limits at Start Zone. U are droping down, map teleports u to start, and you are keep your speed.

**Comment by Technoblazed** [comment]
shavit-core.sp Line 388:

```
if(GetEntityMoveType(client) == MOVETYPE_NOCLIP)
	{
		Shavit_PrintToChat(client, "Your timer %swill not%s start as you are %snoclipping%s.", gS_ChatStrings[sMessageWarning], gS_ChatStrings[sMessageText], gS_ChatStrings[sMessageVariable], gS_ChatStrings[sMessageText]);
		return Plugin_Handled;
	}
```

Would something like this work?

**Comment by shavitush** [comment]
I'll just make the timer not start on non-prespeed styles if you're noclipped

**Comment by Technoblazed** [comment]
perfect

**Comment by shavitush** [comment]
Can you try replicating with 7c94f119f5d4eb58a0855e3b8fa6aee9be30e57d? I'll assume this is fixed for now until anyone is able to replicate the issue.
