### ISSUE TITLE
Bots optimization

### ISSUE THREAD

**Issue by Zelost** [shavitush/bhoptimer#287]
There is a glitch when bots are stuck behind a map, causing lags (red sv), until they finish their run. Any tips to solve this?
P.S. Sorry for my english..

**Comment by shavitush** [comment]
could you record yourself replicating it on a map that has 0 records and 0 replays on it? upload it to youtube afterwards

**Comment by Zelost** [comment]
The reason is - lags caused by the bot which has a record, but stucking while replaying...
Here some example... https://www.youtube.com/watch?v=-3mX0pFjH-o
Glitch is totally random... (Mostly happens after map change or new record set)

**Comment by shavitush** [comment]
i've never seen this happen

is that a workshop map? could you provide error logs?

**Comment by Zelost** [comment]
No it's not. There are also no error logs at all. Lags disappears after bot finishing his replay or reloading the map... Could this be cause of warmup? But it's also happens after a new record was set...

**Comment by Zelost** [comment]
I'll update your timer to the last version now. Hopes it'll works..

**Comment by Technoblazed** [comment]
Any further problems?

**Comment by Technoblazed** [comment]
@shavitush, dead issue :)

**Comment by shavitush** [comment]
👍
