### ISSUE TITLE
shavit_misc_prespeed doesnt seem to work correctly at all

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#290]
`shavit_misc_prespeed "1"` or `shavit_misc_prespeed "2"` or `shavit_misc_prespeed "3"`, when holding down space in the start zone, you fly around and never touch the floor.

EDIT: When `shavit_core_blockprejump "1"` is set.

**Comment by Nickelony** [comment]
+1

**Comment by nknm** [comment]
You never actually fly around if you look at urself in 3rd person u r actually standing on the floor and other players see u also standing on the floor its just a visual bug due to the sv_autobunnyhopping 1 I think, not sure.

**Comment by shavitush** [comment]
this is caused by the engine prediction when csgo's auto bunnyhop is enabled

can't do anything about it, sorry
