### ISSUE TITLE
Issue on plugin startup

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#291]
It appears that shavit-core is being paused on launch, no idea why:

L 10/25/2016 - 12:35:36: [SM] Exception reported: Plugin owning this native is currently paused.
L 10/25/2016 - 12:35:36: [SM] Blaming: shavit-zones.smx
L 10/25/2016 - 12:35:36: [SM] Call stack trace:
L 10/25/2016 - 12:35:36: [SM]   [0] Shavit_GetDB
L 10/25/2016 - 12:35:36: [SM]   [1] Line 213, C:\Users\anthony\Desktop\bhop\shavit-zones.sp::OnPluginStart
L 10/25/2016 - 12:35:36: [SM]   [3] ServerCommandEx
L 10/25/2016 - 12:35:36: [SM]   [4] Line 390, /home/builds/sourcemod/linux-1.8/build/plugins/basecommands.sp::Command_Rcon

**Comment by shavitush** [comment]
>  L 10/25/2016 - 12:35:36: [SM] [4] Line 390, /home/builds/sourcemod/linux-1.8/build/plugins/basecommands.sp::Command_Rcon

the plugin doesn't support late loading
