### ISSUE TITLE
Replay bots

### ISSUE THREAD

**Issue by nknm** [shavitush/bhoptimer#292]
Hello shavit. I've noticed that many of the maps i've been playing have the wr on but no replay bot when i do !wr i see everyone's time but no replay bot replaying those times.
But when i make a better time than the previous wr the bot spawns and starts running the map but with a weird name it says "bot nm time and someone elses name", not my name, and i've noticed that some other players have gotten wrs and the replay bot doest have theire name in it. I'll upload a screenshot later when i see another bot with the wrong name in it.

Edit: Sorry for my english i feel like i've explained myself in a weird way. And i did not delete the replay demo  from the folder nor the wr with !delete
Edit2:
![20161025232359_1](https://cloud.githubusercontent.com/assets/22033631/19708164/8432ee22-9b14-11e6-91aa-d28d40771d83.jpg)
![20161025232643_1](https://cloud.githubusercontent.com/assets/22033631/19708165/84edee20-9b14-11e6-9369-c92d9cf1ad62.jpg)

 Screenshots

**Comment by shavitush** [comment]
error logs?

**Comment by nknm** [comment]
http://pastebin.com/iJDzpQ5P

**Comment by Technoblazed** [comment]
You're using edited code, your timer is missing the `/` between times, who knows what else is gone/replaced.

**Comment by nknm** [comment]
I didnt edit the code xD!

**Comment by shavitush** [comment]
Is this still relevant? Re-open if it is, please. I'm trying to clean through irrelevant issues.
