### ISSUE TITLE
Sound for worst record on server

### ISSUE THREAD

**Issue by thedudeguy1** [shavitush/bhoptimer#293]
How doable would it be to allow an option to specify the worst time on the server for the style the user chose in the shavit-sounds.cfg? For example, if someone finished with the very worst time for the style they selected, a sound specified in the shavit-sounds.cfg would play.

**Comment by Technoblazed** [comment]
I'm fairly certain, this, or something very similar to this was in the plugin a while back, but removed :(

**Comment by Technoblazed** [comment]
Yup https://github.com/shavitush/bhoptimer/commit/38df2183e1c4be47f701c70600d8b63516b774c5#diff-d4bdf5e9672e233b66664d686592f124

**Comment by thedudeguy1** [comment]
@Technoblazed I'm still on that version and that "worst" specification is only for worse than your personal best. What I want is an option for worse than all the other records for the style that someone is playing. i.e. Somebody playing using the forwards style finishes behind all the other forwards records and a sound plays not because they didn't beat their personal best but because they were the worst record on the server.

**Comment by Technoblazed** [comment]
You'd have to have a fallback involved so that it doesnt sound until there is X amount of records.

**Comment by thedudeguy1** [comment]
This is true which adds another bit of extra complication for implementing this.

**Comment by shavitush** [comment]
I can do that.. it would be pretty useless for most users but sure
