### ISSUE TITLE
 [Timer] Timer stopped! Detected inconsistencies in button presses.

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#294]
What is this :| I hate my life. 2 hours into a map and it stops me :|

**Comment by shavitush** [comment]
prevents +strafe, you can disable it with "block_pstrafe" "0"

it also triggers when you alt-tab back into the game and there's lag

**Comment by Technoblazed** [comment]
Thank you :D

**Comment by Technoblazed** [comment]
Really could do with a way to completely stop it. I tab out of my game during runs to do stuff, and it's annoying when your timer is just stopped.

**Comment by shavitush** [comment]
i mean, it triggers when you use a cheat that uses +strafe *or* if you lag really hard when you alt-tab back

"block_pstrafe" "0" will definitely stop it

**Comment by Technoblazed** [comment]
This didn't stop it, still happened:

![Image](https://i.anthonyadams.me/281016021917.png)

**Comment by shavitush** [comment]
oh.. you're right

i found what's causing it and i'll push a fix asap

**Comment by Technoblazed** [comment]
Thanks :D

**Comment by Technoblazed** [comment]
I can't reliably trigger it, so I'll close the issue and let you know if it occurs again I guess
