### ISSUE TITLE
Map tiers and one sound suggestion

### ISSUE THREAD

**Issue by nknm** [shavitush/bhoptimer#297]
I think map tiers are really outdated especially on csgo (my opinion) I don't see map tiers since 1 year ago or something, and also i have a lot of maps on my server to set a tier for all of them and plus i don't have the knowledge to set them all up. I have no idea what is a tier 1,tier 2... I'd suggest the maps were made by exp or pts per map like if i finish with record X pts, a standard amount ignoring the tier of it.
I know it looks unfair for a 10 sec map giving as much points as a 20 min map, but you could make something like points based on the record time. if the record time is over 10 min the timer could calculate the map "tier" such as 10 min record = tier 3 for example and if the record gets beaten the map tier would changed considering the record time and then everyone elses' pts would be updated in the database according to that tier change.

You could make a sound for when someone takes your record such as some deranking sound or sad sound, would be funny :)

**Comment by shavitush** [comment]
I'm gonna end up making the rankings work in a way that points are automatically calculated - it may be a bit unfair as hard maps will reward like easier ones if times and leaderboards are similar but I think that's the best way to execute something like that

**Comment by nknm** [comment]
Yeah I have to agree, btw can i disable the ranks ?
I see everyone as unraked and myself as "one true god"

**Comment by Technoblazed** [comment]
Issue: https://github.com/shavitush/bhoptimer/issues/154 - Remove shavit-ranking & shavit-chat from your server until it's fixed.

**Comment by nknm** [comment]
Thnx a lot :)
