### ISSUE TITLE
sm_slap etc./teleport commands should stop timer

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#300]
Commands that can move a players position or teleport, should stop the timer.

**Comment by shavitush** [comment]
not doable without breaking trigger_teleport, sorry

you'd have to manually edit those

**Comment by Technoblazed** [comment]
Howso? Surely you could just use:
```
MOVETYPE_FLYGRAVITY
```
I may be wrong ofc :(
