### ISSUE TITLE
Stage Zones

### ISSUE THREAD

**Issue by PaxPlay** [shavitush/bhoptimer#303]
Stage Zones that show the player on which stage they are and show the player every zone if they are better or worse then their personal record. You could also Include other Informations like avarage velocity, sync and stuff compared to the PR.

**Comment by shavitush** [comment]
i think this is unnecessary for bhop, sorry

**Comment by del6597** [comment]
I can see the appeal in this sort of idea since you see features like this in racing games when completing a lap or reaching a checkpoint.  Similarly you see speed-runners using xsplit or similar software to do the same thing.

**Comment by Technoblazed** [comment]
Meh, it has arguments for both sides. If someone else were to code it, it might be considered, but as it stands shavit is the only person actively working on the project :)
