### ISSUE TITLE
!hud features 

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#306]
Mostly so I remember later
- Hide chat 
- Disable sounds 

!hud should probably be phased out to the !options, but no harm keeping both :)

**Comment by shavitush** [comment]
Sounds will be tricky to do - but chat is easy! I'll work on it soon :)

**Comment by Nickelony** [comment]
+ Hide the entire hud

Zipcore has added a !soundoff command to your plugin, but it's a little buggy because it stops working sometimes, but it may help you a lot: https://pastebin.com/raw/ssNsCUzn

**Comment by shavitush** [comment]
"Master" hides the entire HUD already.

I already got "disable sounds" implemented for CS:GO, I'll push it soon.

**Comment by Nickelony** [comment]
I mean the UI

cl_drawhud 0 or something

**Comment by shavitush** [comment]
Oh.. I don't know if it's possible. There's this: https://github.com/Nolan-O/bTimes/blob/master/addons/sourcemod/scripting/bTimes-random.sp#L780-L856

But in theory you won't be able to toggle it off.

**Comment by Nickelony** [comment]
Have you tried modifying zipcore's one?

**Comment by shavitush** [comment]
I genuinely thought you meant map sounds, and not sounds from the `shavit-sounds` plugin.. I'll work on it.

**Comment by shavitush** [comment]
Update: I tried implementing "hide chat", but apparently chat-processor conflicts with the plugin. I'll wait for the author to fix it. Closing for now.
