### ISSUE TITLE
Some translations issues

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#309]
As requested by Techno, here are some issues I found:

1. https://puu.sh/s7dDf.png

"Timer Commands" isn't translated, even if:
```
"TimerCommands"
{
	"pl"		"Komendy licznika"
}
```

2. https://puu.sh/s7dZg.png and 10 minutes later: https://puu.sh/s7e2I.png

umm... can't explain this...
Oh and "Add new map zone" is on the 3rd place for some reason.

3. https://puu.sh/s7e5V.png

"x16" got cut off and there is no option to translate FIRST / SECOND.

4. https://puu.sh/s7e7p.png

I know this is a minor issue, but "X" should be after "oś" in polish. Since this happens in most languages, it would be nice if you could translate them separately, like:
```
"XAxis"
{
	"pl"		"oś X"
}
"YAxis"
{
	"pl"		"oś Y"
}
```

5. https://puu.sh/s7efF.png

"**_Right_** krawędź"... same as above, it would be nice to translate them separately.

6. https://puu.sh/s7eYb.png

[PAUSE] is moving "Best" because of the (1)

7. https://puu.sh/s7eZW.png

Why is there an "s" after "skoków"
```
"WRJump"
{
	"pl"		"skoków"
}
```

8. 
```
"FirstCompletion"
{
	"#format"	"{1:c},{2:N},{3:c},{4:c},{5:s},{6:c},{7:c},{8:s},{9:c},{10:c},{11:d},{12:c},{13:d},{14:s},{15:d},{16:s},{17:s},{18:c}"
	"en"		"{1}{2}{3} finished ({4}{5}{6}) in {7}{8}{9} ({10}#{11}{12}) with {13} jump{14}, {15} strafe{16}{17}{18}."
}
```
{14} and {16} is pointless since it's just "s". Why isn't this just translated to "jumps" and "strafes"?
 
9. https://puu.sh/s7fHx.png

"Obróć strefę" means "Rotate zone" and this is the "Modify width/length" menu.

**That's everything I could find atm.**

**Comment by Technoblazed** [comment]
Follow https://github.com/shavitush/bhoptimer/pull/308 for patches.

**Comment by Nickelony** [comment]
@Technoblazed I've been using that version.

**Comment by Technoblazed** [comment]
Ik, I'm just saying watch the PR for the changes you requested.

**Comment by Nickelony** [comment]
@Technoblazed ok :)

**Comment by Technoblazed** [comment]
- [ ] 
- [ ]
