### ISSUE TITLE
!pause issues

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#310]
Another 2 issues I found, but this time it's not because of the translations, so calm down Techno ;)

1. https://puu.sh/s8gM5.png

When paused, the (1) moves the "Best:" text in the original english translation.

2. https://puu.sh/s8ha0.mp4 <- wait till the video loads if it won't open

You can use !pause in the start zone but it won't pause you anyway.

I've been testing this on Techno's PR.

**Comment by Technoblazed** [comment]
1st issue, did that happen before my PR as well?

**Comment by Nickelony** [comment]
@Technoblazed no

**Comment by Technoblazed** [comment]
o.O

**Comment by Nickelony** [comment]
Misunderstanding
