### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by nknm** [shavitush/bhoptimer#313]
the checkpoints are weird i feel like they could be so much better, im using the XTN's version, not sure if he made it or not, idk.
I'd like to be able to use the !cpmenu while having the timer running so i can see what time i'll get if i do my route perfect

**Comment by Technoblazed** [comment]
It's a third party plugin, has ABSOLUTELY nothing to do with shavit's timer.

**Comment by nknm** [comment]
I know what I was asking for is to shavit to add his own cpmenu to his timer, in the future.

**Comment by PaxPlay** [comment]
I wrote up something for this timer with a few modifications of it a while ago.
The code isn't really that good but I can send you the source.

https://pastebin.com/BUt8r9t2

**Comment by shavitush** [comment]
Thanks for the idea @PaxPlay, I'll try implementing something similar to your idea where you have a timer (yet it won't save your time) and a *simple* yet friendly customizable menu.

This is actually high priority and I'll get it done soon!

**Comment by shavitush** [comment]
@PaxPlay may I ask for your implementation of `Shavit_SetTimer`? I get very weird results while trying to implement it this way:

```
public int Native_LoadSnapshot(Handle handler, int numParams)
{
	int client = GetNativeCell(1);

	any[] snapshot = new any[TIMERSNAPSHOT_SIZE];
	GetNativeArray(2, snapshot, TIMERSNAPSHOT_SIZE);

	gB_TimerEnabled[client] = snapshot[bTimerEnabled];
	gF_PauseStartTime[client] = snapshot[fPauseStartTime];
	gF_PauseTotalTime[client] = snapshot[fPauseTotalTime];
	gB_ClientPaused[client] = snapshot[bClientPaused];
	gI_Jumps[client] = snapshot[iJumps];
	gBS_Style[client] = snapshot[bsStyle];
	gI_Strafes[client] = snapshot[iStrafes];
	gI_TotalMeasures[client] = snapshot[iTotalMeasures];
	gI_GoodGains[client] = snapshot[iGoodGains];
	gF_StartTime[client] = GetEngineTime() - snapshot[fCurrentTime];

	return;
}
```

Where `snapshot[fCurrentTime]` is the client's calculated time of when they saved the snapshot.
