### ISSUE TITLE
Wrong font code..

### ISSUE THREAD

**Issue by Zelost** [shavitush/bhoptimer#314]
(Previous version of the timer, without translation files...)
Shavit-Hud, 465 string:
strcopy(sHintText, 512, "<font size=\"18\" face=\"Stratum2\">");
must look like this:
strcopy(sHintText, 512, "<font size=\"20\" font face=\"Stratum2\">");
Otherwise, font is always the same...

**Comment by shavitush** [comment]
> (Previous version of the timer, without translation files...)

no thanks
