### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#317]
1. https://puu.sh/skwJP.png (Tab) of death is still there D:

2. The advertisements finally work!!! but you can't disable them xD
if set to 0.0 they spam like there is no tomorrow.

3. shavit_misc_noclipme "2" doesn't require the "ADMFLAG_CHEATS" flag. Every player can still use it.

**Comment by shavitush** [comment]
About 1: @Technoblazed maybe because of the translations?

I'll fix the rest ASAP!

**Comment by Technoblazed** [comment]
@shavitush Something to do with https://github.com/shavitush/bhoptimer/blob/master/scripting/shavit-hud.sp#L505 . There's an extra tab somewhere, but my head is hurting too much to find it :(

**Comment by shavitush** [comment]
advertisements/noclip2 fixes are implemented

**Comment by Technoblazed** [comment]
SEE! THIS IS ALL BECAUSE THE `(position)` WAS MOVED. >:D

**Comment by Nickelony** [comment]
shavit_misc_noclipme "2" still doesn't require the "ADMFLAG_CHEATS" flag, but I'm gonna close this so you will have less issues to handle :)

**Comment by Technoblazed** [comment]
Is `admin_noclipme` actually a valid command shavit?

**Comment by shavitush** [comment]
No, but `admin_noclipme` is an override you can use. I'll test this btw.

**Comment by Nickelony** [comment]
I've moved this problem to another issue but w/e
You can close this if you want.

**Comment by shavitush** [comment]
Well.. upon testing apparently the maximum value for the cvar was 1 and not 2 therefore it didn't work.. my bad. Fixing.
