### ISSUE TITLE
Translation issues + shavit_misc_noclipme "2" doesn't require the "ADMFLAG_CHEATS" flag

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#318]
V V V Scroll down V V V

**Comment by Technoblazed** [comment]
YOU SAID THERE WERE NO MORE

DJSIFHBKADUSFGKUADADGKUFGADFHAFHH

**Comment by Technoblazed** [comment]
I'll fix now

**Comment by Technoblazed** [comment]
1) Check your translations:
```
FormatEx(sDisplay, 16, "%T", "GridSnap", client, gI_GridSnap[client]);
```
```
"GridSnap"
	{
		"#format"	"{1:d}"
		"en"		"Grid snap: x{1}"
	}
```

**Comment by Technoblazed** [comment]
2) Check your translations:
```
"ZoneSizeIncrease"
	{
		"#format"	"{1:c},{2:c},{3:c},{4:d},{5:c},{6:.01f},{7:c}"
		"en"		"{1}{2} axis{3} (point {4}) increased by {5}{6}{7}"
	}
	"ZoneSizeDecrease"
	{
		"#format"	"{1:c},{2:c},{3:c},{4:d},{5:c},{6:.01f},{7:c}"
		"en"		"{1}{2} axis{3} (point {4}) decreased by {5}{6}{7}"
	}
```
Move your order around for value {2} and axis if you want to switch the values.

**Comment by Nickelony** [comment]
1)
```
"GridSnap"
{
	"#format"	"{1:d}"
	"pl"		"Szerokość kratki: x{1}"
}
```

2)
```
"ZoneSizeIncrease"
{
	"#format"	"{1:c},{2:c},{3:c},{4:d},{5:c},{6:.01f},{7:c}"
	"pl"		"{1}{2} oś{3} (punkt {4}) została zwiększona o {5}{6}{7}"
}
"ZoneSizeDecrease"
{
	"#format"	"{1:c},{2:c},{3:c},{4:d},{5:c},{6:.01f},{7:c}"
	"pl"		"{1}{2} oś{3} (punkt {4}) została zmniejszona o {5}{6}{7}"
}
```

don't have much time now, sry :/

**Comment by Technoblazed** [comment]
2)
```
"ZoneSizeIncrease"
{
    "#format"   "{1:c},{2:c},{3:c},{4:d},{5:c},{6:.01f},{7:c}"
    "pl"        "{1}oś {2}{3} (punkt {4}) została zwiększona o {5}{6}{7}"
}
"ZoneSizeDecrease"
{
    "#format"   "{1:c},{2:c},{3:c},{4:d},{5:c},{6:.01f},{7:c}"
    "pl"        "{1}oś {2} {3} (punkt {4}) została zmniejszona o {5}{6}{7}"
}
```

**Comment by Technoblazed** [comment]
4) Translationssssssssssssssss
```
FormatEx(sRankItem, 64, "%T", "TopNoResults", client);
```
```
"TopNoResults"
	{
		"en"		"No results found."
	}
```

**Comment by Technoblazed** [comment]
4) Translationsssssss
```
m.SetTitle("%T", "TopMenuTitle", client, gI_TopAmount);
```
```
"TopMenuTitle"
	{
		"#format"	"{1:s}"
		"en"		"Top {1} Players"
	}
```

**Comment by Nickelony** [comment]
Sorry for the delay. Today I'll check if everything works fine.

**Comment by Nickelony** [comment]
Since shavit's back, I've got the whole list of translation issues I could find:

1 . https://puu.sh/v5LbF.png - There is a 'tab' before "Best:". Might be related with the translations or the !pause command.

2 . "Timer Commands" isn't translated, even if: (shavit-zones.phrases)

```
"TimerCommands"
{
	"pl"		"Komendy licznika"
}
```

3 . https://puu.sh/v6JxR.png - "Wielkość siatki: x16" is cut out, here's the fix:

replace this: (in shavit-zones.sp)
```
char[] sDisplay = new char[16];
FormatEx(sDisplay, 16, "%T", "GridSnap", client, gI_GridSnap[client]);
```

with this:
```
char[] sDisplay = new char[64];
FormatEx(sDisplay, 64, "%T", "GridSnap", client, gI_GridSnap[client]);
```

4 . https://puu.sh/v6Mw7.png - Wrong label

5 . https://puu.sh/v6JVO.png - "increased" and "decreased" isn't available to translate in this case.

6 . https://puu.sh/v6LFD.png - "Left edge" has the same chat message as "Right edge" and "Front edge" has the same message as "Back edge"


+ The language switched randomly from polish (client language) to english (plugin language) for no reason.

* [ ]  The Tab
* [ ]  Admin menu translation
* [x]  Cutoff
* [ ]  Wrong label
* [ ]  Missing translations
* [ ]  Translation error

**Comment by Technoblazed** [comment]
1. Probably requires a rejiggle of the HUD.
2. No idea why it's not working, probably something to do with the admin menus.
3. Patched in fork.
4. Hmmm
5. This is gonna be a funky translation, but I'll patch it.
6. I'll also poke it
7. If the client doesn't have a cl_language set, or the server can't make up it's mind, it will default to the default sourcemod language, (english)

**Comment by Technoblazed** [comment]
@Nickelony For issue 6, can you send over a copy of your translations for that?

**Comment by Nickelony** [comment]
Here you go: https://puu.sh/w9SDv.zip
It's a little outdated so I don't know if it's still compatible.

**Comment by Technoblazed** [comment]
```
char sEdges[4][64];
			FormatEx(sEdges[0], 64, "%T", "Edge_Right", param1);
			FormatEx(sEdges[1], 64, "%T", "Edge_Back", param1);
			FormatEx(sEdges[2], 64, "%T", "Edge_Left", param1);
			FormatEx(sEdges[3], 64, "%T", "Edge_Front", param1);
```

Is used to determine the edge, don't see how tthat could be happening really :^)

**Comment by Technoblazed** [comment]
Or, I can look at the COMPLETELY WRONG SECTION of the screenshot

**Comment by Nickelony** [comment]
it's in the chat xD
