### ISSUE TITLE
plugin.shavit-hud.cfg doesnt appear to be generating

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#32]
Have restarted the server with the latest version, this .cfg file doesn't seem to be being created and can't find out why, maybe you can take a look?

**Comment by shavitush** [comment]
Well I didn't implement `AutoExecConfig()` for -hud as there's only one cvar, I'll do it anyways.

**Comment by Technoblazed** [comment]
Probably worth adding in now anyway, as I imagine they'll be future things that are required for the hud :3
