### ISSUE TITLE
rank and top

### ISSUE THREAD

**Issue by piotrekkrol7** [shavitush/bhoptimer#321]
Hi i use this plugin and i don't have nothing in !top and i don't have another rank . I finish all map .
No error logs

**Comment by Nickelony** [comment]
The rankings are broken. It's a known issue.

**Comment by Technoblazed** [comment]
https://github.com/shavitush/bhoptimer/issues/154

**Comment by piotrekkrol7** [comment]
when ranking will be repaired? you know something?

**Comment by Technoblazed** [comment]
In the future, no etas.
