### ISSUE TITLE
Help with setting up the plugin?

### ISSUE THREAD

**Issue by Lightningblade67** [shavitush/bhoptimer#322]
Hi,
first of all thank you for putting that much work into your plugin.

The problem is that I do not have much experience with setting up servers and I get this error
![image](https://cloud.githubusercontent.com/assets/15967061/20889919/29c95082-bb05-11e6-956e-cf3bf01f2453.png)

about 10 times every second. I don't know if that's the issue with the plugin putting 2 bots on the server but renaming SourceTV and the first bot instead of the 2 plugin added bots.
![20161205160819_1](https://cloud.githubusercontent.com/assets/15967061/20889930/36134668-bb05-11e6-9380-01b0954ff8b3.jpg)

Another question: are there more styles included than Normal and SW? If so, where do I activate them?

Thank you.

**Comment by Technoblazed** [comment]
@Lightningblade67 

1. Disable sourcetv, it's not needed: `tv_enable 0`
2. `/addons/sourcemod/configs/shavit-styles.cfg`  by default though `!styles` will show you the others.

**Comment by shavitush** [comment]
You should get the 1.5b version as 1.4b is unsupported :)

**Comment by Lightningblade67** [comment]
Thank you for the support. The thing is the SourceTV is another plugin which records everything into demo files. They are used to capture abuses like voice spamming or trolling. People can do !report and select a player. The plugin will then get the demo with the tick. Is there a possibility to find a work around?

**Comment by Technoblazed** [comment]
That sounds like complete cancer for admins.

**Comment by Lightningblade67** [comment]
Well, it keeps the server clean and nice of trolls. The plugin is normally just used on a jail and a minigame server but I'd love to have it on the bhop server aswell

**Comment by Lightningblade67** [comment]
Also sorry again but where do i find the compiled 1.5 version or do i have to make a version of it?

**Comment by shavitush** [comment]
I would gladly provide compiled binaries for 1.5b but I just installed another OS.. you'll have to build it yourself. The 1.5b version has support for SourceTV :)

https://youtu.be/pX1fjkX2e6k

**Comment by Lightningblade67** [comment]
Thank you very much!

**Comment by Lightningblade67** [comment]
Ok, I've now build the SPs and followed your video step by step.Sadly It still throws the same error.
Sorry for the trouble but I really want to make it work^^.
Is there any way that I can get additional support?

**Comment by Technoblazed** [comment]
@Lightningblade67 are you using the latest source code?

**Comment by shavitush** [comment]
well, you'd need the newest version of the timer for custom styles to work, and the error has been solved there

post the output of the following command in your server console please:

    sm plugins list

**Comment by Lightningblade67** [comment]
I did download your latest commit from 19 days ago.

Sadly I couldn't get the first 9 lines since putty doesn't want to create log files...
http://pastebin.com/RzhHU3Px
But i hope this helps

**Comment by Technoblazed** [comment]
Follow these requirements and installed the dependencies, you're missing a few: https://github.com/shavitush/bhoptimer#requirements
