### ISSUE TITLE
Prespeed Help

### ISSUE THREAD

**Issue by Shimshek** [shavitush/bhoptimer#323]
I want to jump in base but i dont want to pass 300 speed in base. How can i do that

**Comment by shavitush** [comment]
if you're running the latest version from this repository, check the config files

**Comment by Technoblazed** [comment]
^

**Comment by Shimshek** [comment]
![adsiz](https://cloud.githubusercontent.com/assets/24484210/21066455/55f9812e-be6e-11e6-8910-2271086fa86e.png)

Where to i must change the speed to 300

**Comment by shavitush** [comment]
cfg/sourcemod/shavit-*.cfg
