### ISSUE TITLE
Replay bots improvement

### ISSUE THREAD

**Issue by theSaint92** [shavitush/bhoptimer#325]
Hello, i was about to host 2 servers connected to one database, but i quickly found out that replay bots are the problem here. I looked into code and found a quick solution replaceing in `shavit-replay.sp` code 
`data/replaybot` with `../../../../../replaybot` which leads to same directory for both servers. It works preety fine as long as u don't play the same map on both servers at the same time. Let me explain the problem on an example : wr for map is 1:00. On first server there is a player who makes a 50second run - bot updates on this server, but it doesnt update on the other (it's understable, and thats not rly the problem since it will be updated when we reload map or something like this) the problems shows up when on the other server another player will make for example 55 seconds run. There is a "NEW WORLD RECORD" message, and bot is named "BOT Normal 50 second", but it shows 55 seconds run :(

As i quickly investigated the code i found out that u keep wr in variable, and updates it only when it needs to be updated - however my quick solution which was putting `UpdateWRCache();` at the begging of the `public void Shavit_OnFinish` from `shavit-wr.sp` didnt work out.

I rly dont have time to investigate it further in nearly future, but maybe u can find a quick solution to this and make some improvement adding commands like `sm_shavit_multiple_servers [0/1]` which would enable the multiple servers mode (disabling it could save some sql queries) and  `sm_shavit_replay_bots_path`, or maybe even better way of saveing replaybots, since this one requires access to some parent folders of `csgo`, which many server hosts could not have access to.

PS1. Some command like `!replay` which would allow u to play replay bot of a style which have it disabled would be preety cool ^^ 8 bots running at once is too much :P 

PS2. Could u plz add in `shavit-hud.sp` in the definition of `#define HUD_DEFAULT				(HUD_MASTER|HUD_CENTER|HUD_ZONEHUD|HUD_OBSERVE|HUD_TOPLEFT|HUD_SYNC|HUD_TIMELEFT)` the `HUD_2DVEL` aswell? My admins says that its preety annoying to explain to every new noob how to turn it on, and it would be fine if I wouldn't have to remember to add this every time u update the plugin ^^

Sorry for my not best english, hope that it's understable
BR
theSaint

**Comment by shavitush** [comment]
I'm really sorry but I can't and won't support sharing the same server folder on over one server (forked servers).
