### ISSUE TITLE
Possible Fix of rankings

### ISSUE THREAD

**Issue by theSaint92** [shavitush/bhoptimer#326]
While writing my alternative ranking system i found out an issue, that might help you to fix your ranking :)

The problem is that  shavit-core is useing REPLACE query that is setting points = 0 (default value) every time a player connect to the server. You can check fix of shavit-core here [>>>LINK TO COMMIT<<<](https://github.com/theSaint92/bhoptimer/commit/f888372)

PS1. In my ranking i use Int's intead of float's for points.

PS2. I wouldn't recommend to use my alternate ranking system yet, since queries i used are quite heavy and im getting 4/5 "Lost connection to MySQL server during query" errors daily. I will work on optimalization and improvement soon

**Comment by Technoblazed** [comment]
Swear I got an email about this hours ago, wtf?

**Comment by theSaint92** [comment]
Sorry im quite new in useing github, and after posting in original thread it looked to me like it might be overlooked since i didn't saw any "move thread up"  or something like this. For the next time i won't spam your email - sorry :(

**Comment by Technoblazed** [comment]
Github puts the newest issue at the top of the list, shavit will look at it eventually, but as the alliedmodders forum says:

```
Notice: Development will be frozen for a while.
I accidentally broke some hard drive partition while trying to get back to Windows from Linux. It had my git projects folder with the chat/rankings/checkpoints unpublished git branches on. In addition, I broke my USB flash drive so it's gonna take a while before I can reformat and install Windows.
I'm really demotivated now, development will be pretty much frozen until I get everything working again and restore lost projects, rewrite what I've lost from the bhoptimer development and of course, set up a comfortable development environment.
Extremely sorry - to all of my plugin's users.
```

**Comment by shavitush** [comment]
good point! i actually had no issues with it to begin with, i think it worked with either sqlite/mysql (afaik they handle `REPLACE` in a different way)

**Comment by Technoblazed** [comment]
So, does this actually work?

**Comment by shavitush** [comment]
it's a 'fix' for points setting to 0 upon connection but not more than that

**Comment by Nickelony** [comment]
Since we've already got a almost fully working version of the Rankings, I think this issue can be closed.
