### ISSUE TITLE
did shavit stop?

### ISSUE THREAD

**Issue by nknm** [shavitush/bhoptimer#329]
title ^

**Comment by Technoblazed** [comment]
From his alliedmodders page, he said he's had no motivation to play games or do anything game related for the last two months.

**Comment by AzaZPPL** [comment]
such is life

**Comment by sigge200** [comment]
is he coming back?

**Comment by Technoblazed** [comment]
Maybe at some point who know

**Comment by shavitush** [comment]
I'm back!
