### ISSUE TITLE
shavit_misc_prespeed 1 Not working!

### ISSUE THREAD

**Issue by T1MOXA** [shavitush/bhoptimer#331]
If you fly with noclip through the texture, and a second before, to start it off, the speed is not reset!

**Comment by Technoblazed** [comment]
https://github.com/shavitush/bhoptimer/issues/286

Issue exists. Duplicate.

**Comment by T1MOXA** [comment]
Yes, I saw but the question is old, and there is no solution, so I created a new one!

**Comment by Technoblazed** [comment]
Plugin development has been stopped, so there's honestly no need to.

**Comment by T1MOXA** [comment]
Where info about it?

**Comment by Technoblazed** [comment]
https://forums.alliedmods.net/showthread.php?p=2477362#post2477362

**Comment by Technoblazed** [comment]
I think there was another post somewhere after that, but not sure where it is.

**Comment by T1MOXA** [comment]
:(
Thanks for information.
I hope he'll be back soon :)

**Comment by shavitush** [comment]
Duplicate of #286.
