### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by samoletik** [shavitush/bhoptimer#333]
L 03/08/2017 - 16:36:27: [SM] Exception reported: Invalid Cookie handle 0 (error 4)
L 03/08/2017 - 16:36:27: [SM] Blaming: shavit-core.smx
L 03/08/2017 - 16:36:27: [SM] Call stack trace:
L 03/08/2017 - 16:36:27: [SM]   [0] GetClientCookie
L 03/08/2017 - 16:36:27: [SM]   [1] Line 944, C:\Users\Denis\Desktop\1.8\addons\sourcemod\scripting\shavit-core.sp::OnClientCookiesCached
L 03/08/2017 - 16:36:28: [SM] Exception reported: Invalid Cookie handle 0 (error 4)
L 03/08/2017 - 16:36:28: [SM] Blaming: shavit-core.smx
L 03/08/2017 - 16:36:28: [SM] Call stack trace:
L 03/08/2017 - 16:36:28: [SM]   [0] GetClientCookie
L 03/08/2017 - 16:36:28: [SM]   [1] Line 944, C:\Users\Denis\Desktop\1.8\addons\sourcemod\scripting\shavit-core.sp::OnClientCookiesCached
L 03/08/2017 - 16:36:28: [SM]   [2] Line 969, C:\Users\Denis\Desktop\1.8\addons\sourcemod\scripting\shavit-core.sp::OnClientPutInServer
Client "nuKa4y" connected (91.207.239.81:27005).
L 03/08/2017 - 16:36:32: [SM] Exception reported: Invalid Cookie handle 0 (error 4)
L 03/08/2017 - 16:36:32: [SM] Blaming: shavit-core.smx
L 03/08/2017 - 16:36:32: [SM] Call stack trace:
L 03/08/2017 - 16:36:32: [SM]   [0] GetClientCookie
L 03/08/2017 - 16:36:32: [SM]   [1] Line 944, C:\Users\Denis\Desktop\1.8\addons\sourcemod\scripting\shavit-core.sp::OnClientCookiesCached
Dropped ArhangelY from server (Disconnect by user.)

Game CSS OB, SourceMod 1.8.0.5975, [shavit] Core (1.5b) by shavit

**Comment by shavitush** [comment]
Post your `databases.cfg` file.

**Comment by samoletik1337** [comment]
"shavit"
	{
		"driver"         "mysql"
		"host"           "43.789.28.113"
		"database"       "shavit_132"
		"user"           "shavit_1324"
		"pass"           "15152"
	}

**Comment by Technoblazed** [comment]
I hope those aren't your actual database connection details.

**Comment by samoletik1337** [comment]
Yes of course

**Comment by del6597** [comment]
Hopefully you're using IP whitelisting for connections then.

**Comment by samoletik1337** [comment]
This is my mistake, I'm sorry)

**Comment by shavitush** [comment]
... edited it.

Anyways, if you have the same issue as this issue's submitter, it's probably with `clientprefs` (SourceMod's cookies manager) being configured incorrectly.
