### ISSUE TITLE
My Zone Colors

### ISSUE THREAD

**Issue by sigge200** [shavitush/bhoptimer#334]
Hello! My Zone colors is all white and i can't change it. If Shavit or anyone else see this comment. Please respond quickly.

**Comment by Technoblazed** [comment]
Did you edit your shavit-zones.cfg and restart your server?

**Comment by sigge200** [comment]
Yes, I've edited it and restart. I've also reset and try to download everyting again. I have the newest version 1.5b and it still doesn't work. Is there a sulution?

I can send you screenshot if you want.

PS: sry for late response.

**Comment by sigge200** [comment]
If shavit sees this pls fix.

**Comment by Nickelony** [comment]
Can't replicate.

The only issue with the zone colors is that the order isn't right. If you change the "Freestyle zone" color, it changes the "Teleport zone" color.

**Comment by shavitush** [comment]
And if you change the color of the teleport zones, will it change the freestyle zones' color?

**Comment by Nickelony** [comment]
yup

**Comment by shavitush** [comment]
I rewrote this one big fucking mess one for all.

I also found out that the previous way would draw every zone that can be placed multiple times (such as freestyles/nolimit/teleports) 4 times. 4 DAMN TIMES. Expect better server performance after this commit.
