### ISSUE TITLE
Help With team change!

### ISSUE THREAD

**Issue by sigge200** [shavitush/bhoptimer#335]
I dont anyone to be able to change team on my server. I need some help!! And its the plugin!

**Comment by Nickelony** [comment]
It's not the plugin because everything works fine for me. Can you post your plugins list?

**Comment by sigge200** [comment]
"[CSS/CS:GO] AbNeR DeathRun Manager" (2.6fix) by AbNeR_CSS
 "Admin File Reader" (1.8.0.5974) by AlliedModders LLC
 "Admin Help" (1.8.0.5974) by AlliedModders LLC
 "Admin Menu" (1.8.0.5974) by AlliedModders LLC
 "AdminTag" (2.0) by KeepCalm
 "Anti-Flood" (1.8.0.5974) by AlliedModders LLC
 "Basic Ban Commands" (1.8.0.5974) by AlliedModders LLC
 "Basic Chat" (1.8.0.5974) by AlliedModders LLC
 "Basic Comm Control" (1.8.0.5974) by AlliedModders LLC
 "Basic Commands" (1.8.0.5974) by AlliedModders LLC
 "Basic Info Triggers" (1.8.0.5974) by AlliedModders LLC
 "Basic Votes" (1.8.0.5974) by AlliedModders LLC
 "botslayer.smx" botslayer.smx
 "Chat-Processor" (2.0.6) by Keith Warren (Drixevel)
 "Client Preferences" (1.8.0.5974) by AlliedModders LLC
 "[ANY] PayPal Donations" (1.3b) by Trinia
 "Dynamic" (0.0.25) by Neuro Toxin
 "Fun Commands" (1.8.0.5974) by AlliedModders LLC
 "Fun Votes" (1.8.0.5974) by AlliedModders LLC
 "Game_Player_Equip Fix" (1.1.1) by Mitch
 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
 "Mapchooser Extended Sounds" (1.10.2) by Powerlord
 "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
 "No Weapon Fix" (3.2) by .#Zipcore
 "Player Commands" (1.8.0.5974) by AlliedModders LLC
 "Reserved Slots" (1.8.0.5974) by AlliedModders LLC
 "Reset Knife" (1.1.0) by Trinia
 "Rock The Vote Extended" (1.10.0) by Powerlord and AlliedModders LLC
 "The RTLer" (1.0.5) by alongub
 "[CSGO] Advanced Admin" (1.6.1) by PeEzZ
 "Sound Commands" (1.8.0.5974) by AlliedModders LLC
 "Stop Map Music" (1.0.0) by GoD-Tony [Fixed by The Count]
 "Store - Trade System" (1.0) by Zephyrus
 "Store - The Resurrection" (1.0) by Zephyrus
 "Test Messages" (1.0.0) by Keith Warren (Drixevel)
 "Thirdperson Mode" (1.0) by Zephyrus

That is all the plugins. Is it maybe a command that i need to change. For now i've just removed the shavit .

**Comment by Technoblazed** [comment]
So just to check, you DONT want people to be able to change teams right?

**Comment by Technoblazed** [comment]
https://github.com/shavitush/bhoptimer/blob/master/scripting/shavit-misc.sp#L462 - Is where the team change code is.

**Comment by shavitush** [comment]
@sigge200 please, you don't need to spam the issue tracker. I don't play CS:S/CS:GO anymore so the project is frozen and I currently have no plans to come back, and my incoming military service doesn't make it any better.

Unless I manage to get the military service cancelled, this project will stay frozen, sorry. Your best bet would be to introduce the plugin to someone and get them to start a fork or get them to contact me at the@shav.it and I'll let them maintain this project instead of me.

**Comment by sigge200** [comment]
Ok! Would you tell me Techno blazed what i should change that 2.

Ok, I will stop posting.
