### ISSUE TITLE
Errors in console [CS:GO]

### ISSUE THREAD

**Issue by gastirt** [shavitush/bhoptimer#337]
I have such errors in console every second:
L 04/08/2017 - 22:01:26: [SM] [1] Shavit_InsideZone 
L 04/08/2017 - 22:01:26: [SM] [2] Line 423, D:\sourcemod\addons\sourcemod\scripting\shavit-hud.sp::UpdateHUD 
L 04/08/2017 - 22:01:26: [SM] [3] Line 375, D:\sourcemod\addons\sourcemod\scripting\shavit-hud.sp::TriggerHUDUpdate 
L 04/08/2017 - 22:01:26: [SM] [4] Line 367, D:\sourcemod\addons\sourcemod\scripting\shavit-hud.sp::UpdateHUD_Timer 
L 04/08/2017 - 22:01:26: [SM] Exception reported: Native is not bound 
L 04/08/2017 - 22:01:26: [SM] Blaming: shavit-hud.smx 
L 04/08/2017 - 22:01:26: [SM] Call stack trace: 
L 04/08/2017 - 22:01:26: [SM] [1] Shavit_InsideZone 
L 04/08/2017 - 22:01:26: [SM] [2] Line 423, D:\sourcemod\addons\sourcemod\scripting\shavit-hud.sp::UpdateHUD 
L 04/08/2017 - 22:01:26: [SM] [3] Line 375, D:\sourcemod\addons\sourcemod\scripting\shavit-hud.sp::TriggerHUDUpdate 
L 04/08/2017 - 22:01:26: [SM] [4] Line 367, D:\sourcemod\addons\sourcemod\scripting\shavit-hud.sp::UpdateHUD_Timer 
my databases.cfg:
	"shavit"
	{
		"driver"         "mysql"
		"host"           "web.ourservers.ru"
		"database"       "game51***_51***"
		"user"           "game51***_51***"
		"pass"           "***"
	}
* - I dont want hacking)
Help me please

**Comment by gastirt** [comment]
Installed since the last update on github

**Comment by Nickelony** [comment]
everyone's got those errors and I think they are harmless so just ignore them.

**Comment by gastirt** [comment]
Spam in console every second
Plugin does not want to work :(
