### ISSUE TITLE
Ranking/Point system

### ISSUE THREAD

**Issue by Vikingvrede** [shavitush/bhoptimer#338]
Hello, i can't get ranking/Points to work. i have seen servers who use your plugin and ranks aswell as points seems to be working fine for them. I have looked at forum posts and looked at other "!Issues" on github. 

Does it only work with local mysql? ( stored on server, i use external btw) 
Or is it only working with sqlite.
Plugin still under maintenance?

**Comment by Technoblazed** [comment]
- Ranking / points are broken in the current version, there is a temporary patch on the alliedmods forum to patch them.
- It supports external  mysql connections.
- Plugin development has stopped.

**Comment by Vikingvrede** [comment]
Thanks @Technoblazed , Could you send link to patch?
Sad to hear that development has stopped. =(

**Comment by Technoblazed** [comment]
https://forums.alliedmods.net/showpost.php?p=2480830&postcount=960

It's highly experimental, backup your database and don't say you werent warned  :^)

**Comment by elleven11** [comment]
Suggest to use stamm instead of that...

**Comment by theSaint92** [comment]
What's that? (stamm)

**Comment by Technoblazed** [comment]
http://lmgtfy.com/?q=sourcemod+stamm+plugin

**Comment by elleven11** [comment]
I tried to make an ez plugin that gives you stamm points when you finish the timer.

But it gives me error 100 on the stamm includes...

(I give up)

**Comment by shavitush** [comment]
Stamm isn't a rankings plugin and isn't a suitable alternative. I'll try to work on rankings again soon.

**Comment by shavitush** [comment]
Duplicate of #154.
