### ISSUE TITLE
Customize styles

### ISSUE THREAD

**Issue by gastirt** [shavitush/bhoptimer#339]
Can I configure that players can't write "!styles" if not startzone and endzone?

**Comment by Technoblazed** [comment]
What's the point in that?

**Comment by gastirt** [comment]
in conventional maps players use unwanted styles

**Comment by Technoblazed** [comment]
So just disable the styles?

**Comment by gastirt** [comment]
style it is a good plugin, but
for example: map - mg_pirates_b1 or any multigames_map and players using !styles and put "low gravity" or more

**Comment by gastirt** [comment]
this is very disturbing

**Comment by Technoblazed** [comment]
Okay, so go into your `addons/sourcemod/configs/shavit-styles.cfg`, and remove the low gravity style?

**Comment by gastirt** [comment]
OK,  thanks
