### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Satont** [shavitush/bhoptimer#340]
idk i uploaded all files, but plugin wont work

**Comment by Nickelony** [comment]
any error logs?
have you compiled the plugins?
maybe it's a mySQL problem?

**Comment by Satont** [comment]
no im not compile plugins, how i can do this on my linux server?

**Comment by Nickelony** [comment]
https://www.sourcemod.net/downloads.php?branch=stable

here you can download SM with the compiler for linux
in the "scripting" folder you have a file named "Compiler", just drag and drop the .sp files on the compiler.

**Comment by Satont** [comment]
How i can do that on my server?

**Comment by Nickelony** [comment]
um... you don't have to compile it on the server, just use a windows compiler on your windows pc and upload the files on the server.

**Comment by RayZz-** [comment]
1. cd to the scripting directory  e.g. `cd /csgo-ds/csgo/addons/sourcemod/scripting`
2. run `./compile.sh`
3. when its completed then look in the compiled folder for the plugins and use those

**Comment by RayZz-** [comment]
my best advice is go in to your logs folder for source mod and check the logs for any errors and post them here or in a [pastebin](http://pastebin.com) or [hastebin](http://hastebin.com) and post the link here

**Comment by Satont** [comment]
So i compile plugin, uploaded, trying to run server, in console i saw some plugins (used sm plugins)
but have much errors 
there is error log file: (cant upload pastebin) https://satont.xyz/s/errors_20170501.log

**Comment by Nickelony** [comment]
you need to setup your database in config/databases.cfg

please read this: https://github.com/shavitush/bhoptimer/blob/master/README.md
Here you have the installation tutorial + the required plugins you must have on your server.

**Comment by Satont** [comment]
Im already did this

**Comment by RayZz-** [comment]
can you copy and paste your databases.cfg here please

**Comment by Satont** [comment]
my databases.cfg: https://satont.xyz/s/databases.cfg
Database created: 
!(img)[https://satont.xyz/s/s110.png]
Mysql daemon working fine (have my site with mysql using)

**Comment by RayZz-** [comment]
`L 05/01/2017 - 13:46:31: [SM] Unable to load plugin "dhooks-test.smx": Required extension "dhooks" file("dhooks.ext") not running
L 05/01/2017 - 13:46:32: [SM] Unable to load extension "dbi.mysql.ext": libz.so.1: cannot open shared object file: No such file or directory
L 05/01/2017 - 13:46:32: [SM] Exception reported: Timer startup failed. Reason: Driver "mysql" not found`

these three lines we need to focus on

**Comment by RayZz-** [comment]
run this command through ssh `
ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock `

**Comment by RayZz-** [comment]
which operating system are you running on your server?

**Comment by Satont** [comment]
debian 8

**Comment by RayZz-** [comment]
when you installed your server did you install the required dependencies  
try tunning this and see if it is installed on your server
`sudo apt-get install lib32gcc1`

**Comment by Nickelony** [comment]
delete dhooks-test.smx from your plugins folder

**Comment by Satont** [comment]
Yep i did this:```
 apt-get install lib32gcc1
Reading package lists... Done
Building dependency tree
Reading state information... Done
lib32gcc1 is already the newest version.
The following packages were automatically installed and are no longer required:
  libc-ares2 libv8-3.14.5
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

```
Here is new log file, after **ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock**
file: https://satont.xyz/s/screenlog.0

**Comment by RayZz-** [comment]
run `ldd -d -r addons/sourcemod/extensions/dbi.mysql.ext.so` in your csgo directory and paste the output

**Comment by Satont** [comment]
```
 linux-gate.so.1 (0xf771e000)
        libm.so.6 => /lib/i386-linux-gnu/i686/cmov/libm.so.6 (0xf7525000)
        libz.so.1 => not found
        libpthread.so.0 => /lib/i386-linux-gnu/i686/cmov/libpthread.so.0 (0xf7508000)
        librt.so.1 => /lib/i386-linux-gnu/i686/cmov/librt.so.1 (0xf74ff000)
        libc.so.6 => /lib/i386-linux-gnu/i686/cmov/libc.so.6 (0xf7352000)
        /lib/ld-linux.so.2 (0xf7721000)

```

**Comment by RayZz-** [comment]
sudo apt-get install zlib1g

**Comment by Satont** [comment]
```
 apt-get install zlib1g
Reading package lists... Done
Building dependency tree
Reading state information... Done
zlib1g is already the newest version.
The following packages were automatically installed and are no longer required:
  libc-ares2 libv8-3.14.5
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

```

**Comment by RayZz-** [comment]
`sudo apt-get install zlib1g:i386`

**Comment by Satont** [comment]
U r my god ] ```
sm plugins
 "Admin File Reader" (1.8.0.5992) by AlliedModders LLC
 "[shavit] Sounds" (1.5b) by shavit
 "Nextmap" (1.8.0.5992) by AlliedModders LLC
 "Anti-Flood" (1.8.0.5992) by AlliedModders LLC
 "Admin Help" (1.8.0.5992) by AlliedModders LLC
 "Basic Chat" (1.8.0.5992) by AlliedModders LLC
 "[shavit] World Records" (1.5b) by shavit
 "Fun Votes" (1.8.0.5992) by AlliedModders LLC
 "Sound Commands" (1.8.0.5992) by AlliedModders LLC
 "Admin Menu" (1.8.0.5992) by AlliedModders LLC
To see more, type "sm plugins 11"
] sm plugins 11
 "Client Preferences" (1.8.0.5992) by AlliedModders LLC
 "[shavit] Miscellaneous" (1.5b) by shavit
 "Test Messages" (1.0.0) by Keith Warren (Drixevel)
 "Player Commands" (1.8.0.5992) by AlliedModders LLC
 "[shavit] Rankings" (1.5b) by shavit
 "Dynamic" (0.0.26) by Neuro Toxin
 "The RTLer" (1.0.5) by alongub
 "[shavit] Chat" (1.5b) by shavit
 "Dynamic Test" (1.0.2) by Neuro Toxin
 "Basic Comm Control" (1.8.0.5992) by AlliedModders LLC
 "Reserved Slots" (1.8.0.5992) by AlliedModders LLC
To see more, type "sm plugins 22"
] sm plugins 22
 "Fun Commands" (1.8.0.5992) by AlliedModders LLC
 "Basic Votes" (1.8.0.5992) by AlliedModders LLC
 "[shavit] Map Zones" (1.5b) by shavit
 "[shavit] Core" (1.5b) by shavit
 "[shavit] Replay Bot" (1.5b) by shavit
 "Basic Commands" (1.8.0.5992) by AlliedModders LLC
 "Basic Ban Commands" (1.8.0.5992) by AlliedModders LLC
 "[shavit] HUD" (1.5b) by shavit
 "Basic Info Triggers" (1.8.0.5992) by AlliedModders LLC
 "[shavit] Dynamic Timelimits" (1.5b) by shavit
 "[shavit] Player Stats" (1.5b) by shavit

```

**Comment by RayZz-** [comment]
glad i could help :)

**Comment by RayZz-** [comment]
i'd close this issue now :)

**Comment by Satont** [comment]
Yea, big thx

**Comment by Satont** [comment]
But i think need to add this all do requeriment servers

**Comment by RayZz-** [comment]
you can run multiple servers on the same system but if you plan on running it on a separate server then you have to rerun 
`sudo apt-get install zlib1g:i386`
`sudo apt-get install lib32gcc1`

if you get the same errors as before
