### ISSUE TITLE
Update gamedata for GetPlayerMaxSpeed

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#341]
Servers with DHooks are likely to crash when custom prestrafe speeds are enabled.

Valve doesn't ship symbol names with binaries anymore so I can't do this myself. If anyone is able to help, this will be great.

Plugin development will be resumed soon too!

**Comment by shavitush** [comment]
Last update broke this offset again.

**Comment by Technoblazed** [comment]
I'd like to say its probably just +1 again

**Comment by shavitush** [comment]
I'll test it soon!

**Comment by shavitush** [comment]
Actually, I forgot to enable static-prestrafe in my public server after applying your commit, my bad. It works.
