### ISSUE TITLE
Enable top-left HUD

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#343]
Custom HUDs are now supported by CS:GO without any client edits, make the feature work in both CS:S and CS:GO.

**Comment by Technoblazed** [comment]
There's a major bug in this which affects widescreen resolutions, text cuts off half way across the screen.

**Comment by shavitush** [comment]
Yeah but the world record text is never long, so it shouldn't matter :P.

**Comment by shavitush** [comment]
Fixed within #345.
