### ISSUE TITLE
bug with text in chat

### ISSUE THREAD

**Issue by samoletik1337** [shavitush/bhoptimer#349]
Words are not complete, but ragged. Game CSS OB, SM 1.8, Timer version 1.5b.
I did not change anything in the source, I put everything from the archive. 
(sorry for google translate).
![20170604010720_1](https://cloud.githubusercontent.com/assets/28659564/26756761/87756aee-48c3-11e7-9510-46b87a1d7b10.jpg)

**Comment by Technoblazed** [comment]
This has literally JUST been patched.

**Comment by shavitush** [comment]
Fixed in 7c94f119f5d4eb58a0855e3b8fa6aee9be30e57d, an hour ago haha. Try again after updating from the master branch!

**Comment by samoletik1337** [comment]
Thank you, now everything is good.
