### ISSUE TITLE
Duplicates in translation files

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#351]
idk if they were intentional, but I found 2 of them:

shavit-stats.phrases.txt
```
"Points"
{
	"en"		"Points"
}
```

shavit-hud.phrases.txt
```
"HudSync"
{
	"en"		"Sync"
}
```

**Comment by Technoblazed** [comment]
Whoops

**Comment by Nickelony** [comment]
oh and this: https://puu.sh/wa1Zh.png
you forgot to add more tabs here
