### ISSUE TITLE
Fix Replay BOT´s

### ISSUE THREAD

**Issue by SpicyGamers** [shavitush/bhoptimer#354]
Hello

I put on my Bhop server, the shavit plugin, and this contains the replay bot's very important for the server, I put everything in the folders, and when I enter the server, when it starts the round the Bot's all die at the beginning of the Round and the round ends so does not allow the gameplay on the server, if you could say some way to solve this was thankful :)

**Comment by rogeraabbccdd** [comment]
It's because there's no record for bots to replay, so bots all die in the beginning of round.
Try "mp_ignore_round_win_conditions 1" to prevent round ends.

**Comment by SpicyGamers** [comment]
Thx for help ;)
