### ISSUE TITLE
Misc don´t work

### ISSUE THREAD

**Issue by SpicyGamers** [shavitush/bhoptimer#356]
In shavit-misc, napa configs folder this Cvar -> shavit_misc_godmode "2"
Because I use the "2" to protect the damage of the other players and the opponents can kill them.
And on the maps of mg_course, when the players die, they are always reborn and die in the startzone, something that should not happen, when we die we should go to the viewer (dead) to see the living.

**Comment by Technoblazed** [comment]
That's a respawn cvar issue, not the plugin causing the respawns

**Comment by SpicyGamers** [comment]
And regarding shavit_misc_godmode "2", can you fix it?

**Comment by Technoblazed** [comment]
Works on mine

**Comment by SpicyGamers** [comment]
In my not only works if it has the value 3 ... the all gode mode

**Comment by SpicyGamers** [comment]
sm plugins reload shavit-core.smx
L 06/09/2017 - 19:20:46: [SM] Exception reported: Client 1 is not connected
L 06/09/2017 - 19:20:46: [SM] Blaming: shavit-core.smx
L 06/09/2017 - 19:20:46: [SM] Call stack trace:
L 06/09/2017 - 19:20:46: [SM] [0] IsFakeClient
L 06/09/2017 - 19:20:46: [SM] [1] Line 990, shavit-core.sp::OnClientPutInServer
L 06/09/2017 - 19:20:46: [SM] [2] Line 294, shavit-core.sp::OnPluginStart
[SM] Plugin shavit-core.smx failed to reload: Error detected in plugin startup (see error logs).

**Comment by shavitush** [comment]
You don't late-load a plugin this big..

**Comment by SpicyGamers** [comment]
In shavit-misc, in the folder configs folder this Cvar -> shavit_misc_godmode "2"
Because I use the "2" to protect the damage of the other players, and the opponents can kill them.

**Comment by shavitush** [comment]
Just tested here, everything is fine. Are you sure the value is set to 2?

**Comment by SpicyGamers** [comment]
yes

**Comment by Technoblazed** [comment]
Is your plugin up to date?

**Comment by Nickelony** [comment]
Can't replicate here.

**Comment by SpicyGamers** [comment]
Yes it is updated!

**Comment by SpicyGamers** [comment]
Please fix, shavit-misc.cfg, because I need this to work shavit_misc_godmode, because I put this value in the sum of "2", and even then the enemies take damage. I do not have logs errors.

**Comment by Technoblazed** [comment]
We can't replicate this issue, can you 100% confirm you're not just downloading a release, and actually downloading the sourcecode?

**Comment by strafe** [comment]
@SpicyGamers make sure your server meets all [the requirements specified](https://github.com/shavitush/bhoptimer#requirements).

As Technoblazed said you shouldn't be downloading the latest release, you need to download the code and compile it yourself, if you're not sure where or how to I've attached the latest version here already built: [bhoptimer-master.zip](https://github.com/shavitush/bhoptimer/files/1074565/bhoptimer-master.zip)
