### ISSUE TITLE
New 'velocity' style setting

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#363]
`velocity` - % of horizontal velocity to keep keep per jump. For example, if set to 0.95, you'll only keep 95% of your speed (even if the jump is perfectly timed) so you can't beat maps by just holding space but you need to strafe more.

**Comment by Nickelony** [comment]
WAAAAAAIT. So if I set this to 2.0 , your speed gain will be 2 times bigger?

**Comment by Technoblazed** [comment]
Apparently so.

**Comment by shavitush** [comment]
@Nickelony exactly! Somewhat like the "crazy speed" style you wanted me to add long ago :P.

**Comment by Nickelony** [comment]
but is it gain per strafe or gain per jump?

**Comment by strafe** [comment]
@Nickelony [it's applied every time you jump.](https://github.com/shavitush/bhoptimer/blob/5adab283f0da5d61988a67eafae3568f43a336eb/scripting/shavit-core.sp#L711)

**Comment by shavitush** [comment]
To achieve higher gains per strafe, you'd need to increase your server's tickrate, which isn't an ideal solution unfortunately.

**Comment by Technoblazed** [comment]
Sanic hedgehog mode or riot
