### ISSUE TITLE
WR shows only 1 record...

### ISSUE THREAD

**Issue by Zelost** [shavitush/bhoptimer#365]
After updating of the timer, !wr windows looks like this with 99% chance (I've got all the records once)..
![image](https://user-images.githubusercontent.com/19249608/27267962-f5cc596a-54b4-11e7-95db-5a5324af1630.png)
Even if a map has more than 10 records, it shows only 1st..

**Comment by Zelost** [comment]
No, it's clear...

**Comment by Zelost** [comment]
Can it be caused by hud module modification? (The only sp I modified)
Cause there is no errors. Sometimes records are right, but mostly it's only 1st...

**Comment by shavitush** [comment]
I cannot replicate this issue.. sorry.

**Comment by Zelost** [comment]
It's ok. Not a huge glitch. It's just weird... Mb it can be a last sm's problem... Both servers dealing dat glitch, since I've updated everything ><

**Comment by Zelost** [comment]
1 of 2 servers was fixed by itself. Probably WR needs some ammount of records to start work properly...
