### ISSUE TITLE
Replay slow-motion style's time.

### ISSUE THREAD

**Issue by Zelost** [shavitush/bhoptimer#366]
For some reason - time flows like in a regular style...
![image](https://user-images.githubusercontent.com/19249608/27310721-fc2eb626-5564-11e7-888a-21dcdd0279ef.png)
After this - hud just turning into a loading message (until bot done his replay)
![image](https://user-images.githubusercontent.com/19249608/27310784-64352098-5565-11e7-8517-3fdff67c3dac.png)

**Comment by Technoblazed** [comment]
Slowmotion doesn't support replays as far as I remember.

**Comment by Zelost** [comment]
Well, it is, but time speed isn't correct. Not a big deal. Just telling...

**Comment by shavitush** [comment]
It's intended, not a bug. I should look a bit more into stuff before labeling them as bugs..

    "halftime"	"0" // calculation of times will be halved, replays WILL NOT function properly

From the styles configuration file.
