### ISSUE TITLE
Crashes after today's  CSGO update..

### ISSUE THREAD

**Issue by Zelost** [shavitush/bhoptimer#369]
[SM] Exception reported: Array index is out of bounds
[SM] Blaming: shavit-wr.smx
[SM] Call stack trace:
[SM]   [1] Line 430, shavit-wr.sp::Native_GetWRTime
[SM]   [3] Shavit_GetWRTime
[SM]   [4] Line 584, shavit-replay.sp::UpdateReplayInfo
[SM]   [5] Line 951, shavit-replay.sp::DelayedUpdate

WR module

I can't even start a server...

**Comment by Zelost** [comment]
All I can do is delete replay.smx - then servers are working...

**Comment by shavitush** [comment]
Can you post an accelerator crash log?

**Comment by Zelost** [comment]
https://crash.limetech.org/khmtgopz4fmu
Well, I will. But the only servers are broken - timers..
Something wrong with replay\wr module. Plugin and server works after disabling of replay.smx

**Comment by shavitush** [comment]
According to reddit users, it's also a thing with KZTimer right now, and according to your crash log, doesn't look like it has anything to do with SourceMod at all. I'd wait for either a Valve/SourceMod update.

**Comment by Zelost** [comment]
Well, hope they are will fix it soon... But if they're not, would you increase maximum of array (if it possible)?

**Comment by e-slut** [comment]
Influx ain't working either it just closes whenever I try to join

**Comment by Technoblazed** [comment]
It's to do with demos and spec tv

**Comment by Zelost** [comment]
Technoblazed, so sourcemod update wouldn't help?

**Comment by e-slut** [comment]
I don't think so it might Blacky got his replay bot working

**Comment by Technoblazed** [comment]
There's a Linux data fix, just literally be patient and wait for sourcemod gamedata updates

**Comment by Zelost** [comment]
I'm on Linux. Where can I find it? o.o Or do I mislead something?

**Comment by Zelost** [comment]
*Waiting is the herdest part*
![image](https://user-images.githubusercontent.com/19249608/27382662-93424920-5690-11e7-9580-7e95bb27e320.png)

**Comment by shavitush** [comment]
Just manually update the gamedata: https://github.com/alliedmodders/sourcemod/commit/9d21c59e01ce6a7af2425d0302dadca

**Comment by Zelost** [comment]
Yeah, it's ok now. :)
