### ISSUE TITLE
Allow bhoptimer to work on Kreedz Climbing servers

### ISSUE THREAD

**Issue by NielsjeNL** [shavitush/bhoptimer#370]
Not too long ago a new game called Kreedz Climbing was released on Steam ([link](http://store.steampowered.com/app/626680)). The game is basically a mod of CS:S, made specifically for KZ, Bhop and surf maps.

When trying to launch the shavitz-core.smx plugin, it complains about being meant to be used only in CS:S and CS:GO. Since KreedzClimbing basically is CS:S, I think this plugin would make a great addition to KZ servers to let players track their times and the like. Please let me know what you guys think about this.

**Comment by Technoblazed** [comment]
It's not a KZ plugin though, and is missing a TON of core features of a KZ plugin.

**Comment by NielsjeNL** [comment]
I wouldn't really know about the missing features for a KZ server. I should've specified that the game itself also has KZ features built in. Think about times, stats, checkpoints, autobhop (server-wide though, not enabled per player), stuff like that. The way this plugin could differentiate itself from the game's features is for example the replay system, the stats system, the rankings system and the ability to hide all other players. Stats within the game itself are only saved for the current map and are basically lost after a map change.

Don't forget that there's also Bhop in this game. I can understand if it's too much work to convert the plugin to KZ and surf, I think the work would be worth it for Bhop though.
I'd love to take a look at getting this working myself, but sadly I'm not that much of a programmer.

**Comment by strafe** [comment]
All the cstrike dependencies don't work so it would be an annoying job I think to go and debug all the compatibility issues with it, along with the fact that game is really focused on KZ rather than bhop or surf. Along with the fact the game has a built in timer, which can be disabled but still this seems like a waste of time.

**Comment by NielsjeNL** [comment]
Oh, I didn't know the plugin is reliant on dependencies from the games itself. That explains a lot, and I understand why it would take quite some time to get stuff working.

Thanks for replying!
