### ISSUE TITLE
Problem with shavit_misc_prespeedlimit & zones

### ISSUE THREAD

**Issue by Nevvy** [shavitush/bhoptimer#374]
Hi
I wan't 2 report 2 bugs
1st. shavit_misc_prespeedlimit is not working properly (CSGO)
cvar values doesn't match 'real' speed limit in zone
For example shavit_misc_prespeedlimit "400" = limit to 305 in game
2nd.
All zones are white when you use "Store by Zephyrus"
(https://github.com/e54385991/Store)
Earlier zones was working properly (Valve messed something with update a time ago)
Without plugin zone colors works

**Comment by shavitush** [comment]
Just merged #372. Is your issue fixed?

**Comment by Nevvy** [comment]
Nope + i have CCSPlayer::SwitchTeam( 0 ) - invalid team index. spam in console
Plugins:
  01 "Dynamic" (0.0.26) by Neuro Toxin
  02 "Basic Votes" (1.8.0.6014) by AlliedModders LLC
  03 "Anti-Flood" (1.8.0.6014) by AlliedModders LLC
  04 "Client Preferences" (1.8.0.6014) by AlliedModders LLC
  05 "Basic Comm Control" (1.8.0.6014) by AlliedModders LLC
  06 "Fun Votes" (1.8.0.6014) by AlliedModders LLC
  07 "Admin Help" (1.8.0.6014) by AlliedModders LLC
  08 "Basic Commands" (1.8.0.6014) by AlliedModders LLC
  09 <Failed> "Nextmap" (1.8.0.6014) by AlliedModders LLC
  10 "Reserved Slots" (1.8.0.6014) by AlliedModders LLC
  11 "Player Commands" (1.8.0.6014) by AlliedModders LLC
  12 "Basic Chat" (1.8.0.6014) by AlliedModders LLC
  13 "Rock The Vote" (1.8.0.6014) by AlliedModders LLC
  14 "MapChooser" (1.8.0.6014) by AlliedModders LLC
  15 "Sound Commands" (1.8.0.6014) by AlliedModders LLC
  16 "Admin Menu" (1.8.0.6014) by AlliedModders LLC
  17 "Fun Commands" (1.8.0.6014) by AlliedModders LLC
  18 "Basic Info Triggers" (1.8.0.6014) by AlliedModders LLC
  19 "Admin File Reader" (1.8.0.6014) by AlliedModders LLC
  20 "Map Nominations" (1.8.0.6014) by AlliedModders LLC
  21 "SourceBans++: SourceSleuth" (1.6.1) by ecca, SourceBans++ Dev Team
  22 "SourceBans++: Bans Checker" (1.6.1) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  23 "SourceBans++: SourceComms" (1.6.1) by Alex, SourceBans++ Dev Team
  24 "SourceBans++: Admin Config Loader" (1.6.1) by AlliedModders LLC, SourceBans++ Dev Team
  25 "SourceBans++: Main Plugin" (1.6.1) by SourceBans Development Team, SourceBans++ Dev Team
  26 "[shavit] Miscellaneous" (1.5b) by shavit
  27 "[shavit] Player Stats" (1.5b) by shavit
  28 "[shavit] HUD" (1.5b) by shavit
  29 "[shavit] Sounds" (1.5b) by shavit
  30 "[shavit] Chat" (1.5b) by shavit
  31 "[shavit] Map Zones" (1.5b) by shavit
  32 "[shavit] World Records" (1.5b) by shavit
  33 "[shavit] Slay BOTS" (1.00) by CamerDisco
  34 "[shavit] Replay Bot" (1.5b) by shavit
  35 "[shavit] Rankings" (1.5b) by shavit
  36 "[shavit] Dynamic Timelimits" (1.5b) by shavit
  37 "[shavit] Core" (1.5b) by shavit

**Comment by Nickelony** [comment]
same thing here with the prespeed, It's set to 250, but it can't go over 162.

**Comment by SlidyBat** [comment]
I think this is due to using 3D speed rather than 2D when calculating if player over prespeed limit

**Comment by strafe** [comment]
@SlidyBat isn't the vector length of 250, 0, 0 and 250, 0 the same anyway?

**Comment by strafe** [comment]
@Nickelony when running on the ground or when you try to jump out the zone?

**Comment by Nickelony** [comment]
Only when trying to jump

**Comment by shavitush** [comment]
Should be good now!
