### ISSUE TITLE
Wall snapping not working as intended

### ISSUE THREAD

**Issue by strafe** [shavitush/bhoptimer#375]
It does snap to certain walls but not always as it should. If I stand in a corner it should snap right into the corner point to make placing that point easy and perfect.

This is what it currently does:
![image](https://user-images.githubusercontent.com/15663890/27656422-c9b2b372-5c40-11e7-8359-36ef0c6e9865.png)

This is how it should be snapping:
![image](https://user-images.githubusercontent.com/15663890/27656428-d38d89ee-5c40-11e7-9ab0-1c1ee00c6e51.png)

**Comment by shavitush** [comment]
What map is that?

**Comment by strafe** [comment]
bhop_24hrs

**Comment by SlidyBat** [comment]
I think this is better way of doing it instead of infinite ray trace and angles:
`public void zone_GetWallSnapPosition(int I_Client, float F_Pos[3])
{
	for (int i = 0; i < 4; i++) 
	
		float F_EndPos[3];
		F_EndPos = F_Pos;

		F_EndPos[i / 2] += ((i % 2) ? -23.0 : 23.0)

		TR_TraceRayFilter(F_Pos, F_EndPos, MASK_SOLID, RayType_EndPoint, HitSelf, I_Client)

		if (TR_DidHit())
		{
			TR_GetEndPosition(F_EndPos);
			F_Pos[i / 2] = F_EndPos[i / 2];
		}
	}
}`

**Comment by shavitush** [comment]
@SlidyBat thanks for the idea!

@strafe is this what you're looking for? https://streamable.com/or2hi

**Comment by strafe** [comment]
Looks perfect.

**Comment by SlidyBat** [comment]
Bit confused about this (maybe I'm just dumb):
`if(AreVectorsEqual(pos, gF_OldPosition[client]) && EmptyVector(gF_WallSnap[client]))
 {
 	final = gF_WallSnap[client];
 	return true;
 }`
Why would wall snap position have to be empty?

**Comment by shavitush** [comment]
@SlidyBat if the current player's position is equal to the old one AND the wall snapping position is empty, skip the ray tracing process. The wall snapping position will be empty if it wasn't ray traced and set before.

**Comment by strafe** [comment]
@shavitush did you test it on 24hrs?

10mb limit is horrible...
![untitled-1](https://user-images.githubusercontent.com/15663890/28222393-3526b268-68bf-11e7-9d45-1ab4da12708a.gif)

**Comment by shavitush** [comment]
Just tested in different maps and seems like it is not working as intended in every map.. for bhop_24hrs try increasing grid snap to 32x as wall snapping uses grid snapping.

I honestly have no idea what's wrong and I'm not a 3D vector, math or trace-ray expert. I'll re-open this issue with 'help wanted' and unless anyone is able to contribute a solution, I'll drop this feature as cursor position zoning exists.

**Comment by strafe** [comment]
Wall snapping should pretty much override grid snapping, so I think if it's on and there's a wall in-range/available then snap to it otherwise fallback to the grid and if it's off just always use the grid.

**Comment by shavitush** [comment]
I mean, wall snapping uses your grid snap as the range for wall snapping.

**Comment by strafe** [comment]
Oh right, maybe you can do something [more like blacky](https://github.com/Nolan-O/bTimes/blob/master/addons/sourcemod/scripting/bTimes-zones.sp#L1196) then where he just uses a fixed distance, I think that's more intuitive.

**Comment by shavitush** [comment]
It's much different as blacky uses `RayType_Infinite` while I use `RayType_EndPoint`. I'll try re-implementing the whole thing I guess..

**Comment by shavitush** [comment]
I'm just extremely dumb, to be honest. https://streamable.com/pne0w

**Comment by strafe** [comment]
@shavitush uh... it's still not really working ☹️ 
Here's what's still happening, works in corners but the beam is stretching way beyond the grid and going to the middle of the wall: https://streamable.com/4wk7h

Some other video I recorded showing what should hopefully be happening in that scenario: https://streamable.com/ari0p

**Comment by shavitush** [comment]
Oh.. didn't realize it was supposed to snap to walls too! I'll try to implement snapping to walls too, and not just to corners.

**Comment by shavitush** [comment]
Tested in my local server and behavior seems identical to the video you sent! Can you confirm?

**Comment by strafe** [comment]
Yep it's working just like in the other video now, great. One more question though, how hard would it be to add some kind of "edge detection" when wall snapping is on, basically so when you're in the position below which is a large percentage of maps it will stick to that edge and the wall like it does with a corner.
![image](https://user-images.githubusercontent.com/15663890/28231365-09a74cb4-68e3-11e7-9baa-53af076d19e0.png)

**Comment by shavitush** [comment]
Will try to do that.

**Comment by strafe** [comment]
@shavitush no problem, this is working as intended now anyway.
