### ISSUE TITLE
Bot respawn

### ISSUE THREAD

**Issue by mrkevin12** [shavitush/bhoptimer#379]
Hello guys! Evry time its a new round the replay-bots are respawning like 50-200 times and the server lagging alot do you know a fix for that?

**Comment by shavitush** [comment]
Disable your server's auto-respawn settings and get rid of any plugin that may enable auto-respawning.

**Comment by mrkevin12** [comment]
Thanks! But i have 1 more problem, now i have 7 bots 1 thats is alive is it possible to only have 1 and not the other 6?

**Comment by Technoblazed** [comment]
Add `"noreplay" "1"` into the styles you dont want a bot for

**Comment by mrkevin12** [comment]
Thx guys! Is it possible to get a "box" around start and end zone?

/Kevin

**Comment by shavitush** [comment]
`shavit_zones_flat 0` in `cfg/sourcemod/plugins.shavit-zones.cfg`

**Comment by mrkevin12** [comment]
Okay thanks!!!! But i still have a problem with the bots whare is the "style" file so i can change that i dont want the bots? :)

**Comment by Skyline23** [comment]
As @Technoblazed said "Add "noreplay" "1" into the styles you dont want a bot for"

**Comment by shavitush** [comment]
addons/sourcemod/configs/shavit-styles.cfg

**Comment by mrkevin12** [comment]
Thx guys! But now when i have made a zone i get the 3d "box" but nothings happens when i jump out of it.
Do you know straight away whats wrong?

/Kevin

**Comment by mrkevin12** [comment]
Hmm i got this errors:
L 07/09/2017 - 10:51:40: [SM]   [1] Line 1892, C:\Users\willi\Desktop\Shavit\addons\sourcemod\scripting\shavit-zones.sp::StartTouchPost
L 07/09/2017 - 10:51:41: [SM] Exception reported: Array index is out of bounds
L 07/09/2017 - 10:51:41: [SM] Blaming: shavit-zones.smx
L 07/09/2017 - 10:51:41: [SM] Call stack trace:
L 07/09/2017 - 10:51:41: [SM]   [1] Line 1910, C:\Users\willi\Desktop\Shavit\addons\sourcemod\scripting\shavit-zones.sp::EndTouchPost
L 07/09/2017 - 10:51:47: [SM] Exception reported: Array index is out of bounds
L 07/09/2017 - 10:51:47: [SM] Blaming: shavit-zones.smx
L 07/09/2017 - 10:51:47: [SM] Call stack trace:
L 07/09/2017 - 10:51:47: [SM]   [1] Line 1892, C:\Users\willi\Desktop\Shavit\addons\sourcemod\scripting\shavit-zones.sp::StartTouchPost
L 07/09/2017 - 10:51:47: [SM] Exception reported: Array index is out of bounds
L 07/09/2017 - 10:51:47: [SM] Blaming: shavit-zones.smx
L 07/09/2017 - 10:51:47: [SM] Call stack trace:
L 07/09/2017 - 10:51:47: [SM]   [1] Line 1910, C:\Users\willi\Desktop\Shavit\addons\sourcemod\scripting\shavit-zones.sp::EndTouchPost

But i dont even host it on my computer but it still got my "computer addres" is it some wrong with the .smx?

**Comment by shavitush** [comment]
I'm honestly not sure how you even managed to mess it up so badly.

I'll explain some things:
1. The "address" (it's called a path) that you see, is the path that the plugin was compiled from. Not the server.
2. Your database might be returning negative values for zone types therefore it errors out. Try deleting all the zones in the map and recreate them.

**Comment by mrkevin12** [comment]
![database](https://user-images.githubusercontent.com/29764137/27995483-773de354-64cf-11e7-99db-3af5074a95fb.PNG)
Hmm, Everything seems to work in phpmyadmin.
Have tryed to reinstall it 2 times will try 1 more time

**Comment by shavitush** [comment]
No.... something is clearly broken for those zones.
![image](https://user-images.githubusercontent.com/3672466/27999196-d151a1ac-6522-11e7-85d5-efe9f01ebae0.png)

**Comment by mrkevin12** [comment]
Hi! I tryed to intall a older version, and everything working fine so im happy. But i have a small problem left, the bots are still alive after the last man dies, is it posible to kill the bot automatically when the last "human" dies?

**Comment by shavitush** [comment]
Sorry, but no. The plugin is designed for kz/bhop/surf (mainly bhop) servers and not for gamemodes with rounds.

**Comment by strafe** [comment]
@mrkevin12 you can try what was posted [here](https://forums.alliedmods.net/showthread.php?p=2003936) should be able to trigger a round end.
