### ISSUE TITLE
Improve checkpoints

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#381]
I need to to remove the limitation of checkpoints, and add an option to cycle between them.

Edit: Will make the limitation 64. Higher numbers make the compilation take too long.

**Comment by PaxPlay** [comment]
Would have made an adt array tbh, easier to delete checkpoints out of.
Also would be cool if you could add an option to save the cheackpoints to a database, since its really useful for whitelist servers.

**Comment by shavitush** [comment]
I'll think about it.
