### ISSUE TITLE
Cvars for bot appearance

### ISSUE THREAD

**Issue by strafe** [shavitush/bhoptimer#390]
Similar to shavit_misc_clantag, I think server owners should be able to set it easily rather than modifying that line. Would also be nice to set the bot name format when it's playing a record and have !replay as a constant when it's idle.

**Comment by shavitush** [comment]
> Would also be nice to set the bot name format when it's playing a record and have !replay as a constant when it's idle.

This is already a thing in #388!

**Comment by shavitush** [comment]
> Would also be nice to set the bot name format when it's playing a record and have !replay as a constant when it's idle.

This is already a thing in #388!

I'll make sure to create a `sourcemod/configs/shavit-replay.cfg` file with some settings, including:
* Bot clan tag.
* Bot name style.
* Central bot (idle) name style.

**Comment by shavitush** [comment]
Implemented. See ` sourcemod/configs/shavit-replay.cfg` for information.
