### ISSUE TITLE
Disable pagination on CP menu

### ISSUE THREAD

**Issue by strafe** [shavitush/bhoptimer#392]
There's space for all options if the page buttons are removed, will be much cleaner to not have use velocity on another page.
![image](https://user-images.githubusercontent.com/15663890/28219407-c47293ee-68b3-11e7-8aef-bf90dee24f86.png)

Also due to the nature of checkpoints I think this menu should be displayed forever until something else interrupts it rather than 60 seconds.

**Comment by shavitush** [comment]
I don't have a CS:GO server instance installed so I can't test it. As CS:S has 1 extra item per menu, due to back being 8, next being 9 and exit being 0.

Please re-open the issue if it's still a problem.
