### ISSUE TITLE
Hud don't work with UTF8

### ISSUE THREAD

**Issue by T1MOXA** [shavitush/bhoptimer#393]
![image](https://user-images.githubusercontent.com/19938629/28223100-b51260ae-68d2-11e7-8af0-313885dd1a88.png)

**Comment by T1MOXA** [comment]
With Cyrillic problems too.

**Comment by strafe** [comment]
Works fine for me I think this is down to your SQL database.
![image](https://user-images.githubusercontent.com/15663890/28223354-ff07e6f8-68c2-11e7-990d-84af7c465373.png)
![image](https://user-images.githubusercontent.com/15663890/28223360-02a77a26-68c3-11e7-8176-c91e59739fb2.png)

**Comment by shavitush** [comment]
Set your database's collation to UTF8MB4.
