### ISSUE TITLE
Strange time in new time feature

### ISSUE THREAD

**Issue by T1MOXA** [shavitush/bhoptimer#395]
![image](https://user-images.githubusercontent.com/19938629/28229434-6d2bf9a8-68eb-11e7-9f8e-94748a03c6b5.png)
What are these numbers ?
Should it be like this ?

**Comment by shavitush** [comment]
To be fair I haven't tested this feature in a server with more than one player so it was bound to happen.. can I have a full screenshot of the leaderboard?

**Comment by shavitush** [comment]
Also, try again after applying this patch!

**Comment by T1MOXA** [comment]
Yes, now everything is OK, but now I can't bunnyhopping at the start.
