### ISSUE TITLE
Next button isn't capped in checkpoints

### ISSUE THREAD

**Issue by strafe** [shavitush/bhoptimer#399]
You can select checkpoints that don't exist.

![image](https://user-images.githubusercontent.com/15663890/28249428-76bac360-6a4d-11e7-89d5-2d671b1c53af.png)

Edit: To add sm_tele can teleport to checkpoints that don't exist.

**Comment by strafe** [comment]
@shavitush do you think it would be better to have sm_save and sm_tele work the same way the menu does when no argument is given? I think that would me more intuitive for players and actually make it usable for routing without needing to rebind constantly.

**Comment by shavitush** [comment]
Good point.

**Comment by shavitush** [comment]
@strafe what about now?

**Comment by strafe** [comment]
Doing `sm_save` prints the following in chat:
```
[Timer] Checkpoint (1) saved.
[Timer] Checkpoint (1) saved.
```

**Comment by shavitush** [comment]
Should be good now!
