### ISSUE TITLE
Store player's duck state in checkpoints

### ISSUE THREAD

**Issue by strafe** [shavitush/bhoptimer#401]
If it isn't players can do multiple 64 unit jumps in a row: https://streamable.com/vb758

[Something like this.](https://github.com/TotallyMehis/Influx-Timer/commit/467fa1fc05d46525e362f43f7c6b9307e6394007)

**Comment by shavitush** [comment]
Note to myself: Save the player's stamina too, otherwise scroll segments might be horribly unfair.

**Comment by shavitush** [comment]
Another note: Store the player's `targetname` (`m_iName`) too.
