### ISSUE TITLE
Possibility to add replaybots next to central replaybot

### ISSUE THREAD

**Issue by cytrus224** [shavitush/bhoptimer#402]
for example bot normal and bot bonus normal

**Comment by Nickelony** [comment]
Would be nice if this would be a setting in shavit-styles.cfg (e.g "force_replay" "1")

**Comment by strafe** [comment]
Can't it just have 1 replay key like hsw?

**Comment by shavitush** [comment]
@strafe it can - and that's what I'm going to do.

**Comment by Tanami** [comment]
is this done?

**Comment by strafe** [comment]
>is this done?

No

**Comment by rtldg** [comment]
added looping bots, dynamicly spawning bots, and spectatable props for replays in https://github.com/shavitush/bhoptimer/commit/9e43f67fc3a66554b3d8ec253332a8b511d1d9d1
