### ISSUE TITLE
Unknown column 'rowid' in 'field list'

### ISSUE THREAD

**Issue by strafe** [shavitush/bhoptimer#406]
This might be something I messed up no clue but sometimes when going to a map zoned or unzoned this error is given and if the map is zoned none of them load.
`[shavit-zones.smx] Timer (zone refresh) SQL query failed. Reason: Unknown column 'rowid' in 'field list'`

**Comment by shavitush** [comment]
My fault, that's because I tested on SQLite and `rowid` doesn't exist in MySQL.

**Comment by shavitush** [comment]
Can you see if the issue is fixed now? I can't reproduce it on my end anymore.

**Comment by strafe** [comment]
@shavitush seems like the only thing that sets `gB_DBReady` to true is not being called at all, so the zones are not loaded.

**Comment by shavitush** [comment]
Test again please! Haven't had the chance to test but this solution seems better.

**Comment by strafe** [comment]
Yep it works, that's what I did in the meantime to fix it too, just feels kind of a hacky way to fix it.

**Comment by strafe** [comment]
@shavitush should there also be a similar else statement in SQL_AlterTable2_Callback? What if the table needs to be altered and completes successfully, won't gB_DBReady still be false?

**Comment by shavitush** [comment]
It won't matter, because `gB_DBReady` is being put in an `if()` statement only in OnMapStart()!
