### ISSUE TITLE
Autorespawn -shavit-misc

### ISSUE THREAD

**Issue by Hugopereira785** [shavitush/bhoptimer#407]
Hi, I'm trying to create a mg / course server, and the courses need autorespawn with spawn-kill detector. (Or franug). But for this I need to remove the "shavit_misc_autorespawn" cvar through .sp. As a retreat without causing damage to the plugin? Just remove this:
 GCV_AutoRespawn = CreateConVar ("shavit_misc_autorespawn", "1.5", "Seconds to wait before respawning player? \ N0 - Disabled", 0, true, 0.0, true, 10.0);
Thanks for listening

**Comment by strafe** [comment]
Just set `shavit_misc_autorespawn 0.0` in `cfg/sourcemod/plugin.shavit-misc`

**Comment by Hugopereira785** [comment]
No, that does not let me be reborn, with any other plugin

**Comment by Skyline23** [comment]
You mean you want to reborn and dont take any damage from spawnkiller? if so, try to remove the trigger_hurt or give players godmode

**Comment by Hugopereira785** [comment]
No, I want to respawn but the shavit autorespawn is not leaving, I use another plugin to detect the spawn kill and these two plugins are giving interference.

**Comment by Skyline23** [comment]
I dont understand what you are talking about, but I think you can disable `shavit_misc_autorespawn` and use `mp_respawn_on_death_(c)t` instead.

**Comment by Technoblazed** [comment]
This isn't necessarily a bug, nor is it something that would be `fixed`, it's a timer designed for bhop servers, not course servers.

**Comment by Hugopereira785** [comment]
So I wanted to know if I could take this:: GCV_AutoRespawn = CreateConVar ("shavit_misc_autorespawn", "1.5", "Seconds to wait before respawning player? \ N0 - Disabled", 0, true, 0.0, true, 10.0);

Without causing problems

**Comment by Technoblazed** [comment]
What?

**Comment by strafe** [comment]
Why do you want to take it out... setting it to 0.0 will have the same effect as completely removing it.

**Comment by Hugopereira785** [comment]
@strafe  with 0.0  can not even be born.

But thaks!

**Comment by Technoblazed** [comment]
Yeah, 0.0 would disable auto respawning.

**Comment by Hugopereira785** [comment]
@Technoblazed 
Yes, but I can not be born anymore, even with another plugin

**Comment by Technoblazed** [comment]
Having checked the code, the bhop plugin isn't causing that.

**Comment by strafe** [comment]
@Hugopereira785 test this out on your server and tell us if it can respawn you, thanks.
```SourcePawn
#include <cstrike>

public void OnPluginStart()
{
	RegConsoleCmd("sm_respawnme", SM_RespawnMe);
}

public Action SM_RespawnMe(int client, int args)
{
	if(!IsPlayerAlive(client))
		CS_RespawnPlayer(client);

	return Plugin_Handled;
}
```

**Comment by Hugopereira785** [comment]
I have already resolved, thanks for the help
