### ISSUE TITLE
shavit-misc (Team change_unlimited)

### ISSUE THREAD

**Issue by Hugopereira785** [shavitush/bhoptimer#409]
The shavit-misc plugin does not allow the (team change unlimit)

Does anyone have the solution for this?

Thanks for the attention.

**Comment by Skyline23** [comment]
`AddCommandListener(Command_Jointeam, "jointeam");`

`public Action Command_Jointeam(int client, const char[] command, int args)
{
	if(!IsValidClient(client))
	{
		return Plugin_Continue;
	}

	char[] arg1 = new char[8];
	GetCmdArg(1, arg1, 8);

	int iTeam = StringToInt(arg1);

	if(GetClientTeam(client) == iTeam)
	{
		return Plugin_Continue;
	}

	switch(iTeam)
	{
		case CS_TEAM_T:
		{

			CS_SwitchTeam(client, CS_TEAM_T);
			CS_RespawnPlayer(client);
		}

		case CS_TEAM_CT:
		{
			CS_SwitchTeam(client, CS_TEAM_CT);
			CS_RespawnPlayer(client);
		}

		case CS_TEAM_SPECTATOR:
		{
			CS_SwitchTeam(client, CS_TEAM_SPECTATOR);
		}

		default:
		{
			return Plugin_Continue;
		}
	}

	return Plugin_Continue;
}`

**Comment by strafe** [comment]
You need to be more specific... I can switch team unlimited times with the timer's default configuration so I doubt this is even a timer related issue.

**Comment by Technoblazed** [comment]
Can you provide an output of `sm plugins list` please.

**Comment by Hugopereira785** [comment]
I am using this plugin: TeamChange Unlimited
And the plugin is not letting him do his job. The plugin blocks players from entering a certain team.
Sorry for my bad english

Plugin link: https://forums.alliedmods.net/showthread.php?p=1877187

**Comment by shavitush** [comment]
Remove the plugin then, my plugin handles it properly for servers that don't have rounds and/or teams. If you have an issue with TeamChange Unlimited, please report it to the plugin's author instead.

**Comment by juppsy** [comment]
@Hugopereira785 I had the same problem. Add "mp_ignore_round_win_conditions 1" on your gamemode config. 
@shavitush you can include it if you want, like in cksurf. 
For dead connected people and that think with "Match starting in..." I didn't find a command/fix/plugin.
