### ISSUE TITLE
shavit-anticheat

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#411]
Decided to do this. I have most of it ready but a rewrite is definitely needed, don't expect it to be out any soon. The timer itself is a much higher priority for me.

Should include:
- [ ] Bunnyhop script detection:
  - [ ] Perfect jumps rate.
  - [ ] Average ticks on ground.
  - [ ] Scroll patterns. (before/after hitting ground, raytracing to ground and distance comparisons)
  - [ ] Jump key hold time.
  - [ ] Interval per scroll.
---
- [ ] Strafe-hack detection:
  - [ ] Strafe gains (to prevent things like this: https://youtu.be/3m7qUyB8w3Q?t=9).
  - [ ] `sidemove` (or `forwardmove` for SW) manipulation.
  - [ ] Strafe synchronization.
  - [ ] Key switching intervals, should detect strafe nulling configs/"K120  #syndrome".
---
- [ ] Detections:
  - [ ] Log all scroll/strafe stats of suspected cheaters.
  - [ ] Warn to online admins (if there are any) on detections and log.
  - [ ] Allow admins to see scroll/strafe stats of online players.

Note: I have the bunnyhop script detection part done already. AFAIK there weren't any scripts that got past it and most detections I've got on my server had irregular stats. Looking for testers with "undetected scripts" that are willing to test on CS:S (insecure server), hit me up.

**Comment by Skyline23** [comment]
Will it be opensource?

**Comment by Technoblazed** [comment]
I'd assume so, with the plugin being open source :^)

**Comment by Skyline23** [comment]
But I'm afraid the coder will update their cheat to bypass AC

**Comment by strafe** [comment]
Will this be stand-alone or rely heavily on other modules?

**Comment by e-slut** [comment]
Will it all be free or is there going to be a paid version?

**Comment by shavitush** [comment]
Accidentally included the Release milestone, whoops.

---

@Skyline23 it'll be open-source. It doesn't matter that much because those are supposed to be sensitive, and trying to so hard to not be caught while (for example) bhop scripting will result in horrible perfect jump percentage to the point it's not viable to cheat.
@strafe the only thing I have in mind is [bhopstats](https://shavitush.github.io/bhopstats/) as a dependency, it'll be able to run standalone but use timer natives.
@e-slut this plugin is 100% open-source, I don't sell plugins.

**Comment by shavitush** [comment]
gave up on shavit-anticheat, this will be a different plugin, forked from oryx, see https://github.com/shavitush/Oryx-AC
