### ISSUE TITLE
shavit-chat issues

### ISSUE THREAD

**Issue by juppsy** [shavitush/bhoptimer#412]
1: Every time when I'm stopping the server I'm receiving this error: http://imgur.com/a/YL2JK

2: !ranks or !chatranks is buggy I think. When I type one of thease, only in  console appears -3. It is normal?

Question: What can I do to show like this: https://gyazo.com/8e643c1531fd77cae4547869d7a9a777 ?
On me appears GAMEMODE :: TIME, example: N :: 23.

**Comment by Technoblazed** [comment]
1. Imgur gallery redirects so that was useless.
2. That's an old style syntax, there's a new config file in addons/sourcemod/configs, can't remember the name of it but you can change it to a similar syntax

**Comment by juppsy** [comment]
Sorry, my fault at that link. Edited.

**Comment by Technoblazed** [comment]
Oh also, ranking being broken is a known issue.

**Comment by shavitush** [comment]
Disable shavit-chat and shavit-rankings. They're not usable at the moment.
