### ISSUE TITLE
Hopping issue

### ISSUE THREAD

**Issue by juppsy** [shavitush/bhoptimer#413]
Sometimes when I start a map it begins to hop weird like I'm pressing W. 
That's on normal style.

Also I have another issue. When I setup the server on local bot appears. Now, when I put that plugin on my server bot isn't on game.

**Comment by Technoblazed** [comment]
Do you have the same styles config on both? And are you running -nobots or a bot quota zero enforcer on the other server

**Comment by juppsy** [comment]
The first problem wos from airaccelerate. I think it doesn't load everytime from the cfg file. After I put 
sv_airaccelerate 1000 on my server.cfg file, the problem was solved.

I really don't know what happends with the bot. I have the same config files as my local server but it doesn't appears.

Also, a friend noticed that: http://steamcommunity.com/sharedfiles/filedetails/?id=1085973591
End zone HUD when he was in run.

**Comment by Technoblazed** [comment]
Advice would be to use a gamemode_casual_server.cfg, but that's just preference.

**Comment by Technoblazed** [comment]
Also that screenshot doesn't exist, can you confirm you're also using the latest version of the plugin?

**Comment by juppsy** [comment]
Sorry about that image, I didn't know that he will delete it. I just wanted to report that issue/bug to you.

I just saw the -nobots flag on server console from the starting plugin from the hosted server. I'm sure that's the "problem" with the bot. Sorry about that.

**Comment by shavitush** [comment]
If you can show me how to reproduce the end zone HUD issue step-by-step, re-open this issue.
