### ISSUE TITLE
Show world record time in !replay/style menus

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#414]
Figured this would be a nice quality-of-life addition to prevent players from accidentally playing replays they don't really want to watch.

**Comment by strafe** [comment]
Would be nice to just have this in all similar menus like !style and !wr.
```
Normal - WR: 10.2
Sideways - WR: 10.5
W-Only - WR: 12.1
```

**Comment by strafe** [comment]
@shavitush these should probably have `FormatSeconds` run on them, they look a little weird with times over a minute.

**Comment by shavitush** [comment]
I should have definitely tested it on maps longer than 1 minute lol..
