### ISSUE TITLE
Map finished times near PB (#1/56)

### ISSUE THREAD

**Issue by juppsy** [shavitush/bhoptimer#415]
Hello, is any method to put the number of map finished times near PB rank, for example #1/**56**?

**Comment by shavitush** [comment]
Is this for the CS:GO HUD, or for the top-left HUD?

**Comment by juppsy** [comment]
For the CS:GO HUD. It's any method to add the WR from top-left HUD to CS:GO HUD?

**Comment by strafe** [comment]
I think changing ;ine 529 in shavit-hud from
```SourcePawn
Format(sHintText, 512, "%s%T: %s (#%d)", sHintText, "HudBestText", client, sPB, (Shavit_GetRankForTime(gBS_Style[target], fPB) - 1));
```
to
```SourcePawn
Format(sHintText, 512, "%s%T: %s (#%d/%d)", sHintText, "HudBestText", client, sPB, (Shavit_GetRankForTime(gBS_Style[target], fPB) - 1), Shavit_GetRecordAmount(gBS_Style[target]));
```
will work for you.

**Comment by juppsy** [comment]
Yeah, it works. Thank you so much.

Is there any method to put WR from top-left HUD to CS:GO HUD and keep both of them?

**Comment by strafe** [comment]
Yes but where would you put it? With the current HUD you can fit 6 items on it which are currently all being used, so you'd either need to reduce the font-size of the HUD or replace one of the existing items like Jumps, Strafes, etc.

**Comment by juppsy** [comment]
I was wondering about that. I want to keep them all. I think is enought space. Best put under time and WR where best was placed. I think that would look nice. 

Is it posibile to add a custom hud? Different resolutions may affect it?

**Comment by strafe** [comment]
I won't list all the changes you need to make here cause line numbers just get messy but you can see them in [the commit on my fork](https://github.com/strafe/bhoptimer/commit/682ebc788bb78e68fdd08403df6bd6f18d70ee92).

[Here's the full file if you just want to overwrite yours.](https://raw.githubusercontent.com/strafe/bhoptimer/master/scripting/shavit-hud.sp)

**Comment by juppsy** [comment]
I'll try it tomorow. Thank you so much.

**Comment by juppsy** [comment]
It works but it looks pretty messy (http://imgur.com/a/lsrby). Where should I put that lines to be like default but with WR under Best?

Also, where should I need to modify the text from "Best" to "PB"? I searched some files but I didn't found it (or I'm a bit blind).

**Comment by Nickelony** [comment]
"Best" can be found in the HUD translation files

**Comment by strafe** [comment]
@juppsy like this?
![image](https://user-images.githubusercontent.com/15663890/28550672-92fbff10-70da-11e7-909b-12583dcde9e4.png)

If so, again see the [commit](https://github.com/strafe/bhoptimer/commit/aeb945330e35f405729b034c40bb805bd6829da2) & [full file](https://github.com/strafe/bhoptimer/blob/aeb945330e35f405729b034c40bb805bd6829da2/scripting/shavit-hud.sp).

As Nickelony said the "Best" text can be changed in `sourcemod/translations/shavit-hud.phrases.txt` under `HudBestText`.

**Comment by juppsy** [comment]
Thank you so much, you really helped me.

**Comment by Technoblazed** [comment]
I actually personally like this hud :^)
