### ISSUE TITLE
Central replay bot bugs

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#416]
Not sure what caused it, but it happened in my CS:GO server. 

* ~~It played without being requested upon a new record.~~
* ~~Beating a WR should stop the replay playback of the central bot, if the broken WR was of the same style. I think I tried to do it before and it worked, but it didn't for some reason in my CS:GO server.~~
* ~~The HUD doesn't show up for the central replay bot.~~
* When idle, the central bot floats around instead of being stuck in one spot.

**Comment by shavitush** [comment]
> When idle, the central bot floats around instead of being stuck in one spot.

I suspect that this happens in CS:GO due to a specific movetype. I don't really play CS:GO so I can't really check. Does anyone have a clue?

**Comment by strafe** [comment]
Personally for me the central bot when idle stays in one spot and just looks around in a maybe 10° cone, after playing records it stays frozen on the last frame of the replay until a new one is requested.

Some other stuff that could maybe work:
`bot_zombie 1`
`MOVETYPE_NONE` or `MOVETYPE_NOCLIP`
`SetEntityFlags(client, GetEntityFlags(client) | FL_ATCONTROLS);`

**Comment by shavitush** [comment]
> Otherwise it will stay frozen on the last frame of a replay until a new one is requested.

This is intended. The first one is not though.

**Comment by strafe** [comment]
If a map has a `Normal` replay available and is loaded why does the bot immediately go to the last frame of that recording and sit there?
