### ISSUE TITLE
Pay for ranks and bonus zones

### ISSUE THREAD

**Issue by juppsy** [shavitush/bhoptimer#418]
I know, it's an issue category but I saw you active here and I want to talk in private with you. We can do this?

**Comment by Technoblazed** [comment]
- Bonus Zones already exists, the bonus timer will be implemented soon: https://github.com/shavitush/bhoptimer/issues/133
- Rankings will also be fixed soon: https://github.com/shavitush/bhoptimer/issues/338 https://github.com/shavitush/bhoptimer/issues/326
- Shavit has already said he doesn't charge for plugins ¯\_(ツ)_/¯

**Comment by shavitush** [comment]
I don't charge for any plugin that's related to bhop. I want the community to grow as a whole and I do my best to make it happen.

So sorry, but I won't accept that. I'll be working on rankings when I finish taking care of all the major issues right now - I'll be done with bonuses/multi-track support by then.
