### ISSUE TITLE
Sound bug

### ISSUE THREAD

**Issue by juppsy** [shavitush/bhoptimer#420]
Some people doesn't hear the WR sound, doesn't matter what sound it is. That thing on different maps, not only on a single map.

**Comment by cytrus224** [comment]
Have you set fastdl properly?

**Comment by juppsy** [comment]
I think yes because only few players doesn't hear it.

**Comment by shavitush** [comment]
Not an issue here. Tell your players to fix their `cl_downloadfilter` setting.

**Comment by juppsy** [comment]
They have it set to `all`.

**Comment by shavitush** [comment]
Have you tried setting `sv_pure` to 0?

**Comment by juppsy** [comment]
Yes, I have it. I reinstalled the server yesterday and problem fixed for people who had that problem. I don't know for others, no reports now.

**Comment by strafe** [comment]
This is almost certainly not a timer issue, again...
