### ISSUE TITLE
Add New Pauze Zone.

### ISSUE THREAD

**Issue by samoletik1337** [shavitush/bhoptimer#422]
It would be nice to add a new zone, a pause zone. Example: https://www.youtube.com/watch?v=8G_9KZSdb1U . It would be very useful in places where timing is needed.

**Comment by shavitush** [comment]
I said it multiple times, this timer is designed for *bhop* servers. Proper bunnyhop maps don't have rotating objects or timing based things. Sorry, but this zone won't be added.
