### ISSUE TITLE
Use accurate mins/maxs for zone trigger bounds

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#424]
Figured out that it's correct in CS:S but not so much in CS:GO.

The idea is to grab the mins/maxs value from a player and use it for zones.

**Comment by strafe** [comment]
Seems fine to me and the players bounds are 32 units wide/deep in both games.

**Comment by shavitush** [comment]
From my testing it seemed very accurate in CS:S but I could get a bit out of the zone in CS:GO and it'd still keep me there. Might be an effect of ping as I was testing on 100~, but I still need to get proper values for the height as the player model changed between the games. A notable example for that is bhop_apricity, where the hole that takes you to the last stage is too small for the CS:GO model to fit in.

**Comment by strafe** [comment]
Yeah I believe that's because the only thing that differs between games is the height of the model when crouching, CS:S is 36 as opposed to CS:GO's 54 but they're both 72 when standing. Not sure if it's really possible to deal with that in a good way.

Here's a video of me on the edge of the zone with 30 ping: https://streamable.com/wdg92

**Comment by shavitush** [comment]
> but they're both 72 when standing

Are you sure about that? I recently came across this kz_bhop_yonkoma run on CS:GO https://youtu.be/gkwukWk8Pnk?t=110 and upon testing in CS:S it doesn't look like this skip is so easily done (both on autobhop settings) - I assumed it's because of the player model's height.

**Comment by strafe** [comment]
Well there seems to be conflicting information about the measurements in CS:S but assuming the Valve wiki is not wrong then I think so.

https://developer.valvesoftware.com/wiki/Dimensions
https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Mapper%27s_Reference

**Comment by strafe** [comment]
Nice way, maybe only way, to get the player's bounds.
```SourcePawn
float fMin[3], fMax[3];
GetEntDataVector(client, Offset_VecMin, fMin);
GetEntDataVector(client, Offset_VecMax, fMax);
```

**Comment by shavitush** [comment]
```sp
#include <sourcemod>

#pragma semicolon 1
#pragma newdecls required

public void OnPluginStart()
{
	RegConsoleCmd("sm_dimensions", Command_Dimensions, "Print out your player's bounding box.");
}

public Action Command_Dimensions(int client, int args)
{
	if(client == 0)
	{
		return Plugin_Handled;
	}

	float mins[3];
	GetEntPropVector(client, Prop_Send, "m_vecMins", mins);
	ReplyToCommand(client, "Mins: {%.03f, %.03f, %.03f}", mins[0], mins[1], mins[2]);

	float maxs[3];
	GetEntPropVector(client, Prop_Send, "m_vecMaxs", maxs);
	ReplyToCommand(client, "Maxs: {%.03f, %.03f, %.03f}", maxs[0], maxs[1], maxs[2]);

	return Plugin_Handled;
}
```

CS:S
> Mins: {-16.000, -16.000, 0.000}
> Maxs: {16.000, 16.000, 62.000}

Gonna update my CS:GO server now and test.
