### ISSUE TITLE
Bot big issue after !knife and !ws

### ISSUE THREAD

**Issue by juppsy** [shavitush/bhoptimer#430]
After I added the !knife and !ws plugin, I just saw 2 bots bugged on the server.

Screens: http://imgur.com/a/mlbOE

**Comment by Technoblazed** [comment]
Both of those plugins go against Valve's ToS.

**Comment by juppsy** [comment]
And that's why it happens?

**Comment by del6597** [comment]
Who knows why it happens? It doesn't matter in the long run because anyone running a server with those plugins will eventually get shutdown by Valve anyway. Why waste the effort of checking/making it compatible if it results in bans?

**Comment by Technoblazed** [comment]
Can't replicate the bug without those plugins. Don't support servers with the plugins. ez.
