### ISSUE TITLE
Chat plugin rewrite

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#436]
This version won't depend on `shavit-rankings`, it'll support custom settings for custom flags so it can be used as an admin setting or even a donor perk and privileged users will be able to change their settings with commands.

Support for `shavit-rankings` will be added once the rankings plugin is finished.

**Comment by shavitush** [comment]
Information about it, from `FEATURES.md`. It's basically the famous "ccname"/"ccmsg".

#### shavit-chat
The chat plugin manipulates chat messages sent by players.  
It includes custom chat names, tags, colors and all can be defined by the players/admins.  
Admins need the chat flag, or the "shavit_chat" override (good for a donator perk).  
There's a user-friendly command named !cchelp so the users can easily understand what's going on.

**Comment by strafe** [comment]
@shavitush the plugin is missing the `myinfo` section.

**Comment by shavitush** [comment]
@strafe whoops! I'll fix it in the upcoming pull request.
