### ISSUE TITLE
Replays not working

### ISSUE THREAD

**Issue by e-slut** [shavitush/bhoptimer#438]
https://streamable.com/uf9fl
Using latest version from bugfixes branch.

**Comment by juppsy** [comment]
Yes, it doesn't work properly: http://imgur.com/a/dLm5Q

**Comment by shavitush** [comment]
Anything in error logs?

**Comment by shavitush** [comment]
👌 

![image](https://user-images.githubusercontent.com/3672466/28751791-56bf3e48-7519-11e7-9b49-22fa5cebf282.png)
