### ISSUE TITLE
Zones Invisible to players / admins

### ISSUE THREAD

**Issue by Ounces** [shavitush/bhoptimer#443]
I am able to see and create zones but other admins with the same flags and just regular players cannot see the zones. I have confirmed that the files have been downloaded to the admins/players system and are available on the redirect server.

Although it's not a big deal & the zones work as intended other players would like to see the zones.

**Comment by shavitush** [comment]
Edit `shavit-zones.sp`, change this part:

```sp
	for(int i = 1; i <= MaxClients; i++)
	{
		if(IsClientInGame(i) && !IsFakeClient(i))
		{
			float eyes[3];
			GetClientEyePosition(i, eyes);

			if(GetVectorDistance(eyes, center) <= 1024.0 ||
				(TR_TraceRayFilter(eyes, center, CONTENTS_SOLID, RayType_EndPoint, TraceFilter_World) && !TR_DidHit()))
			{
				clients[count++] = i;
			}
		}
	}
```

To
```
	for(int i = 1; i <= MaxClients; i++)
	{
		if(IsClientInGame(i) && !IsFakeClient(i))
		{
			clients[count++] = i;
		}
	}
```

Does the issue fix? Also, are you on CS:S or CS:GO?

**Comment by Ounces** [comment]
CS:S & no they are still unable to see the zones.

**Comment by shavitush** [comment]
Try setting `shavit_zones_usecustomsprite` to 0 from within `cfg/sourcemod/plugin.shavit-zones.cfg` and restart your server. Let me know if it's fixed.

**Comment by Ounces** [comment]
That fixes it.

**Comment by shavitush** [comment]
Then something definitely isn't fine with your materials! Here's what I can think about breaking it:
1. The zone sprite materials are not on the server.
2. There's a wrong version (or there isn't any) of them on your fast downloads server.
3. The `sv_pure` value of the server is wrong.

**Comment by Ounces** [comment]
Alright, will look into it. 

Thanks for clearing that up.
