### ISSUE TITLE
Prevent falling blocks

### ISSUE THREAD

**Issue by juppsy** [shavitush/bhoptimer#444]
Is there a cvar to prevent blocks to fall on maps like bhop_csgo_neon, bhop_aztec or it will be added? That thing is too frustrating when are 20+ players online because most of them will fall.

**Comment by strafe** [comment]
Use MultiPlayer Bunny Hops:
[CS:S](https://forums.alliedmods.net/showthread.php?p=808724)
[CS:GO](https://gitlab.com/Zipcore/MPBH)
