### ISSUE TITLE
Mute others' gun sounds/footsteps when hide is enabled

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#445]

**Comment by strafe** [comment]
@shavitush `sv_footsteps` does exist and work in CS:GO it's just locked like `sv_enablebunnyhopping` used to be.

**Comment by shavitush** [comment]
@strafe Are you sure? If it's locked, I hope it at least can get replicated to clients.

Try removing this `if(gEV_Type == Engine_CSS)` statement and let me know if it my implementation actually works for CS:GO.

**Comment by strafe** [comment]
Seems to be working as intended in CS:GO yep.

Also noticed this in my error logs maybe it's a side effect of the upgrade that is intended so I'll just leave it here.
```
L 07/31/2017 - 10:50:20: [shavit/shavit-wr.smx] Timer (WR UpdateLeaderboards) SQL query failed. Reason: Unknown column 'track' in 'field list'
L 07/31/2017 - 10:50:20: [shavit/shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Unknown column 'track' in 'field list'
L 07/31/2017 - 10:50:20: [shavit/shavit-timelimit.smx] Timer (TIMELIMIT time selection) SQL query failed. Reason: Unknown column 'r.track' in 'where clause'
L 07/31/2017 - 10:50:20: [shavit/shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Unknown column 'track' in 'field list'
L 07/31/2017 - 10:50:20: [shavit/shavit-timelimit.smx] Timer (TIMELIMIT time selection) SQL query failed. Reason: Unknown column 'r.track' in 'where clause'
L 07/31/2017 - 10:51:19: Error log file session closed.
```

**Comment by shavitush** [comment]
Does that message keep appearing after a server restart though?

**Comment by strafe** [comment]
No just once.

**Comment by shavitush** [comment]
It's fine then, nothing destructive. I'll apply the CS:GO commit.
