### ISSUE TITLE
Hud settings doesn't saves

### ISSUE THREAD

**Issue by juppsy** [shavitush/bhoptimer#447]
Few people told me that their hud settings doesn't saves. That's weird because I don't have that problem.

**Comment by Technoblazed** [comment]
Can't replicate, check your clientprefs is configured correctly.

**Comment by juppsy** [comment]
I haven't changed the configuration of clientprefs. It's sqlite as default.

**Comment by strafe** [comment]
Can you get some _proof_ from these people that it doesn't work. You are reporting a bunch of issues no one else has encountered, how can we trust that these people are competent enough to spend time trying to fix an issue that might not even exist.

**Comment by shavitush** [comment]
Do you shut down your server often? The settings only get saved to the `clientprefs` database when you change maps.

**Comment by strafe** [comment]
I've been on your server @juppsy and had no problem with sounds or HUD clientprefs.

**Comment by Technoblazed** [comment]
That's a hard xd

**Comment by Nickelony** [comment]
I think those people are trolling you. I can't replicate any of your issues.

**Comment by shavitush** [comment]
Well @strafe pretty much confirmed this is either a troll or you definitely shut down your server after changing a setting.. I'm closing this.
