### ISSUE TITLE
Add native to disable chat boolean for the next Shavit_PrintToChat

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#448]
Figured something that prints to chat very often like SSJ might be annoying so..

"chat boolean" as in the tick sound you hear whenever there's a chat message.

**Comment by shavitush** [comment]
Usage example of stopping the chat ticking sound:
```sp
Shavit_StopChatSound();
Shavit_PrintToChat(client, "some useful text here");
```

**Comment by strafe** [comment]
Very nice
