### ISSUE TITLE
Zones grid snap isn't accurate?

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#452]
Something like this: https://puu.sh/wYKxg.jpg happens on a lot of maps where only 1 of the sides isn't visible because it's stuck in the wall or something. I don't know if this can be fixed or if it's a game issue.

Edit: Zone creation video: https://puu.sh/wYKMr.mp4

It's 100% not the maps fault because the whole map was made on grid 16 as you can see here in hammer: https://puu.sh/wYL0L.png

**Comment by strafe** [comment]
Are you sure the actual start zone width is a multiple of 16? It's possible the map maker made it a random width, 30 units would be a good example of this.

I believe you can use zone snapping here though and it will snap correctly into that corner.

**Comment by Nickelony** [comment]
@strafe Check out my edit, I'm the map creator so I know that something is wrong.

**Comment by shavitush** [comment]
I'm pretty sure it's because one of the walls collide with a wall. 
![image](https://user-images.githubusercontent.com/3672466/28831659-dadade92-76e2-11e7-8bbd-72c10ae68331.png)

Here's an example from kz_bhop_yonkoma's .vmf, it also happens there due to old design.

What I recommend you to do is reduce the grid snap and do cursor zoning so it'll look more aesthetic. Can't really do much about it :/.

**Comment by strafe** [comment]
Does seem like something timer specific though: https://streamable.com/j539e

Maybe you should add a beam offset like Influx to pull the beams in a bit from the actual bounds?

**Comment by shavitush** [comment]
@strafe is this the implementation you asked for?
@Nickelony can you try `shavit_zones_offset 2.0` (or even 1.0) and let me know if it works? It only changes the *visual* box!

**Comment by Nickelony** [comment]
@shavitush offset 0.5 fixes the problem, but I think the best default value would be 1.0.
The only problem here is that the offset doesn't apply to the zone while drawing, It's not a big issue, but it might still annoy some admins. Video: https://puu.sh/wZrfT.mp4

**Comment by shavitush** [comment]
From my testing in some narrow (bhop) maps, 1.0 seemed A LOT. I guess it really is map dependent though..

I guess this is finished then!
