### ISSUE TITLE
Looking for new default zone beam sprites!

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#462]
~~I'm looking for zone sprites that look good for both CS:S and CS:GO, which can work just fine when you adjust their color. The sprite should be similar to the current CS:S sprite as in being simplistic - no text and works well with the default 2.0 width setting.~~

~~I'm also looking for a similar sprite that will be used for the line that goes out of the player to the grid snap while setting up zones. It will appear as white in-game.~~

~~I honestly have no clue how to illustrate/design myself so, if there are compatibility issues with either games we can use different sprites per game. It should be compatible with the GNU GPL v3 license so we don't do copyright infringements.~~

~~Let me know if you're willing to help with this and I'll assign you!~~

**Comment by strafe** [comment]
Why not just use the default beams for each game and support custom sprites if people want them?

**Comment by shavitush** [comment]
That's already (sort of) the case, see `shavit_zones_usecustomsprite`. It defaults to 1 and uses the currently provided sprites, the CS:GO one was made by a friend (I think so at least, that's what they told me; but honestly it looks very dated) and the CS:S one is the one OCB had before they shut down.
If it's set to 0 then it'll use the game's default sprites/halos.

However, I feel like having a 'standard' for beam sprites will be better, to avoid confusions and possible issues with different sprites. The default beam sprite and the beam sprite I provided for CS:GO both look horrible and make zoning look not aesthetic, unfortunately. The CS:S sprite is decent but it doesn't react too well to different colors.

**Comment by strafe** [comment]
Yeah I was suggesting that convar should be 0 by default in my opinion, when OCB was still up I worked with karasu on that server not sure why the beam's colour was shifted but I guess it was for a reason either way making the beam monochrome then adjusting the light factor accordingly will make it work perfectly with custom colours as shown here in CS:GO
![image](https://user-images.githubusercontent.com/15663890/28998040-fc258b62-7a19-11e7-81ee-e3db7ddcc9a8.png)

**Comment by e-slut** [comment]
I just like the regular laser beam to be honest

**Comment by shavitush** [comment]
@strafe was this screenshot done with CS:GO's default beam? What width setting is that?

**Comment by shavitush** [comment]
Well, upon testing apparently the CS:GO default sprite is definitely this one and it looks great even in CS:S. I'll push an update to use this one as the default even for CS:S after some adjustments :).

**Comment by strafe** [comment]
@shavitush no it is not the default CS:GO beam, in my post I said "With the CS:S beam" meaning the one you package with the timer for CS:S from OCB.

**Comment by shavitush** [comment]
Yeah, but I ended up using the CS:GO beam instead that is provided by Valve - seemed to work. It looks aesthetic and it's visible:
![image](https://user-images.githubusercontent.com/3672466/29003208-1ac1b7b6-7abb-11e7-9994-21802b4db05f.png)
![image](https://user-images.githubusercontent.com/3672466/29003213-2c489d92-7abb-11e7-814a-6094d8b54af0.png)
