### ISSUE TITLE
Mysql error times are not saving,

### ISSUE THREAD

**Issue by deven10100** [shavitush/bhoptimer#467]
`L 08/07/2017 - 02:20:44: [shavit-stats.smx] Timer (get WR amount) SQL query failed. Reason: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'prg_bhopshavit.playertimes.auth' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

`L 08/07/2017 - 02:20:44: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'prg_bhopshavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

> `Database server

Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.19-0ubuntu0.16.04.1 - (Ubuntu)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)
Web server

nginx/1.10.3
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $
PHP extension: mysqli Documentation
PHP version: 7.1.6-1~ubuntu16.04.1+deb.sury.org+1`

**Comment by shavitush** [comment]
> this is incompatible with sql_mode=only_full_group_by

This is an issue with your unusual MySQL server configuration which I can't support - sorry.

**Comment by deven10100** [comment]
Anyone who has this error in the future and hosts there own mysql server and are using mysql 5.7 and above, Restricted tables are enabled by default. add this into your my.cnf file to unrestrict your tables, basically allowing code from 5.7 and below sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
