### ISSUE TITLE
Shavit_OnTierAssigned forward

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#475]
Should be called whenever a map's tier gets loaded. This is so we you could edit the menus of stuff like !nominate to show the map's tier.

```sp
forward void Shavit_OnTierAssigned(const char[] map, int tier);
```

**Comment by shavitush** [comment]
Usage example: (in `nominations_extended.sp`)

```sp
public void Shavit_OnTierAssigned(const char[] map, int tier)
{
	char[] sMap = new char[160];
	GetCurrentMap(sMap, 160);
	GetMapDisplayName(sMap, sMap, 160);

	if(StrEqual(sMap, map))
	{
		Shavit_PrintToChatAll("Tier has been changed to \x03%d\x01.", tier);
	}

	g_mapTrie_Tier.SetValue(map, tier);
}
```

![image](https://user-images.githubusercontent.com/3672466/29297003-90cf0024-8166-11e7-96e3-f9a388c44bd0.png)

![image](https://user-images.githubusercontent.com/3672466/29297079-25e516c6-8167-11e7-8ef6-efd1806841c1.png)

**Comment by Nairdaa** [comment]
asd
