### ISSUE TITLE
Spamming error.

### ISSUE THREAD

**Issue by Zelost** [shavitush/bhoptimer#478]
[SM] Exception reported: Temp entity property "m_iWeaponID" not found
[SM] Blaming: timer/shavit-misc.smx
[SM] Call stack trace:
[SM]   [0] TE_ReadNum
[SM]   [1] Line 2084, shavit-misc.sp::Shotgun_Shot

Any ideas?

**Comment by Technoblazed** [comment]
I'll open a pr for the fix

**Comment by Technoblazed** [comment]
https://github.com/shavitush/bhoptimer/pull/479

Also note pre strafing is broken, pretty sure the GetMaxPlayerSpeed offset was changed, will be investigating when home.

**Comment by shavitush** [comment]
@Technoblazed the easy way to know if GetPlayerMaxSpeed broke, is to check if your prestrafe is the same with a knife/USP.

**Comment by Technoblazed** [comment]
You can't prestrafe at all anymore

**Comment by Technoblazed** [comment]
And the usp prespeed is 240 units

**Comment by shavitush** [comment]
Prestrafe is actually dependent on a combination of `sv_accelerate 5`, `sv_friction 4` and CS:GO Movement Unlocker. Might be the latter having its Linux signature outdated, as blackhawk reported that it works fine on Windows machines.

**Comment by Technoblazed** [comment]
This issue is fixed now :^)
