### ISSUE TITLE
Problem with prefix.

### ISSUE THREAD

**Issue by live4net** [shavitush/bhoptimer#48]
I install new version (from git) of timer, add prefix in plugin.shavit-core.cfg. Plugin crash server, when i change style. Plugin create only two tables in my database:
shavit_mapzones
shavit_playertimes

database.conf
"shavit"
{
            "driver"                        "mysql"
            "host"                          "my_hostname"
            "database"                      "live4net_4fun"
            "user"                          "*******"
            "pass"                          "*****"
            "timeout"                     "10"
            "port"                  "3306"
}

logs:
L 06/12/2016 - 18:15:55: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Table 'live4net_4fun.shavit_users' doesn't exist
L 06/12/2016 - 18:15:56: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Table 'live4net_4fun.shavit_users' doesn't exist
L 06/12/2016 - 18:15:58: [shavit-core.smx] Timer error! Failed to insert "Adi"'s data to the table. Reason: Table 'live4net_4fun.shavit_users' doesn't exist

in plugin.shavit-core.cfg:
shavit_core_sqlprefix "shavit_"

**Comment by live4net** [comment]
Sry, I add description now.

**Comment by shavitush** [comment]
`sm plugins list` output please

**Comment by live4net** [comment]
29 "[UMC] Random Cycle" (3.4.7-dev) by Steell
  30 "fun_disarm.smx"
  31 "steam bot" (1.0) by Adi - live4net
  32 "SourceBans++" (1.5.3) by SourceBans Development Team, Sarabveer(VEER™)
  33 "[UMC] Echo Nextmap" (3.4.7-dev) by Steell
  34 "Basic Chat" (1.6.2-dev+4566) by AlliedModders LLC
  35 "TeamChange Unlimited" (1.2.2) by Sheepdude
  36 "SourceComms" (SBR-1.5.3) by Alex, Sarabveer(VEER™)
  37 "Advertisements" (0.5.7) by Tsunami
  38 "Checkpoints" (1.0.0 (GNU/AGPLv3)) by 1Swat2KillThemAll
  39 "[UMC] Player Limits" (3.4.7-dev) by Steell
  40 "Basic Votes" (1.7.3-dev+5278) by AlliedModders LLC
  41 "CS:GO DEMO Crash Fix" (1.1.0) by Thiry
  42 "Admin Menu" (1.7.3-dev+5278) by AlliedModders LLC
  43 "VIP Sell" (1.0) by live4net
  44 "Web Shortcuts CS:GO version" (2.2) by Franc1sco franug and James "sslice" Gray
  45 "[shavit] HUD" (1.5b) by shavit
  46 "[shavit] Map Zones" (1.5b) by shavit
  47 "Admin File Reader" (1.7.3-dev+5278) by AlliedModders LLC
  48 "[UMC] Vote Command" (3.4.7-dev) by Steell
  49 "Reserved Slots" (1.7.3-dev+5278) by AlliedModders LLC
  50 "SourceBans Checker" (SBR-1.5.3) by psychonic, Ca$h Munny, Sarabveer(VEER™)
  51 "Czas" (1.0) by Adi - live4net
  52 "Filtr" (1.0) by Adi
  53 "FragRadio SourceMod Plugin" (1.4.5) by BomBom - Dunceantix
  54 "[CSGO] Team Limit Bypass" (1.1) by Zephyrus
  55 "SQL Admin Manager" (1.6.2-dev+4566) by AlliedModders LLC
  56 "[UMC] Ultimate Mapchooser Core" (3.4.7-dev) by Steell
  57 "Fun Commands" (1.7.3-dev+5278) by AlliedModders LLC
  58 "Surf Tools" (1.6) by Fredd
  59 "Sound Commands" (1.7.3-dev+5278) by AlliedModders LLC
  60 "[UMC] Map Weight" (3.4.7-dev) by Steell
  61 "Client Preferences" (1.7.3-dev+5278) by AlliedModders LLC
  62 "[CS:GO] Player Trails" (1.0.1) by Maxximou5
  63 "SM SKINCHOOSER" (2.7) by Andi67
  64 "Player Commands" (1.7.3-dev+5278) by AlliedModders LLC
  65 "MOTDgd Adverts" (2.3.5) by Blackglade and Ixel
  66 "Self Noclip" (1.0.0) by killjoy
  67 "[UMC] Post-Played Exclusion" (3.4.7-dev) by Sazpaimon and Steell
  68 "[shavit] World Records" (1.5b) by shavit
  69 "MG Menu" (1.0) by Adi - live4net
  70 "SourceSleuth" (SBR-1.5.3) by ecca, Sarabveer(VEER™)
  71 "[UMC] Prefix Exclusion" (3.4.7-dev) by Steell
  72 "Basic Commands" (1.7.3-dev+5278) by AlliedModders LLC
  73 "[shavit] Sounds" (1.5b) by shavit
  74 "PermaMute" (0.1) by Ryan "FLOOR_MASTER" Mannion
  75 "secret plugin" (1.0) by Adi
  76 "SM Parachute" (2.5) by SWAT_88
  77 "AdminSentinel" (1.2.100) by <eVa>StrontiumDog
  78 "Game_Player_Equip Fix" (1.1.01) by Mitch
  79 "i3D-Teleport" (1.11) by Tony G.
  80 "Disable HUD money" (1.0) by Pheonix (˙·٠●Феникс●٠·˙)
  81 "[UMC] Nominations" (3.4.7-dev) by Steell
  82 "Basic Comm Control" (1.7.3-dev+5278) by AlliedModders LLC
  83 "No Dependencies Noblock" (1.0) by ml
  84 "[Any] Chat Logging Redux + RTF Support" (1.0.8) by McFlurry, Keith Warren (Jack of Designs)
  85 "Stop Map Music" (1.0.0) by GoD-Tony [Fixed by The Count]
  86 "[Source 2009] Custom Chat Colors" (3.0.1) by Dr. McKay
  87 "[UMC] Player Count Monitor" (3.4.7-dev) by Steell
  88 "[UMC] Rock The Vote" (3.4.7-dev) by Steell
  89 "[shavit] Core" (1.5b) by shavit
  90 "[shavit] Miscellaneous" (1.5b) by shavit

**Comment by shavitush** [comment]
i'll go through this later

**Comment by shavitush** [comment]
I fixed it again because of an issue; check commit ef33d51b6a4cb1a848846020f743b80d4aff5c59 for more info. let me know if you have issues please!
