### ISSUE TITLE
Rank showing out of 0 total players; no points

### ISSUE THREAD

**Issue by michaelrw10** [shavitush/bhoptimer#483]
You may or may not know this already, but I want to report anything I find just in case you're not aware. Hope I can be of some help with testing.

Using the latest rankings branch code, when you do !rank or !stats to check global server rank, it will say 2/0, or 1/0, or rank number 'x' out of zero.
In the database, for the 'playertimes' and 'users' tables, both have a points column.. both show 0.

**Comment by shavitush** [comment]
Ranks aren't even finished yet, this is irrelevant.

**Comment by michaelrw10** [comment]
ok, just trying to help mate. someone suggested i post it here
