### ISSUE TITLE
Error in logs - Blaming: shavit-wr.smx

### ISSUE THREAD

**Issue by MynDoS** [shavitush/bhoptimer#484]
Hello,
I have this error logs on my server
`L 08/27/2017 - 16:27:14: [SM] Exception reported: Invalid index 0 (count: 0)
L 08/27/2017 - 16:27:14: [SM] Blaming: shavit-wr.smx
L 08/27/2017 - 16:27:14: [SM] Call stack trace:
L 08/27/2017 - 16:27:14: [SM]   [0] ArrayList.Get
L 08/27/2017 - 16:27:14: [SM]   [1] Line 1642, shavit-wr.sp::GetRankForTime
L 08/27/2017 - 16:27:14: [SM]   [2] Line 449, shavit-wr.sp::Native_GetRankForTime
L 08/27/2017 - 16:27:14: [SM]   [4] Shavit_GetRankForTime
L 08/27/2017 - 16:27:14: [SM]   [5] Line 476, shavit-hud.sp::UpdateHUD
L 08/27/2017 - 16:27:14: [SM]   [6] Line 388, shavit-hud.sp::TriggerHUDUpdate
L 08/27/2017 - 16:27:14: [SM]   [7] Line 380, shavit-hud.sp::UpdateHUD_Timer`

SM  1.8.0.6024

**Comment by shavitush** [comment]
Please attach your whole error log file.

**Comment by MynDoS** [comment]
[errors_20170827.txt](https://github.com/shavitush/bhoptimer/files/1254892/errors_20170827.txt)

**Comment by shavitush** [comment]
@MynDoS thanks! Will be fixed soon.

**Comment by MynDoS** [comment]
When can you expect update?

**Comment by MynDoS** [comment]
When can you expect update?

**Comment by shavitush** [comment]
Sorry for taking so long, but this is now fixed.
