### ISSUE TITLE
[ZONES] Map: surf_summer.

### ISSUE THREAD

**Issue by UnderWayne1337** [shavitush/bhoptimer#485]
On map surf_summer this plugin, bad work (teleport on spawn)
Go to map teleporter (plugin go to spawn)
Put !stop on chat, plugin don't tp me to spawn - I can pass the map, without time and with time there.

**Comment by cytrus224** [comment]
This is a timer made specific for bhop mode, not surf.

**Comment by Technoblazed** [comment]
Go use cksurf or the influx timer if you want a surf plugin.

**Comment by e-slut** [comment]
I would use KP cksurf https://github.com/fluffyst/Surftimer or marcowmadeira's cksurf https://github.com/marcowmadeira/ckSurf

**Comment by Technoblazed** [comment]
https://github.com/TotallyMehis/Influx-Timer

**Comment by strafe** [comment]
His issue doesn't even sounds surf related though

**Comment by Technoblazed** [comment]
It sounds like bad zoning.

**Comment by shavitush** [comment]
> Put !stop on chat, plugin don't tp me to spawn

!stop stops your timer, doesn't teleport you anywhere.

**Comment by Lime18** [comment]
At me something similar on bhop-maps, sometimes I do not trigger trigger_teleport / trigger_push, I can not reveal the reason of a bug as it is shown after 3-4 hours of operation of the server (it does not depend on the card).

**Comment by shavitush** [comment]
Try `shavit_misc_resettargetname 0` in `cfg/sourcemod/plugin.shavit-misc.cfg`?

**Comment by Lime18** [comment]
@shavitush this did not solve the problem :(

**Comment by shavitush** [comment]
`sm plugins list` output? Run the command via RCON (not sm_rcon)

**Comment by Lime18** [comment]
The fact is that the server worked only with shavit-plugins and the problem was observed ... The problem appeared after one of the timer updates (I can not say for sure). At the moment, it's only a complete reboot of the server.

**Comment by shavitush** [comment]
What about shavit-replay? Does unloading it solve the trigger issue?

**Comment by Lime18** [comment]
give me a day, I'll check it out.

**Comment by Lime18** [comment]
The problem still exists.

**Comment by Lime18** [comment]
Found! If you delete the zones (Start / End) triggers on the marp, it's funny that after a full restart of the server, the triggers work for some time normally...

**Comment by shavitush** [comment]
Interesting. I'll check it out whenever I have time.

Unfortunately not too soon, lost my phone (therefore access to 2FA) so I have to delay development a bit D:

**Comment by UnderWayne1337** [comment]
Shavit, what should I do? If on ordinary maps (where I do not load the timer plug-ins), I throw everything at ct / t and the map changes abruptly? Used before the old version, this was not ..

**Comment by Technoblazed** [comment]
The plugin doesn't support late loading, don't disable it on those maps. If you need a timer for deathrun/surf use a different timer.

**Comment by strafe** [comment]
Well if you run a multimode server and one of them is bhop then why shouldn't it be used on the bhop maps?

**Comment by shavitush** [comment]
@Technoblazed it does support late loading actually

**Comment by Technoblazed** [comment]
That'd be why then :^)

**Comment by UnderWayne1337** [comment]
@PaxPlay i use this timer on bhop maps, per death - plugin respawn me, how to off this?

**Comment by PaxPlay** [comment]
@UnderWayne1337 
`shavit_misc_autorespawn 0` for autorespawn
`shavit_misc_godmode 0` for godmode
edit `cfg/sourcemod/plugin.shavit-misc.cfg` to change them

**Comment by UnderWayne1337** [comment]
@PaxPlay thanks

**Comment by UnderWayne1337** [comment]
@PaxPlay and.. Maybe u say, why ct team (1 player) spawn on t spawn, i disable plugin on mg_tv_tower_v2, if i disable plugin (put shavit' timer to disabled) everything is fine!

**Comment by Lime18** [comment]
I was not entirely right, it seems the problems are exactly in the Start Zones!

**Comment by Lime18** [comment]
I found a map where the problem is clearly visible (do not work boosts)
http://steamcommunity.com/sharedfiles/filedetails/?id=1155421980

**Comment by shavitush** [comment]
This was solved a few days ago.
