### ISSUE TITLE
shavit (Team change_unlimited)

### ISSUE THREAD

**Issue by Hugopereira785** [shavitush/bhoptimer#488]
I am using this plugin: TeamChange Unlimited
And the plugin is not letting him do his job. The plugin blocks players from entering a certain team.
Sorry for my bad english

Plugin link: https://forums.alliedmods.net/showthread.php?p=1877187

Help please

**Comment by shavitush** [comment]
Comment (or remove) this line from shavit-misc.sp and recompile. I won't remove the feature.

```sp
AddCommandListener(Command_Jointeam, "jointeam");
```
