### ISSUE TITLE
Remote Database 

### ISSUE THREAD

**Issue by SeatloN** [shavitush/bhoptimer#489]
Hello ! 

I have a game server with your timer and i use a remote ( Same data center) Database,

My issue is on some map loads the server gets a massive lag on first minutes, around 300 ms in var and sv and if i do "rcon stats" the load on CPU is almost at 100%. 

Is this only because of the MySQL server don't respond in time or can it be configuration on my part that is the issue ? 

Best regards Seatlon

**Comment by shavitush** [comment]
You can't do much about it, sorry! bhoptimer is supposed to run on low latency database servers. 
You'll have to either start using SQLite (that'll not allow usage of the rankings plugin) or host the database locally.

**Comment by cytrus224** [comment]
Had same issue,  if you can, set higher open_files_limit, it could help.
