### ISSUE TITLE
Does not display the zones.

### ISSUE THREAD

**Issue by samoletik1337** [shavitush/bhoptimer#490]
Why if you install more than 6 zones on the map, the following areas are not visible. Here is a screenshot.
![20170919191708_1](https://user-images.githubusercontent.com/28659564/30597139-8d4d6e16-9d6f-11e7-9892-981b772696fe.jpg) The sixth area is not displayed correctly. And when you create more zones, they are not visible.
Game CSS OB, SM 1.8, The latest version of the timer.

**Comment by PaxPlay** [comment]
I believe that there is a maximum amount of beams that can be drawn at the same time. This would be a limitation with the engine.
However, there probably won't ever be any situation in which so many zones have to be displayed at the same time.

**Comment by strafe** [comment]
Yes, there is a temp ent limit of 64.

blacky has [some code in bTimes](https://github.com/Nolan-O/bTimes/blob/master/addons/sourcemod/scripting/bTimes-zones.sp#L965-L979) to only draw 4 beams per frame to allow drawing of _infinite_ zones.

Pretty sure his logic is wrong though; he states the limit is 32 event though it's 64 and on top of that 4 zones would create 48 temp ents not 32 anyway.

**Comment by shavitush** [comment]
So basically if I were to draw 64 beams per frame (as long as they are *created* in different frames) it could be fixed?

**Comment by strafe** [comment]
@shavitush yep you can have any amount of beams on the screen at once by queuing the creation, assuming the first created beam's life is long enough to still be there at the end.

Probably easier to just draw 5 zones per frame with something similar to blacky's code though, using 64 might save a frame in certain situations but at least there's some space left with 5 * 12 just in case.

**Comment by shavitush** [comment]
Apparently this isn't an issue in CS:GO, makes sense why there wasn't an extensive report before..

![image](https://user-images.githubusercontent.com/3672466/32814077-12e5b854-c9b6-11e7-81af-8ac10fcabfb1.png)

**Comment by shavitush** [comment]
There we go.

![20171115041933_1](https://user-images.githubusercontent.com/3672466/32815337-389e2828-c9bc-11e7-95ec-007a7c2c24d8.jpg)
