### ISSUE TITLE
Adding support for mapzones implemented in maps

### ISSUE THREAD

**Issue by cytrus224** [shavitush/bhoptimer#491]
https://forums.alliedmods.net/showthread.php?t=301186
Thats great idea, not having to put mapzones everytime, not worrying about time differencies.

**Comment by Technoblazed** [comment]
Sounds like more effort than it's worth.

**Comment by strafe** [comment]
Doubt that standard will be adopted for bhop, there's at least a couple thousand legacy maps that won't support it and mappers aren't going to see that thread.

**Comment by MountFranklin** [comment]
Getting this out to mappers and map-porters would be great. Having to zone 1200 maps is shit enough as it is.

**Comment by SlidyBat** [comment]
There might be some initial effort in terms of adding it as feature, but it's easier to implement than regular zones. No need to save or set anything, just need to hook the zones. True that old maps won't be supported but in the long run this saves everyone A LOT of time. Not sure if you've ever had to bulk zone hundreds of maps but its not fun.

**Comment by shavitush** [comment]
get me any actual map that uses this kind of zones and i'll gladly try implementing this

**Comment by Nickelony** [comment]
Please do it. I'll update all my 86 maps with those zones. :)

**Comment by SlidyBat** [comment]
https://mega.nz/#!V8UkkTSL!LOJ0QYRtrupJ8ivbyhKRZHODstU2Z4XRdlAjOc50BZo

This is a map made for testing it out. Don't worry about the Stage X start/end, that was a scrapped idea.

**Comment by shavitush** [comment]
@SlidyBat is this map for CS:S or CS:GO?

**Comment by SlidyBat** [comment]
CS:GO, do you need one for CS:S?

**Comment by shavitush** [comment]
I'd love one, it's much harder to test things with CS:GO as the game takes much longer to run and alt-tabbing is kinda broken for me there.

**Comment by Technoblazed** [comment]
Stick it in fullscreen windowed Kappa

**Comment by SlidyBat** [comment]
https://mega.nz/#!V8UkkTSL!LOJ0QYRtrupJ8ivbyhKRZHODstU2Z4XRdlAjOc50BZo

**Comment by shavitush** [comment]
@SlidyBat 

```
sm_map fly_mev_test
CModelLoader::Map_IsValid:  Map 'maps/fly_mev_test.bsp' bsp version 21, expecting 20
```

**Comment by SlidyBat** [comment]
Woops, looks like I accidentally reuploaded the CS:GO version.
Heres the right one: https://mega.nz/#!A9sAEaLR!gaE3Q3zNKQzfSKxQkM_zH9Lp79C_q_I6Qi-1F3jqA1Y

**Comment by shavitush** [comment]
@SlidyBat just started implementing this - are checkpoint zones just for timers that have something like WRCP and save the best time for that checkpoint?

**Comment by SlidyBat** [comment]
Yeah pretty much. Maps might have them, but if you don’t want to implement them you don’t really have to. Same with bonuses and the tier/mapper name stuff. Only essentials are start/end.

Also thanks for implementing this, I’ll try to get some mappers on board now and hopefully it’ll pick up.
