### ISSUE TITLE
Zone borders disappear when a corner is inside a wall.

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#493]
Screenshots:
https://puu.sh/xNpHc.jpg
https://puu.sh/xNpQx.png

**Comment by shavitush** [comment]
not sure if this is fixable, pretty sure the wall needs to be textured as nodraw for the client to render it

**Comment by strafe** [comment]
This isn't a timer-specific thing, any beams that travel through certain brushes/solids will not be drawn for whatever reason. Probably requires some annoying math to change zone points to the nearest visible location to fix.

**Comment by Nickelony** [comment]
Ok, but this is a recent glitch that wasn't there before, so... I'm not sure what's causing it. :/

It might be caused because of the new zones, but I haven't tested it yet. (will do later)
