### ISSUE TITLE
shavit bhop settings help

### ISSUE THREAD

**Issue by rdubbz** [shavitush/bhoptimer#496]
Im using shavits for my bhop server, and im in the shavit.styles.cfg to fix settings, but i cant find what to set them to. When i try bhopping i feel like i cant gain speed. the fastest people can go is like 500 speed. It almost feels like sometimes you cant even make it to the final platforms because we can't get enough speed.

**Comment by strafe** [comment]
Do you have `"bunnyhopping" "1"` set for the style you're having the issue with?

**Comment by rdubbz** [comment]
I added that to the shavit.styles.cfg file, and i set the airacell on 1000. Just something feels off u cant gain speed. This is server info 198.204.252.139:27070 if you can join and maybe see what im talking about

**Comment by strafe** [comment]
I think you have an older version of the timer installed, download the latest version [here](https://github.com/shavitush/bhoptimer/archive/master.zip).

**Comment by rdubbz** [comment]
Ok i updated the files and now when i go in the server the replay bot keeps killing suiciding, and its saying im being compensated money, and its restarting the round. Why is all this happening now ?

**Comment by rdubbz** [comment]
and for some reason sm_difficulty is not working now, and its still the same issue it feels like u cant gain speed or even get to the next block when i bhop. autobhop is on, and something is seriously wrong

**Comment by strafe** [comment]
I've been on your server, `shavit-styles.smx` is not present or is not loading, check your error logs.

**Comment by rdubbz** [comment]
How do i get it to load ? the file is there

**Comment by shavitush** [comment]
There's no `shavit-styles` though.

@rdubbz can you post your addons/sourcemod/logs/error_XXXX.log files here?

**Comment by rdubbz** [comment]
can you add me on steam or join my discord ?

**Comment by rdubbz** [comment]
how come all the other shavit smx files are there but not the styles. I  installed the new copy from  the github.

**Comment by rdubbz** [comment]
also i just went through the github i cant find the shavit-styles.smx file. When i look in the plugins folder i see all the other shavit stuff just not the styles one

**Comment by strafe** [comment]
As shavit said there isn't one it was my mistake.

**Comment by shavitush** [comment]
I'll repeat myself, if you want help:

@rdubbz can you post your addons/sourcemod/logs/error_XXXX.log files here?

**Comment by rdubbz** [comment]
@shavitush https://pastebin.com/Q5zUfEfX

**Comment by strafe** [comment]
Dynamic was removed in d3a0d5b pretty sure you're using an old version of the timer still?

**Comment by rdubbz** [comment]
@shavitush I had the old one then i uploaded the new stuff over it. Where do i put these files you just sent me the .sp files ? Sorry for all the questions im pretty new to this

**Comment by strafe** [comment]
You can compile the source (`.sp` files) yourself or use the pre-compiled ones, upload them to the `addons/sourcemod/plugins` folder.

**Comment by rdubbz** [comment]
@shavitush ok i dont see a shavit-style.smx in this file

**Comment by strafe** [comment]
Firstly I'm not @shavitush, secondly there is no `shavit-styles.smx` I told you that was my mistake, it does not exist.

**Comment by rdubbz** [comment]
whats the command to change styles when i type sm_difficulty it says unknown command, and im on the server now, and im telling you something is wrong with the speed.

**Comment by rdubbz** [comment]
Nevermind the speed feels much better now, but why doesnt chat work why cant people type to each other ?

**Comment by rdubbz** [comment]
im trying to figure out where to change the timer on the map so it changes to the next map when time runs out, and since people cant type in chat they cant rtv the map and go to the next voted map

**Comment by shavitush** [comment]
You're a really hard person.. what's your server's tickrate?
Disable shavit-chat and chat-processor if you don't want the chat processing from bhoptimer.
`mp_ignore_round_win_conditions 1` is the setting you're looking for.
Use a map management plugin such as Mapchooser Extended and configure it properly; this has nothing to do with bhoptimer.

**Comment by rdubbz** [comment]
@shavitush i don't mean to be a pain. i did read everything that how i originally got everything installed. I was having errors thats why i came here. Now the speed and everything feels good.

**Comment by shavitush** [comment]
sv_alltalk?

**Comment by rdubbz** [comment]
ya thats on. I thought the shavit chat stopped voice chat as well. It just stops typing ?

**Comment by shavitush** [comment]
It stops because you have chat-processor installed but not the required configuration for it.

> L 10/23/2017 - 05:57:56: [chat-processor.smx] Error parsing the flag message formatting config for game 'csgo', please verify its integrity.

**Comment by rdubbz** [comment]
so should i remove the smx for shavit-chat ? also for the maps zones do we have to add them manually or is their a list of maps that already have zones pre configured ?

**Comment by shavitush** [comment]
No, just install chat-processor properly. It comes with files that you place in the `configs/` directory.
And yes, you need to add zones manually or ask a server owner for a database populated with zone data.

**Comment by rdubbz** [comment]
where do i get the files for the chat thing your talking about, because i installed everything for all folder on the github. i thought i already installed everything

**Comment by rdubbz** [comment]
This is my first time ever doing this stuff. Sorry for all the questions but i been really struggling trying to get everything to work

**Comment by shavitush** [comment]
https://forums.alliedmods.net/showthread.php?t=286913

**Comment by rdubbz** [comment]
ok and this needs to be setup just to make it so people can type in chat ?

**Comment by shavitush** [comment]
Yes.. set it up with the config files that come with it.

**Comment by rdubbz** [comment]
so all i do is but the smx in the plugins folder then the cfg in the configs folder ? Is that it

**Comment by strafe** [comment]
@rdubbz you put `chat-processor.smx` in the plugins folder and `chat-processor.cfg` in the configs folder.

Both of those folders are located in `addons/sourcemod/`.

**Comment by rdubbz** [comment]
ok and last thing how do you make it so you and someone else can jump on the same platform. When people jump on the same block it makes you start over.

**Comment by shavitush** [comment]
google "mpbhops"
