### ISSUE TITLE
Chat integration for rankings

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#499]
Now that rankings are done, this can be worked on.

!chatranks - a menu with multiple options you can choose from, as long as you apply to the specified rank. Should have a preview mode with a rough preview of chat messages will look. The ability to toggle ccname/ccmsg should be in too.
`addons/sourcemod/configs/shavit-chat.cfg` - configuration file with many options, including rank range, points range, rank% percentage (out of ranked players) and the ability to define custom prefix, chat color, description in menu etc.

(base idea "borrowed" from bTimes v2)

**Comment by Reev3** [comment]
when is this gonna be done? i want ranks :)

**Comment by shavitush** [comment]
Whenever I work on it.

**Comment by ZeitZumKiffen** [comment]
Yeah, i wait for this too Reev3 ^^
