### ISSUE TITLE
!wr don't work - error log

### ISSUE THREAD

**Issue by live4net** [shavitush/bhoptimer#50]
L 06/17/2016 - 12:45:09: [shavit-wr.smx] Timer (WR SELECT) SQL query failed. Reason: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\'bhop_christmas\' AND style = 0 ORDER BY time ASC' at line 1
L 06/17/2016 - 12:45:10: [shavit-wr.smx] Timer (WR SELECT) SQL query failed. Reason: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\'bhop_christmas\' AND style = 1 ORDER BY time ASC' at line 1
L 06/17/2016 - 12:45:13: [shavit-wr.smx] Timer (WR SELECT) SQL query failed. Reason: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\'bhop_christmas\' AND style = 2 ORDER BY time ASC' at line 1
L 06/17/2016 - 12:45:15: [shavit-wr.smx] Timer (WR SELECT) SQL query failed. Reason: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\'bhop_christmas\' AND style = 3 ORDER BY time ASC' at line 1

**Comment by shavitush** [comment]
will work on it today
