### ISSUE TITLE
shavit-rankings making server crash

### ISSUE THREAD

**Issue by 5H4D0W5T4LK3R** [shavitush/bhoptimer#502]
L 10/30/2017 - 18:44:53: [shavit-rankings.smx] Transaction query (0): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= (SELECT SUM((points * (@f := 0.975 * @f) / 0.975)) FROM playertimesJOIN (SELEC' at line 1

This is the error I get, when this command is entered sm_recalcmap

**Comment by shavitush** [comment]
The current rankings have no transactions, you're running an outdated version of rankings.
