### ISSUE TITLE
#502 Issue

### ISSUE THREAD

**Issue by 5H4D0W5T4LK3R** [shavitush/bhoptimer#503]
I downloaded the bhop-mastertimer just as is, compiled it added it to plugins, I even created a new database to test it. I'm still getting the same error, even with the newest version

**Comment by strafe** [comment]
@5H4D0W5T4LK3R as @shavitush has already told you, there are no transactions in `shavit-rankings`` after the rewrite.

The error you're reporting was removed in 7e1ffd4 so it's impossible for you to be running the latest version. Download it [here](https://github.com/shavitush/bhoptimer/archive/master.zip) please.
