### ISSUE TITLE
GetMapTier and GetMapTiers

### ISSUE THREAD

**Issue by PaxPlay** [shavitush/bhoptimer#504]
Usage maybe in a custom mapchooser plugin to display the maps with tier when voting.
native int GetMapTier(char[] mapname);
native StringMap GetMapTiers(); // returns all map tiers

**Comment by shavitush** [comment]
Will be definitely worked on, thanks.

However `Shavit_GetMapTier` will be a `bool`, as not every map has a tier defined to it.
