### ISSUE TITLE
!top / points issue, maps with console messages & recalc. points

### ISSUE THREAD

**Issue by cesoun** [shavitush/bhoptimer#505]
Player ranks seem to only update when a player is online so for those who only come on once or twice remain in the leader boards with the same points even though the points have changed.

Tried removing / changing the points in the database and they remained the same on the leader board even after restarts / map changes. Those who are online see change within 1-2 map changes.

As for the console bug, on certain maps such as arcanev1 when the stage is unlocked its tells the players that the stage has been unlocked but then repeats the last command with some of the text cut off.

https://i.imgur.com/hl62PNz.png

Unsure if this is seen by all players atm.

Not sure if this is a known thing or not but during a recalcmap / recalcall the % of completion never seems to be consistent and stops randomly at times. Not sure if it actually stops or just stops outputting to the console.

**Comment by shavitush** [comment]
> Player ranks seem to only update when a player is online so for those who only come on once or twice remain in the leader boards with the same points even though the points have changed.

> Tried removing / changing the points in the database and they remained the same on the leader board even after restarts / map changes. Those who are online see change within 1-2 map changes.

Do you have anything in your error logs? With the newest version of rankings (master branch) this isn't the behavior, and map points get updated immediately after map changes, even for players that aren't logged in.

In fact, with the newest version of rankings, player points don't update when players connect to the server at all. It's being done for every player upon map changes.

I'm afraid you're running an older version. Make sure to apply those queries if you're getting the latest version and your database isn't brand new, it will allow points and the leaderboards to update quickly.

> https://i.imgur.com/hl62PNz.png

> Unsure if this is seen by all players atm.

Assuming this is CS:S, you're probably running an old version of Chat-Processor.

> Not sure if this is a known thing or not but during a recalcmap / recalcall the % of completion never seems to be consistent and stops randomly at times. Not sure if it actually stops or just stops outputting to the console.

Seems to be alright for me. Is your database hosted locally?

**Comment by cesoun** [comment]
The points are working now after updating the database. Only error still hanging:

`L 11/03/2017 - 00:53:11: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2017 - 00:53:11: [SM] Blaming: shavit-chat.smx()
L 11/03/2017 - 00:53:11: [SM] Call stack trace:
L 11/03/2017 - 00:53:11: [SM]   [0] Database.Escape
L 11/03/2017 - 00:53:11: [SM]   [1] Line 494, ...\shavit-chat.sp::SaveToDatabase()
L 11/03/2017 - 00:53:11: [SM]   [2] Line 262, ...\shavit-chat.sp::Command_CCName()`

Grabbed the latest commit 1,060 & the Chat-Processor just in case. Was using the 1,057 commit prior.

The ccname / ccmsg / cchelp commands work and apply custom colors to users names / messages. It also outputs `Unknown command: sm_ccname`

Not sure if there is a newer version of Chat-Processor that I am unaware of outside of the github page.
Will look around in the meantime. 

My database didn't have a `chat` table and doesn't seem to want to make one. 
Exported my current database and tried it with an empty one but it created the `maptiers, mapzones, playertimes, users` again without the `chat` table. Assuming its related to the error.

As for !recalcmap / !recalcall they seem to work as intended but output isn't consistent. Tested it off a fresh boot with no players online.

**Comment by shavitush** [comment]
Thanks for the detailed report!

Can you let me know what's the output of this query, when you run it manually?

   CREATE TABLE IF NOT EXISTS `chat` (`auth` CHAR(32) NOT NULL, `name` INT NOT NULL DEFAULT 0, `ccname` CHAR(128), `message` INT NOT NULL DEFAULT 0, `ccmessage` CHAR(16), PRIMARY KEY (`auth`));

`shavit-chat` is supposed to run this automatically

**Comment by cesoun** [comment]
Sure thing:
https://i.imgur.com/edOJXID.png

> ```MySQL
> MySQL returned an empty result set (i.e. zero rows). (Query took 0.0017 seconds.)
> CREATE TABLE IF NOT EXISTS `chat` (`auth` CHAR(32) NOT NULL, `name` INT NOT NULL DEFAULT 0, `ccname` CHAR(128), `message` INT NOT NULL DEFAULT 0, `ccmessage` CHAR(16), PRIMARY KEY (`auth`))
> ```

**Comment by shavitush** [comment]
Does it actually create the table upon running this query?

**Comment by cesoun** [comment]
Ah sorry, yes the table gets created. 

Went ahead and did a reboot and had a few people try to ccname but got the same error output as before:

> L 11/03/2017 - 19:35:30: [SM] Exception reported: Invalid database Handle 0 (error: 4)
> L 11/03/2017 - 19:35:30: [SM] Blaming: shavit-chat.smx()
> L 11/03/2017 - 19:35:30: [SM] Call stack trace:
> L 11/03/2017 - 19:35:30: [SM]   [0] Database.Escape
> L 11/03/2017 - 19:35:30: [SM]   [1] Line 494, ...\shavit-chat.sp::SaveToDatabase()
> L 11/03/2017 - 19:35:30: [SM]   [2] Line 262, ...\shavit-chat.sp::Command_CCName()

Along with the `Unknown command: sm_ccname`. 
ccname / ccmsg is still applied to the users, but during that session only.

No other error output outside of that.

**Comment by shavitush** [comment]
Interesting. Do you have a Discord account? I'd love to do a follow-up with you somewhere around Sunday

**Comment by cesoun** [comment]
Sure thing, not sure when i'll be around. Should catch me eventually.
cesoun#6588

**Comment by shavitush** [comment]
Seems to be an issue with remote databases, trying to figure out a fix now.
