### ISSUE TITLE
change laser colour per track

### ISSUE THREAD

**Issue by MountFranklin** [shavitush/bhoptimer#508]
Currently the zones are set to start and end colour for all. Able to add the ability to change bonus start and end to differentiate the two modes for users who put bonus zones in normal map zones?

**Comment by shavitush** [comment]
![20171117084033_1](https://user-images.githubusercontent.com/3672466/32933548-02b66e6a-cb73-11e7-829e-19df9cb8bc7f.jpg)
![20171117084035_1](https://user-images.githubusercontent.com/3672466/32933549-02d93008-cb73-11e7-9806-f71ac728c39c.jpg)
