### ISSUE TITLE
Add old WR time to Shavit_OnWorldRecord

### ISSUE THREAD

**Issue by SlidyBat** [shavitush/bhoptimer#512]
Was trying to make a plugin that shows time difference between new/old WR when it's beaten but I couldn't find any way to do that using the natives/forwards provided.

I was thinking could be done by adding a new parameter to the forward called  `float oldtime` or maybe adding another native `Shavit_GetTimeForRank` which gives details for the record at a certain rank, which could help for getting time for 2nd ranked player.

**Comment by shavitush** [comment]
I'll do my best to add both the old WR time and the native, thanks!
