### ISSUE TITLE
Can't drop weapons

### ISSUE THREAD

**Issue by zeddy1234** [shavitush/bhoptimer#514]
Hey, I'm also unable to drop weapons. Whenever I use the drop command, the weapon model stays on screen, without crosshair and arms. New players don't know about the !hideweapon command and it loosk pretty bad. Can I disable it somehow? It also causes isssue with my !knife and !ws plugin.

**Comment by shavitush** [comment]
!knife and !ws aren't supported, not by me and not by Valve.

Anyways, sounds like a SourceMod issue or another plugin that's incompatible. 

Set `shavit_misc_dropall` to 0 in cfg/sourcemod/plugin.shavit-misc.cfg

**Comment by zeddy1234** [comment]
Doing that makes it so players cant drop weapons at all :(

**Comment by strafe** [comment]
This isn't something specific to the timer, @shavitush you can try killing weapons in `CS_OnCSWeaponDrop` or block picking up weapons with SDKHooks, I believe both of those should stop this.

**Comment by shavitush** [comment]
@zeddy1234 That's your server setting.. set mp_death_drop_gun to a proper value
@strafe Thanks for the suggestion; however not allowing weapon pickups will break parts in a map like exodus

**Comment by zeddy1234** [comment]
Ah, mp_deathdrop gun fixed it. But the !knife and !ws still don't work with timer on, without it they work fine. I'll see what I can do to mess with it.

**Comment by shavitush** [comment]
I can't support those.
