### ISSUE TITLE
Edit rank system to lose no points

### ISSUE THREAD

**Issue by zeddy1234** [shavitush/bhoptimer#515]
Hey, is it possible to make the rank system so players only gain points for completion, but dont lose points if others beat them? I like a grind method on my servers for points, and all my players like it too. 

Would be great if you could do that! Also, it only shows max 150 players in ranks [Im guessing its because of the player win-lose point system]. Please make it possible to have more players possible when you type !rank, cheers.

**Comment by shavitush** [comment]
No, I don't want to change the way the ranking system works. Currently it's like that so players strive for server records and better times across all styles.

To allow !top to show... 1000 players, edit `UpdateTop100` to this:
```sp
void UpdateTop100()
{
	char[] sQuery = new char[512];
	FormatEx(sQuery, 512, "SELECT auth, name, FORMAT(points, 2) FROM %susers WHERE points > 0.0 ORDER BY points DESC LIMIT 1000;", gS_MySQLPrefix);
	gH_SQL.Query(SQL_UpdateTop100_Callback, sQuery, 0, DBPrio_Low);
}
```
