### ISSUE TITLE
Recalculating points only goes to 50%

### ISSUE THREAD

**Issue by SlidyBat** [shavitush/bhoptimer#516]
https://i.imgur.com/tHBYQf5.png

**Comment by Tomekosi** [comment]
shavit-rankings.sp line 729 missing destructor. DataPack pack = new DataPack(); should be deleted afterwards. Creates a huge memory leak when server contains alot of maps. :)

**Comment by shavitush** [comment]
@SlidyBat can I have your style config file?
@Tomekosi wrong. The datapack is deleted from within the callback, see line 750:

```sp
delete view_as<DataPack>(data);
```

**Comment by Technoblazed** [comment]
I had the issue slidy had the other day, I just always assumed it was the console saying leave me alone. Even though it only says up to 50%, it does do all 100%.

**Comment by SlidyBat** [comment]
Yea it does go to 100%, de_ maps are last ones. I'll upload style config later today.

**Comment by Technoblazed** [comment]
Honestly, pretty sure it's just rate limiting from the game.

**Comment by shavitush** [comment]
@Technoblazed it's more likely that this code is faulty:

```
int max = ((gA_ValidMaps.Length * 2) * gI_RankedStyles);
float current = ((float(++gI_Progress[client]) / max) * 100.0);
```

rather than any kind of rate limiting

**Comment by Technoblazed** [comment]
`gA_ValidMaps.Length * 2` why are you multiplying this by 2?

**Comment by shavitush** [comment]
Because of tracks, `max` is the amount of recalculations that need to be ran aka (number of maps * number of tracks) * ranked styles

Changing `* 2` to `TRACKS_SIZE` works too

**Comment by Technoblazed** [comment]
Hm, what if there's no bonus tracks created, could that cause it?

**Comment by shavitush** [comment]
No, it shouldn't.
My theory is that `gI_RankedStyles` gets doubled, I'll push an update to fix it, if it's the case.
