### ISSUE TITLE
Spec list doesn't show admins

### ISSUE THREAD

**Issue by zeddy1234** [shavitush/bhoptimer#517]
Hey, the spectator list on the left side doesn't show when any admin or mod is spectating a player. Is this intentional ? And can it be changed?

Even when 2 people are spectating someone and admin or mod spectates the player, it will only show the 2 non admins spectating.

**Comment by Technoblazed** [comment]
Admins are hidden from the spectator list, so won't appear. If there's just one admin spectating, there won't be a menu. This is intentional.

**Comment by zeddy1234** [comment]
Can I remove this feature?

**Comment by zeddy1234** [comment]
Ah nvm, did it, thanks for the help.

**Comment by shavitush** [comment]
I'll change the behavior of this so admins can see other admins in the list.

**Comment by zeddy1234** [comment]
Ah, perhpas a command like !hidemyass would be better that allows admins to remove themselves from speclist.
