### ISSUE TITLE
Low grav bug

### ISSUE THREAD

**Issue by zeddy1234** [shavitush/bhoptimer#520]
Hey, low gravity style bugs with a lot of maps, especially ones which already have low gravity blocks, these don't give any boosts to you that are neccessary.

On top of this, some maps like bhop_craton don't even allow you to do first block [It's a normal block] with low gravity selected. Can this be fixed?

**Comment by SlidyBat** [comment]
I doubt this can be fixed through sourcemod without breaking some maps, but would be good to have a command like !normalgrav that resets your gravity in case a booster changes it.

**Comment by Nickelony** [comment]
Low gravity blocks? you mean trigger_gravity?

if so, there's an easy fix for this:
```
bool gB_TouchingTrigger[MAXPLAYERS + 1]; // use this wherever you need

public void OnPluginStart()
{
	HookEvent("player_spawn", PlayerSpawnEvent);
	HookEntityOutput("trigger_teleport", "OnStartTouch", StartTouchTrigger);
	HookEntityOutput("trigger_teleport", "OnEndTouch", EndTouchTrigger);
}

public void OnMapStart()
{
	HookEntityOutput("trigger_teleport", "OnStartTouch", StartTouchTrigger);
	HookEntityOutput("trigger_teleport", "OnEndTouch", EndTouchTrigger);
	// this has to be done in both OnPluginStart() and OnMapStart()
}

public void PlayerSpawnEvent(Event event, const char[] name, bool dontBroadcast)
{
	int client = GetClientOfUserId(event.GetInt("userid"));
	gB_TouchingTrigger[client] = false;
}

public int StartTouchTrigger(const char[] output, int entity, int client, float delay)
{
	if(client < 1 || client > MaxClients)
	{
		return;
	}
	
	if(!IsClientInGame(client) || !IsPlayerAlive(client))
	{
		return;
	}
	
	gB_TouchingTrigger[client] = true;
}

public int EndTouchTrigger(const char[] output, int entity, int client, float delay)
{
	if(client < 1 || client > MaxClients)
	{
		return;
	}
	
	if(!IsClientInGame(client) || !IsPlayerAlive(client))
	{
		return;
	}
	
	CreateTimer(0.1, BlockOffTrigger, client, TIMER_FLAG_NO_MAPCHANGE); // it doesn't work without a timer. (idk why)
}

public Action BlockOffTrigger(Handle timer, any client)
{
	gB_TouchingTrigger[client] = false;
	return Plugin_Stop;
}

// YOUR CODE HERE.
```

**Comment by shavitush** [comment]
@Nickelony 
> // it doesn't work without a timer. (idk why)

you have to use RequestFrame() to get it done on the next tick (to simulate a "post hook")

**Comment by shavitush** [comment]
@zeddy1234 I'm unsure of a real fix for this. Any thoughts of a zone to make gravity be handled by the game and map as long as you're in it?

**Comment by Nickelony** [comment]
Lol that's what the code I gave you does. As long as you're inside trigger_gravity, the plugin's gravity stops working and after leaving the zone it should be normal again. Just use the bool before the gravity settings or something.

**Comment by shavitush** [comment]
Oh.. I interpreted it you mean it as a standalone plugin fix. My bad.

**Comment by SlidyBat** [comment]
I don't think thats what he meant. There are certain boosters that work by having trigger_multiple that sets entity gravity to a certain value when touched for a while, then set it back to 1, which breaks low grav style. I've tried fixing this with plugin before, but like I said, always breaks some maps.

Also you should create your hooks on round start post rather than on map start.

**Comment by rtldg** [comment]
>On top of this, some maps like bhop_craton don't even allow you to do first block [It's a normal block] with low gravity selected. Can this be fixed?

That seems to work fine for me. Something might've changed to fix that in the past 4 years.

For the rest of the issue though, I added two zone types to help. https://github.com/shavitush/bhoptimer/commit/c55531168d5186e3ddb76fd9c7479b0692cbb015
- `Zone_NoTimerGravity`: This will stop the timer from changing the player's gravity while they're inside this zone. This will be useful if you run into sections with boosters that also use gravity and you need to just wrap the entire section to prevent lowgrav from interfering.
- `Zone_Gravity`: This will set all players' gravity to whatever gravity scale is set on the zone while they're inside. This is useful for places like `bhop_voyage`'s hot-air balloon level (which has problems with lowgrav and the player floats up right before they can reach the bottom).
