### ISSUE TITLE
Replay bot getting stuck but increases its speed to ridiculous values

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#521]
Just happened in my CS:GO server, the replay bot suddenly hit a speed of over 10k and started accelerating even further, not even moving (therefore not being teleported), destroying the server's performance (variance going up to over 40ms) while being spectated.

Has anyone experienced this before?

**Comment by strafe** [comment]
Is it replicable? If so maybe you could share the replay file.

**Comment by cytrus224** [comment]
It happened for me on zipcore's and rumour's(blacky) version. Replay file isnt the issue, bots sometime get stuck and getting huge speed therefore lagging the server. There's simple fix, however i'm not a coder, i can share replay plugin someone worked for me, you can find fix there.

**Comment by shavitush** [comment]
@strafe not really, playing the replay file again doesn't result in the same issue
@cytrus224 I'd love to see a replay bot plugin where this doesn't happen and I'll try to see what might be a possible fix for it.

**Comment by cytrus224** [comment]
Add me on discord, #8019

**Comment by Technoblazed** [comment]
You have to give the name and the number ;)

**Comment by cytrus224** [comment]
cytrus224, #8019 
@Technoblazed havent used discord a lot, ty :P

**Comment by shavitush** [comment]
aye captain

![image](https://user-images.githubusercontent.com/3672466/32623870-394032ba-c590-11e7-90f4-73d3cfb3dd83.png)

**Comment by shavitush** [comment]
Alright, so possible fixes are: (I need to implement all of those)

* Teleporting the bot if its position is way too far from the one it's supposed to be in. (perhaps `1536 / interval_per_tick`?)
* Reset the `vel[]` array to 0.0.
* Figure out how to properly make the bot crouch when needed so such situations won't happen at all; apparently this bug only happens when the replay has crouching.
* DEFINITIVE FIX: Set the bot's movetype to noclip. Unfortunately this will stop the footstep sound so it's a last resort. If I apply this, use `m_CollisionGroup` value of 1 rather than 2.

**Comment by strafe** [comment]
Influx timer uses `MOVETYPE_NOCLIP` on replaying bots.

**Comment by Lime18** [comment]
It helped me			

> SetEntityMoveType(client, ((GetEntityFlags(client) & FL_ONGROUND) > 0) MOVETYPE_WALK:MOVETYPE_NOCLIP);

Replaced

> SetEntityMoveType(client, ((GetEntityFlags(client) & FL_ONGROUND) > 0) MOVETYPE_NOCLIP:MOVETYPE_NOCLIP);

**Comment by PaxPlay** [comment]
I thought you already fixed that in [this](https://github.com/shavitush/bhoptimer/commit/73f054f213f8823fc4ec50fbef8ebfa30762fe3c) commit so apparently that check doesn't quite work.

Taken from [here](https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/shavit-replay.sp#L1057).
```sourcepawn
if((gI_ReplayTick[style] % RoundToFloor(gF_Tickrate * 1.5)) == 0 && GetVectorLength(vecVelocity) < 2.0 * fDistance)
{
	TeleportEntity(client, vecPosition, vecAngles, vecVelocity);
}
```

**Comment by PaxPlay** [comment]
There is quite a lot wrong with that, you're comparing a velocity in units/second with a distance in units that the player passed in a single tick FROM THE SAME TWO POINTS.

What you should do is compare the velocity that the player had when running the map (or rather the velocity from the position current and last frame of the array list) with the velocity you're teleporting the player.

This should work:
```sourcepawn
if((gI_ReplayTick[style] % RoundToFloor(gF_Tickrate * 1.5)) == 0) // don't acces the arraylist every frame
{
	float vecLastPosition[3];
	vecLastPosition[0] = gA_Frames[style][track].Get(gI_ReplayTick[style] - 1, 0);
	vecLastPosition[1] = gA_Frames[style][track].Get(gI_ReplayTick[style] - 1, 1);
	vecLastPosition[2] = gA_Frames[style][track].Get(gI_ReplayTick[style] - 1, 2);
	
	if(GetVectorLength(vecVelocity, true) / GetVectorDistance(vecLastPosition, vecPosition, true) > 2.0) // keep it squared for performance
	{
		TeleportEntity(client, vecPosition, vecAngles, vecVelocity);
	}
}
```
NOT TESTED

**Comment by shavitush** [comment]
@PaxPlay Leaving it squared didn't work quite well as numbers were VERY inflated; however leaving it not not squared was perfectly fine (and upon profiling, didn't seem to be problematic at all!) - so there we go, we have a solution. Thank you very much for noticing the issue :)
