### ISSUE TITLE
Saving cp's as spectator

### ISSUE THREAD

**Issue by m-yk** [shavitush/bhoptimer#525]
using !save to save a checkpoint as spectator then respawning and using !tele will freeze you in the coords & show the saved velocity instead of continuing movement. Used sm_restart & was still frozen insdie start zone, had to toggle noclip on & off for movement to become normal. i guess thats why the !cp menu is blocked when not alive

https://youtu.be/X4afnWSFZZc

**Comment by shavitush** [comment]
The issue is because of your movetype while specatating. I need to make it so saving is only possible while spectating *someone else* (if in spectator team) and use their movetype/speed/location etc.. or even their whole timer snapshot so you could practice someone else's run.

**Comment by shavitush** [comment]
Alright, I don't really have anyone to test this with but it should work. Can you let me know if it works?

**Comment by m-yk** [comment]
problem is fixed, 

only issue i have with it in its current state is you can't save checkpoints from the replay bot, when done by menu its force closes & sm_save is an unknown command. (https://vgy.me/xD8gOp.png)

**Comment by shavitush** [comment]
I think you're lacking the new translation files from the rankings branch, it should output an error message telling you to spectate a player or be alive to use the command. I do plan on making it possible to save it from a replay's POV but it isn't as easy as it seems, considering movetype, targetname, speed, gravity, stamina and ducking status are much harder to replicate on a replay bot :/
