### ISSUE TITLE
Can't get the shavit-chat module to work

### ISSUE THREAD

**Issue by Dunkstormen** [shavitush/bhoptimer#526]
Everything seems to work except the chat module. The chat tags doesn't apply to the player when he is typing in chat. Nothing is changed and everything is as default.

Tried to get SCP working aswell, but it sadly wont load. And yes, I've got Dynamics working on the server ;)

Any ideas/hints to what I should do?

**Comment by m-yk** [comment]
if chat tags you mean the ones based of ranks, im pretty sure they arent functional yet.

**Comment by Dunkstormen** [comment]
Well if that is the case, I might just go and follow this repo, and hope for it to be functional soon 👍

**Comment by shavitush** [comment]
!ccname and !ccmsg are how you use it right now; that's an admin/donor feature and will be integrated with ranks soon, see #499
