### ISSUE TITLE
BlockTeamForCoursesMaps and Franug Auto-Respawn 

### ISSUE THREAD

**Issue by blackzon** [shavitush/bhoptimer#531]
This Two plugins in title dont work with your most updated timer shavit. 
I try to load, reload, refresh this two plugins and still dont work with timer.
Please Helpe me.

**Comment by Technoblazed** [comment]
- BlockTeamForCoursesMaps: Can't find the plugin, but sounds like a team blocker, for course maps...
- Auto-Respawn: It's a bhop timer. All this plugin does is add cvars for use on course maps.

**Comment by blackzon** [comment]
https://forums.alliedmods.net/showthread.php?p=2282312 - here is the block team for courses maps

**Comment by blackzon** [comment]
And The Auto Respawn from the shavit plugin when spawnprotection from corses maps are activated the respawn are always respawning

**Comment by shavitush** [comment]
I have no interest in supporting this kind of behavior, sorry. This plugin was intended for bhop servers, not minigame.

Simple edits can fix your issues.

shavit-misc: Remove the following line (or comment it) and recompile the plugin.

```sp
AddCommandListener(Command_Jointeam, "jointeam");Z
```

Set `shavit_misc_autorespawn` to 0 in `cfg/sourcemod/plugin.shavit-misc.cfg`.
