### ISSUE TITLE
Wrong World records (MVP) counting

### ISSUE THREAD

**Issue by Lime18** [shavitush/bhoptimer#532]
![1](https://user-images.githubusercontent.com/29817277/32983399-ff0999bc-cca4-11e7-9d42-176c535f684d.png)
![2](https://user-images.githubusercontent.com/29817277/32983401-ff2f4cac-cca4-11e7-80ff-85c25d0bd29f.png)
The player has passed more than 60 maps with top-1

**Comment by shavitush** [comment]
Hi, could you send me a dump of your database (most importantly, `users`/`playertimes` tables) so I could investigate with your setup?

**Comment by Lime18** [comment]
@shavitush sent you a request in discord.

**Comment by shavitush** [comment]
Should work now, I'll push the commit in a moment.

![image](https://user-images.githubusercontent.com/3672466/32985665-9a76c082-ccc8-11e7-9628-bd1a212a8ef8.png)

**Comment by Lime18** [comment]
Excellent thank you!
Look again at this, !rr
![4](https://user-images.githubusercontent.com/29817277/32985718-b68bd574-ccd1-11e7-8869-cc17732dbcee.png)
![5](https://user-images.githubusercontent.com/29817277/32985719-b6afeab8-ccd1-11e7-9d52-eb8cc0340aa9.png)
