### ISSUE TITLE
[shavit-core.smx] Timer error! Failed to insert "âœªplayernameª"'s data to the table. Reason: Incorrect string value: '\xE2\x9C\xAAsat...' for 

### ISSUE THREAD

**Issue by yogev2255** [shavitush/bhoptimer#533]
[shavit-core.smx] Timer error! Failed to insert "âœªplayernameª"'s data to the table. Reason: Incorrect string value: '\xE2\x9C\xAAsat...' for column 'name' at row 1
i am geting this spam on the logs why ?

**Comment by kidfearless** [comment]
update the collation on your name column in your users table to a multi byte safe option, such as utf8mb4_unicode_ci
