### ISSUE TITLE
Can't delete all map records through admin menu

### ISSUE THREAD

**Issue by cytrus224** [shavitush/bhoptimer#534]
https://imgur.com/a/3ODxa

**Comment by cytrus224** [comment]
And "all records for map "bhop_name" for style"
https://imgur.com/a/FS405

**Comment by cytrus224** [comment]
nevermind, just all records at once.

**Comment by shavitush** [comment]
Are you on a remotely hosted database?

**Comment by cytrus224** [comment]
It's hosted on same dedicated machine

**Comment by cytrus224** [comment]
Issue doesn't exist anymore.
