### ISSUE TITLE
!wr bug

### ISSUE THREAD

**Issue by cytrus224** [shavitush/bhoptimer#535]
11 normal records on the map, shows only 1 time(wr)
https://imgur.com/a/fsH7b

**Comment by shavitush** [comment]
Can you send me a dump of your database?

**Comment by cytrus224** [comment]
I've cleaned all records and players from the database, just launched new edition, i'll check if problem still exists and i'll send you it.

**Comment by cytrus224** [comment]
I've sent you database on discord.

**Comment by shavitush** [comment]
Is this still an issue with the latest `chat` branch?

**Comment by cytrus224** [comment]
Yep 
![image](https://user-images.githubusercontent.com/17723060/33803991-4015e1f6-dd9c-11e7-9b62-9439ca4736b1.png)

**Comment by shavitush** [comment]
Send me another copy of your up-to-date database, I'll check this with bhop_x

**Comment by cytrus224** [comment]
Sent you database on discord

**Comment by cytrus224** [comment]
I guess its fixed :P
