### ISSUE TITLE
HUD lists mode as normal while on LG using !cp

### ISSUE THREAD

**Issue by MountFranklin** [shavitush/bhoptimer#536]
Just confirmed this on CSGO:

In start zone, save a !cp while on !lg
Use !style to change to normal/any other mode
Use !cp to teleport to your startzone point.

LG will be on, but your HUD will register as normal. Almost thought it was on normal, but an admin just confirmed it to be an LG time.

**Comment by shavitush** [comment]
Ah.. it's about snapshots not sending the style update forward in case it has been changed. I'll push an update quickly.
