### ISSUE TITLE
Hide chat commands (Chat triggers)

### ISSUE THREAD

**Issue by Dunkstormen** [shavitush/bhoptimer#539]
Would it be a possibility to hide commands like !r and !wr from the chat? Since it annoys me how much people are spamming !r and !wr constantly.

**Comment by cytrus224** [comment]
Isnt it hidden already?

**Comment by shavitush** [comment]
uh...

```sp
public Action OnClientSayCommand(int client, const char[] command, const char[] sArgs)
{
	if(IsChatTrigger())
	{
		// hide commands
		return Plugin_Handled;
	}
}
```

this exists since version 1.4b iirc.. are you running some external chat processor that isn't SCP or Chat-Processor?

**Comment by Dunkstormen** [comment]
No, not running any ChatProccessor plugins. Will try making a test server only using the shavit plugin to see if it still persists. I'll update with result when done :)
