### ISSUE TITLE
Restarts the round.

### ISSUE THREAD

**Issue by mathiaas** [shavitush/bhoptimer#54]
If only 1 player or so is playing, and someone connects and joins a team, it ends/restarts the round.

**Comment by shavitush** [comment]
does `mp_warmup_end` also cause the round end/restart too?

**Comment by mathiaas** [comment]
Could be warmup, I'll check on it later today and let you know! (but it doesn't show that warmup is active)

**Comment by shavitush** [comment]
Could you update me?

**Comment by StrafeHack** [comment]
This isn't anything to do with the Timer. It's a known but in GO where if there is no one on one team and someone switches it triggers a round end event. Here's a thread about it: https://forums.alliedmods.net/showthread.php?t=227322

The round end reason called always seems to be 15 from what I've seen

**Comment by shavitush** [comment]
Alright, I'll add something that blocks CSRoundEndReason:15 when I finish with rankings :)
