### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by Reev3** [shavitush/bhoptimer#540]
L 11/25/2017 - 01:27:28: [SM] Call stack trace:
L 11/25/2017 - 01:27:28: [SM] [1] Line 368, C:\Users\Reeve\Desktop\addons\sourcemod\scripting\shavit-replay.sp::Cron
L 11/25/2017 - 01:27:31: [SM] Exception reported: Dynamic array is too big
L 11/25/2017 - 01:27:31: [SM] Blaming: shavit-replay.smx

Bug happened 2 seconds after I got MySQL set up where console would spam messages like this and server would totally break.

**Comment by shavitush** [comment]
@Reev3 how many styles do you have configured?

**Comment by Reev3** [comment]
@shavitush i just have the default styles, but it did break right after i set up the database so that could be it.

[errors_20171125.log](https://github.com/shavitush/bhoptimer/files/1503367/errors_20171125.log)

**Comment by shavitush** [comment]
L 11/25/2017 - 01:01:16: [SM] Exception reported: Timer startup failed. Reason: [2005]: Unknown MySQL server host 'http://ncf.gflclan.com' (4)

That's your issue. Your database isn't configured correctly.

**Comment by Reev3** [comment]
i was just dumb and put http:// in it. we all good now. ty :)
