### ISSUE TITLE
ssj doesn't work with chat-processor

### ISSUE THREAD

**Issue by Reev3** [shavitush/bhoptimer#546]
ssj doesn't work with the chat-processor plugin, but ccname doesn't work without chat-processor. :(

p.s. also, when are the chat ranks supposed to come out?

**Comment by cytrus224** [comment]
> ssj doesn't work with the chat-processor plugin, but ccname doesn't work without chat-processor. :(

Isnt related to timer. SSJ-advanced is worknig fine for me. https://forums.alliedmods.net/showthread.php?t=287039


> p.s. also, when are the chat ranks supposed to come out?

When they are ready and finished.

**Comment by shavitush** [comment]
SSJ works fine on both CS:S and CS:GO, with my timer, with Chat-Processor and I'm honestly not sure what you're on about..

If you want to use my semi-rewrite of SSJ: some optimizations here and there, reorganized menu, prints using bhoptimer and no chat sound, there you go: https://gist.github.com/shavitush/05b3ff765a0115b48b7463e80c1983fb

This isn't related to bhoptimer anyways, you should report this kind of issues to Chat-Processor's or SSJ's author(s).
