### ISSUE TITLE
TF2 support

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#549]
Apparently people want a working, complete timer plugin for TF2 (mainly for surf/jump gamemodes).

I think that bhoptimer can do well at this.
I also think that the TF2 community deserves this as their game isn't terrible at all, it's free-to-play and I believe it can raise awareness to the awesomeness of the movement game-modes in Source games!

I've heard of people charging money (triple digits USD) for edits of bhoptimer that adjust it to be compatible with TF2, which is in my opinion unfair to both me and server operators that can't afford spending such a hefty amount. Although I can't stop that because of GPL, but justice has to be served somehow.

However, it isn't the easiest thing to support as I don't really play TF2 myself (yet).

React with emojis:
* 👎 - TF2 support is unnecessary.
* 👍 - Integrate into bhoptimer's main branch.
* 😄 - Create a separate branch with support for TF2 and cherry-pick commits from master.
* 🎉 - An "upstream fork" by the community that pulls new changes from the master branch of the current bhoptimer.

Reply with text if there's anything additional to note!

**Comment by strafe** [comment]
Isn't TF2 a tickless game?

**Comment by shavitush** [comment]
That's what I thought, but after some discussion in #sourcemod (well.. through the Discord <-> IRC relay) 

```
<nephyrin> ? TF2 is 66 tick
<shavit> nephyrin: i'm just going by what psychonic said https://forums.alliedmods.net/showpost.php?p=2528300&postcount=5
<nephyrin> psychonic is a duck. I'm not sure what tickless would even mean for a source engine game.
<KyleS> 1000tick, like goldsrc
<psychonic> "frameless"
<psychonic> not tickless
<psychonic> henryg's words
<shavit> hmm.. what does it actually imply though
<nephyrin> It used to be that the server would wake up, try to run a tick, then run any other operations, and finish. Dedicated servers have no other operations, so it would just wake up 1000 times to do 66 ticks, which made no sense and was an artifact of the engine behaving like a listen server
```

**Comment by strafe** [comment]
Interesting, I'm pretty sure psychonic was where I got that impression from too. Sounds good but I don't think it should take priority over important things like #499. Is this an after-release thing?

**Comment by e-slut** [comment]
I know Open Timer got ported to TF2 and I found some parts of Resurfed timer on Github but I don't think it's the full thing.

**Comment by shavitush** [comment]
@strafe theoretically speaking, this shouldn't be hard to do at all, so I don't see a reason to do it after releasing

**Comment by shavitush** [comment]
That was easier to implement than I thought.. however I don't plan on updating it unless I missed a few CS-only things in this commit :)


![surf_utopia_v30019](https://user-images.githubusercontent.com/3672466/33802960-e9696b84-dd8c-11e7-80c2-5a2e06c97d1c.jpg)
![surf_utopia_v30017](https://user-images.githubusercontent.com/3672466/33802961-ea831e8e-dd8c-11e7-81b0-96c4e9c45d96.jpg)
![surf_utopia_v30015](https://user-images.githubusercontent.com/3672466/33802962-eb4c74c8-dd8c-11e7-92ea-66c152a65cdb.jpg)

**Comment by e-slut** [comment]
Nice!
