### ISSUE TITLE
Bots.

### ISSUE THREAD

**Issue by mathiaas** [shavitush/bhoptimer#55]
For some reason, without shavit-replay it seems to add bots.

Running:

shavit-core
shavit-hud
shavit-misc
shavit-wr
shavit-zones

I have -nobots now, but without it, it adds the bots.

**Comment by shavitush** [comment]
add `bot_quota 0` to gamemode_*_server.cfg (replace \* with your gamemode)

**Comment by mathiaas** [comment]
I'd like to re-open this as it doesn't happen without the plugin.
`bot_quota` is already set to 0. That's what is weird.

**Comment by shavitush** [comment]
Give me the output of `sm plugins list`

**Comment by shavitush** [comment]
Could you update me?
