### ISSUE TITLE
OnFinish - could you extend it a bit?

### ISSUE THREAD

**Issue by mathiaas** [shavitush/bhoptimer#56]
This is not really an issue, just a feature request.

Well basically "Shavit_OnFinish" isn't called if a player finishes the map but with the timer stopped. (i.e for using +left/+right binds)
This causes players not to be slayed if they've used a +left/+right bind, as the Shavit_OnFinish isn't called.

Perhaps you could add a bool with the _OnFinish forward? Like `bool timerrunning` or another forward that is called when a player enters an end zone, even if the players timer isn't running..

Unless I missed this in the .inc.

**Comment by shavitush** [comment]
I don't see it being useful, just use `Shavit_OnStop` :)

**Comment by mathiaas** [comment]
The reason as to why I want it is that we're running a minigames server, where players shouldn't DIE for using +left/+right, they should still be able to finish the map, but without the timer.

I still need them slayed as they enter the exit zone. Otherwise I'll have to add slay-zones at every end. :<

**Comment by shavitush** [comment]
https://forums.alliedmods.net/showpost.php?p=2325875&postcount=126

**Comment by mathiaas** [comment]
Exactly. That doesn't get triggered as OnFinish doesn't get triggered if your timer isn't on. (+left/+right)

**Comment by shavitush** [comment]
Oh, now I understand what you wanted haha
I need to think about how to do that though

**Comment by mathiaas** [comment]
Well two ideas could be:

Add a bool like, `bool timerrunning` to the OnFinish, or you could add another OnFinish (with another name of course) but for like "in general" on finish, which is called whether the timer is running or not.

**Comment by shavitush** [comment]
I tried thinking about a solution, but tbh I couldn't think about anything that isn't too resource-intensive. For your purpose, you can use this:

```
#include <sourcemod>
#include <sdktools>
#include <shavit>

public Action Shavit_OnPlayerRunCmd(int client)
{
	if(IsPlayerAlive(client) && Shavit_GetTimerStatus(client) != Timer_Running && Shavit_InsideZone(client, Zone_End))
	{
		ForcePlayerSuicide(client);
	}
}
```

Sorry for not being able to implement `timerrunning` in the forward :(
