### ISSUE TITLE
Segmented timers

### ISSUE THREAD

**Issue by cyrenacia** [shavitush/bhoptimer#563]
I apologize ahead of time if this is already included and I have overlooked it, but I'm primarily interested in setting this plugin up to run on surf, TF2, with a mixture of linear and staged maps. Linear is fine, with a zone at the start and end, however for staged, is it at all possible to set individual segments with zones and have them log separately, rather than multiple stages and their included zones logging a singular best time from a stage to the map as a whole?

**Comment by shavitush** [comment]
The plugin wasn't designed for this purpose - I think it is a design mistake from my side, but it really is too late to do this kind of massive changes right now, especially when it's designed around bhop and KZ.
I don't think I will do this on my own right now or anytime soon, even though it's a great suggestion.
