### ISSUE TITLE
Timer error!

### ISSUE THREAD

**Issue by Lime18** [shavitush/bhoptimer#564]
[shavit-core.smx] Timer error! Failed to insert "🔥RIMSE🔥ᶠᵘᶜᵏᵤ"'s data to the table. Reason: Incorrect string value: '\xF0\x9F\x94\xA5RI...' for column 'name' at row 1
[shavit-core.smx] Timer error! Failed to insert "💎 Kry 💎"'s data to the table. Reason: Incorrect string value: '\xF0\x9F\x92\x8E K...' for column 'name' at row 1

**Comment by BenediktKrimmel** [comment]
inb4 sql injection through player name on databases to get all the wrs

**Comment by shavitush** [comment]
@BenediktKrimmel no, the strings are escaped everywhere the user can input anything.
@Lime18 change your database and table collation/formats to UTF8 or UTF8MB4, this isn't an actual timer error but one with your MySQL database.

I also highly recommend to follow this: https://github.com/shavitush/bhoptimer/wiki/4.-Extra:-Updating-(Database)

**Comment by Lime18** [comment]
@shavitush it helped, thank you.
