### ISSUE TITLE
Bug settings reset and block bunnyhopping in startzone dont work

### ISSUE THREAD

**Issue by iTzBla** [shavitush/bhoptimer#567]
Im playing nice but when map change all the shavit settings reset.
Block bunnyhopping in startzone dont work too.

https://www.youtube.com/watch?v=26zheMDEhYk

**Comment by strafe** [comment]
@iTzBla are you actually changing these settings in `cfg/sourcemod/plugin.shavit-*.cfg`?

**Comment by iTzBla** [comment]
Yes

**Comment by strafe** [comment]
So when do they work, only on the first map after a server restart or only when switching between two different maps?

**Comment by iTzBla** [comment]
Example:
Server start work
Change map bug
Change map work
Change map bug
...

**Comment by iTzBla** [comment]
?

**Comment by shavitush** [comment]
I can't replicate this at all, no one else can either.. if anyone else finds out how to replicate this issue please do reply
