### ISSUE TITLE
Allow a config setting to store replay data in a specific folder/server with details

### ISSUE THREAD

**Issue by MountFranklin** [shavitush/bhoptimer#570]
I run two servers linked to the same database. One whitelisted, another public. Linking replay data is annoying because if a bot is saved on one server, it's not possible to replay it on another.

Is there a possibility to set up a webserver and have the timer save replay data there? As long as both servers are linked to the one database, saving there wouldn't be an issue. This means that running Whitelist/VIP servers will be viable with the same database, meaning users can build around that.

**Comment by shavitush** [comment]
I (personally) don't think storing on a different server is a good idea. However I could add a config setting so you can choose a path to read/write replays from/to. Thanks for the suggestion!

**Comment by strafe** [comment]
@shavitush people would still be locked to the `/csgo|cstrike|tf` root directory though wouldn't they? Personally I think  it's good practice to keep data like replays inside `/data` but I suppose extra configuration is never a bad thing.

@MountFranklin I might be missing something that would make this not possible but if you have full access to the machine(s) your servers are running on you could try [`rsync`](https://linux.die.net/man/1/rsync) with [`cron`](https://linux.die.net/man/5/crontab) (or even something smarter) to keep the replay directories synced. If the servers are on the same machine _I think_ you could even just use a symlink.

**Comment by shavitush** [comment]
@strafe AFAIK, as long as the user running the server has write and read access to that path, then they can write there. I will test this soon, and if it happens to not be possible I'll have to drop this request.

**Comment by MountFranklin** [comment]
@strafe Unfortunately, due to the constraints on my regions average hosting companies, be it GSP or WebHosting, it's not really possible. I've already asked them and they have refused.

I sparked this idea due to being asked to move about 10-15 replay bots from one server to another. If they sync, then users can grind safely on the Whitelist and the public can rtv spam as they see fit.

I understand that it's a hassle, but Australia really is a horrible place to host servers.

**Comment by Technoblazed** [comment]
@MountFranklin Alternatively, create an ftp bash script that gets the latest files on a crontab, and transfer it between servers.

**Comment by MountFranklin** [comment]
@Technoblazed I'm going to admit that I am the WORST when it comes to finding his own solution, which is why I requested a config.

I understand code on a basic lvel and can pseudo it to a good level, I just can't write it for the life of me.

**Comment by shavitush** [comment]
@strafe you were right! The solution was to escape the game directory by using `../` until you get to the path you want.

**Comment by strafe** [comment]
@shavitush very cool, never considered using things like `..` and `~`.

For anyone interested it should still be possible to get the server's full path using the `server_spawn` event, it's kind of bad and doesn't always fire but it works(ish), Sikari posted some more information on it [here](https://forums.alliedmods.net/showthread.php?t=301285).
