### ISSUE TITLE
Switching to spectate and back affects time.

### ISSUE THREAD

**Issue by kidfearless** [shavitush/bhoptimer#571]
So switching to spectate and then joining a team causes the players time drop when they join a team again. It drops it more the longer their time is, and usually around the hour mark will drop them by a minute. Doing /pause and /resume doesn't seem to change it at all though.

**Comment by shavitush** [comment]
Set `shavit_misc_restorestates` to 0 for now. A proper fix for this depends on #440, so whenever SourceMod 1.9 is stable.

**Comment by strafe** [comment]
I believe 1.9 is technically stable now since it's no longer master, should probably wait till they update the downloads section though. [1.10 builds](http://www.sourcemod.net/smdrop/1.10/)

**Comment by shavitush** [comment]
#440 has been applied! Can you try and see if this issue is solved now?
