### ISSUE TITLE
Speed max 320 

### ISSUE THREAD

**Issue by blackzon** [shavitush/bhoptimer#573]
I just install the timer and when i try to BHOP the speed go max 320 and if i change sv_maxspeed 320 to bigger noclip dont work, and i change many things and still 320 speed max

**Comment by shavitush** [comment]
open your server's console, write "sm plugins list" and post the output here

**Comment by blackzon** [comment]
"[UMC] Prefix Exclusion" (3.4.6-dev) by Steell
 "Basic Chat" (1.8.0.6017) by AlliedModders LLC
 "[UMC] End of Map Vote Warnings" (3.4.6-dev) by Steell
 "Chat-Processor" (2.0.9) by Keith Warren (Drixevel)
 "Fun Votes" (1.8.0.6017) by AlliedModders LLC
 "Weapons & Knives" (1.1.1) by kgns | pluginal.com
 "Map configs" (1.3) by Berni
 "[UMC] Admin Menu" (3.4.6-dev) by Steell
 "TOG Clan Tags" (2.2.7) by That One Guy
 "[UMC] Rock The Vote" (3.4.6-dev) by Steell
"[UMC] Random Cycle" (3.4.6-dev) by Steell
 "[UMC] Player Count Monitor" (3.4.6-dev) by Steell
 "Objective Remover" (0.0.2) by SavSin
 "Admin File Reader" (1.8.0.6017) by AlliedModders LLC
 "SM FPVMI - Custom Weapons Menu" (3.1) by Franc1sco franug
 "[UMC] End of Map Vote" (3.4.6-dev) by Steell
 "Basic Info Triggers" (1.8.0.6017) by AlliedModders LLC
 "[UMC] Player Limits" (3.4.6-dev) by Steell
 "SM DEV Zones" (2.2.4) by Franc1sco franug & Root
 "No Dependencies Noblock" (1.0) by ml
 "Sound Commands" (1.8.0.6017) by AlliedModders LLC
"SM First Person View Models Interface" (3.1) by Franc1sco franug
 "Admin Help" (1.8.0.6017) by AlliedModders LLC
 "Stop Map Music" (1.0.0) by GoD-Tony [Fixed by The Count]
 "[shavit] Core" (1.5b) by shavit
 "[shavit] World Records" (1.5b) by shavit
 "[UMC] Time Limits" (3.4.6-dev) by Steell
 "Basic Comm Control" (1.8.0.6017) by AlliedModders LLC
 "SM DEV Zones - Teleport" (2.0) by Franc1sco franug
 "[shavit] HUD" (1.5b) by shavit
 "ServerAdvertisements3" (3.1.3) by ESK0
 "[UMC] Ultimate Mapchooser Core" (3.4.6-dev) by Steell
"[UMC] Nominations" (3.4.6-dev) by Steell
 "Basic Commands" (1.8.0.6017) by AlliedModders LLC
 "Admin Chat and Tag Personalizado" (2.5) by Marco Machado Smartfuzion
 "[UMC] Post-Played Exclusion" (3.4.6-dev) by Sazpaimon and Steell
 "[shavit] Miscellaneous" (1.5b) by shavit
 "Anti-Flood" (1.8.0.6017) by AlliedModders LLC
 "Player Commands" (1.8.0.6017) by AlliedModders LLC
 "[UMC] Map Weight" (3.4.6-dev) by Steell
 "Admin Menu" (1.8.0.6017) by AlliedModders LLC
 "[UMC] Echo Nextmap" (3.4.6-dev) by Steell
 "[UMC] Map Commands" (3.4.6-dev) by Steell
"[shavit] Chat" (1.5b) by shavit
 "[shavit] Player Stats" (1.5b) by shavit
 "Basic Votes" (1.8.0.6017) by AlliedModders LLC
 "SM Franug Auto Respawn" (1.7.1) by Franc1sco franug
 "[shavit] Map Zones" (1.5b) by shavit
 "Client Preferences" (1.8.0.6017) by AlliedModders LLC
 "Fun Commands" (1.8.0.6017) by AlliedModders LLC
 "Nextmap" (1.8.0.6017) by AlliedModders LLC
 "Gloves" (1.0.1) by kgns - wasdzone
 "Default SM Text Replacer" (0.32.GO) by Mitch/Bacardi
 "Simple Chat Processor (Redux)" (1.1.5) by Simple Plugins, Mini
"BoomPanel" (1.00) by boomix
 "[shavit] Sounds" (1.5b) by shavit
 "[UMC] Vote Command" (3.4.6-dev) by Steell
 "Basic Ban Commands" (1.8.0.6017) by AlliedModders LLC
 "Reserved Slots" (1.8.0.6017) by AlliedModders LLC
 "[Any] SteamWorks Game Description Override" (0.1) by Dr. McKay, Sarabveer(VEER�)

**Comment by shavitush** [comment]
what about the following?

```
sm_cvar sv_enablebunnyhopping
sm_cvar sv_autobunnyhopping
```

**Comment by blackzon** [comment]
i do not put this, but in the plugin i have it activeted

**Comment by shavitush** [comment]
do you have a discord account? if so, please join the project's server and message me there https://discord.gg/jyA9q5k

**Comment by blackzon** [comment]
ok i put waht you send in my customcfg and it works
sm_cvar sv_enablebunnyhopping
sm_cvar sv_autobunnyhopping

**Comment by shavitush** [comment]
i don't need you to put those commands in your custom cfg, but rather - input those into your server's console and give me the output of both commands

**Comment by blackzon** [comment]
sm_cvar sv_autobunnyhopping
[SM] Value of cvar "sv_autobunnyhopping": "0"

**Comment by shavitush** [comment]
what about the first command?

**Comment by blackzon** [comment]
sm_cvar sv_enablebunnyhopping
[SM] Value of cvar "sv_enablebunnyhopping": "1"

**Comment by shavitush** [comment]
you shouldn't be stuck on 320 speed then. is your `sv_maxvelocity` set to something very low?

**Comment by blackzon** [comment]
320 but if i change noclip dont work and stays 320 velocity

**Comment by blackzon** [comment]
but now its ok i put those commands in my customcfg and works

**Comment by strafe** [comment]
@blackzon try removing them and see if it still works, those commands without a value shouldn't affect your server.

**Comment by shavitush** [comment]
`sv_maxvelocity` is supposed to be set to 3500 by default

**Comment by blackzon** [comment]
now is 3500 without those commands

**Comment by shavitush** [comment]
glad to hear it's fixed even though i did nothing
