### ISSUE TITLE
'infinite' checkpoints

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#575]
Also: Add entity flags, only change movetype if it's changing to `MOVETYPE_LADDER`

**Comment by shavitush** [comment]
Feel free to mess around with this, I tested in a local server and it seemed fine. Might have missed something though. Will close in a day or two if there are no reports.

**Comment by e-slut** [comment]
I tested with over 200+ checkpoints and it worked fine and the movetype thing works as well!
