### ISSUE TITLE
Cant normally jump from start zone.

### ISSUE THREAD

**Issue by T1MOXA** [shavitush/bhoptimer#577]
After plugins update to latest version from version with shavit_misc_prespeedlimit cvar, players can't jump from start zone to first stage.

shavit_core_blockprejump "0"
shavit_misc_prespeed "1"
shavit_misc_prestrafelimit "30"

When i set shavit_misc_prespeed to 0 all fine, but it's not a very good solution.

**Comment by shavitush** [comment]
Make your start zone smaller. I made prespeed limits work similarly to how other popular timers (mainly bTimes2 and the other one by the Chinese CS:GO dev) do it.

**Comment by T1MOXA** [comment]
It's not very convenient to do...
I have more than a hundred maps.
I find it easier to roll back the plugin to older version.

**Comment by T1MOXA** [comment]
What is the general advantage of this system ?

And, can you tell me what commit it was added ?

**Comment by shavitush** [comment]
The advantage is so that players are not stopped in place, but slowed down if they jump from *in within* the start zone.

1d84cfe8664eaa2ee8e611da044eeab993082bc2

**Comment by PaxPlay** [comment]
Its supposed to stop you from prespeeding in the start zone without just limiting your speed to 260 to allow for "prestrafing", a technique used to gain up to 290u/s on the ground. If youre on csgo, this wont work because the VALVE devs disabled it, you can however install [csgo_movement_unlocker](https://forums.alliedmods.net/showthread.php?t=255298) by peacemaker to enable it again (you also have to set sv_friction to 4.4 for it to work).

**Comment by shavitush** [comment]
I second @PaxPlay's reply and I'd like to add, that if you do get Movement Unlocker, the combination of `sv_friction 4`, `sv_accelerate 5` and `sv_accelerate_use_weapon_speed 0` are the standard settings for bhop, as the huge first chunk of bhop maps in CS:GO were direct ports from CS:S, and those are the default settings there.

**Comment by T1MOXA** [comment]
> Its supposed to stop you from prespeeding in the start zone without just limiting your speed to 260 to allow for "prestrafing", a technique used to gain up to 290u/s on the ground. If youre on csgo, this wont work because the VALVE devs disabled it, you can however install csgo_movement_unlocker by peacemaker to enable it again (you also have to set sv_friction to 4.4 for it to work).

I put csgo_movement_unlocker and nothing has changed.
sv_friction is on 4.4

> The advantage is so that players are not stopped in place, but slowed down if they jump from in within the start zone.

Sounds good, but it seems csgo it's not working.
The player from the start drops like a stone, and this complicates the game.

**Comment by T1MOXA** [comment]
> I second @PaxPlay's reply and I'd like to add, that if you do get Movement Unlocker, the combination of sv_friction 4, sv_accelerate 5 and sv_accelerate_use_weapon_speed 0 are the standard settings for bhop, as the huge first chunk of bhop maps in CS:GO were direct ports from CS:S, and those are the default settings there.

"sv_accelerate" = "6.5"
"sv_friction" = "4.4"
"sv_accelerate_use_weapon_speed" = "0"

**Comment by strafe** [comment]
@T1MOXA I think you should be using the _CS:S / standard settings_:
```
sv_friction 4
sv_accelerate 5
```

**Comment by T1MOXA** [comment]
> @T1MOXA I think you should be using the CS:S / standard settings:
> 
> sv_friction 4
> sv_accelerate 5

Nothing has changed

**Comment by T1MOXA** [comment]
Any ideas ?

**Comment by shavitush** [comment]
can you record a video?
