### ISSUE TITLE
Precise times, regardless of tickrate

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#578]
Basically, implement this: https://blog.momentum-mod.org/post/146131743729/how-the-momentum-mod-timer-works-how-to-get-a

Relies on #440

I might not have time to do this or other big stuff myself as I'm getting enlisted next month. If you can lend a hand, it would be awesome!

**Comment by strafe** [comment]
They had a small problem with that as well, [seen here](https://github.com/momentum-mod/game/pull/73).

**Comment by rtldg** [comment]
pretty sure this has been solved by https://github.com/shavitush/bhoptimer/pull/931 (and any subsequent bug-fix commits to it)
