### ISSUE TITLE
Showing track selected somewhere

### ISSUE THREAD

**Issue by cytrus224** [shavitush/bhoptimer#584]
Like idk, central hud Style: B Style,, and scoreboard prefix BN:time
And make it, so style is colored like track mapzone start color(in hud)

**Comment by theSaint92** [comment]
Can you write it again? in english? xD

**Comment by shavitush** [comment]
Already exists in the CS:S HUD. I don't know how to integrate this nicely into the CS:GO HUD, sorry.
