### ISSUE TITLE
'Optimize' full map points recalculation into less queries

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#586]
Idea: implement MySQL function(s) to calculate points for a given record by either `id` or `time`, `map`, `track` and `style`.

The given parameters for this function should also include: points per tier setting, map tier.

(this is mainly to solve @cytrus224's issue where their server leaks memory due to so many queries at once)

**Comment by shavitush** [comment]
This update has changed the structure of `playertimes`, so for the query to work properly you'll have to drop all the indexes on `playertimes` and run the following queries:

```sql
ALTER TABLE playertimes ADD INDEX `map` (`map`, `style`, `track`);
ALTER TABLE playertimes ADD INDEX `auth` (`auth`, `date`, `points`);
ALTER TABLE playertimes ADD INDEX `time` (`time`);
```

You're encouraged to also modify `style` and `track` to `TINYINT`.

@cytrus224 I'm looking forward to see new results from you!

**Comment by cytrus224** [comment]
Seem to be working and its fast, very very fast 🥇
