### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by tagisgame** [shavitush/bhoptimer#593]
I have an errors while compiling a shavit. It looks like this:
![image](https://user-images.githubusercontent.com/36208687/35882989-1c5a531a-0b86-11e8-947c-224d59910f7d.png)
and
![image](https://user-images.githubusercontent.com/36208687/35883011-2e228b1c-0b86-11e8-9d4a-957b1082d68a.png)
Rest of plugins compiled properly:
![image](https://user-images.githubusercontent.com/36208687/35883126-8ac0cf46-0b86-11e8-9fe2-550dadcccb16.png)

I am using the newest stable Sourcemod (version 1.8 - build 6040). I included all from .zip file. What am I doing wrong?

**Comment by cytrus224** [comment]
Use sourcemod 1.9, it's required now. https://www.sourcemod.net/downloads.php?branch=dev

**Comment by tagisgame** [comment]
Thx cytrus, I did not noticed 👍
