### ISSUE TITLE
Shavit on deathrun :/

### ISSUE THREAD

**Issue by tagisgame** [shavitush/bhoptimer#594]
I put shavit on DR server. How can i fix that TT spawns on CT spawn?

![image](https://user-images.githubusercontent.com/36208687/35885024-dcff0880-0b8c-11e8-8be5-a1dee5b28d02.png)

**Comment by Nickelony** [comment]
This timer wasn't designed for deathrun. I don't think there's any way to change it.

**Comment by tagisgame** [comment]
:( On forums people recommending this to DR too. I don't know other timers as good as shavit.

**Comment by strafe** [comment]
@tagisgame look at the cvars in `plugin.shavit-misc.cfg` and `plugin.shavit-zones.cfg`. You can customise what happens to players when they spawn and disable the restart commands.
