### ISSUE TITLE
cant cycle weapons using keyboard while spec/keyboard hud enabled

### ISSUE THREAD

**Issue by sunha7** [shavitush/bhoptimer#595]
https://youtu.be/2lrnRxwFMzE excuse my loud keyboard

guessing it has something to do with the game taking your input as menuselect 1; menuselect 2 etc instead of slot1 slot2 slot3

**Comment by shavitush** [comment]
let me know if anyone knows a workaround for this

**Comment by m-yk** [comment]
could move the keys into center-hud and have specs in center hud but just as a number

**Comment by rtldg** [comment]
added something that'll show the !keys text in the center by default instead of the menu (although it can be toggled back from !hud). I left the spectators list in the menu still though https://github.com/shavitush/bhoptimer/commit/f474a944aead9ab9ec5aaa7a2107db17f8ce6319
