### ISSUE TITLE
shavit-rankings generally not running

### ISSUE THREAD

**Issue by adamercsn** [shavitush/bhoptimer#596]
Working database as well as generally working plugins, all but rankings that is, simply returns with this:
`[shavit-rankings.smx] Timer (rankings, update all points) error! Reason: FUNCTION mgtimer.GetWeightedPoints does not exist`

(Using latest compiled shavit-rankings.sp from this github)

**Comment by m-yk** [comment]
I believe the problem is you haven't updated your database when you updated the timer, few updates back it was required

https://github.com/shavitush/bhoptimer/wiki/4.2.-Extra:-Updating-(Database)

**Comment by shavitush** [comment]
Manually execute the following queries, do you get any errors?

```sql
DELIMITER ;;
DROP FUNCTION IF EXISTS GetWeightedPoints;;

CREATE FUNCTION GetWeightedPoints(authid CHAR(32))
RETURNS FLOAT
BEGIN
DECLARE p FLOAT;
DECLARE total FLOAT DEFAULT 0.0;
DECLARE mult FLOAT DEFAULT 1.0;
DECLARE done INT DEFAULT 0;
DECLARE cur CURSOR FOR SELECT points FROM playertimes WHERE auth = authid AND points > 0.0 ORDER BY points DESC;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
OPEN cur;
iter: LOOP
	FETCH cur INTO p;
	IF done THEN
		LEAVE iter;
	END IF;
	SET total = total + (p * mult);
	SET mult = mult * 0.975;
END LOOP;
CLOSE cur;
RETURN total;
END;;

DELIMITER ;
```

**Comment by adamercsn** [comment]
Thanks for the answer, i will try to get access to the database asap and reply with whether your solution works.
