### ISSUE TITLE
Have bonus Start/End zones be separate from main.

### ISSUE THREAD

**Issue by kidfearless** [shavitush/bhoptimer#597]
So instead of making the zones and then selecting which track it belongs to, you would select the track first and then the zone type. I can't count the number of times I quickly tried to make a bonus zone and accidentally replaced the main start zone.

**Comment by PaxPlay** [comment]
I see what you want but the current implementation has the advantage of being easy to extend with new tracks. What I'd suggest is having to choose the track **before** you set the points on an extra menu.

```
Zone Menu
  -- Start Zone
    -- Main
    -- Bonus
  -- End Zone
    -- Main
    -- Bonus
  -- ...
```

**Comment by shavitush** [comment]
implemented @PaxPlay's idea
