### ISSUE TITLE
scroll

### ISSUE THREAD

**Issue by skyjamrey3** [shavitush/bhoptimer#599]
scroll lets you still autohop

**Comment by skyjamrey3** [comment]
scroll lets you still autohop

**Comment by cytrus224** [comment]
shavit-styles.cfg, check if "autobhop"	is set to 1

**Comment by skyjamrey3** [comment]
its set to 0

**Comment by cytrus224** [comment]
sv_autobunnyhopping?

**Comment by shavitush** [comment]
it's sv_autobunnyhopping, you shouldn't set it to 1
