### ISSUE TITLE
Points given for finishing a map

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#60]
Hi, I just finished a map and was provided with 

` [Timer] This record was rated -1.00 points.
 [Timer] Total points: -1.00.
 [Timer] You are ranked 1 with -1.00 points.`

Any ideas why it would give -1 points?

**Comment by shavitush** [comment]
Because you didn't set points for the map.
Check the cd83d4d238ccfbe202767c70aae4575cf53613bb

**Comment by Technoblazed** [comment]
Would the ideal time be classed as the ideal record time? How exactly would this work?

**Comment by shavitush** [comment]
You set for example: 10.0s ideal time and 10.0 points for it.
If you score 10.1s, you'll get somewhere around 9.9 points. If you get below 10.0s, you'll 25% extra points for beating the ideal time. If your time is better than the ideal one, you'll get more points and vice versa.

**Comment by Technoblazed** [comment]
How difficult would it be for the ideal time to be autocalculated to the server world record, i.e. WR is ideal, so gets full points, but if someone beats the time, the new ideal is set, and the ranks recalculate shifting the points to the true values

**Comment by shavitush** [comment]
Nice idea! But.. it will create a very big overload on the MySQL server. I need to think of a solution before I implement something like that.

**Comment by Technoblazed** [comment]
Maybe, upon the player completing the map, it reloads their profile, or they are able to do it themselves, so instead of force reloading everyone, just reload clients when they finish maps or manually refresh themselves.
