### ISSUE TITLE
Shavit chat idea *

### ISSUE THREAD

**Issue by 5H4D0W5T4LK3R** [shavitush/bhoptimer#613]
Would it be possible to implement a way into shavit-chat where you can assign like a customrank to a certain steamID, if possible? @

**Comment by 5H4D0W5T4LK3R** [comment]
Sorry for my incompetence, but where do I get this exactly?

**Comment by shavitush** [comment]
refer to https://bhop.online/

> It includes custom chat names, tags, colors and all can be defined by the players/admins.
Admins need the chat flag, or the “shavit_chat” override (good for a donator perk).

**Comment by 5H4D0W5T4LK3R** [comment]
Cool thanks
