### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by kidfearless** [shavitush/bhoptimer#614]
I thought I might post some suggestions that might be nice.

1. Adding a jump height multiplier for styles.
2. Changing halftime so that you can set custom timer speeds.
3. Adding !setstart so that players can set their own start positions.
4. Starting a time for the bonus will have !r return them to the start of the bonus.

**Comment by cytrus224** [comment]
1. "gravity"			"1.0" // Gravity setting, 1.0 for default. Standard for low gravity styles is 0.6.
2. "halftime"			"0" // Calculation of times will be halved, replays WILL NOT function properly.

**Comment by shavitush** [comment]
1. Will be added.
2. Will be deprecating `halftime` in favor of `timescale`.
3. Will be added, only usable in start zone.
4. Will be added. !r will restart to main timer if you have no active timer at all.

**Comment by shavitush** [comment]
update: 2 is now implemented

**Comment by rtldg** [comment]
1 was already done. looks like 3 happened anyway. 
4 was done in https://github.com/shavitush/bhoptimer/commit/e6b3baae81454dc0250e7324e0c871fdb9441411 , https://github.com/shavitush/bhoptimer/commit/96ee05b5aa152e6638ab56434ba9acb14b86b941 , and https://github.com/shavitush/bhoptimer/commit/a89e30632202a4ff1e074a8df99f90fe99f2c1f7
