### ISSUE TITLE
I can't scripting

### ISSUE THREAD

**Issue by ThanhByKyTa** [shavitush/bhoptimer#616]
//// shavit-misc.sp
//
// shavit-misc.sp(1600) : error 017: undefined symbol "IsNullVector"
// shavit-misc.sp(1745) : error 017: undefined symbol "IsNullVector"
// shavit-misc.sp(2448) : error 017: undefined symbol "IsNullVector"
//// shavit-core.sp
//
// shavit-core.sp(1773) : error 017: undefined symbol "GetGameFrameTime"
// shavit-core.sp(1773) : warning 213: tag mismatch
//// shavit-zones.sp
//
// shavit-zones.sp(2418) : error 017: undefined symbol "IsNullVector"

**Comment by SlidyBat** [comment]
You need to compile with and use SM 1.9

**Comment by ThanhByKyTa** [comment]
thanks
