### ISSUE TITLE
Calculate points based on tiers

### ISSUE THREAD

**Issue by StrafeHack** [shavitush/bhoptimer#62]
I saw your back and forth with Techno and I have to agree that this current method is too complicated and tedious. If server owners want to use this they will have to set all maps before letting people play since if not they will get -1 for finishing. Also as you said in the readme it should be simple and this kind of isn't.

In my opinion a better solution would be to calculate the points that are given based on your position compared to how many times total, let owners set base points through a cvar then let them set a tier for a each map 1-6 that points will scale on.

Also of course having base points and defalt tier 1 will solve the default -1 point issue while making sure it can't be abused.

Edit: Also forgot to mention with this method you could also add a native to get map tier so we can use it in mapchooser, nominate and rtv so players know what they're voting for.

**Comment by shavitush** [comment]
I have already solved the -1 point issue in the `rankings` branch, didn't push to `master` yet.
I will *consider* doing tier-based rankings, I don't promise anything though!

**Comment by shavitush** [comment]
Also I'd like to note, that the system is retroactive right now.
If you set points for a map, it will recalculate the points for every record that was previously set, and the players will have their points/rank recalculated upon connection.

**Comment by StrafeHack** [comment]
Ah well that definately makes it a lot better. Good job. I'm happy with this system then

**Comment by shavitush** [comment]
:)
