### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by baferpro** [shavitush/bhoptimer#620]
Add cvar which disables this or that plugin.
Since the unloading of plugins does not work.

**Comment by strafe** [comment]
Suggested previously in #74 
What's wrong with unloading?

**Comment by baferpro** [comment]
On one map i use(mg_100traps_v4_1.cfg)
```
sm plugins load shavit-core.smx
sm plugins load shavit-zones.smx
sm plugins load shavit-wr.smx
sm plugins load shavit-stats.smx
sm plugins load shavit-replay.smx
sm plugins load shavit-rankings.smx
sm plugins load shavit-sounds.smx
sm plugins load shavit-hud.smx
sm plugins load shavit-misc.smx
sm plugins load shavit-chat.smx
sm plugins load shavit-timelimit.smx
```
On next map(mg_office_course_2013_fix.cfg)
i use
```
sm plugins load shavit-core.smx
sm plugins load shavit-zones.smx
sm plugins load shavit-wr.smx
sm plugins load shavit-stats.smx
sm plugins unload  shavit-replay.smx
sm plugins load shavit-rankings.smx
sm plugins load shavit-sounds.smx
sm plugins load shavit-hud.smx
sm plugins unload shavit-misc.smx
sm plugins load shavit-chat.smx
sm plugins unload shavit-timelimit.smx
```
but  shavit-replay.smx and shavit-misc.smx  work!
Because they will stop working only when the server is restarted.

**Comment by shavitush** [comment]
remove the .smx

**Comment by baferpro** [comment]
The console says that the plugin was successfully shut down, but there is on server no!

**Comment by baferpro** [comment]
shavitush commented 33 minutes ago
remove the .smx
--
Nothing changed

**Comment by MountFranklin** [comment]
```
sm plugins load shavit-core
sm plugins load shavit-zones
sm plugins load shavit-wr
sm plugins load shavit-stats
sm plugins unload  shavit-replay
sm plugins load shavit-rankings
sm plugins load shavit-sounds
sm plugins load shavit-hud
sm plugins unload shavit-misc
sm plugins load shavit-chat
sm plugins unload shavit-timelimit
```
Do not include .smx when using load/unload of plugins. Use the full plugin name without any file prefix.

**Comment by baferpro** [comment]
`Do not include .smx when using load/unload of plugins. Use the full plugin name without any file prefix.`
I already wrote that I did so ..
Nothing changed.

**Comment by PaxPlay** [comment]
try `sm plugins list` and unload by its id
