### ISSUE TITLE
Add a cvar, which makes you start the timer on first jump in startzone

### ISSUE THREAD

**Issue by cytrus224** [shavitush/bhoptimer#628]
sourcecode style

**Comment by Nickelony** [comment]
I actually have that done, but it's glitchy af.
It's really hard to find a good solution for this.

I'll post it later.

**Comment by shavitush** [comment]
90cd1ba53c65056714447ad8de079cae7881a080

shavit_misc_prespeed 4
shavit_core_nozaxisspeed 1
