### ISSUE TITLE
Checkpointing old replays while they are ducking causes the player to be stuck ducking.

### ISSUE THREAD

**Issue by kidfearless** [shavitush/bhoptimer#632]
Using cpmenu on replays from before the fCPDucktime update will cause the player's viewmodel to bounce up and down unless the crouch. The problem doesn't exist in newer replays and the only way to fix it is by reconnecting to the server.

**Comment by shavitush** [comment]
Can you attach an old replay that is affected by this?

**Comment by kidfearless** [comment]
https://drive.google.com/file/d/14tXxRpqoA-5HeIzEg7BQJqKkWVKmGCyf/view
bhop_easy_csgo

**Comment by rtldg** [comment]
not sure if this'll ever end up fixed but i'm attaching the replay zip in case the google drive link ever dies
[bhop_easy_csgo.zip](https://github.com/shavitush/bhoptimer/files/7001069/bhop_easy_csgo.zip)

**Comment by rtldg** [comment]
Checkpointing that old replay seems to work fine now
