### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#633]
> // Should zones be drawn as flat instead of a 3D box?
> // -
> // Default: "0"
> // Minimum: "0.000000"
> // Maximum: "1.000000"
> shavit_zones_flat "1"

Please make:
> shavit_startendzones_flat "1"
> shavit_customzones_flat "0"

Or something like that. Could use a separator for start/end zones from rest of zones, like freestyle etc.
Or just let us decide what zone should be 3d or 2d for each zone available in the timer.

**Comment by shavitush** [comment]
in zones config:
```
"flat"		"0"
```
or 1
