### ISSUE TITLE
[Request] noclip vs startzone

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#634]
Make noclip automatically disable when players enter the startzone by !r (or any other command that restart the timer, for example - style change) or flying into one, while still letting them use !nc!/p (whatever noclip command) in startzone to fly out.

**Comment by shavitush** [comment]
```sp
#include <sourcemod>
#include <shavit>

public void Shavit_OnRestart(int client, int track)
{
	if(GetEntityMoveType(client) == MOVETYPE_NOCLIP)
	{
		SetEntityMoveType(client, MOVETYPE_WALK);
	}
}
```
won't be implemented into bhoptimer itself, sorry

**Comment by Nairdaa** [comment]
Well, should be. There is no reason to keep the style inside of noclip. It just rapes the freedom of movement.

**Comment by Nairdaa** [comment]
Works like a charm and should be implemented imo. Thank you :-)
