### ISSUE TITLE
Add a native? to get the total times on a map

### ISSUE THREAD

**Issue by StrafeHack** [shavitush/bhoptimer#64]
I think it's only done once that I've seen in the !wr menu but it requires an sql query there.

When a player finishes for the first time or with a new PB I think it should be displaying their rank. e.g. "Rank: 23/157" this data could also be used on the HUD.

**Comment by shavitush** [comment]
> When a player finishes for the first time or with a new PB I think it should be displaying their rank. e.g. "Rank: 23/157" this data could also be used on the HUD.

can't happen unless i cache the whole leaderboard and just shift cells up/down when needed. according to @ofir753, his timer got a massive improvement in performance after he stopped caching and resorting the leaderboard so many times

have to deny, sorry
