### ISSUE TITLE
ERRORS IN COMPILATION OF .SP FILES

### ISSUE THREAD

**Issue by rafaluta1** [shavitush/bhoptimer#643]
Hello.. I'm getting errors in compilation from .sp files. more specific in zones and core. Does it have any fix?
shavit-zones.sp(2443) : error 017: undefined symbol "IsNullVector"

shavit-core.sp(1835) : warning 213: tag mismatch
shavit-core.sp(1835) : error 017: undefined symbol "GetGameFrameTime"

**Comment by cytrus224** [comment]
Use sourcemod 1.9. https://www.sourcemod.net/downloads.php?branch=dev
Gosh, why noone reads the wiki

**Comment by rafaluta1** [comment]
"Download the latest "stable" SourceMod release for your operating system" <- You should,instead fix this line in the wiki. :)

**Comment by Nairdaa** [comment]
> Server requirements:

Metamod: Source and SourceMod 1.9 or above installed.

**Comment by cytrus224** [comment]
1.9 is basically "stable", 1.10 is actual dev branch(master)

**Comment by rafaluta1** [comment]
I was following the wiki and when i did what was said in there, sorry my friend

**Comment by Nairdaa** [comment]
You didn't.

**Comment by cytrus224** [comment]
Edited the wiki, it says 

> 1.9 SourceMod release

 instead of "stable" 

> Sourcemod release

 now.

**Comment by rafaluta1** [comment]
OK , All compiled successfully but when I start the server I get this error:
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error

**Comment by rafaluta1** [comment]
Ok. Fixed, Thanks
