### ISSUE TITLE
Stuck in download screen

### ISSUE THREAD

**Issue by rafaluta1** [shavitush/bhoptimer#645]
When I try to enter the server it get stuck in downloading the files. the download stucks in -294132 of 0. Does someone has a fix for it?

**Comment by Technoblazed** [comment]
Not a bhop issue, welcome to csgo fastdl

The only way to fix it afaik is to enable sv_allowupload to 1, but it can have super bad consequences.

**Comment by rafaluta1** [comment]
Tryed this putting in serverstart command line and nothing changed. Who tries to enter in the server get stuck in downloading files :/

**Comment by rafaluta1** [comment]
The only way i solved it was deleting the files that were not downloading prpperly

**Comment by strafe** [comment]
Please stop making issues that aren't related to the timer, ask @ https://forums.alliedmods.net instead.
