### ISSUE TITLE
Maps using mod_zone_start can't have a custom points and have no beams.

### ISSUE THREAD

**Issue by kidfearless** [shavitush/bhoptimer#647]
I came across this on bhop_cyanglow_csgo which uses fly map zones. the origins on the maps start and end zones are not centered to the brush and cause players to become stuck in the ground when they spawn and when they use !end. You are unable to place a a custom spawn point, as it thinks there already is one. On a side note of this issue, there's no start/end zone beams for zones created this way.

**Comment by shavitush** [comment]
i can't really parse the brush model so i can't draw the zones
the other bug is a map issue. i talked to the mapper back in the day and he had the origin of the brush in the wrong spot. again there's not much i can do to parse the brush model via sourcemod
*very* late but i'm cleaning up issues
