### ISSUE TITLE
[Bug] Entering a map teleport inside the main start zone to the bonus start zone fails to correctly switch to the bonus track

### ISSUE THREAD

**Issue by pabp** [shavitush/bhoptimer#652]
A map where this is possible would be, for example, bhop_aurum_csgo. The main start zone overlaps with the tele that takes you to the bonus and the start text label correctly shows you're in a start zone standing in the bonus start, but leaving it reveals the main timer is still running. Using !b works, however. I found this using [this branch](https://github.com/shavitush/bhoptimer/commit/ea339ed6c7fb2eed26e921a5966b33b87ac283e4) though I think it's probably something I could replicate on 2.2.0 as well.

I can make a video showing what I mean if it helps.

**Comment by Nairdaa** [comment]
Use the newest branch and change the startzone position? :P

**Comment by pabp** [comment]
Yeah, happens on 2.2.0 as well. Also I was slightly wrong in the OP, the teleport to the bonus is actually outside the start zone but it still fails to switch to the bonus track once teleported.

**Comment by cytrus224** [comment]
That's how it supposed to work. Theres no issue
You should only be able to change track by command to prevent stopping your timer if you're going through another track start zone
