### ISSUE TITLE
[Request] !top{style}

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#654]
Quite alot of players play HSW/W-Only/D-Only.
Would be cool to have a command where players could compare their top rankings only for their favourite style.
eg.: 
- !topw
- !tophsw
- !topseg
- !topd
- !topa
etc.

**Comment by shavitush** [comment]
i don't like the idea of registering this many commands

unless you have a use case for it

**Comment by Nairdaa** [comment]
Then just maybe do sub-menus for !top like you have for !wr ?:-)
