### ISSUE TITLE
[ Bug ] CheckPoints still bugged :-(

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#655]
The menu doesn't respond in normal styles cp when you try saving a check point. sm_save does work and u can teleport afterwards via the menu.

However, cp withs fine for segmented style : o

Attaching a video to show exactly what I mean.
[https://www.youtube.com/watch?v=bjXOHmon4Ck](https://www.youtube.com/watch?v=bjXOHmon4Ck)

**Comment by shavitush** [comment]
update to 9d4077d4ba3d20dd232c7fbbefcaac7562b67b12

there's just no way, i literally fixed it last monday https://streamable.com/jo2mm

**Comment by Nairdaa** [comment]
But that refers only to a topleft hud bug, so I didn't even bother downloading it. How could that be related? Just asking out of curiousity, dling and updating now.
