### ISSUE TITLE
[ Request ] cvars for replays

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#659]
Something like

bot_weapon "1"/"2"/"3"

1=  usp
2 = glock
3 = no weapon

Please.

**Comment by strafe** [comment]
Why can't we have
```
bot_weapon "weapon_usp"
bot_weapon "weapon_glock"
bot_weapon ""
```
I'd also drop the `weapon_` prefix but some item classnames (at least in CS:GO) start with `item_`.

**Comment by Nairdaa** [comment]
Well sure, that works as well.
Would it be possible to use any weapon then? Like m249 for gigglez or scout.

**Comment by strafe** [comment]
Yep, any weapon or equippable item hopefully like the [Medi-Shot in CS:GO](https://i.ytimg.com/vi/NNefUwHQ07Q/maxresdefault.jpg).

**Comment by Nairdaa** [comment]
Kay, waiting forward. Also, left u a message on Discord. Not sure if you missed it, because you never answered.
