### ISSUE TITLE
[ Request ] thing about checkpoints in the segmented mode if possible

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#661]
Yes, I know you love me because of the checkpoints, shavit.

Would it be possible for you to implement an option to remember the checkpoints for lets say a minute or two after the player has left the server? Sometimes some people require a relog. On short maps it doesn't matter that much really, but imagine having to relog/disconnecting middle into benchmark or badges.

**Comment by cytrus224** [comment]
Or keep them till mapchange :P

**Comment by Nairdaa** [comment]
No, it's important to release the useless cache, not only at the map change. Imagine 300 players saving 100 cp's during the day without changing the map at all.

**Comment by shavitush** [comment]
no
