### ISSUE TITLE
[ Request ] Time played.

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#662]
Could you please add the time played on the server in !stats?
It would be awesome if you made it not count the time when the player is not actually playing (eg. not moving or spectating) and do something like

> Time played: HH:MM:SS
> Overall online: HH:MM:SS

for example

Could actually be a very nice feature in your timer to play with later on adding custom plugins, like to add some perks, like store gifts for free after reaching certain point, or points multiplier for certain time with just refering to what time played the player has and so on.

**Comment by shavitush** [comment]
i cant see how this is relevant to the bhoptimer, it's multipurpose

**Comment by shavitush** [comment]
no, functionality already exists in multiple third party plugins
