### ISSUE TITLE
[Issue] Segfault occurs on Linux TF2 server

### ISSUE THREAD

**Issue by anthonyntsc** [shavitush/bhoptimer#664]
When shavit-wr.smx is loaded, the server will segfault when a player joins. 
The segfault doesn't occur when the bhoptimer's sqlite db is deleted, but it'll happen again if the map is switched and the db is present.

I'm using bhoptimer v2.2.0 on TF2 on Ubuntu 18.04
I've tried both the release and the compiling from source

Here are the last few lines of console before the server completely exits

EDIT: This happens on both sqlite and mysql

```
Server waking up from hibernation
L 08/25/2018 - 15:46:25: "Nystrata<2><[U:1:189779379]><>" connected, address /*my address*/
Client "Nystrata" connected (23.243.149.146:27005).
L 08/25/2018 - 15:46:26: "Nystrata<2><[U:1:189779379]><>" STEAM USERID validated
L 08/25/2018 - 15:46:39: "Nystrata<2><[U:1:189779379]><Unassigned>" joined team "Blue"
./srcds_run: line 324: 15740 Segmentation fault      (core dumped) $HL_CMD
BFD: warning: /home/path/to/tf2/core is truncated: expected core file size >= 669442048, found: 1212416
Cannot access memory at address 0xf7fea924
Cannot access memory at address 0xf7fea920
Failed to read a valid object file image from memory.
Cannot access memory at address 0xf7fea924
Cannot access memory at address 0xf7fea920
debug.cmds:5: Error in sourced command file:
No function contains program counter for selected frame.
email debug.log to linux@valvesoftware.com
Sat Aug 25 15:46:39 EDT 2018: Server Quit
```

**Comment by anthonyntsc** [comment]
There really isn't any helpful info pertaining to the crash aside that I could find aside from the segfault error
Here's the full console log: https://pastebin.com/raw/sffNcRT7

**Comment by shavitush** [comment]
sorry for the delay. if this is still an issue, please report with an accelerator dump
