### ISSUE TITLE
[ Issue ] sm_save

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#665]
> [Promising] Promises : spec me
> Nairda is joining the Spectators
> [Promising] Promises : wtf is wrong
> [Promising] Promises : seg normal
> [Promising] Promises : normal?
> [ Timer ] Type !recent to check recent wrs!
> ** ♫♫ Nairda : xD
> ** ♫♫ Nairda : cus practice
> [Promising] Promises : same run
> ** ♫♫ Nairda : as i said
> ** ♫♫ Nairda : reset checkpoints
> ** ♫♫ Nairda : and !seg
> [Promising] Promises : i di
> [Promising] Promises : did
> [Promising] Promises : 3times now
> [Promising] Promises : ive still the normal cp
> [Promising] Promises : i reset it but have still the last normal cp
> [Promising] Promises : do u use save checkpoint or sm_save
> ♫♫ Nairda : save
> ♫♫ Nairda : i dont sm_save
> [Promising] Promises : ye bug is in sm_save

It basically switches to Practice Segmented Normal with sm_save.

I beg you man, please fix the cp finally :p

**Comment by shavitush** [comment]
fixed bruv
