### ISSUE TITLE
Better weapon clean up for csgo and css

### ISSUE THREAD

**Issue by StrafeHack** [shavitush/bhoptimer#67]
I think it's still a good idea to include weapon cleaning in the timer itself, if you don't agree fair enough.
This works well for me when players drop weapon and when they die or suicide, it also obviously allows you to leave map weapons in.

public void OnClientPutInServer(int client)
{
	SDKHook(client, SDKHook_WeaponDrop, OnWeaponDrop);
}

public void OnWeaponDrop(int client, int weapon)
{	
	if(IsValidEntity(weapon))
		AcceptEntityInput(weapon, "Kill");
}

**Comment by shavitush** [comment]
I agree. I'm currently working on `shavit-chat` though so I'll have to implement it later :)

**Comment by StrafeHack** [comment]
Fair enough, I'm more excited for chat anyway :)

**Comment by shavitush** [comment]
🎉
