### ISSUE TITLE
[ Request ] Show prespeed in replay

### ISSUE THREAD

**Issue by Uronic** [shavitush/bhoptimer#672]
I was wondering if it was possible to see the player prespeeding at the start of each run when replaying their runs.

**Comment by Nairdaa** [comment]
I'd love that as well.

**Comment by Uronic** [comment]
Now that i think about it this would probably require a db and repla file reset because i dont think the replay thing records the prespeed atm

**Comment by shavitush** [comment]
i can mark replays to have this without breaking backwards compatibility

**Comment by Uronic** [comment]
oh nice xd

**Comment by Nairdaa** [comment]
nice! can't wait :)

**Comment by kidfearless** [comment]
Implemented in 44a6b1646f823ee3cab794d2d3b6e057179d8d34
