### ISSUE TITLE
[ Request ] Show tier in hud

### ISSUE THREAD

**Issue by Uronic** [shavitush/bhoptimer#675]
Imo, I think it would be better if the tier would appear in the hud instead of having to type !tier in chat, there is space in the hud i think

**Comment by Nairdaa** [comment]
On the right side of the hud imo.

**Comment by Uronic** [comment]
Aka why I said there is space in the hud

**Comment by Nairdaa** [comment]
> Big -1 from me. The HUD should be reserved for dynamic information, not static info that changes on a per-map basis. HUD clutter should be reduced as much as possible.
> 
> A better solution would be printing the map tier to chat on player's first spawn - you don't need to constantly look at your hud and remind yourself of the tier.

Somehow there is still static info like current wr etc at the top left hud. Your solution is not better, because people barely keep attention to chat usually, especially right after they spawn. It would be better to just stick to !tier with your idea.

**Comment by sneak-it** [comment]
> Somehow there is still static info like current wr etc at the top left hud. Your solution is not better, because people barely keep attention to chat usually, especially right after they spawn. It would be better to just stick to !tier with your idea.

WR is not static, it is whatever the current record is. That could change at any time. Map tiers do not change, therefore static.

I think there is a disconnect with the word 'HUD' - perhaps OP should clarify. Most people usually consider the "HUD" the hint section, seems like what you are referring to is the game_text.

**Comment by strafe** [comment]
`game_text` is a point entity, the timer's top-left HUD doesn't use that, it uses SourceMod's `Show(Sync)HudText` which I believe internally uses the `HudText` usermessage.

Personally I'm not opposed to showing the tier in the top-left HUD as its dedicated to information that doesn't update as often, but please don't add infrequently used data to the center HUD.

**Comment by Nairdaa** [comment]
> `game_text` is a point entity, the timer's top-left HUD doesn't use that, it uses SourceMod's `Show(Sync)HudText` which I believe internally uses the `HudText` usermessage.
> 
> Personally I'm not opposed to showing the tier in the top-left HUD as its dedicated to information that doesn't update as often, but please don't add infrequently used data to the center HUD.

Adding tier there is spam imo ;-p I mean the only place to see the actual map tier would be somewhere above the actual timeleft, wich is the right hud.

**Comment by e-slut** [comment]
Just add the tier to the hud while you're in the start zone useless while running a map

**Comment by Uronic** [comment]
Yea thats a good idea
