### ISSUE TITLE
[Request] Disable Autobhop CVAR or Style Per Map

### ISSUE THREAD

**Issue by LagMyAss** [shavitush/bhoptimer#677]
Hey, im running a multigamers server and i have to disable autobunnyhop on some maps. I'd love if it could be added an **OPTIONAL** Cvar that disables autobunnyhop(there was on previous versions of the timer) or configure styles per map.

**Comment by Cruze03** [comment]
Just make scroll the default style and remove normal style

**Comment by LagMyAss** [comment]
instead of the cvar, can you make it to check if "autobhop" string exists on config, if not follow server settings?

**Comment by strafe** [comment]
> instead of the cvar, can you make it to check if "autobhop" string exists on config, if not follow server settings?

That's not backwards compatible, could add a third value like `-1` to follow the server's setting.

**Comment by LagMyAss** [comment]
yes ok, let it be :D

**Comment by shavitush** [comment]
use case is not for bhop servers and breaks the concept of styles being universal regardless of maps
won't be added, sorry
