### ISSUE TITLE
Recent Records and ranks not showing up.

### ISSUE THREAD

**Issue by Weeeishy** [shavitush/bhoptimer#68]
Hello Shavit,

Recently I've moved to a new host and I've used the same database however I cleared all of the tables except mapzones. But for some reason the web page isn't showing the recent records even though I see the records on the playertimes on my database. I'm using the same database for both database.cfg and config.php and it used to work fine on the old host, not sure what happened. The other thing about ranking is that it's not giving the players any points, and it shows unranked even after finishing new maps.

One thing I know for sure that the server is connecting to the database since its logging all of the new records, but not the points or other stuff. Same for web interface, it's not picking up any records.

I'm using the latest commit which is **cf4d528**
Database.cfg

```
	"shavit"
	{
		"driver"			"mysql"
		"host"			"185.62.188.4"
		"database"			"khaleeji_shavit"
		"user"			"khaleeji_shavit"
		"pass"			""
	}
```

config.php

```
// ip address to the mysql server
define('DB_HOST', '185.62.188.4');

// mysql username
define('DB_USER', 'khaleeji_shavit');

// mysql password
define('DB_PASSWORD', '');

// mysql database (schema) name
define('DB_SCHEMA', 'khaleeji_shavit');
```

EDIT: I did a clean install with the latest SM and different database, and still same results.

**Comment by shavitush** [comment]
is 185.62.188.4 hosted locally?
do you get any error logs?

**Comment by Weeeishy** [comment]
It's not hosted on the same server. I see, if that's the case then thank you. :)
