### ISSUE TITLE
[ Request ] Show replay info in replay hud

### ISSUE THREAD

**Issue by Uronic** [shavitush/bhoptimer#680]
Basically what I mean is when a replay is played, in the hud it would show things such as the sync, the strafes, amount of jumps, and maybe in chat it would also print to client the ssj of the replay too.

**Comment by shavitush** [comment]
unfortunately it is way too much data and due to limitations with sourcemod (only having one kind of data type being `cell_t` at 4 bytes) we cannot do this without running out of memory
