### ISSUE TITLE
[ Issue ] Disappearing CP menu :-(

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#696]
https://www.youtube.com/watch?v=6J7BqP4N8IU

The menu just disappears for a while making it unavailable for use for a couple sec (sometimes disappears forever, and you gotta !cp again.).

I've absolutely no idea what's causing it. I've heared it happen before for people without an admin, like an anti-flood check, but I double checked I'm a 99:z flag admin, wich ignores the SM's flood thing. No lag on my end either.

I was spamming "2" the entire time it was not visible, got instantly teleported the moment the menu showed up on itself again.

**Comment by shavitush** [comment]
packet loss

**Comment by rtldg** [comment]
late update comment: this was "fixed" for the segmented checkpoint menu by making it also reopen every 0.5s in `v3.0.5` / https://github.com/shavitush/bhoptimer/commit/aa78c6fc0edf134ec296d2038e82157f02d1975c

**Comment by Nairdaa** [comment]
late closed thread comment: This was never a packet loss issue.

**Comment by rtldg** [comment]
late replay: it is
