### ISSUE TITLE
Low Gravity Short Jump 

### ISSUE THREAD

**Issue by guyzin** [shavitush/bhoptimer#697]
I was setting up my styles and I realized that low gravity is jumping low, usually on other bhop servers with shavit I can get it
890/880 ssj, and in mine I can not 850 :(

Sorry, I'm using google translate

		"name"				"Low Gravity"
		"shortname"			"LG"
		"htmlcolor"			"DB88C2"
		"command"			"lg; lowgrav"
		"clantag"			"LG"

		"gravity"			"0.6"

		"unranked"			"0"
		"rankingmultiplier" "1.30"
		"runspeed"			"260.00"

**Comment by Nairdaa** [comment]
What game? CSS or CSGO? And are you sure the tickrate is correct?

**Comment by guyzin** [comment]
Csgo, yeap, 1000

**Comment by Uronic** [comment]
> 
> 
> Csgo, yeap, 1000

1000 tickrate? r u sure you're not referring to your sv_airaccelerate and not tickrate

**Comment by guyzin** [comment]
'-' airaccelerate 100, tickrate 128

**Comment by Nairdaa** [comment]
Have you tried my settings?

**Comment by guyzin** [comment]
yes nairdaa


and my scroll is in trouble, auto bhop is enabled on it :(

if you can help me <3

**Comment by Nairdaa** [comment]
Did you fix LG with my settings or not? Give me the IP of your server please and send the scroll settings as well.

**Comment by Nairdaa** [comment]
Just join the official timer's discord and poke me there, easier to have a chat, rather than answering here.
https://discord.gg/zJa5WE
