### ISSUE TITLE
Percentage Based Rankings

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#70]
As it stands at the minute, this chat would do, i.e:

1 -> Master
2-5 -> Pro
7-15 -> Semipro Etc.

The percentage based system would be more along the lines of,

1 -> Master
Top 1% -> Pro
Top 2-5% -> Semipro etc.

Where the % is the top of all players that use the server.

**Comment by shavitush** [comment]
Should the "top of all players that use the server" be the amount of players who ever played, or only players who have at least one ranked time?

**Comment by Technoblazed** [comment]
If a client has points, they should be considered as a client :D

**Comment by Technoblazed** [comment]
This doesn't even seem that purposeful anymore :D

**Comment by shavitush** [comment]
welp
