### ISSUE TITLE
[Feature Request] Have option to print a player's prespeed in chat

### ISSUE THREAD

**Issue by mbhound** [shavitush/bhoptimer#703]
There should be a togglable option to print a player's prespeed on their first jump. This would be very useful since your prespeed can determine how well of a run you get and can allow players to optimize their runs.

**Comment by Uronic** [comment]
#672

**Comment by cytrus224** [comment]
Just use ssj 🤔

**Comment by Nairdaa** [comment]
> SSJ is completely separate from recording & printing the speed when leaving the start zone. If WR leaves start zone 50 units faster on a 15 second map, that's a massive difference and you could end up wasting your time without proper prespeed.

You can just edit the ssj settings to print speed on every jump and it will print the speed on 1st jump too (prespeed).

**Comment by shavitush** [comment]
@Nairdaa it's not what he's asking

**Comment by strafe** [comment]
If this is for bots it's covered by #672, if not use an SSJ plugin that supports first jump speed.

**Comment by Nairdaa** [comment]
> @Nairdaa it's not what he's asking

That's exactly what he's asking in OP.

**Comment by mbhound** [comment]
@Nairdaa I'm just asking for the first jump,not every jump.
@strafe  not for bots, live as a person trying to bhop

**Comment by strafe** [comment]
@mbhound use SSJ then.

**Comment by sneak-it** [comment]
How about for prespeed leaving the start zone? That would make more sense, and is common in surf to know when you have the potential to have a wr run.

**Comment by Nairdaa** [comment]
https://paste.ofcode.org/nRG9srzgnUHYbHZ3uwapiT

just use only the prespeed setting.

**Comment by mbhound** [comment]
At the same time?

**Comment by strafe** [comment]
> At the same time?
Yes, prespeed is a separate setting in the menu. Just install the plugin and try it
