### ISSUE TITLE
[ Request ] Maps left/done thing

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#704]
Hey,

1. Could you please add !mapsleft / !mapsdone commands so we don't have to !stats -> style -> mapsleft/mapsdone from there?
2. Add maptier next to map name in the menu.
3. When clicking the number in menu of the map name -> auto nominate and show wr's menu of the map, instead of going back to the !stats menu.

**Comment by shavitush** [comment]
3 will not be added because it is not universal. people may use different mapchooser/nomination plugins and i rather not have more dependencies

rest will be added :)
