### ISSUE TITLE
[Feature Requests] Replay Improvements

### ISSUE THREAD

**Issue by kidfearless** [shavitush/bhoptimer#705]
1. Add a convar to save #2 times in case of record deletion.

2. ~~When someone finishes a run check to see if their time is better than the current replay, and if there isn't one then add their run as the replay.~~ edit by shavIt: added

3. If the replay doesn't have a matching record to go with it then delete the replay file(new format only).

4. ~~Players who start the replays being able to stop the bot.~~ edit by shavit: added

The third one is more of a way to deal with these:  #602 #667 #568

**Comment by shavitush** [comment]
1 will not be implemented because i want to spare disk space

3 is unnecessary because the mentioned issues are closed, closing this!
