### ISSUE TITLE
[ Request ] "Finished a map" on scroll - chat message

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#706]
> [ Timer ] [Bonus] You have finished (Scroll) in 25.760 with 36 jumps, 102 strafes @ 90.42%. (+2.530)

Hey, Could you please add % perf ratio of the run after jumps, just like you have sync after strafes?

eg.

> [ Timer ] [Bonus] You have finished (Scroll) in 25.760 with 36 jumps (50%), 102 strafes @ 90.42%.(+2.530)

**Comment by Nairdaa** [comment]
#656 HA ! touché

**Comment by shavitush** [comment]
it makes the message very long and imo it is not fitting very well. you can see the perfect jumps in !wr
