### ISSUE TITLE
Using WR as the ideal server time and calculate points from there

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#71]
If the WR was used as the ideal time, the points  could be awarded based off of a set config option, this would mean that there would be no need to visit each map to add a time and points value. However to reduce sql strain, the update could be completed on map completion, or personal refresh by the user, updating their points to the correct value.

**Comment by shavitush** [comment]
As for now, re-calculating a whole map with around 1000 records in total (across all styles) takes around 1.5 minutes on my server (newest MariaDB, [MC-128 from OVH](https://www.ovh.com/us/dedicated-servers/game/)).

Sadly I won't implement it unless we find a better method to update multiple rows with the least queries possible. SourceMod's MySQL driver won't allow me to use a semicolon to distinguish between two queries in one call.

I'll keep this issue open for now, maybe someone knows a better solution!

**Comment by mathiaas** [comment]
Would for sure appreciate automatic calculation of the points and average/ideal time.

A lot of hassle to go through setting points for all the maps. (especially since you need to take the records (ideal time) into consideration)

**Comment by shavitush** [comment]
I agree about only the need to set points for maps instead of also time, but as I said I can't think of any method that cam update sooo many rows efficiently enough

**Comment by mathiaas** [comment]
Perhaps using SQLs "AVG" to get the average time from all records per map then calculate the points that you should receive out of that.

**Comment by shavitush** [comment]
As a very competitive bhop player (I'm not just a developer :D) I think that this isn't a correct way to calculate points, and it still doesn't solve the issue of executing so many queries (up to 20k in some cases) when someone gets a new WR.

**Comment by Technoblazed** [comment]
Having just finished zoning 360 maps, I'm now stuck with the issue of having no idea of ideal times D:

**Comment by Technoblazed** [comment]
Would an alternative option just be to have the ability to set a predefined points to get for beating a map, with the points for styles specified in the shavit.inc as they currently are, and then change this again in the future?

**Comment by shavitush** [comment]
i disagree about this solution

**Comment by Technoblazed** [comment]
As a temporary solution rather than have to add ideal times to each map, would it be possible to be able to set points for each style that is beaten, a default value, i.e. 50 points for each style completed, which then takes in the points values in the shavit.inc . Ideal times can't really be set easily and there hasn't been a suitable replacement from this post.

**Comment by shavitush** [comment]
i actually started thinking about a way that will do what i want within a single query, just need to write the query itself and see if it works with sqlite too because it's a bit complex

i'll try doing it within the next hours (if i don't fall asleep, it's 6:30am ;_;)

**Comment by shavitush** [comment]
easier than expected!
![firefox_2016-08-03_07-05-26](https://cloud.githubusercontent.com/assets/3672466/17353480/b81d6194-5948-11e6-8b58-6d06acf2e613.png)

is there any objection about a system that updates every time on the map within one query, to be time% of the mappoints set and deprecate 'ideal times'?

**Comment by Technoblazed** [comment]
Hmm, another cool feature, would be to have cvars, or even just code them  into the shavit.inc similar to the similar points gain, to set a value for the points gained based on tier, and then a fallback value if no tier is set.

**Comment by shavitush** [comment]
I'm not sure if you understood; but this system I suggested is basically -
1. Set points for a map.
2. Points for all players update automatically, no need to waste time deciding on ideal time.

So you don't even need to decide a tier

**Comment by Technoblazed** [comment]
That'd be one way, I'd probably end up just setting points based on how they're tiered though :D

**Comment by shavitush** [comment]
I see! I'll start implementing it soon 👍

**Comment by Technoblazed** [comment]
:D :+1:

**Comment by StrafeHack** [comment]
Yep this is awesome glad you figured it out, I would like the points based on tiers within a config aswell rather than setting each map alone.

It's already hard enough to decide between 1 to 6 nevermind thinking of a point value

**Comment by shavitush** [comment]
so i could set a cvar like shavit_rankings_points which would set points to be (cvar value * tier) in relation to the time and wr?

**Comment by StrafeHack** [comment]
Yep that sounds perfect, and I think make it so all maps default to Tier 1 if that's not in already

**Comment by Technoblazed** [comment]
Maybe not cvar value * tier, seems a bit steep. But a value inside shavit.inc, similar to how you have the current increases per rank. I.e. 1x for tier 1, 1.5x tier 2 etc. Value * 6 would be pretty insane.

**Comment by StrafeHack** [comment]
^ Yes I like that

**Comment by Technoblazed** [comment]
@StrafeHack Out of curiosity, what points do you give for your styles?

**Comment by StrafeHack** [comment]
I don't use the rankings or chat plugins because I'm just using this for lan runs but I still like the idea of this replacing API Timer completely since that just causes people problems.

If I was to though, I would choose 1.0 for normal styles like Auto and Scroll.
1.5 for odd styles like W, SW, and HSW
and 0.5 for fun styles like LG and SM

**Comment by Technoblazed** [comment]
I use api timer on my old server, day by day, the plugin slowly gets worse and worse lol

**Comment by shavitush** [comment]
Yeah so I'm really close to finishing the new ranking system that is also based on tiers.

**Comment by Technoblazed** [comment]
@shavitush did you just delete a comment o.O

**Comment by shavitush** [comment]
@Technoblazed yeah i didnt finish writing and tapped ctrl+enter

**Comment by Technoblazed** [comment]
ah lol, I'll let you finish

**Comment by shavitush** [comment]
So I'm really close to finishing the new algorithm that is also based on tiers and WR time instead of an 'ideal time' set; so far this is the only thing I'm sure is missing -

This query is updating the whole users table and sets their points to `STEAMID_HERE`'s sum of points within one query, instead of doing around 250k queries in total: it's just one that runs in under 0.10 seconds so it's super nice. It only works with MySQL but it's really worth it, so we don't get people with high amounts of points there even if we delete their records.
```
UPDATE users SET points = (SELECT SUM(a.pts) ptssum
FROM (SELECT (points * (@f := 0.95 * @f) / 0.95) as pts
FROM playertimes t CROSS JOIN
     (SELECT @f := 1.0) params
WHERE auth = "STEAMID_HERE" AND points > 0.0
ORDER BY points DESC) a);
```

The thing is, it uses `STEAMID_HERE`'s point values instead of `auth` from the current `users` row.

My attempt on fixing it was to assign the letter `u` to `users`, and then do `WHERE auth = u.auth` but it didn't work:

```
 #1054 - Unknown column 'u.auth' in 'where clause'
```

So yeah this is the only thing that keeps us away from it. If any of you know how to do that let me know please; I'm not really good with SQL so it's quite confusing..

**Comment by Technoblazed** [comment]
I've got someone that might be able to help, but people that still use sqlite are old school anyway :dancer:

**Comment by shavitush** [comment]
It doesn't break anything, not even for SQLite users but it indeed is useful if it's a success, and I hope it is.

**Comment by Technoblazed** [comment]
I have someone that does sql for a living, should be online shortly

**Comment by Technoblazed** [comment]
Ok, so here you have `auth = "STEAMID_HERE"` you want `auth = u.auth`

**Comment by shavitush** [comment]
Yeah, that's the finalized query when it's like that:

```sql
UPDATE users u SET points = (SELECT SUM(a.pts) ptssum
FROM (SELECT (points * (@f := 0.95 * @f) / 0.95) as pts
FROM playertimes t CROSS JOIN
     (SELECT @f := 1.0) params
WHERE auth = u.auth AND points > 0.0
ORDER BY points DESC) a);
```
```
 #1054 - Unknown column 'u.auth' in 'where clause'
```

**Comment by Technoblazed** [comment]
I'll get back to you when I've got an answer

**Comment by Technoblazed** [comment]
Thanks for ^

**Comment by Technoblazed** [comment]
@shavitush Your `u` for users is being specified outside of your subquery. You'd have to use `users`. instead.

**Comment by shavitush** [comment]
I ended up doing it with a pretty messy way. It works, slowly! But it works :)
I didn't test it with more than one player in my server so it might not work as expected, feedback would be needed and I'm really tired of this rankings system, might just leave it like that because so far it's more fair and competitive than the rest.

Will push the update in a few moments.

**Comment by shavitush** [comment]
Use `sm_settier` to set the map's tier.

**Comment by shavitush** [comment]
Will close this issue for now; poke me on #71 for feedback
