### ISSUE TITLE
Chat colors only in spectate?

### ISSUE THREAD

**Issue by zeddy1234** [shavitush/bhoptimer#712]
Hey, the player chat names / message colors only show when a player is spectating.

When you're not in spectate, its team colors and normal message colors only. [I have not made any mistakes with my config file , shavit-chat.cfg]

Any idea why this is happening?

**Comment by Nairdaa** [comment]
pastebin.org and show us your shavit-chat.cfg please.

**Comment by zeddy1234** [comment]
https://pastebin.com/pfsMhCpf

I tried with default shavit config as well.
Only see colors when players are spectating.

**Comment by Nairdaa** [comment]
Are you using any chat processor?

**Comment by Nairdaa** [comment]
https://github.com/shavitush/bhoptimer/releases/tag/v2.2.0

> Wrote a new chat processor for bhoptimer.
Uninstall any other chat processor you have installed.

**Comment by zeddy1234** [comment]
Nope, no chat processor. Do I need to have any custom extensions for this to work or something?

**Comment by shavitush** [comment]
can i have your plugins list and error logs if there are any?

**Comment by zeddy1234** [comment]
"Admin File Reader" (1.9.0.6269) by AlliedModders LLC
 "Admin Help" (1.9.0.6269) by AlliedModders LLC
 "Admin Menu" (1.9.0.6269) by AlliedModders LLC
 "Anti-Flood" (1.9.0.6269) by AlliedModders LLC
 "Basic Ban Commands" (1.9.0.6269) by AlliedModders LLC
 "Basic Chat" (1.9.0.6269) by AlliedModders LLC
 "Basic Comm Control" (1.9.0.6269) by AlliedModders LLC
 "Basic Commands" (1.9.0.6269) by AlliedModders LLC
 "Basic Info Triggers" (1.9.0.6269) by AlliedModders LLC
 "Basic Votes" (1.9.0.6269) by AlliedModders LLC
 "Client Preferences" (1.9.0.6269) by AlliedModders LLC
 "CS:GO Movement Unlocker" (1.0) by Peace-Maker
 "Fun Commands" (1.9.0.6269) by AlliedModders LLC
 "Fun Votes" (1.9.0.6269) by AlliedModders LLC
 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
 "Mapchooser Extended Sounds" (1.10.2) by Powerlord
 "MPBH" (1.0) by DaFox, petsku & Zipcore
 "Nextmap" (1.9.0.6269) by AlliedModders LLC
 "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
 "Panorama - Timeleft" (1.0.0) by Fastmancz
 "PermaMute" (0.1) by Ryan "FLOOR_MASTER" Mannion
 "Player Commands" (1.9.0.6269) by AlliedModders LLC
 "Reserved Slots" (1.9.0.6269) by AlliedModders LLC
 "Rock The Vote Extended" (1.10.0) by Powerlord and AlliedModders LLC
 "Say Sounds (including Hybrid Edition)" (4.0.8) by Hell Phoenix|Naris|FernFerret|Uberman|psychonic|edgecom|woody|Miraculix|gH0sTy
 "sbp.smx" sbp.smx
 "Server Advertisement" (2.4b) by ESK0
 "[shavit] Chat Processor" (2.3.5) by shavit
 "[shavit] Core" (2.3.5) by shavit
 "[shavit] HUD" (2.3.5) by shavit
 "[shavit] Miscellaneous" (2.3.5) by shavit
 "[shavit] Rankings" (2.3.5) by shavit
 "[shavit] Replay Bot" (2.3.5) by shavit
 "[shavit] Sounds" (2.3.5) by shavit
 "[shavit] Player Stats" (2.3.5) by shavit
 "[shavit] Dynamic Timelimits" (2.3.5) by shavit
 "[shavit] World Records" (2.3.5) by shavit
 "[shavit] Map Zones" (2.3.5) by shavit
 "Show Triggers" (1.1) by ici
 "Slope Landing Fix" (1.2) by Mev & Blacky
 "Sound Commands" (1.9.0.6269) by AlliedModders LLC
 "SSJ: Advanced" (1.4.1) by AlkATraZ


L 12/17/2018 - 12:06:02: [SM] Unable to load extension "outputinfo.ext": The specified module could not be found.


L 12/17/2018 - 12:06:02: [SM] Unable to load extension "soundlib.ext": The specified module could not be found.


L 12/17/2018 - 12:06:02: [SM] Unable to load plugin "boosterfix.smx": Required extension "OutputInfo" file("outputinfo.ext") not running
L 12/17/2018 - 12:06:02: [SM] Unable to load plugin "saysounds.smx": Required extension "Sound Info Library" file("soundlib.ext") not running
L 12/17/2018 - 12:06:02: [SM] Unable to load plugin "selfMute.smx": Could not find required plugin "voiceannounce_ex"

Fixed the last 2 errors now, none of these seem to be it though.

**Comment by zeddy1234** [comment]
Its a basic plugin that blocks sm plugins command. Disabling it didn't change anything. Is there any server currently using the plugin where colors are working? Any IP?

**Comment by Nairdaa** [comment]
> "Say Sounds (including Hybrid Edition)" (4.0.8) by Hell Phoenix|Naris|FernFerret|Uberman|psychonic|edgecom|woody|Miraculix|gH0sTy

Try disabling that, it has chat hooks in it
