### ISSUE TITLE
Map restart?

### ISSUE THREAD

**Issue by zeddy1234** [shavitush/bhoptimer#717]
Hey, the map randomly restarts once every map

I've set ignore round conditions 1 ,and it happens only on bhop server, when someone joins a certain team, everyone gets reset and maptime resets to full as well. Is this a common bug? I've checked my plugins and settings, doesn't seem to be it.

**Comment by Nairdaa** [comment]
mp_autoteambalance "0"

**Comment by shavitush** [comment]
inactive issue. @zeddy1234 reopen this if you still have the issue and can provide info to troubleshoot it better
