### ISSUE TITLE
[ Request ] So there is timeleft...

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#718]
Could we please have a !timedone or something like that to see how long a map has been on? I mean ofc, you can refer from mp_timelimit (hi, hud!) etc, but it can be dynamic (hi, timer svar!) + people sometimes extend the map limit.

**Comment by shavitush** [comment]
timeleft is a sourcemod feature hello

no

use !maptime https://forums.alliedmods.net/showthread.php?p=1618015

**Comment by Nairdaa** [comment]
Thanks alot.

**Comment by Nairdaa** [comment]
But it's a CSGO plugin, I main CSS ;;

**Comment by shavitush** [comment]
it works for css

**Comment by Nairdaa** [comment]
Ya just took a look at the code. Thanks man.
