### ISSUE TITLE
!ranks showing message after response.

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#72]
https://gyazo.com/7da37a4a05dde731c9724818c7f22042

As you can see, the "List of chat ranks:" appears after the response, is this intentional?

**Comment by shavitush** [comment]
It isn't actually, from what I see, it happens every once in a while, not always.

I can probably fix it by sending the "List of chat ranks:" message with SayText2. I'll do it soon!

**Comment by Technoblazed** [comment]
Thanks :D

**Comment by Technoblazed** [comment]
Another issue:

https://gyazo.com/48a3ed631c1ee2a85327f5c48e6efc69

`"[U:1:181992512]" // my steamid for example, use steamid3
    {
        "prefix"        "{default}[{orchid}MANAGER{default}]"
        "name"          "{default}{team}{name}"
    }`

**Comment by shavitush** [comment]
it's fine, prefixes are limited to 32 characters
you might want to remove the {default} from the beginning

**Comment by Technoblazed** [comment]
Didn't know of the restriction, thanks :D

**Comment by shavitush** [comment]
argh don't close it, i need to fix the chat ranks command issue
