### ISSUE TITLE
[ Request ] Replay rewind/fastforward

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#722]
Could admins get some extra buttons in the replay menu to fastforward a replay or rewind the replay abit?

Like jump 1 sec forward or rewind by 1 sec.

**Comment by rtldg** [comment]
added this and changed the menu up a bit in https://github.com/shavitush/bhoptimer/commit/a2735d8a2a322d6cb25d0617c49ee9563e3a3be9
