### ISSUE TITLE
Sharing replaybots between servers

### ISSUE THREAD

**Issue by Intellectualism** [shavitush/bhoptimer#723]
I understand you can set a specific location to save and load bots from, But I was wondering how can some achieve having to separate servers save and load bots from the same folder? I have see this done with Uninspired Gaming's public and test server. If both servers and on same map, And you get a record on the test server it will change on public along with showing the record bot on that server.

**Comment by cytrus224** [comment]
Its pretty easy. Host them on a single machine. https://github.com/theSaint92/shavit-uniquemap

**Comment by shavitush** [comment]
use symbolic links or sync the files and follow @cytrus224's advice
