### ISSUE TITLE
[Bug?] Zone teleportation in spectators

### ISSUE THREAD

**Issue by 2x9Mon** [shavitush/bhoptimer#724]
I found out that you can actually tp to zones in spectators, using free cam.
I don't know if it's a bug or a cool feature, but looks odd, lol.

**Steps to represent:**

1. Go to spectators
2. Change your view to a **Free Cam**
3. Type !r or !b in chat
4. It actually teleports you to one of the zones

**Comment by shavitush** [comment]
intentional, change `shavit_misc_respawnonrestart` if you don't like the behavior
