### ISSUE TITLE
[ Request ] Sync in replay hud

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#727]
Hey, could we get something like final avg sync of the run in in the right hud?

![image](https://user-images.githubusercontent.com/38843773/51642140-8d592400-1f68-11e9-926c-fa660bceafd9.png)
Like not here but where the spec list is?

i know of https://github.com/shavitush/bhoptimer/issues/680 but yea, just reminding.

**Comment by shavitush** [comment]
sourcepawn doesn't allow us to have types of less than 4 bytes (`char` excluded iirc) so we're running out of memory very quickly if i add more data per frame. end goal to extend replays is some day, write a c++ extension to handle frames. i can't do this atm nairda, sorry
