### ISSUE TITLE
[Bhop Style] TAS?

### ISSUE THREAD

**Issue by normalamron** [shavitush/bhoptimer#728]
Hi guys. I want play tas style. Influx is so bad. btimes is expensive. Will tas style come?

**Comment by Nairdaa** [comment]
Shavit's been working on it. It's definitely comming, altho no1 knows when.
Soon™

**Comment by shavitush** [comment]
will take a while, i'm unable to work on the plugin for a while (dev will resume in late february) and tas isn't finished

**Comment by blankbhop** [comment]
@normalamron bTimes2 has been leaked already, there's no point in contemplating buying it.

**Comment by normalamron** [comment]
@blankbhop https://forums.alliedmods.net/showthread.php?p=2578206
I tried but it didn't work

**Comment by strafe** [comment]
@normalamron that is not bTimes 2, it's a fork of 1.8.3 — [you can find 2 here](https://github.com/blankbhop/btimes).

**Comment by shavitush** [comment]
yall
