### ISSUE TITLE
Problem with autbh (speed)

### ISSUE THREAD

**Issue by MynDoS** [shavitush/bhoptimer#729]
Hello
I have problem with shavit, because if I delete all plugins shavit, speed on server work fine, but if I add shavit_core and other plugins, autobh work like that
My server with shavit:
https://www.youtube.com/watch?v=rodw0B0XiTU

The server on which it works well: 
https://www.youtube.com/watch?v=4fH4bH0mZak

So, my server block speed when player jump and he is on the ground (check "vel" -> velocity)

**Comment by shavitush** [comment]
get "csgo movement unlocker"

**Comment by MynDoS** [comment]
This https://forums.alliedmods.net/showthread.php?t=255298?
If yes, i check this plugin and it doesn't work :/

**Comment by Nairdaa** [comment]
I noticed jump lag.

sv_autobunnyhopping 1

It's that.

**Comment by Nairdaa** [comment]
¯\_(ツ)_/¯

**Comment by shavitush** [comment]
@MynDoS a bit late.. but can i get your plugins list?
