### ISSUE TITLE
A few things you need to do before the official 1.5 release.

### ISSUE THREAD

**Issue by Nickelony** [shavitush/bhoptimer#73]
1. Block the radio commands, because people are just spamming them like retards and there is no reason to keep them.
2. Disable blood decals since it's even more useless than the radio commands and I think you know how awful the map looks like after a PERIOD of time. :>
3. Add Slowmotion and LowGravity styles, because everyone's waiting for it.

**Comment by shavitush** [comment]
for the no blood thingy just use this plugin https://forums.alliedmods.net/showthread.php?t=282918
