### ISSUE TITLE
Zone Line

### ISSUE THREAD

**Issue by normalamron** [shavitush/bhoptimer#733]
Can i change zone line ?

**Comment by strafe** [comment]
You can edit the zone sprite in `addons/sourcemod/configs/shavit-zones.cfg`.

**Comment by normalamron** [comment]
@strafe I didnt mean that. Can it look btimes zones or another

**Comment by Nairdaa** [comment]
@normalamron Yes, you can edit the zone sprite in `addons/sourcemod/configs/shavit-zones.cfg`.
