### ISSUE TITLE
After Deleting Records

### ISSUE THREAD

**Issue by IAmSadIAm** [shavitush/bhoptimer#734]
Whenever you delete a record, you aren't allowed to select the style again when spectating the replay bot. Is there a way to fix this?

**Comment by shavitush** [comment]
no, when you delete the record the replay is also deleted

**Comment by IAmSadIAm** [comment]
I know the record and replay gets deleted, but the record and replay behind
the first one isn’t playable through the replay bot.

**Comment by Nairdaa** [comment]
Because there is no replay to be replayed. The file gets overwritten with every new wr.
