### ISSUE TITLE
[Suggestion] Have seperate chat message when there is no bonus start zone

### ISSUE THREAD

**Issue by mbhound** [shavitush/bhoptimer#735]
Instead of have the user getting a message that the start zone has not been zoned, a more user friendly message could be made such as "there is no bonus on the map" if so desired.

**Comment by Uronic** [comment]
can't you just change the translations in shavit-core.phrases.txt lmao

**Comment by mbhound** [comment]
I'm saying for there being no bonus start zone and no main start zone to display different messages instead of the same one. I didn't see them as separate.

**Comment by mbhound** [comment]
"StartZoneUndefined"

	{

		"#format"	"{1:s},{2:s}"

		"en"		"Your timer {1}will not{2} start as a start zone for the map is not defined."

	}

i.e. split this into two one for main track and one for bonus
