### ISSUE TITLE
[Request] Mark trigger as start/end zone

### ISSUE THREAD

**Issue by kidfearless** [shavitush/bhoptimer#736]
It would be nice to be able to mark certain teleport/trigger brushes as different zones for the map.

**Comment by whocodes** [comment]
I believe what you're asking is for the ability to make a pre-existing `trigger_multiple` usable as start/end zone? If so:

https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/shavit-zones.sp#L684

You can do this by giving the triggers custom names when creating the map. I believe you should also be able to assign these names to the triggers using Stripper: Source, so there's no need to re-compile a new map version to assign the correct trigger names.

You can use it like this: `mod_zone_(start/end)_[bonus]`
Example regular start zone: `mod_zone_start`
Example bonus end zone: `mod_zone_end_bonus`

**Comment by rtldg** [comment]
Just giving some updated info about how the timer follows https://github.com/3331/fly#trigger_multiple for prebuilt map zones.
And also that it uses
```
mod_zone_bonus_X_start
mod_zone_bonus_X_end
mod_zone_bonus_X_checkpoint_X
```
instead of the the ones in the reply above

**Comment by rtldg** [comment]
this is doable now, although some things like `trigger_teleport`s and multiple start zones should be done with the hammerid option in the menu.

some example menus on `bhop_somp_mountain_css`
![image](https://user-images.githubusercontent.com/55846624/173238680-70765bef-999e-4060-b1be-297a7768b344.png)
![image](https://user-images.githubusercontent.com/55846624/173238753-d39f9e60-42eb-4916-86ae-914f457b204c.png)
