### ISSUE TITLE
update timer

### ISSUE THREAD

**Issue by normalamron** [shavitush/bhoptimer#742]
How can i update timer on lan server ?

**Comment by normalamron** [comment]
just plugins ? scripts or translation ?

**Comment by deadw1nter** [comment]
[i forgot theres a thing called wiki](https://github.com/shavitush/bhoptimer/wiki/1.-Installation-(from-source))

**Comment by strafe** [comment]
> i forgot theres a thing called wiki

Those instructions are for installing, not updating. If you follow them you will overwrite your config files.

**Comment by deadw1nter** [comment]
> If you follow them you will overwrite your config files.
thanks for mentioning.  but IMO not overwriting config == update
