### ISSUE TITLE
[CSGO] Disable player's dynamic clantag

### ISSUE THREAD

**Issue by Cruze03** [shavitush/bhoptimer#744]
Is there someway you can remove player's dynamic clantag? Example: ★Aimbot, ★Wallhack etc..
^ this sheit.
Something like this: https://forums.alliedmods.net/showpost.php?p=2337679&postcount=6

**Comment by sneak-it** [comment]
You can't prevent players from changing their clantag, but you can use this to stop them from changing it often: https://forums.alliedmods.net/showthread.php?p=2367842#post2367842

**Comment by strafe** [comment]
Since `CS_SetClientClanTag` bypasses ClientCommandKeyValues you can simply block that type and the timer's clan tag functionality will continue to work.
```SourceMod
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>

public Action OnClientCommandKeyValues(int client, KeyValues kv)
{
	char sSection[16];
	if (kv.GetSectionName(sSection, sizeof(sSection)) && StrEqual(sSection, "ClanTagChanged"))
		return Plugin_Handled;

	return Plugin_Continue;
}
```

**Comment by Cruze03** [comment]
Wow thanks strafe! Working!! 👍
