### ISSUE TITLE
Shavit-Chat causing server crashes

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#75]
I honestly can't tell you what the issue is, but with dynamic/rtler/shavit-chat enabled, the server seems to stop on retrieving game data and then revert to the default map with no players able to connect.

With them disabled, everything works fine again, so something in the plugins is essentially crashing the server, there's no logs or anything to support this however.

**Comment by shavitush** [comment]
rtler isn't a requirement, it's optional :)

also, try reverting to this version of chat: https://github.com/shavitush/bhoptimer/blob/af7d62d4a6bebdde8fa2d433a300b744743daaf0/scripting/shavit-chat.sp

let me know if it's fixed

**Comment by shavitush** [comment]
also, could you use Accelerator and provide a crash dump?

**Comment by Technoblazed** [comment]
Reverting to that version seems to fix it, however after that, returning to the shavit-chat version that I had before, the maps appear to load again. The wasn't crashing as such, just would ALWAYS return to the default map the second it ended.

Accelerator wouldn't create crash dumps, because it wasn't crashing, weird how it was doing it before, but stopped now o.O

**Comment by shavitush** [comment]
That's.. weird. Glad you solved it though
