### ISSUE TITLE
shavit.inc Errors

### ISSUE THREAD

**Issue by XanXTV** [shavitush/bhoptimer#750]
The following errors show up whenever I attempt to compile any of the provided .sp files from the newest version v2.4.1.

I have attempted using multiple SourceMod compilers from 1.7 all the way to the latest 1.9 release with no success. The .inc file was not modified.

`//// shavit-rankings.sp
//
// scripting\include\shavit.inc(115) : error 001: expected token: "{", but found "struct"
// scripting\include\shavit.inc(117) : error 001: expected token: "public", but found "char"
// scripting\include\shavit.inc(118) : error 001: expected token: "}", but found "char"
// scripting\include\shavit.inc(118) : error 021: symbol already defined: "sShortName"
// scripting\include\shavit.inc(119) : error 021: symbol already defined: "sHTMLColor"
// scripting\include\shavit.inc(120) : error 021: symbol already defined: "sChangeCommand"
// scripting\include\shavit.inc(121) : error 021: symbol already defined: "sClanTag"
// scripting\include\shavit.inc(122) : error 021: symbol already defined: "sSpecialString"
// scripting\include\shavit.inc(123) : error 021: symbol already defined: "sStylePermission"
// scripting\include\shavit.inc(126) : error 001: expected token: "{", but found "struct"
// scripting\include\shavit.inc(160) : error 054: unmatched closing brace ("}")
// scripting\include\shavit.inc(162) : error 001: expected token: "{", but found "struct"
// scripting\include\shavit.inc(164) : error 001: expected token: "public", but found "char"
// scripting\include\shavit.inc(165) : error 001: expected token: "}", but found "char"
// scripting\include\shavit.inc(170) : error 054: unmatched closing brace ("}")
// scripting\include\shavit.inc(172) : error 001: expected token: "{", but found "struct"
// scripting\include\shavit.inc(187) : error 054: unmatched closing brace ("}")
// scripting\include\shavit.inc(322) : error 017: undefined symbol "timer_snapshot_t"
// scripting\include\shavit.inc(322) : error 001: expected token: ";", but found "]"
// scripting\include\shavit.inc(381) : error 017: undefined symbol "timer_snapshot_t"
// scripting\include\shavit.inc(381) : error 001: expected token: ";", but found "]"
// scripting\include\shavit.inc(1089) : error 017: undefined symbol "stylesettings_t"
// scripting\include\shavit.inc(1089) : error 001: expected token: ";", but found "]"
// scripting\include\shavit.inc(1165) : error 017: undefined symbol "timer_snapshot_t"
// scripting\include\shavit.inc(1165) : error 001: expected token: ";", but found "]"
// scripting\include\shavit.inc(1174) : error 017: undefined symbol "timer_snapshot_t"
//
// Compilation aborted.
// 26 Errors.
//
// Compilation Time: 0.25 sec
// ----------------------------------------`

**Comment by strafe** [comment]
Compile with SourceMod 1.10

**Comment by XanXTV** [comment]
That fixed the issue, thank you so much! 👍
