### ISSUE TITLE
Style modif

### ISSUE THREAD

**Issue by normalamron** [shavitush/bhoptimer#751]
i want use cp menu on (sideways, hsw, scroll etc.)
but when i use cp menu my timer is stopping
how can i change this options
i cant find in any config file

**Comment by shavitush** [comment]
that's how bhop timers work. if you want segmented style, add `segments` to specialstring like so:

    "specialstring"	"segments"

timer has to stop without segments as you could save a checkpoint near the end and teleport to it right after starting
