### ISSUE TITLE
[Request] Show bonus records on !style menu when on bonus track

### ISSUE THREAD

**Issue by mbhound** [shavitush/bhoptimer#754]
If this is possible, please make it so that you can see bonus records instead of normal records on the !style menu when on the bonus track. It is useful to see what records have not been taken.

**Comment by Nairdaa** [comment]
Maybe not instead, but an extra menu like !bstyle or an actual menu at !style to choose from main/bonus could be nice, indeed.

**Comment by Nairdaa** [comment]
Being able to see the bonus wr with !style should be by default on track, you're right.

Sorry.
