### ISSUE TITLE
Recess zone beam

### ISSUE THREAD

**Issue by normalamron** [shavitush/bhoptimer#755]
I tried to add btimes zone beam but i cant
how can i add and find recess zone beam

**Comment by Nairdaa** [comment]
https://github.com/shavitush/bhoptimer/wiki/2.7.-Configuration:-Zones

**Comment by normalamron** [comment]
Do you know good zone beam and how can i find

**Comment by Nairdaa** [comment]
Yes I do know. The default one is the best one.

Otherwise http://www.google.com

**Comment by normalamron** [comment]
dude are u kidding me
i want this beam
![Adsız](https://user-images.githubusercontent.com/47062844/54306415-5c958280-45da-11e9-995a-6233eb00ae92.png)

**Comment by cytrus224** [comment]
its ugly wtf

**Comment by normalamron** [comment]
i think sweat and better than straight line

**Comment by Nairdaa** [comment]
Speak english here, please.

**Comment by normalamron** [comment]
Who? me

**Comment by Nairdaa** [comment]
No, me.

**Comment by normalamron** [comment]
You're not helping 
dont comment if you dont help me

**Comment by deadw1nter** [comment]
bluelightningscroll3
and remember, you should be kind when you are asking for help

**Comment by Nairdaa** [comment]
He's not even asking for help. He's asking for a ready solution, for somebody to do it for him from scratch to the end. He's not even capable to read the guide where it's all clean written how to edit. Nobody can't help he's incapable of even finding the sprite alone lol. Can you please close this thread already, @shavitush ?

**Comment by normalamron** [comment]
first searched from google I came here for not finding anything and i use google translate
i think you're irrelevant

**Comment by Nairdaa** [comment]
............................................________ 
....................................,.-'"...................``~., 
.............................,.-"..................................."-., 
.........................,/...............................................":, 
.....................,?......................................................, 
.................../...........................................................,} 
................./......................................................,:`^`..} 
.............../...................................................,:"........./ 
..............?.....__.........................................:`.........../ 
............./__.(....."~-,_..............................,:`........../ 
.........../(_...."~,_........"~,_....................,:`........_/ 
..........{.._$;_......"=,_......."-,_.......,.-~-,},.~";/....} 
...........((.....*~_......."=-._......";,,./`..../"............../ 
...,,,___.`~,......"~.,....................`.....}............../ 
............(....`=-,,.......`........................(......;_,,-" 
............/.`~,......`-...................................../ 
.............`~.*-,.....................................|,./.....,__ 
,,_..........}.>-._...................................|..............`=~-, 
.....`=~-,__......`,................................. 
...................`=~-,,.,............................... 
................................`:,,...........................`..............__ 
.....................................`=-,...................,%`>--==`` 
........................................_..........._,-%.......` 
...................................,

**Comment by shavitush** [comment]
jesus fucking christ PLEASE behave guys. this person asks for help clearly because they could not figure it out on their own. @normalamron i apologize for the trouble caused. please re-open this issue if you haven't found a solution yet
