### ISSUE TITLE
Allow timer data to persist after the user disconnects

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#757]
* Persist it for a specified amount of time or allow it to persist until map change.
* Clear the persisted data after map change or when the player gets their data reloaded.
* Save the timer data, replay data (if exists), player coordinates/speed etc and everything that CPs normally save.

**Comment by Nairdaa** [comment]
Nice. I suggested it on discord like a month ago if not more. "Useless" :P

**Comment by shavitush** [comment]
shavit_misc_persistdata
