### ISSUE TITLE
WR counter query is inaccurate

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#760]

**Comment by Nairdaa** [comment]
It counts every wr, including the bonus.
Also there is no menu in !stats to view other style statistics. Should be another enhancement to the timer imo.

**Comment by Nairdaa** [comment]
https://www.youtube.com/watch?v=El_vW8bAMwM Something like this, for each style, that I had in my scroll timer.

Just noticed it only showed the steamid only for normal, but whatever, that timer never got finished.
