### ISSUE TITLE
[Request] Don't change page when selecting style on replay too soon

### ISSUE THREAD

**Issue by mbhound** [shavitush/bhoptimer#763]
So basically when I'm watching a run on the replay bot and it is just at the end, there is an annoying period of time between the end of the run and when you can start the next one. Often times I'll make my selection for the style I want to watch next too soon which will change the style menu page back to the first. Is it possible to reopen the menu to the same page of the style which I clicked too soon?

**Comment by Nairdaa** [comment]
`// Time to wait before restarting the replay after it finishes playing.
// -
// Default: "5.0"
// Minimum: "0.000000"
// Maximum: "10.000000"
shavit_replay_delay "3.0"`

> plugin.shavit-replay.cfg

It's in cstrike/sourcemod/cfg
