### ISSUE TITLE
Record prestrafe for replay

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#765]
note to self: shavit_replay_prestrafe_time 1.0

no there will not be recording of post-run movements because they are useless

**Comment by blankbhop** [comment]
add this with 2.5 smh

**Comment by shavitush** [comment]
i wanted but my code ended up being ugly, i'll revisit it some other time

**Comment by blankbhop** [comment]
cmon dont be a coward

**Comment by blankbhop** [comment]
you haven't merged the pull request so it isn't too late

**Comment by strafe** [comment]
Would be ideal if this still respected the changes made in ff0aa5b. If the bot begins to move immediately after requesting the replay, SrcDemo2/SDR will not have a non-frame blended frame at the start to fade in/out on.

**Comment by whocodes** [comment]
Post run movements are a necessary feature so that you don’t encounter the bug where the bot seems to teleport into the end zone for the last few frames of the run.

Example: https://youtu.be/x8-_mJqb9DI

**Comment by whocodes** [comment]
Also this was already requested in #672 so you can close that issue out.

**Comment by shavitush** [comment]
@whocodes this is not a bug in bhoptimer, feel free to check replays in any server running it

**Comment by whocodes** [comment]
My apologies; I thought I was on a server with shavit’s just now when I noticed the bug was apparent, but it was actually running an older version of bTimes.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Cruze03** [comment]
We need this!! 😁

**Comment by kidfearless** [comment]
Currently being previewed in 986ebcd427b816d99dda24a9ed746c67e2f122ba
