### ISSUE TITLE
Use a third-party AutoExecConfig include to ease updating

### ISSUE THREAD

**Issue by strafe** [shavitush/bhoptimer#769]
SourceMod's built-in `AutoExecConfig` native lacks the ability to append new convars. This leaves end-users to choose between deleting the existing config and combining it with the newly generated one or adding new convars to the existing config themselves.

Impact's [AutoExecConfig](https://forums.alliedmods.net/showthread.php?t=204254) or KissLick's [AutoExecConfigAppend](https://forums.alliedmods.net/showthread.php?t=233282) are probably the best options, but others exist.

**Comment by kidfearless** [comment]
Implemented in 3283a26d45f52c580fe087782511a29fe60c32f9
