### ISSUE TITLE
[Request] Change sm_p to show profile instead of no clip

### ISSUE THREAD

**Issue by mbhound** [shavitush/bhoptimer#772]
RegConsoleCmd("sm_p", Command_Noclip, "Toggles noclip.");
RegConsoleCmd("sm_prac", Command_Noclip, "Toggles noclip. (sm_p alias)");
RegConsoleCmd("sm_practice", Command_Noclip, "Toggles noclip. (sm_p alias)");
RegConsoleCmd("sm_nc", Command_Noclip, "Toggles noclip. (sm_p alias)");
RegConsoleCmd("sm_noclipme", Command_Noclip, "Toggles noclip. (sm_p alias)");

The rest are fine but sm_p would make way more sense if it showed profile.

**Comment by shavitush** [comment]
i personally agree, but it's been the 'standard' command used to noclip in bhop servers ever since i started bhopping (cs:s, 2012) and bhoptimer isn't the first timer to implement it. i think it'd be unfair to change the command everyone is so used to. just like how i wouldn't be forcing players to use !sr (server record) instead of !wr (world record), even though !wr is not often what the command describes it is

**Comment by Nairdaa** [comment]
!p is profile on fap bihapzor!

**Comment by mbhound** [comment]
95% of people - oh I want to noclip let me type !nc
4% of people - oh I want to noclip and i'm a css hopper let me type !p oh wait that doesn't work let me type !nc or noclip in console
1% of people - I have hsw brain and don't know how to noclip

**Comment by strafe** [comment]
`p` for practice is the standard noclip command. I don't think it's a good idea to change it, but someone with a populated server could collect actual statistics on which of 5 aliases people are actually using.

**Comment by mbhound** [comment]
how is no clipping practice? it is !cp for practicing

**Comment by whocodes** [comment]
I’ve been bunnyhopping on Counter Strike for well over 10 years now, and I fully believe it should be changed to ‘sm_nc’. The people that are used to ‘sm_p’ may be inconvenienced for the 10 seconds it takes to realize it’s the wrong command, and type the new command instead, but that hardly seems like a big deal. They can adjust to the new command and change their bind.

**Comment by rtldg** [comment]
went ahead and did this in https://github.com/shavitush/bhoptimer/commit/c9f8724d507deb8dc9cd3ce420b1985ebd29437b since it's not a big deal
