### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by Wsmalle** [shavitush/bhoptimer#774]
edited by shavit: what in the flying fuck is this long text?

**Comment by shavitush** [comment]
jesus christ PLEASE don't post such long texts in issues, it's COMPLETELY unreadable and you can get the point across easily

anyway. requirements state you need sourcemod 1.10, so get it and the errors will be fixed. use the compiled files from the releases page if you don't know how to compile

**Comment by Wsmalle** [comment]
@shavitush from compile https://i.imgur.com/CObgX0P.png

**Comment by shavitush** [comment]
get sourcemod 1.10. locking this
