### ISSUE TITLE
[SM] Failed to load plugin

### ISSUE THREAD

**Issue by Wsmalle** [shavitush/bhoptimer#775]
https://i.imgur.com/vPhAbbj.png

**Comment by sneak-it** [comment]
Requirements:
- SourceMod 1.10 or above

**Comment by Wsmalle** [comment]
its SourceMod 1.10.7

**Comment by sneak-it** [comment]
No such sourcemod version exists. Your error is telling you that you are not using Sourcemod 1.10 on your server.

**Comment by Wsmalle** [comment]
@sneak-it im so sry i haved 1.9 sorry
