### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by rvidelaa** [shavitush/bhoptimer#778]
I have the MySQL server in the same location as the gameserver (same machine), tried different IP's in databases.cfg, adding the prefix in the file shavit-prefix.txt, and nothing...

> Errors:
> shavit-zones.smx: Unable to load plugin (no debug string table)
> shavit-sounds.smx: Unable to load plugin (no debug string table)
> shavit-core.smx: Unable to load plugin (no debug string table)
> shavit-misc.smx: Unable to load plugin (no debug string table)
> shavit-rankings.smx: Unable to load plugin (no debug string table)
> shavit-timelimit.smx: Unable to load plugin (no debug string table)
> shavit-replay.smx: Unable to load plugin (no debug string table)
> shavit-stats.smx: Unable to load plugin (no debug string table)
> shavit-chat.smx: Unable to load plugin (no debug string table)
> shavit-hud.smx: Unable to load plugin (no debug string table)
> shavit-wr.smx: Unable to load plugin (no debug string table)`

> "shavit"
> 	{
> 		"driver"			       "mysql"
> 		"host"				"csgo.gamerlive.cl"
> 		"database"			"bhop"
> 		"user"				"bhop_user"
> 		"pass"				"XXXXXXXX"
> 		"port"				"3306"
> 	}

> SourceMod Version Information:
>     SourceMod Version: 1.9.0.6276
>     SourcePawn Engine: 1.9.0.6276, jit-x86 (build 1.9.0.6276)
>     SourcePawn API: v1 = 4, v2 = 12
>     Compiled on: Mar 28 2019 17:12:25
>     Built from: https://github.com/alliedmodders/sourcemod/commit/2bfc349
>     Build ID: 6276:2bfc349
>     http://www.sourcemod.net/

> Metamod:Source version 1.10.7-dev
> Built from: https://github.com/alliedmodders/metamod-source/commit/63da1c3
> Build ID: 970:63da1c3
> Loaded As: Valve Server Plugin
> Compiled on: Mar 28 2019
> Plugin interface version: 15:14
> SourceHook version: 5:5
> http://www.metamodsource.net/

**Comment by shavitush** [comment]
the requirements state that you need sourcemod 1.10

please follow the requirements
