### ISSUE TITLE
GeoIP Shavit-Chat Crash

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#78]
Sourcemod Version: Latest 1.8
Stack Trace: https://crash.limetech.org/3pbitisifean

Upon player connect with shavit-chat enabled, the server seems to crash. Other than the stack trace there are no other logs, any ideas?

**Comment by shavitush** [comment]
i'll check that

**Comment by shavitush** [comment]
in `OnClientPutInServer` (shavit-core) could you replace this whole section and try again?

From this:

```
char[] sIP = new char[32];
GetClientIP(client, sIP, 32);

char[] sCountry = new char[45];
GeoipCountry(sIP, sCountry, 45);

if(strlen(sCountry) == 0)
{
	strcopy(sCountry, 45, "Local Area Network");
}
```

To this:

```
char[] sIP = new char[32];
GetClientIP(client, sIP, 32);

char[] sCountry = "Local Area Network";
```

Also remove the <geoip> include. Does it still happen?

**Comment by Technoblazed** [comment]
Works fine with the replacement and removal

**Comment by shavitush** [comment]
Try now, with this fix.

**Comment by Technoblazed** [comment]
Server crashes

**Comment by shavitush** [comment]
this is in no way related to shavit-chat then
i think you'll have to apply this workaround and [file a bug](https://bugs.alliedmods.net/). it's not related to my plugin, sorry

**Comment by Technoblazed** [comment]
Just to let you know, I got a response, Sourcemod versions 5919 and a few others have a GeoIP.dat of 0 bytes. So if anyone else experiences the issue, they should get the .dat from a previous version.
