### ISSUE TITLE
How to disable plugin?

### ISSUE THREAD

**Issue by mazariniz** [shavitush/bhoptimer#781]
Hey, i saw https://github.com/shavitush/bhoptimer/issues/620
But the question is actual for me.
I'm also running map configurator on my server. And i don't know how to unload your plugins automatically.
Commands, such as:
sm plugins unload shavit-core
sm plugins unload shavit-hud...

doesn't work, plugins still will be loaded

Why this happens?
Could it be because some plugins using natives from shavit?

With regards,
mazariniz

**Comment by strafe** [comment]
[Late-loading is not supported.](https://github.com/shavitush/bhoptimer/issues/615#issuecomment-476108979)

**Comment by mazariniz** [comment]
So, there is no options to unload plugin within SM, without changing source code?

**Comment by strafe** [comment]
Unloading should be fine, just not loading.

**Comment by mazariniz** [comment]
sm plugins unload shavit-...
sm plugins load_lock

seems as it works, thx
