### ISSUE TITLE
Is there a way to mute player's jumpsound too like footsteps when you type !hide?

### ISSUE THREAD

**Issue by Cruze03** [shavitush/bhoptimer#787]
First of all, thanks for this amazing timer. It's really good and has really good configs. Only thing I think this timer lack is the one I mentioned in issue title and stage/checkpoints zones(not that important). Hopefully someone helps!
Edit: Game - CSGO

**Comment by strafe** [comment]
Yes but it involves detouring `CCSPlayer::OnLand` through an extension and maintaining the relevant gamedata. It's probably out of the scope of this plugin.

You can replicate `sv_min_jump_landing_sound 9999999` to a player when they have hide enabled to prevent them hearing all footsteps (including their own).

**Comment by Cruze03** [comment]
Okay thanks!! Another thing:

Anyone else facing crash when using "number" of shavit-sounds.cfg? Accelerator says something related to "PrecacheSound"
