### ISSUE TITLE
Disable spectator

### ISSUE THREAD

**Issue by vovo4ka960** [shavitush/bhoptimer#788]
Hello!
How to make sure that the spectator is always off for you? 
But do not remove this feature in the settings.
I want to make sure that when you log on to the server, it was turned off according to the standard, and you could turn it on if you wish.

**Comment by sneak-it** [comment]
`mp_spectators_max` ?

**Comment by shavitush** [comment]
# ____--**\*\*bhop\*\***--____timer
not letting players spectate is terrible and i can't see a reason for why it would be good. disabling that functionality will allow players to cheat more easily (as they cannot be watched) and you won't be able to see others' routes unless they have a replay.. assuming you even have replays enabled considering you asked for this

if you really want this, disable the jointeam hook (there's a cvar in the misc plugin, set it to 0) and use some kind of hook for the command that doesn't allow spectating and fade everyone to black upon death

**Comment by vovo4ka960** [comment]
I wanted to do this for one reason only.
Because it interrupts other menus on the server.
If you could make observers in hud, it would be just great!

**Comment by whocodes** [comment]
He's asking how to disable Spectators in the HUD, not the ability to spectate.

**Comment by strafe** [comment]
It should not interrupt other menus, it checks whether the client has another menu open before sending the panel.
```sourcepawn
(GetClientMenu(client, null) == MenuSource_None || GetClientMenu(client, null) == MenuSource_RawPanel)
```
Last time I checked this worked as expected.
