### ISSUE TITLE
[ Request ] Show rank in the top left hud

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#789]
Hello,

![Clipboard01](https://user-images.githubusercontent.com/38843773/56248366-04a1de00-60a8-11e9-898c-a8a4ac70facd.jpg)

Could you please do something like this? Both for spectators/players?

**Comment by shavitush** [comment]
no thats ugly

**Comment by Nairdaa** [comment]
You're ugly.
