### ISSUE TITLE
Crashing when using "number" of shavit-sounds.cfg

### ISSUE THREAD

**Issue by Cruze03** [shavitush/bhoptimer#790]
Accelerator says something related to ```PrecacheSound```

My config:
```"2" "shavit/top10.mp3"```

* Tried using this mp3 in other modes (noimprovment, first etc) and it works perfectly so it's not mp3 problem nor file path problem.
* Tried with and without "number" configuration and only crashes when using it.

**Comment by Nairdaa** [comment]
That's not your whole config mate. The server won't crash because of a sound not being able to be played. Even if it's a format not supported by the engine.

**Comment by Cruze03** [comment]
Noone else facing this? ☹️

**Comment by ImmortaI** [comment]
I'm not sure why it wouldn't precache the sound, you can manually fix this temporarily by adding it to OnMapStart in any plugin you currently run

AddFileToDownloadsTable("sound\shavit\top10.mp3");
PrecacheSound("sound\shavit\top10.mp3", true);

For example.

**Comment by shavitush** [comment]
i'm sorry but no one else has this (and you're not replying to comments), closing for now. update if it still happens and you can troubleshoot

**Comment by Cruze03** [comment]
I did that. (AddFileToDownloadsTable and PrecacheSound) still crashes :(
