### ISSUE TITLE
godmode does not work correctly

### ISSUE THREAD

**Issue by Septembers** [shavitush/bhoptimer#791]
Hello. I am using version 2.5.4
shavit_misc_godmode "2"
But players do damage to each other.

**Comment by Septembers** [comment]
How to make that when you change the team did not revive?

**Comment by ImmortaI** [comment]
shavit-misc is probably not loading, check your log files

**Comment by Septembers** [comment]
> shavit-misc is probably not loading, check your log files

Sorry for the long answer. All modules are loaded, there are no errors in the logs.
