### ISSUE TITLE
Persist CP data

### ISSUE THREAD

**Issue by blankbhop** [shavitush/bhoptimer#793]
After disconnection CP's should persist, along with Segmented run data. This is mandatory as I was in a sub 4 minute segmented run on bhop_nextgen, and I crashed and my entire run was gone.

**Comment by Nairdaa** [comment]
> =＾● ⋏ ●＾=02/04/2019
> it's much more complicated to save cps
> i can try in next update, no guarantees

:-(

**Comment by blankbhop** [comment]
This timer is a -rep until this is a feature :(

**Comment by Nairdaa** [comment]
You have it wrong. It's a +rep, because that might become a feature. It's not like you even had the reconnect respawn feature on blackys anyway.

**Comment by whocodes** [comment]
don’t use cheat and your game won’t crash HA

**Comment by blankbhop** [comment]
Dude delete this comment, I can't bhop properly without the cheats

**Comment by bhopalex** [comment]
This is a feature I'd like to suggest adding as well. Preferably with the option to enable it for players by flag.
