### ISSUE TITLE
Timer plugin wont work

### ISSUE THREAD

**Issue by edqn** [shavitush/bhoptimer#794]
Hello, i just started to make a css bhop server and i followed the youtube tutorial but when i reload the game and do /admin there is no option for setting up times. thanks in advance

**Comment by edqn** [comment]
Never mind i found the issue, i have not turned the files into smx in the plugins

**Comment by shavitush** [comment]
you should follow basic installation from https://timer.shav.it/ instead

> * [Download an existing release](https://github.com/shavitush/bhoptimer/releases) - installing is simply drag & drop into the game server’s directory.
