### ISSUE TITLE
compile error please help

### ISSUE THREAD

**Issue by edqn** [shavitush/bhoptimer#795]
I got errors like this for every shavit file, please help i am trying to get the smx files. thanks

//// shavit-timelimit.sp
//
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(123) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(125) : error 001: expected token: "public", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(126) : error 001: expected token: "}", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(126) : error 021: symbol already defined: "sShortName"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(127) : error 021: symbol already defined: "sHTMLColor"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(128) : error 021: symbol already defined: "sChangeCommand"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(129) : error 021: symbol already defined: "sClanTag"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(130) : error 021: symbol already defined: "sSpecialString"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(131) : error 021: symbol already defined: "sStylePermission"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(134) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(172) : error 054: unmatched closing brace ("}")
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(174) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(176) : error 001: expected token: "public", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(177) : error 001: expected token: "}", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(182) : error 054: unmatched closing brace ("}")
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(184) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(199) : error 054: unmatched closing brace ("}")
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(334) : error 017: undefined symbol "timer_snapshot_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(334) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(402) : error 017: undefined symbol "timer_snapshot_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(402) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1157) : error 017: undefined symbol "stylesettings_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1157) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1233) : error 017: undefined symbol "timer_snapshot_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1233) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1242) : error 017: undefined symbol "timer_snapshot_t"
//
// Compilation aborted.
// 26 Errors.
//
// Compilation Time: 0.39 sec
// ----------------------------------------

//// shavit-wr.sp
//
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(123) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(125) : error 001: expected token: "public", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(126) : error 001: expected token: "}", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(126) : error 021: symbol already defined: "sShortName"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(127) : error 021: symbol already defined: "sHTMLColor"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(128) : error 021: symbol already defined: "sChangeCommand"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(129) : error 021: symbol already defined: "sClanTag"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(130) : error 021: symbol already defined: "sSpecialString"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(131) : error 021: symbol already defined: "sStylePermission"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(134) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(172) : error 054: unmatched closing brace ("}")
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(174) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(176) : error 001: expected token: "public", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(177) : error 001: expected token: "}", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(182) : error 054: unmatched closing brace ("}")
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(184) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(199) : error 054: unmatched closing brace ("}")
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(334) : error 017: undefined symbol "timer_snapshot_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(334) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(402) : error 017: undefined symbol "timer_snapshot_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(402) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1157) : error 017: undefined symbol "stylesettings_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1157) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1233) : error 017: undefined symbol "timer_snapshot_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1233) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1242) : error 017: undefined symbol "timer_snapshot_t"
//
// Compilation aborted.
// 26 Errors.
//
// Compilation Time: 0.37 sec
// ----------------------------------------

//// shavit-zones.sp
//
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(123) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(125) : error 001: expected token: "public", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(126) : error 001: expected token: "}", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(126) : error 021: symbol already defined: "sShortName"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(127) : error 021: symbol already defined: "sHTMLColor"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(128) : error 021: symbol already defined: "sChangeCommand"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(129) : error 021: symbol already defined: "sClanTag"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(130) : error 021: symbol already defined: "sSpecialString"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(131) : error 021: symbol already defined: "sStylePermission"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(134) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(172) : error 054: unmatched closing brace ("}")
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(174) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(176) : error 001: expected token: "public", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(177) : error 001: expected token: "}", but found "char"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(182) : error 054: unmatched closing brace ("}")
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(184) : error 001: expected token: "{", but found "struct"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(199) : error 054: unmatched closing brace ("}")
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(334) : error 017: undefined symbol "timer_snapshot_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(334) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(402) : error 017: undefined symbol "timer_snapshot_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(402) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1157) : error 017: undefined symbol "stylesettings_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1157) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1233) : error 017: undefined symbol "timer_snapshot_t"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1233) : error 001: expected token: ";", but found "]"
// C:\Users\Windows PC\Desktop\shav\addons\sourcemod\scripting\include\shavit.inc(1242) : error 017: undefined symbol "timer_snapshot_t"

**Comment by shavitush** [comment]
your compiler is old. get sourcemod 1.10

please follow the requirements, i wrote them so people will read them instead of asking such questions

**Comment by edqn** [comment]
> your compiler is old. get sourcemod 1.10
> 
> please follow the requirements, i wrote them so people will read them instead of asking such questions

how do i download 1.10? it is pink and wont let me download

**Comment by shavitush** [comment]
![image](https://user-images.githubusercontent.com/3672466/56895679-6e4fbe00-6a92-11e9-8b71-12e17f13f97b.png)

**Comment by edqn** [comment]
hello, i tried to compile using sourcemod 1.10's compiler, but i still got the same issues. is there a way around it? or something else i could do to get the smx files? thanks

**Comment by whocodes** [comment]
Ensure that you have the correct version of `shavit.inc` in your include folder. 

You can also just download the compiled smx from here:
https://github.com/shavitush/bhoptimer/releases
