### ISSUE TITLE
[ Suggestion ] shavit-chat.cfg

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#796]
Could you please add "wrs" ? I'd love to be able to add a chat rank to choose from the !chatrank based on the amount of world records the player has.

**Comment by shavitush** [comment]
#782

**Comment by rtldg** [comment]
added in https://github.com/shavitush/bhoptimer/commit/3ca87e27c8e53aac01e84486b4587b296176c346
