### ISSUE TITLE
Issue with !hide

### ISSUE THREAD

**Issue by Git-Jamie** [shavitush/bhoptimer#799]
Hiding a playing with custom particle trails does not hide them. Was looking to see if anyone has fixed this but in the end someone gave me a snippet to hide them, can this be implemented into the timer?

void FunctionBlah()

{
    // Create your particle entity...
    [...]
    
    SetEdictFlags(entity, GetEdictFlags(entity)&(~FL_EDICT_ALWAYS)); // to allow settransmit hooks
    SDKHookEx(entity, SDKHook_SetTransmit, OnSetTransmit);
}

public Action OnSetTransmit(int entity, int client)
{
    SetTransmitFlags(entity);
    return g_bHide[client] ? Plugin_Handled : Plugin_Continue;
}

stock void SetTransmitFlags(int entity)
{
    if (GetEdictFlags(entity) & FL_EDICT_ALWAYS) {
        SetEdictFlags(entity, (GetEdictFlags(entity) ^ FL_EDICT_ALWAYS));
    }
}

**Comment by Git-Jamie** [comment]
`void FunctionBlah()
{
    // Create your particle entity...
    [...]
    
    SetEdictFlags(entity, GetEdictFlags(entity)&(~FL_EDICT_ALWAYS)); // to allow settransmit hooks
    SDKHookEx(entity, SDKHook_SetTransmit, OnSetTransmit);
}

public Action OnSetTransmit(int entity, int client)
{
    SetTransmitFlags(entity);
    return g_bHide[client] ? Plugin_Handled : Plugin_Continue;
}

stock void SetTransmitFlags(int entity)
{
    if (GetEdictFlags(entity) & FL_EDICT_ALWAYS) {
        SetEdictFlags(entity, (GetEdictFlags(entity) ^ FL_EDICT_ALWAYS));
    }
}  `

**Comment by shavitush** [comment]
that's for whatever plugin you have that creates the particle trails, not the timer
