### ISSUE TITLE
Key limiting style ladder fix

### ISSUE THREAD

**Issue by bhopalex** [shavitush/bhoptimer#800]
Adding a grace period of 1-1.5s of unlocked keys after leaving a ladder will fix getting stopped in the air when doing a ladder strafe without adding a freestyle zone at every one.

**Comment by revosw** [comment]
Change needed here, I think:
https://github.com/shavitush/bhoptimer/blob/very_good_yes/addons/sourcemod/scripting/shavit-core.sp#L2793-L2815

If the logic is written before 31st of May, I'll be able to do a test drive and eventually do a pr of my favorite value.

**Comment by shavitush** [comment]
i have implemented an alternative solution. instead of a timed grace period, you can use all keys until you touch the ground, then the key restrictions get enabled agian
