### ISSUE TITLE
track "completions" for times

### ISSUE THREAD

**Issue by shavitush** [shavitush/bhoptimer#804]
e.g. player finishes map bhop_ml once, !wr menu shows "completions: 1"
the player finishes it again on a different style, it shows 1 completion
the player finishes it once again, but on the first style, it shows 2 completions

not a retroactive change, unfortunately

**Comment by whocodes** [comment]
When I was writing my timer, I considered saving a new row for every time recorded (even if it’s not an improvement, or if they already had a row for that same style/track). This would obviously be incredibly inefficient so I reworked the query to include `completions = completions + 1`
