### ISSUE TITLE
[SM] Unable to load plugins

### ISSUE THREAD

**Issue by savile7249** [shavitush/bhoptimer#805]
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "csgo_movement_unlocker.smx": Error detected in plugin startup (see error logs)
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "helpful\unrealphys.smx": Required extension "Client Preferences" file("clientprefs.ext") not running
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "mpbh.smx": Required extension "SDKHooks" file("sdkhooks.ext") not running
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "pushfix.smx": Required extension "SDKHooks" file("sdkhooks.ext") not running
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "rtv\customrtv.smx": Required extension "Client Preferences" file("clientprefs.ext") not running
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "shavit-chat.smx": Required extension "Client Preferences" file("clientprefs.ext") not running
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "shavit-core.smx": Required extension "Client Preferences" file("clientprefs.ext") not running
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "shavit-hud.smx": Required extension "Client Preferences" file("clientprefs.ext") not running
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "shavit-misc.smx": Required extension "Client Preferences" file("clientprefs.ext") not running
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "shavit-replay.smx": Required extension "SDKHooks" file("sdkhooks.ext") not running
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "shavit-stats.smx": Required extension "GeoIP" file("geoip.ext") not running
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "shavit-wr.smx": Native "Shavit_LogMessage" was not found
L 05/25/2019 - 19:21:38: [SM] Unable to load plugin "shavit-zones.smx": Required extension "SDKHooks" file("sdkhooks.ext") not running

**Comment by shavitush** [comment]
are you on sourcemod 1.1 or whatever? sdkhooks comes preinstalled with sourcemod since 1.5.
use sm 1.10 or above

**Comment by savile7249** [comment]
actually I’m using 1.10 dev build 6416.That happened when i try to make a LAN server

**Comment by shavitush** [comment]
you're missing extensions. installed wrong build  of sourcemod perhaps?

**Comment by savile7249** [comment]
I did same steps as my friend told me.But his system is Windows 7 my system is Windows 10. Is that the problem?

**Comment by shavitush** [comment]
no. can you join the timer's discord server so we can troubleshoot this easily? https://discord.gg/jyA9q5k
