### ISSUE TITLE
very_good_yes version:  Weapon 194 is not owned by client 15

### ISSUE THREAD

**Issue by Cruze03** [shavitush/bhoptimer#807]
L 05/28/2019 - 09:02:20: [SM] Exception reported: Weapon 194 is not owned by client 15
L 05/28/2019 - 09:02:20: [SM] Blaming: Shavit/shavit-misc.smx
L 05/28/2019 - 09:02:20: [SM] Call stack trace:
L 05/28/2019 - 09:02:20: [SM]   [0] CS_DropWeapon
L 05/28/2019 - 09:02:20: [SM]   [1] Line 3317, bhoptimer-v2.5.4\addons\sourcemod\scripting\shavit-misc.sp::Command_Drop

**Comment by Lime18** [comment]
this fix prevents you from throwing away weapons.

**Comment by whocodes** [comment]
> this fix prevents you from throwing away weapons.

But this commit has already been reverted?

**Comment by Lime18** [comment]
@whocodes Oh, thanks ^^
