### ISSUE TITLE
[Request] Question

### ISSUE THREAD

**Issue by Had3s99** [shavitush/bhoptimer#812]
Hello,

How enable the plugin only on course map ?

Thanks.

**Comment by Prefix** [comment]
Use UMC

**Comment by Nairdaa** [comment]
This is a bhoptimer, not minigametimer.

**Comment by Had3s99** [comment]
@Nairdaa yes and ? Lot of plugin have cvar to disable or enable the plugin so i want to know how i can turn off with cvar or other idea

**Comment by Nairdaa** [comment]
The timer has no such cvar.
Code a plugin that disables shavit's plugins when a map name starts with `mg_`

**Comment by strafe** [comment]
@Had3s99 late-loading will not be supported, https://github.com/shavitush/bhoptimer/issues/615#issuecomment-476108979.

**Comment by Had3s99** [comment]
Yeah but i don't have find how disable shavit's plugins when a map name contains multigame :(

**Comment by strafe** [comment]
You don't.

**Comment by Had3s99** [comment]
Even with other plugin to manage the loading of the plugin ?

**Comment by Nairdaa** [comment]
https://github.com/shavitush/bhoptimer/issues/812#issuecomment-500951295

**Comment by Had3s99** [comment]
Yes but how, there is public plugin for do that ?

**Comment by Nairdaa** [comment]
`#include <sourcemod>

public OnMapStart() 
{ 
	decl String:mapname[128]
	GetCurrentMap(mapname, sizeof(mapname))
	
	if (StrContains(mapname, "mg_", false) == 0)
	{
		ServerCommand("sm plugins unload shavit-core")
	}
}`

Didn't test.
[shavit-unload.zip](https://github.com/shavitush/bhoptimer/files/3278725/shavit-unload.zip)

**Comment by bhopalex** [comment]
https://forums.alliedmods.net/showthread.php?p=607079

**Comment by Had3s99** [comment]
Yeah now it's work, but before i've do the same plugin but that doesn't work but well thanks

**Comment by Nairdaa** [comment]
yesn't
