### ISSUE TITLE
shavit-wr overwriting PBs with worse times

### ISSUE THREAD

**Issue by bhopalex** [shavitush/bhoptimer#813]
If a client's data is not loaded yet (which happens a lot on the latest timer version) and they beat a map, their time will overwrite their old time no matter how much longer it was. There needs to be a check in the Shavit_OnFinish function to see if client data has been loaded yet.

Also, there is no chat message for times longer than your PB, which can be fixed super easily with the below code added just after line 2053:

else
	{
		Shavit_PrintToChat(client, "%s[%s]%s %T", gS_ChatStrings.sVariable, sTrack, gS_ChatStrings.sText, "WorseTime", client, gS_ChatStrings.sStyle, gS_StyleStrings[style].sStyleName, gS_ChatStrings.sText, gS_ChatStrings.sVariable2, sTime, gS_ChatStrings.sText, jumps, strafes, sSync, gS_ChatStrings.sWarning, sDifference);
	}

**Comment by Nairdaa** [comment]
"Also, there is no chat message for times longer than your PB" 
Wut? I have them.
