### ISSUE TITLE
Able to spam team change 

### ISSUE THREAD

**Issue by EvanIMK** [shavitush/bhoptimer#815]
(For CSGO don't know it happens on other games). If you press m to choose team and then spam press 1 then 2, it repeatedly changes your team. There should be a limit on how much you can change team. There's probably other plugins that can fix this, but it would be nice if the timer did it.

**Comment by strafe** [comment]
You can disable this in the shavit-misc config if people are abusing it.
```
shavit_misc_jointeamhook

Hook 'jointeam'?
0 - Disabled
1 - Enabled, players can instantly change teams.
```
