### ISSUE TITLE
[Request] Dynamic Time Difference

### ISSUE THREAD

**Issue by blankbhop** [shavitush/bhoptimer#818]
Fuckithops has a feature where it displays a time difference between the player and the current wr, I'm not sure how exactly it works, but I think it is something with the bot path and how close you are to the bot at a certain time.

**Comment by Nairdaa** [comment]
Has nothing to do with the bot.
WR time - Current time = time to WR.

**Comment by kidfearless** [comment]
added

**Comment by Nairdaa** [comment]
heH
