### ISSUE TITLE
Feature requests for 1.5b

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#82]
Seeing as github is a better place due to enhancement tags and milestones, here are a few other feature requests that have been previously mentioned:

1. Only spawn bots if there is a record present for the bot.
2. Create cvar to override the shavit.inc bot configs, to allow the disabling of bots via a convar, i.e
`shavit_misc_bots_enabled`

**Comment by shavitush** [comment]
will do 1
how do you plan to use 2? give me an example scenario so i know what to do

**Comment by Technoblazed** [comment]
For example in shavit.inc, you have NRM, SW and HSW set to use bots, so three bots will be present on the server. In the situation that you wish to run a test, the only way that the client would be able to remove the bots from the server, would be to stop the server and add -nobots to the launch parameter, as the bots spawn even with bot_quota set to 0. It's more of a development command

**Comment by shavitush** [comment]
you could also do `sm plugins unload shavit-replay` for this situation but i get your point :) i'll add `shavit_replay_enabled` when i get around to it

**Comment by Technoblazed** [comment]
Awesome, thanks

**Comment by Technoblazed** [comment]
Another addition:

Adding a custom spawn zone, instead of spawning in the centre of start zones, makes it easier to spawn where the land is uneven, meaning that players are spawned in the ground when spawning in zones.

**Comment by Technoblazed** [comment]
Additional request:

Ability to add tiers to maps, i.e. Tiers database table and print the tier to chat 15 seconds after player spawn

**Comment by shavitush** [comment]
i've added 1 already
will do 2 soon

about the custom spawn zone, you can use grid snapping in zones and it'll be fine in most cases

**Comment by shavitush** [comment]
done some veryminor testing and cvar changing while the map is loaded, didn't see any issue.
report issues if there are any!
