### ISSUE TITLE
[ Request / Suggestion ] Scroll styles and walkable maps

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#828]
Hey, there are some maps that you can literally just walk. Seen some people abuse it and doing scroll times to farm some extra points for the ranking. 

Could you please add something like, if 30 sec on timer and jumps = 0,  or a minute and jumps < 30 (excluding kz_ and xc maps, only the ones that start with "bhop_"), to prevent the funny guys from getting times like that?

I don't have a great solution for that, but I believe you completely understand my idea.

**Comment by sneak-it** [comment]
Who cares, they're getting slower times than everyone else.

**Comment by Nairdaa** [comment]
They farm the points that way. If they can't finish a map on a certain style, they shouldn't be awarded for completing the map on it.

**Comment by shavitush** [comment]
this is the most pointless suggestion i've ever seen sorry nairda
