### ISSUE TITLE
Checkpoints from replaybots don't transfer style settings.

### ISSUE THREAD

**Issue by kidfearless** [shavitush/bhoptimer#829]
When saving a checkpoint off of a replay, style settings aren't transferred over until the next jump. for slowing timescale styles that means that something that was 80k speed is now 8k.

**Comment by rtldg** [comment]
This was fixed as well as it can be somewhere in 3.0.0 and 3.0.3 as far as I know

**Comment by Nairdaa** [comment]
Surely fixed in 3.0.7a :J
