### ISSUE TITLE
Real prestrafe

### ISSUE THREAD

**Issue by StrafeHack** [shavitush/bhoptimer#83]
Most runs going on globaljumps are being done on sourcecode, they have kztimer style prestrafe with a 290 max instead of 276.

**Comment by shavitush** [comment]
278.03 is the absolute max prestrafe you can achieve in CS:S. I can't see how 290 is any fair considering you can easily hit 280 LJ blocks like that (not to mention they're easily done with 272~ prestrafe in CS:GO)

Will tag as 'wontfix' until I see an actual reasoning that doesn't break gameplay

**Comment by StrafeHack** [comment]
Well, I wasn't really looking at it from a long jump perspective in kz maps. More in a route way, since have 287 out of the start zone allows you on some maps to hit blocks you wouldn't be able to otherwise.

If it ever was added I agree it should be off or at least 276 by default.

**Comment by shavitush** [comment]
you can disable the 'blockprejump' cvar and just start jumping while inside the start zone, then you start with 280

**Comment by StrafeHack** [comment]
Yeah that's what I'm doing at the moment. Thanks for considering it anyway.

**Comment by shavitush** [comment]
:)
