### ISSUE TITLE
Migrated sqlite database of the plugin. No zones and can't create zones.

### ISSUE THREAD

**Issue by Cruze03** [shavitush/bhoptimer#832]
If anyone is kind enough to fix this database or test my database: https://www.dropbox.com/s/sszt3j6xt05bjsu/bhop.zip?dl=0

**Comment by Nairdaa** [comment]
Migration is not supported for sqlite.

**Comment by Nairdaa** [comment]
https://github.com/shavitush/bhoptimer/blob/979c911a268f22bd94c930ed7f7722bd8426b326/addons/sourcemod/scripting/shavit-core.sp#L2219

**Comment by rtldg** [comment]
sqlite should work for the most part with migrations but `alter table` & migrations can be iffy so it isn't recommended for a bhoptimer db.
Anyways, this is an old issue, I can't imagine you still need that db fixed (not that I would try to fix it), and most migrations should be sqlite compatible these days so I'll close this issue.
