### ISSUE TITLE
Player velocity

### ISSUE THREAD

**Issue by Zetsuyaa** [shavitush/bhoptimer#833]
Hello, I've been trying to setup a private server for me for either bhop and trikz, but I noticed my player speed goes to about 286 strafing without jumping while on any other server it goes to about 270ish. I also can't do runboosts and I believe its the same issue. I've tried to do accelerate 5 and airaccelerate 100/150 but nothing seems to change the speed. If I do accelerate 4 the speed slows down to about 230-240 strafing but it's pointless to lj this way.

**Comment by daniel3k3** [comment]
what speed do you get walking without prestrafing? if you get 260 its normal youre getting 286 with prestrafing. keep airaccelerate on 1000 if youre doing autobhop and accelerate on 5 too. to change runspeed go on shavit-styles.cfg and in the style youre looking for change "runspeed" from "260.00" to "250.00"

**Comment by Zetsuyaa** [comment]
Thanks, that solved it :)

**Comment by Zetsuyaa** [comment]
Now the problem is that when I'm perfoming a runboost, the player on top of me runs faster than me making it impossible to do it. How do I fix it?

**Comment by daniel3k3** [comment]
you should both have the same speed if you are using the same style. make sure hes not on legit while youre on auto or vice versa, otherwise youll need someone smarter than me

**Comment by Zetsuyaa** [comment]
Unfortunaly we both are on same style. Checking on any other bhop/trikz server, i see my maxspeed is 260 and when strafing around 276. There's something making my player's movement faster  on my server and I can't figure out what.

**Comment by Zetsuyaa** [comment]
BUMP

The player movement speed is fixed, the problem now is the runboost. The player on top gets faster as soon as he lands on the head of the player on the ground making it impossible to rb, unless the player on top stops and them jump so  both run at the same time.

**Comment by daniel3k3** [comment]
i really dont understand what you mean. if the top player is coming with speed and just holds w, its very normal that hes gonna end up falling in front of the bottom player in the rb since he already has speed. thats why everyone just stops and does a jump so they both start running at the same time.

**Comment by Zetsuyaa** [comment]
Here's what happens on my server:
https://www.youtube.com/watch?v=uHOvAJoFWsQ&feature=youtu.be

Heres what it should be and it is on any other server: 

https://www.youtube.com/watch?v=ecXNNH6L0wk&feature=youtu.be

**Comment by daniel3k3** [comment]
Im not sure its the issue, but does the style youre on have easybhop "on" (stamina off)? It should have easybhop off, that might work(trikz is played with stam)

**Comment by Zetsuyaa** [comment]
Unfortunaly I have already disabled it.

I appreciate that you're trying to help me, thanks!
