### ISSUE TITLE
!profile won't work.

### ISSUE THREAD

**Issue by Sacricx** [shavitush/bhoptimer#834]
Hey na, 
I run 2 CS:GO Servers on a Dedicated Server. I did the same steps as usual when installing this timer on a new server: Drag&Drop the files, adding an entry in the database.cfg + created a database in mysql. 

Today I wanted to reinstall my 2 servers to have a clean setup with the bhop timer ver. 2.5.5a.
when I type !profile ingame on my servers, then the menu wont show up. Instead I see in the error logs this: 

[shavit-stats.smx] Timer (statsmenu) SQL query failed. Reason: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank FROM users u1 JOIN (SELECT points FROM users WHERE auth = 35819838) u2 WHER' at line 1

Anyone an idea ? 

Thanks in Advance !

Sacricx

**Comment by shavitush** [comment]
mysql version?

**Comment by Sacricx** [comment]
Server version: 8.0.17

**Comment by shavitush** [comment]
```sql
SHOW CREATE TABLE users;
```

pretty please

**Comment by Sacricx** [comment]
Ty very much for your time its appreciated !

I did successfully execute that in the timer database, restarted the server, typed !profile in the chat, but sadly the same result.

**Comment by shavitush** [comment]
the query outputs a resultset with a query; i need to see the resultset

**Comment by Sacricx** [comment]
![results](https://user-images.githubusercontent.com/42757343/66248167-df6f5d80-e723-11e9-9d4c-975b051d340b.PNG)

**Comment by shavitush** [comment]
bro i need the entire thing lol

**Comment by Sacricx** [comment]
Could you be more specific ? I only created Databases and imported Datbases so far. This is a little new to me. How do I provide what you need ? 

When I execute the query, I get the result you see there in the picture. When you need something else, please tell me what exactly you need and where to find it.

Sorry for the incompetency at this point. Usually I dont have to deal with such things.

**Comment by Sacricx** [comment]
Sorry, my fault:

![aefaefaef](https://user-images.githubusercontent.com/42757343/66249730-1bacb900-e738-11e9-9ad8-7f3d4ed08952.PNG)

I just had to enable full text *facepalm*

I guess that is what you need then.

**Comment by shavitush** [comment]
you're running an old version of the database

run the migrations command when the server is empty and is password protected, see if it fixes the issue; sm_migrations all

give it up to 15 minutes before you restart the server

**Comment by Sacricx** [comment]
Yeah, I saw that in your release notes for updating the timer when an old Database is present.

But Im running the new CS:GO server with a new Timer Database. Its not possible that I run the old Database with the new server since I made sure to setup everything properly. 

Maybe snipped accidentally the old database resultset. But the new server runs 100% with the a created Database. I did update the Picture in my post as you can see with the new Database resultset.

**Comment by Sacricx** [comment]
So, What I did is this:

1. Downloaded a *new* CS:GO Server via *steamcmd*
2. Added the latest *Metamod 1.10* and *Sourcemod 1.10* 
3. Added an entry in *sourcemod/database.cfg* 
4. Completley reinstalled the latest WAMP Stack and started MYSQL & Apache Server.
5. Created a new Database called *bhoptimer* with *utf8mb4_general_ci* collation
6. Dragged&Dropped the latest Timer files into csgo/
7. Started the server, joined, typed !profile = same error:

L 10/06/2019 - 00:52:12: [shavit-stats.smx] Timer (statsmenu) SQL query failed. Reason: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank FROM users u1 JOIN (SELECT points FROM users WHERE auth = 35819838) u2 WHER' at line 1

P.S. Also I tried to recompile all modules with the latest Sourcemod 1.10 but got the same result.

Any idea ? @shavitush

**Comment by Nairdaa** [comment]
> SELECT points FROM users WHERE auth = 35819838

"rank FROM users u1 JOIN (SELECT points FROM users WHERE auth = 35819838) u2 WHER" why is there a "WHER" at the end instead of "WHERE"?

**Comment by Nairdaa** [comment]
Do you have access to SSH? Can you check your MySQL version, please?

> # mysql -V
mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper
root@Ubuntu-1604-xenial-64-minimal ~ #

**Comment by Sacricx** [comment]
> 
> 
> Server version: 8.0.17

**Comment by Sacricx** [comment]
Im operating on Windows Dedicated Server Datacenter 2016 not Linux

**Comment by Nairdaa** [comment]
Whoops.

Message me on Discord please.

**Comment by Sacricx** [comment]
I need your Discordtag then :P

**Comment by Nairdaa** [comment]
You're not on shavit's discord? https://discord.gg/sHrBWv
My DC tag is Nairda#2748

**Comment by Sacricx** [comment]
The error is kinda "fixed" by (who thought it could be that) not using WAMP. I did install XAMPP for test purpose and *tadaaaa* !profile works and no SQL error >_>

Strange is just, that this problem did never occur with WAMP before. Even with a reinstallation of WAMP the problem could not be solved. Maybe its an issue with the latest version of it. Who knows.

Nairda recommended this as alternative: https://laragon.org/

Huge thx to @Nairdaa for figuring that out with me !
And ofc ty also for *your* time @shavitush !

**Comment by Nairdaa** [comment]
Well if it works on XAMPP, then it will work on laragon as well. Just switch to linux already instead.

**Comment by Sacricx** [comment]
I noticed, That the new MYSQL version 8.0 and higher caused the problem with a 80% chance. 
Even a usbserver with apache, php, mysql was able to handle the !profile command. And it was mysql version 5.6. Maybe this helps you other guys, if you have any problem with that.

**Comment by shavitush** [comment]
use newest mariadb
