### ISSUE TITLE
Shavit-Misc prevents players from joining directly into the spectator team

### ISSUE THREAD

**Issue by turtlshell** [shavitush/bhoptimer#838]
As the title says, players who join the server can't join the spectators team directly. They have to join a team first, then go into specs.
I've had a few complaints about this so I felt it necessary to open an issue.
Interestingly, when the cvar "shavit_misc_respawnonteam" is set to 0 it does let players join directly to spectators, although this of course prevents them from spawning once they try to join a non-spectator team.

**Comment by Lightningblade** [comment]
THATS RIGHT, I COMPLAINED ABOUT THIS SHIT. WHEN YOU CLICK 6 OR ON SPECTATOR ON JOIN 
![image](https://user-images.githubusercontent.com/30607152/68093379-4bfd8980-fe95-11e9-85f1-8e2e11a03ec7.png) YOU SPAWN IN. WTF. LIKE I HAVE THE TIME TO WASTE 1,14 SECONDS EVERY TIME IM JOINING A SERVER.

**Comment by turtlshell** [comment]
This is what I have to deal with on a daily basis.

**Comment by Nairdaa** [comment]
Yea, shavit, fix your shit.

**Comment by mighty9245** [comment]
Yea, shavit, fix your shit.

**Comment by blankbhop** [comment]
Yea, shavit, fix your shit. I'm literally pissed.

**Comment by strafe** [comment]
What's your `mp_humanteam` value?

**Comment by shavitush** [comment]
Yea, shavit, fix your shit. I'm literally pissed.

**Comment by Nairdaa** [comment]
> What's your `mp_humanteam` value?

It's T.

**Comment by strafe** [comment]
If you have an `mp_humanteam` value that corresponds to a team, it overwrites the team you're attempting to join when you use the `jointeam` command (the choose team menu uses this).
https://github.com/shavitush/bhoptimer/blob/979c911a268f22bd94c930ed7f7722bd8426b326/addons/sourcemod/scripting/shavit-misc.sp#L663-L672

**Comment by Nairdaa** [comment]
Will it not make you spawn at any team then?

**Comment by strafe** [comment]
It will try to spawn on on whichever team you've defined with `mp_humanteam` even if you select spectator.

**Comment by turtlshell** [comment]
so bAsically I have to choose between (1) letting people join spec from connect but they can join ct or t (2) not letting people join spec from connect but i can force all humans to T so they are separate from the replay bot

**Comment by strafe** [comment]
At the moment yeah pretty much, if you use the change in #839 you can have both.

**Comment by Nairdaa** [comment]
or (3) ill edit the spawn thing to force spawn players on T.

**Comment by turtlshell** [comment]
nairda made a workaround. closing :)
