### ISSUE TITLE
Admin command to restart a specifc replay 1.5b

### ISSUE THREAD

**Issue by StrafeHack** [shavitush/bhoptimer#84]
This basically goes along with my other request as it's related to helping with recording demos.

You may already know of this issue but on almost every server with bots when the map changes the bot starts the run before any player can load and and start spectating it, on long maps this means you must wait the for the bot to finish a whole lap and then another just to get the recording.

SrcDemo also seems to get choppy if you start the movie recording quite far into the demo (10 mins+) but never if you start it within the first 30 seconds. Although this might just be for me.

Just thought, this doesn't resolve the issue for general players, so maybe if you do add the bots freezing on the first frame, make them freeze quite a bit longer for the first start of the map.

**Comment by shavitush** [comment]
added first/last frame freezing, re-open if you still need this command
