### ISSUE TITLE
CS:GO Update Hint styles issue

### ISSUE THREAD

**Issue by T1MOXA** [shavitush/bhoptimer#840]
After today update hint messages was broken.
![image](https://user-images.githubusercontent.com/19938629/69150513-8005bb00-0ae1-11ea-88ac-5793916c9c7a.png)
Any ideas ?

**Comment by Lightningblade** [comment]
Might have set a new standard for the markup language. Read the patch notes, or documentation

**Comment by SaengerItsWar** [comment]
here is a updated version posted on discord https://cdn.discordapp.com/attachments/389675820412698628/646306269493329950/shavit-hud.sp

**Comment by itstragicz** [comment]
![Capture](https://user-images.githubusercontent.com/33912221/69247906-282f8880-0ba3-11ea-81e9-4d453b6d5b5d.PNG)

Didn't work for me, (i put it in the scripts folder with all the other.sp's).

**Comment by csestonia** [comment]
Did not work for me! tried 5 different plugins Franc1scos and fenix! 
It was very strange it actually worked the fenix plugin but after I started updading levels ranks it just stoped working! I didnt touch anything else! and by now I updated sm, exts and stuff! but still
I dont understand whats the issue! 
I seriously tried 5 different plugins! ofcourse I didnt do restart for server I hope this is not a big issue! I tried to play with sm plugins load/unload and also with changing map!


<img width="794" alt="Screen Shot 2019-12-02 at 10 26 47 am" src="https://user-images.githubusercontent.com/58268449/69943764-53dd3780-14ee-11ea-8c8b-056e0b05884b.png">
<img width="536" alt="Screen Shot 2019-12-02 at 10 26 32 am" src="https://user-images.githubusercontent.com/58268449/69943765-53dd3780-14ee-11ea-9ab5-8662122a65f6.png">

**Comment by csestonia** [comment]
Update:
It did fix [SHOP] Roll Hint box! 
But still the screenshot from above is not working!

**Comment by Nairdaa** [comment]
> ofcourse I didnt do restart for server I hope this is not a big issue!

...

**Comment by csestonia** [comment]
> > ofcourse I didnt do restart for server I hope this is not a big issue!
> 
> ...
lol...
It did help to fix issue with SHOP Roll hint text with no restart! )
