### ISSUE TITLE
Server crashes with mapconfigs plugin while changing map 

### ISSUE THREAD

**Issue by caleon1** [shavitush/bhoptimer#846]
Hello, I have a problem where the server would crash every time I enable/disable the plugin with berni's [mapconfigs](https://forums.alliedmods.net/showthread.php?p=607079) plugin.

In the map specific configs unload complete bhoptimer plugins with the cmd "sm plugins unload", then if I change to a map (where bhoptimer is loaded by default) from a a map where the bhoptimer is disabled, the server crashes with no errors logged.

I found out that the same issue was here: [LINK](https://github.com/shanapu/MyJailbreak/issues/280)

Any ideas how to fix this issue?

**Comment by mighty9245** [comment]
afaik bhoptimer doesn't support late loading and there is not much you can do about that

**Comment by kidfearless** [comment]
The timer doesn't support late-loading and probably never will.
