### ISSUE TITLE
replay Where to store documents？

### ISSUE THREAD

**Issue by qq1461513552** [shavitush/bhoptimer#848]

**Comment by blankbhop** [comment]
Elaborate please, are you asking where replaybot data is stored?

**Comment by deadw1nter** [comment]
[wiki page](https://github.com/shavitush/bhoptimer/wiki/2.4.-Configuration:-Replay) If you mean configuring replay settings, check

**Comment by kidfearless** [comment]
It's been 3 weeks since this was posted, so I'm going to close it.
