### ISSUE TITLE
[ Suggestion ] wipeplayer addition

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#849]
Could you please make it so that all the wr replay files of the player that's being wiped out off the database get deleted too?

**Comment by kidfearless** [comment]
They already do get deleted, `DeleteUserData` in shavit-core handles that.

**Comment by Nairdaa** [comment]
The fuck? Well, I got plenty of zeltim's replays and he's been removed from the db with !wipeplayer :/

**Comment by Nairdaa** [comment]
https://github.com/shavitush/bhoptimer/blob/979c911a268f22bd94c930ed7f7722bd8426b326/addons/sourcemod/scripting/shavit-core.sp#L771

Where is the part covering the file deletion?

**Comment by kidfearless** [comment]
The first if statement in the function, along with the various callbacks for it. I can't remember for certain, but I believe that the replay format can affect whether or not it will be deleted with !wipeplayer.
https://github.com/shavitush/bhoptimer/blob/979c911a268f22bd94c930ed7f7722bd8426b326/addons/sourcemod/scripting/shavit-core.sp#L773-L785
