### ISSUE TITLE
Server Record Demos - Cvar to set amount to be saved per map.

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#85]
The situation that this would be used is for example, if the value was set to 3, 3 demos of each style could be saved, in this case, should the #1 record be scripting or something like that, that demo can be deleted and the lower demo used. 

More of a use to stop having to use no demo at all.

**Comment by shavitush** [comment]
might be added when i rewrite the replay bot plugin from scratch (1.5b), i don't guarantee anything though

**Comment by shavitush** [comment]
have decided this is really only for rare cases and decided to not write it, sorry
