### ISSUE TITLE
hud not desplaying html correct

### ISSUE THREAD

**Issue by NordicGamerFE** [shavitush/bhoptimer#850]
anyone know what would cause this?
![image](https://user-images.githubusercontent.com/18188155/71875186-0161ed00-3124-11ea-8a80-dc2f9846a986.png)

**Comment by freakexeuLow** [comment]
> 
> 
> anyone know what would cause this?
> ![image](https://user-images.githubusercontent.com/18188155/71875186-0161ed00-3124-11ea-8a80-dc2f9846a986.png)

Here's the fix: [https://github.com/Franc1sco/FixHintColorMessages](https://github.com/Franc1sco/FixHintColorMessages)

**Comment by mighty9245** [comment]
> anyone know what would cause this?
the fact that you are playing a broken game

**Comment by kidfearless** [comment]
csgo dropped support for html elements in the center hud. Use the fix provided above.
