### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Veeksi** [shavitush/bhoptimer#851]
Is it possible to disable plugin itself via convar, like changing sv_enablebunnyhopping and sv_autobunnyhopping to 0 (Impossible with sm_cvar atleast)? I'd like to use it just when I exec my specific config not always but loading shavit-core.smx aftwerwards gives error so I guess because it works w/ mysql it can't be loaded afterwards.

**Comment by Veeksi** [comment]
Like my server is normally used for dm, but sometimes we would like to bhop so I could execute my own config which loads all needed plugins.

**Comment by kidfearless** [comment]
No, the plugin doesn't support late-loading and probably never will.
