### ISSUE TITLE
[request] killfeed enable

### ISSUE THREAD

**Issue by stub3** [shavitush/bhoptimer#855]
Could it be possible to add enabling killfeed? It would help to see time when I, or someone dies at a point in map.

**Comment by mighty9245** [comment]
for what purpose?

**Comment by stub3** [comment]
On a server that has deaths possible to make things harder, to see how far you have progressed in the level. Without it you cannot know how good you did precisely, with a time on killfeed (that probably will be automatic given that the time spent is on scoreboard) you can compare your time to a point in a map and see how you did.

**Comment by mighty9245** [comment]
bro, it's bhoptimer, it's not meant to be used with other gamemodes than bhop

**Comment by stub3** [comment]
alright, thanks for your time

**Comment by shavitush** [comment]
shavit_misc_hideteamchanges 0

**Comment by stub3** [comment]
thanks!

**Comment by Nairdaa** [comment]
you're welcome
