### ISSUE TITLE
! commands are not hidden

### ISSUE THREAD

**Issue by NordicGamerFE** [shavitush/bhoptimer#856]
when i do ! commands they arent hidden and shown in chat any fixes anyone know or the issue?

**Comment by Nairdaa** [comment]
It's a sourcemod config, has nothing to do with the timer.

**Comment by shavitush** [comment]
@Nairdaa the timer actually hides them by default

@NordicGamerFE do you use a custom chat processor?

**Comment by NordicGamerFE** [comment]
Yes i use chat processor

**Comment by Nairdaa** [comment]
Then don't use it :P

**Comment by NordicGamerFE** [comment]
@Nairdaa also i usually use one place for everything close related to shavits so people have a good place to go when they got a issue

**Comment by NordicGamerFE** [comment]
also while i am here. i heard there is a plugin for auto zones when the map has premade end and start buildt in you wouldnt know anything about this?

**Comment by shavitush** [comment]
this bhop timer is the first public plugin to implement premade zones, it's been a feature for a good while now. assuming the map has zones built in per the [Fly zoning standards](https://github.com/3331/fly), the zones will work as well as !r, !end, bonus as well

**Comment by strafe** [comment]
The intended way to do this is through SourceMod's `core.cfg`, specifically [this](https://github.com/alliedmodders/sourcemod/blob/master/configs/core.cfg#L32-L40) section. Set silent to `"/!"` and public to `""`.

**Comment by NordicGamerFE** [comment]
Thank you for your respond but this did nothing :(

Sincerely Kevin

**Comment by kidfearless** [comment]
That is the solution though
