### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by NickFlamel13** [shavitush/bhoptimer#858]
Hello my friend! How fix this problem? 
![20200215202111_1](https://user-images.githubusercontent.com/33942668/74592447-8cdb7180-5032-11ea-8f9c-76dd872951d2.jpg)

**Comment by cytrus224** [comment]
https://github.com/Franc1sco/FixHintColorMessages

**Comment by NickFlamel13** [comment]
> https://github.com/Franc1sco/FixHintColorMessages

Thanks fo hel me!
