### ISSUE TITLE
Problem with hub

### ISSUE THREAD

**Issue by DaigoBhop** [shavitush/bhoptimer#860]
Hello ,I have a problem with the hub and I am not good at fixing problems.
https://www.noelshack.com/2020-08-7-1582457174-counter-strike-global-offensive-screenshot-2020-02-23-12-12-42-34.jpg

Help pls.

Sry for my english...

**Comment by freakexeuLow** [comment]
> 
> 
> Hello ,I have a problem with the hub and I am not good at fixing problems.
> https://www.noelshack.com/2020-08-7-1582457174-counter-strike-global-offensive-screenshot-2020-02-23-12-12-42-34.jpg
> 
> Help pls.
> 
> Sry for my english...

[https://github.com/shavitush/bhoptimer/issues/858](https://github.com/shavitush/bhoptimer/issues/858)

**Comment by DaigoBhop** [comment]
> > Hello ,I have a problem with the hub and I am not good at fixing problems.
> > https://www.noelshack.com/2020-08-7-1582457174-counter-strike-global-offensive-screenshot-2020-02-23-12-12-42-34.jpg
> > Help pls.
> > Sry for my english...
> 
> #858

Fixed now ty
