### ISSUE TITLE
[ Request ] ccname/ccmsg

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#861]
Hello,

Could you please make the access to that be stored in MySQL instead of admin flags? It would be really nice to just type !ccadd [playername/steamid] or !ccdelete as an admin rather than browsing the server files and giving somebody an admin flag.

**Comment by Nairdaa** [comment]
Bump! :< k3n pls, i know you love mysql

**Comment by rtldg** [comment]
added sm_ccadd and sm_ccdelete in https://github.com/shavitush/bhoptimer/commit/19c5ccb7f38cc793f974a2c118c1c10ccc20e71a
let me know if you have any problems
