### ISSUE TITLE
Native is not bound

### ISSUE THREAD

**Issue by Septembers** [shavitush/bhoptimer#869]
i use Latest commit 53d7150

L 03/25/2020 - 11:08:27: [SM] Exception reported: Native is not bound
L 03/25/2020 - 11:08:27: [SM] Blaming: shavit/shavit-hud.smx
L 03/25/2020 - 11:08:27: [SM] Call stack trace:
L 03/25/2020 - 11:08:27: [SM]   [1] Shavit_InsideZone
L 03/25/2020 - 11:08:27: [SM]   [2] Line 1354, C:\Users\September-PC\Desktop\COMPILE 1.10\shavit-hud.sp::UpdateMainHUD
L 03/25/2020 - 11:08:27: [SM]   [3] Line 873, C:\Users\September-PC\Desktop\COMPILE 1.10\shavit-hud.sp::TriggerHUDUpdate
L 03/25/2020 - 11:08:27: [SM]   [4] Line 865, C:\Users\September-PC\Desktop\COMPILE 1.10\shavit-hud.sp::Cron
L 03/25/2020 - 11:08:27: [SM]   [5] Line 765, C:\Users\September-PC\Desktop\COMPILE 1.10\shavit-hud.sp::OnGameFrame

![image](https://user-images.githubusercontent.com/30748067/77542268-fb73e080-6eb6-11ea-8d20-09eb38dc5c22.png)

**Comment by mighty9245** [comment]
scroll up, there should be main error somewhere in the beggining that causes this spam
