### ISSUE TITLE
shavit_misc_prespeed don't take changes

### ISSUE THREAD

**Issue by wer1Kua** [shavitush/bhoptimer#87]
On any value of shavit_misc_prespeed I still can't jump on startzone.

**Comment by shavitush** [comment]
cfg/sourcemod/plugin.shavit-core.cfg
shavit_core_blockprejump 0

**Comment by wer1Kua** [comment]
Thanks. But I don't understand why this convar don't generated in my plugin.shavit-core.cfg, I'm just put them into this file.
