### ISSUE TITLE
Teams Bug

### ISSUE THREAD

**Issue by xFlume** [shavitush/bhoptimer#873]
Hey,
i got Shavit BhopTimer Plugin (2.5.6) and when someone join to CT Team so the round just restart and its doing all the cvars and match start how can i fix it ?

**Comment by xFlume** [comment]
i know the bug is cuz you got x seconds to join team if not is will force pick team for you and i want to disable it to test if the problem solved someone can help me ?

**Comment by xFlume** [comment]
problem is solved

**Comment by Cruze03** [comment]
Hello how did you fix this issue?
