### ISSUE TITLE
Improve stages

### ISSUE THREAD

**Issue by mbhound** [shavitush/bhoptimer#875]
1. Start zone should be considered zone 1 and all other created zones should be greater than 1
1a. !s # should take you back to that stage
2. The time it takes to go from the last stage to the end zone should be printed in chat
3. (maybe) keep the time running if you want to go back to a zone that you already passed
3a. Have a sm_back command which restarts you on that stage

**Comment by BoomShotKapow** [comment]
#1042 If you'd like to give it a look and let me know if there's anything you'd like to see that was missed.
