### ISSUE TITLE
Native to get client status of !hide

### ISSUE THREAD

**Issue by Cruze03** [shavitush/bhoptimer#876]
As the title says, can you create a new native to get client's status of !hide which returns boolean value? Thanks <3

**Comment by Cruze03** [comment]
[OFFTOPIC]
Oh! And another small issue is that when shavit-chat.smx is installed, chat sound still plays even when shavit_core_nochatsound is 1. [https://github.com/shavitush/bhoptimer/blob/2ad6152c82ac47dcec4fe4937e5d266a26e1b3c5/addons/sourcemod/scripting/shavit-chat.sp#L491]Boop(url)

**Comment by EvanIMK** [comment]
> As the title says, can you create a new native to get client's status of !hide which returns boolean value? Thanks <3
This should work. 74a903309a48859790531d64319c6dd1cfd81019

> Oh! And another small issue is that when shavit-chat.smx is installed, chat sound still plays even when shavit_core_nochatsound is 1. [https://github.com/shavitush/bhoptimer/blob/2ad6152c82ac47dcec4fe4937e5d266a26e1b3c5/addons/sourcemod/scripting/shavit-chat.sp#L491](url)

I'm pretty sure this is a sourcemod/csgo bug. Updating to sourcemod 1.11 fixed this for me.

**Comment by Cruze03** [comment]
Thanks EvanlMK <3
