### ISSUE TITLE
Can we somehow change style settings per map?

### ISSUE THREAD

**Issue by Cruze03** [shavitush/bhoptimer#877]
As the title says, is it possible to change style settings like "velocity_limit" in per map basis? Thanks :)

**Comment by kidfearless** [comment]
Functionality already exists though the documentation isn't very clear on it.

The best way to do this would be inside the `Shavit_OnStyleConfigLoaded` forward. Then using the `Shavit_GetStyleSettings` you would get a reference to the style settings for the style you want to modify. Changes to the enum struct should be copied back.

**Comment by Cruze03** [comment]
A little example/snippet for normal style would help :(

**Comment by kidfearless** [comment]
```
#include <sourcemod>
#include <shavit>

public void Shavit_OnStyleConfigLoaded(int styles)
{
	char map[PLATFORM_MAX_PATH];
	GetCurrentMap(map, PLATFORM_MAX_PATH);
	if(StrContains(map, "bhop_lego2") != -1)
	{
		for(int style = 0; style < styles; ++style)
		{
			stylesettings_t settings;
			Shavit_GetStyleSettings(style, settings);
			settings.fVelocityLimit = 3500.0;
		}
	}
}

**Comment by Cruze03** [comment]
`#include <sourcemod>
#include <shavit>

#pragma semicolon 1
#pragma newdecls required

float g_fDefaultVelocityLimit;

public void Shavit_OnStyleConfigLoaded(int styles)
{
	char map[PLATFORM_MAX_PATH];
	GetCurrentMap(map, PLATFORM_MAX_PATH);
	if(StrEqual(map, "workshop/1264810092/bhop_sandtrap", false) || StrEqual(map, "bhop_sandtrap", false) || StrEqual(map, "bhop_icetrap", false))
	{
		stylesettings_t settings;
		Shavit_GetStyleSettings(0, settings);
		g_fDefaultVelocityLimit = settings.fVelocityLimit;
		settings.fVelocityLimit = 4500.0;
	}
}

public void OnMapEnd()
{
	if(StrEqual(map, "workshop/1264810092/bhop_sandtrap", false) || StrEqual(map, "bhop_sandtrap", false) || StrEqual(map, "bhop_icetrap", false))
	{
		stylesettings_t settings;
		Shavit_GetStyleSettings(0, settings);
		settings.fVelocityLimit = g_fDefaultVelocityLimit;
	}
}`
No velocity limit change in Normal style :(

**Comment by Nairdaa** [comment]
if(StrEqual(map, "workshop/1264810092/bhop_sandtrap", false)


set to true

**Comment by Cruze03** [comment]
I don't think that'd make difference though

**Comment by Nairdaa** [comment]
then don't do it

**Comment by kidfearless** [comment]
You can now set style settings mid-game, They will be reset every time the style config is loaded. Here is how you would set the velocity limit to 4500.0 for normal on bhop_sandtrap and bhop_icetrap.
```
#include <shavit>

public void Shavit_OnStyleConfigLoaded(int styles)
{
	char map[PLATFORM_MAX_PATH];
	GetCurrentMap(map, PLATFORM_MAX_PATH);
	GetMapDisplayName(map, map, PLATFORM_MAX_PATH);
	if(StrEqual(map, "bhop_sandtrap", false) || StrEqual(map, "bhop_icetrap", false))
	{
		Shavit_SetStyleSettingFloat(0, "velocity_limit", 4500.0);
	}
}
```
