### ISSUE TITLE
Map does not change after round and timelimit end

### ISSUE THREAD

**Issue by wer1Kua** [shavitush/bhoptimer#88]
I have a bug. Testing in 2 different servers and trying different methods for nextmap voting - they don't work on new version bhoptimer. With default mapchooser from SM 1.8 vote is present, but map don't change after out of timelimit and roundtime. With UMC or default Valve voting (mp_endmatch_votenextmap 1 without any plugins) vote is missing and also map don't change.

Also I'm trying change this cvar's:
mp_timelimit 2
mp_maxrounds 0
mp_roundtime 2
mp_ignore_round_win_conditions 1

But this is don't work. How to fix change map on the server?

**Comment by shavitush** [comment]
i see, that's caused because of the 'round draw' fix i added. i'll try to find a solution
