### ISSUE TITLE
[ Suggestion ] bot steps

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#880]
"shavit_misc_bhopsounds - Should bhop (landing and jumping) sounds be muted? 0 - Disabled 1 - Blocked while !hide is enabled 2 - Always blocked"

shavit_misc_bot_bhopsounds

to hear the jumps of a bot while spectating them/next to you. Will probably be cancer because of the fact they are in noclip, but hey, always an idea.

**Comment by mbhound** [comment]
Also disable glock switching fire mode sounds

**Comment by kidfearless** [comment]
Bots don't jump, which is why any ssj plugin will have trouble with them.
> Also disable glock switching fire mode sounds
That's already a convar, or can be enforced with existing convars
