### ISSUE TITLE
[ Request ] Make a cvar to show keys pressed by default to everyone 

### ISSUE THREAD

**Issue by freelayer** [shavitush/bhoptimer#888]
Help, I can't find the cvar

**Comment by Nairdaa** [comment]
there isn't one

**Comment by freelayer** [comment]
Well..... what if I wanted to people have this enabled by default ? , Can I do that somehow?

**Comment by Nairdaa** [comment]
You'd have to edit the timer's code. The least you can do is just ask for a CVAR to be added in the next release for that.

**Comment by bali2k** [comment]
You can set what to show default in shavit-hud.sp
There's a line with `#define HUD_DEFAULT` where you set what to show default and `#define HUD_DEFAULT2` what to hide default. So in your case you have to edit line `#define HUD_DEFAULT` and add there `HUD_KEYOVERLAY`.
