### ISSUE TITLE
Using native Shavit_SetClientTimescale only affects players within the start zone

### ISSUE THREAD

**Issue by hermansimensen** [shavitush/bhoptimer#892]
Video showing that the timescale gets reset as soon as you leave the startzone: https://drive.google.com/file/d/1snvEc85KPIm2T3xvlGNO7OLRqSJ4c5yI/view?usp=sharing

I made a simple test plugin for testing if there was something wrong with my TAS plugin, or if the problem was with the natives.
 
```
#define DEBUG

#define PLUGIN_NAME           "timescaletest"
#define PLUGIN_AUTHOR         ""
#define PLUGIN_DESCRIPTION    ""
#define PLUGIN_VERSION        "1.0"
#define PLUGIN_URL            ""

#include <sourcemod>
#include <sdktools>
#include <shavit>
#pragma semicolon 1


public Plugin myinfo =
{
	name = PLUGIN_NAME,
	author = PLUGIN_AUTHOR,
	description = PLUGIN_DESCRIPTION,
	version = PLUGIN_VERSION,
	url = PLUGIN_URL
};

public void OnPluginStart()
{
	RegConsoleCmd("sm_scale", Command_Scale);
}

public Action Command_Scale(int client, int args)
{
    PrintToServer("Setting scale to 0.2");
    setTimescale(client, 0.2);
    return Plugin_Handled;
}

void setTimescale(int client, float timescale) 
{
	Shavit_SetClientTimescale(client, timescale);
} 
```

It yielded the same result

**Comment by Nairdaa** [comment]
There is no problem with natives. TAS works just fine. It's on your end.

**Comment by hermansimensen** [comment]
Further testing reveals that its not leaving the zone that is the problem. It's caused by the first jump after leaving the zone. Also affects bonus start zone.

**Comment by AlphaDelta** [comment]
Affects `player_speedmod` as well. Player's timescale is reset after every jump.

**Comment by Nairdaa** [comment]
@AlphaDelta https://github.com/CharlesBarone/bhoptimer/blob/master/addons/sourcemod/scripting/shavit-tas.sp
