### ISSUE TITLE
Server crash caused by the new timer version.

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#894]
Throttle dump: [https://pastebin.com/6KzFsVUv](url)

SM Error log:

> L 04/15/2020 - 23:56:53: [SM] Exception reported: Invalid plugin address
L 04/15/2020 - 23:56:53: [SM] Blaming: shavit-wr.smx
L 04/15/2020 - 23:56:53: [SM] Call stack trace:
L 04/15/2020 - 23:56:53: [SM]   [0] Call_Finish
L 04/15/2020 - 23:56:53: [SM]   [1] Line 2118, D:\steamcmd\css\cstrike\addons\sourcemod\scripting\shavit-wr.sp::Shavit_OnFinish
L 04/15/2020 - 23:56:53: [SM]   [3] Call_Finish
L 04/15/2020 - 23:56:53: [SM]   [4] Line 1532, D:\steamcmd\css\cstrike\addons\sourcemod\scripting\shavit-core.sp::Native_FinishMap
L 04/15/2020 - 23:56:53: [SM]   [6] Shavit_FinishMap
L 04/15/2020 - 23:56:53: [SM]   [7] Line 2960, D:\steamcmd\css\cstrike\addons\sourcemod\scripting\shavit-zones.sp::StartTouchPost

**Comment by kidfearless** [comment]
Closing this as it's been found that it's due to a third party plugin needing to be recompiled
