### ISSUE TITLE
Random Round Restart

### ISSUE THREAD

**Issue by Cruze03** [shavitush/bhoptimer#902]
Anyone else face this random round restart? I think it happens when shavit timer connects to mysql database, not sure. Only happens once every map, random time!

 any help is appreciated, facing and finding fix for this from a long time :(

**Comment by Nairdaa** [comment]
https://github.com/shavitush/bhoptimer/search?q=round+restart&type=Issues

**Comment by Cruze03** [comment]
All I found is `mp_autoteambalance 0`. Did that, still the same :/ Tried the latest plugin with SM 1.10 and MM 1.10 :(

**Comment by hermansimensen** [comment]
@Cruze03 Compile this and add to your plugins. 

`#include <sourcemod>
#include <cstrike>

public Action CS_OnTerminateRound(float &delay, CSRoundEndReason &reason)
{
    if(reason == CSRoundEnd_GameStart)
    {
        return Plugin_Handled;
    }

    return Plugin_Continue;
}
`

**Comment by Cruze03** [comment]
Can confirm that fixed the issue, thanks @hermansimensen <3
