### ISSUE TITLE
Issue with adding of tags to bhop server.

### ISSUE THREAD

**Issue by WonderCrust** [shavitush/bhoptimer#903]
Recently on our server we've decided to re do the chat ranks and add new tags based on player ranks, but for some reason only some tags are working and others have a completely invisible chat ID's so you don't even know who is sending a message. The server manager made a change so that the tags are based off of hard ranks instead of % of ranks but that had no effect. 

There are no errors in the logs, but the issue persists regardless of multiple server resets.

The information necessary according to your guidelines:

-Game: CSGO
-Yes latest steam version
-Server OS is Windows.
-Latest MM + SM

I have a list of all the servers Plugins and Extensions should you need it.

I will attach an image of the issue at hand that we are dealing with,

Much thanks.

PS: Custom tags still work.

![Chatrank missing](https://user-images.githubusercontent.com/64557153/80644201-90936780-8a69-11ea-8e30-f4b61f150686.png)

**Comment by cytrus224** [comment]
you should probably attach shavit-chat.cfg, thats kinda important

**Comment by WonderCrust** [comment]
> you should probably attach shavit-chat.cfg, thats kinda important

Will this suffice?

[MN7fpjjV.txt](https://github.com/shavitush/bhoptimer/files/4554512/MN7fpjjV.txt)

**Comment by Nairdaa** [comment]
try removing the hearts from the "1" tag, i wonder if 4 byte chars can fuck it up

**Comment by WonderCrust** [comment]
> try removing the hearts from the "1" tag, i wonder if 4 byte chars can fuck it up

We just adjusted and reset the server, still the same result

**Comment by Nairdaa** [comment]
Ok, I've no idea. Sorry.

**Comment by WonderCrust** [comment]
> Ok, I've no idea. Sorry.

Thank you anyway!

**Comment by WonderCrust** [comment]
We have resolved the issue, thanks you for the support.

**Comment by Nairdaa** [comment]
And what was the issue, in case someone else has the problem?
