### ISSUE TITLE
Terrible server performance at times when shavit_replay_prerun_always is enabled.

### ISSUE THREAD

**Issue by hermansimensen** [shavitush/bhoptimer#904]
Issue made on request by KiD Fearless.

After my public servers have been running for a few hours with the cvar enabled, it starts to lag. I could get around 150 sVar at times. After testing around I found this lag to be related to how many players are in the starting zone. The server lag continues even after map change, and the only thing that would stop it is to do a full restart of the server. 

After disabling this cvar, the servers have been running fine.

**Comment by kidfearless** [comment]
This should be fixed by https://github.com/shavitush/bhoptimer/tree/26c9f0381d875e353f564b75ebd6c57e9eae45a5 give it a try and let me know if that helps.
