### ISSUE TITLE
[?] Unreal style not working

### ISSUE THREAD

**Issue by Cruze03** [shavitush/bhoptimer#905]
Does it not work or does it need some external plugin?
You can just normally bhop around just like normal autobhop style
```
"13"
{
		"name"				"Unreal"
		"shortname"			"UR"
		"htmlcolor"			"B074C4"
		"command"			"unreal; ur"
		"clantag"			"UR"

		"autobhop"			"1"
		"easybhop"			"1"

		"unranked"			"0"
		"noreplay"			"1"

		"sync"				"1"
		"strafe_count_w"	"0"
		"strafe_count_a"	"1"
		"strafe_count_s"	"0"
		"strafe_count_d"	"1"

		"rankingmultiplier"	"0.8"

		"special"			"5" // unreal physics flag
}

**Comment by CharlesBarone** [comment]
Unreal is not included with the timer...

**Comment by CharlesBarone** [comment]
I assume you are referring to this plugin https://forums.alliedmods.net/showthread.php?t=241453

**Comment by Nairdaa** [comment]
`"special"			"5" // unreal physics flag`

This flag makes it more special than it's supposed to.

**Comment by kidfearless** [comment]
> does it need some external plugin?

yes, someone ported the plugin above to shavits timer a few years ago. I think it was in the wiki at one point but it doesn't seem to be there.

Here's an old copy of it I had laying around, it doesn't compile anymore so you'd have to make some changed
[unrealphys.zip](https://github.com/shavitush/bhoptimer/files/4796004/unrealphys.zip)
