### ISSUE TITLE
Map Tiers

### ISSUE THREAD

**Issue by Technoblazed** [shavitush/bhoptimer#91]
maptiers table added to the database schema

**Comment by shavitush** [comment]
i dont understand

**Comment by Technoblazed** [comment]
The ability to add map tiers to maps, and have the player view the tier of the map on connect, would be a nice feature to have to display the difficulty to the client. Tiers could be stored in a database and added to each map.

**Comment by shavitush** [comment]
oh ok

**Comment by shavitush** [comment]
when i start working on tiers, i'll use a dedicated sqlite database for tiers (only within shavit-rankings) as i can't modify existing sqlite tables and we don't want data loss
