### ISSUE TITLE
Shavit-replay console errors

### ISSUE THREAD

**Issue by 5H4D0W5T4LK3R** [shavitush/bhoptimer#910]
I'm running a bhop server for quite a while now with the shavit plugin. Yesterday I decided to update the plugin again since April, since yesterday my console is getting spammed with this. 

https://pastebin.com/piY9pL2q

I am running newest sourcemod + metamod and newest csgo update. I see 5 days ago there was a fix for a "replay bug" by "Nairdaa" but that also doesn't seem to work. This error causes my server's sv to go to 500.

Any help would be greatly appreciated

**Comment by kidfearless** [comment]
I haven't had time to work on the timer recently to fix the changes that were released. Please revert to release V2.5.6

**Comment by 5H4D0W5T4LK3R** [comment]
Awesome, thanks for the help! Rolled back, works for now
