### ISSUE TITLE
Wont let me set time for maps.

### ISSUE THREAD

**Issue by Spyrah** [shavitush/bhoptimer#911]
I want to set bhop timer to maps only go for 20 minutes then change. Is it locked with the plugin to a certain amount of time?

**Comment by Nairdaa** [comment]
No.

**Comment by Spyrah** [comment]
> No. mp_timelimit and disable dynamic map time inside of the timer configs

Ty! this worked but the time at the top doesn't change. It just stays default, but the map changes after the time ends. Is there any way to fix that?

**Comment by Nairdaa** [comment]
> Ty! this worked but the time at the top doesn't change. 

What do you mean? 
Just poke me on discord.

**Comment by Spyrah** [comment]
> > Ty! this worked but the time at the top doesn't change.
> 
> What do you mean?
> Just poke me on discord.

I just figured it out. Sorry for bugging, just changed things in a couple files. Ty for helping!!!
