### ISSUE TITLE
Ranks arent working

### ISSUE THREAD

**Issue by Spyrah** [shavitush/bhoptimer#912]
I tried to set up the ranks system with mysql and for some reason they dont work. I put all the information in the databases.cfg. Are the ranks just messed up?

**Comment by Nairdaa** [comment]
Yes, it's totally the timer's fault and 50 other servers that use the plugin have that issue too, but never wrote anything about it.

**Comment by Spyrah** [comment]
> Yes, it's totally the timer's fault and 50 other servers that use the plugin have that issue too, but never wrote anything about it.

so it is broken?

**Comment by Nairdaa** [comment]
Yea, completely broken.
[https://i.imgur.com/wxt9lX1.png](url)

**Comment by Velscard** [comment]
I am able to change the chat names, colors, and requirements for them, but the actual rankings to obtain them doesn't work. I don't know if I'm missing files or something but none of the commands that I have searched for have worked either. I believe this is the issue that Spyrah is also having but I'm not completely sure.

**Comment by Nairdaa** [comment]
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.
> Link some error logs, no1 here has a magical orb to predict what you've done wrong.

**Comment by kidfearless** [comment]
Closing this since it's been a month since he's last posted anything
