### ISSUE TITLE
Custom player models cause players to be teleported on certain maps

### ISSUE THREAD

**Issue by mbhound** [shavitush/bhoptimer#913]
1. Equip a custom player model in csgo
2. Spawn in and either type !spec and then !r or switch teams
3. Get randomly teleported in the map (usually directly above the start zone but not always the case)

Some maps which this occurs on: bhop_p03_go, bhop_cobblestones, bhop_qmpa

**Comment by mbhound** [comment]
Also:
- bhop_fuckdream
- bhop_easyhop_cozyedition_csgo
- bhop_nox

**Comment by sneak-it** [comment]
Fixed by manually updating CS:GO server. Looks like there is an optional update available that Valve failed to mention:
Prior to fix: `Protocol version 13752 [1105/1105]`
Fixed with version: `Protocol version 13752 [1107/1107]`
