### ISSUE TITLE
Noclip glitches

### ISSUE THREAD

**Issue by ProphetMuhammad11** [shavitush/bhoptimer#916]
Players can use noclip out of start and boost up, sometimes out of a map or on a wall to get a better time. If you could make it teleport the player back to the start once they leave noclip, it would fix it.

**Comment by Nairdaa** [comment]
> If you could make it teleport the player back to the start once they leave noclip, it would fix it.

Dumb idea. People use it very often to check if a jump is possible with higher speed etc. Just do it the way I have it done on Ultima. If noclip, timer can't start at all, even in startzone. If you noclip inside, timer stops. No way to get boosted up that way. Also why aren't you blocking the Z axis in start zone?

**Comment by kidfearless** [comment]
Implemented noclip restrictions in https://github.com/shavitush/bhoptimer/commit/16e832dc779956c27f507d3cea3938e68f4a72f3
