### ISSUE TITLE
Replay playback speed

### ISSUE THREAD

**Issue by stevenjw01** [shavitush/bhoptimer#917]
Currently using the latest source (5/31) and the latest build (2.5.6) the playback speed on 128 tick is twice as fast. When changing the server to 64 tick the replay speed is normal; I've tried deleting all records and recording them in 128 tick to see if that's the problem but nothing. This isn't using any fast forwarding just tick rate.

**Comment by azalty** [comment]
@kidfearless dead issue but this was a bug report, not a feature request 😆

**Comment by Nairdaa** [comment]
Instructions unclear, there are only 12 months in a year, while the OP states he's using source from 5th day of 31st month.

**Comment by azalty** [comment]
> Instructions unclear, there are only 12 months in a year, while the OP states he's using source from 5th day of 31st month.

YYYY/MM/DD > DD/MM/YYYY > MM/DD/YYYY

**Comment by Nairdaa** [comment]
Lol.

**Comment by rtldg** [comment]
nairda is telling me this is fixed and that it's fine to close

**Comment by Nairdaa** [comment]
I mean the tick shouldn't matter for the replay speed nowadays as long as they are using the newest timer. Idk about the situation on ancient versions like 2.5.6, probably still fucked.
