### ISSUE TITLE
[Request] Add {chatname} to clantag options

### ISSUE THREAD

**Issue by bali2k** [shavitush/bhoptimer#926]
It would be great if there was an option to add {chatname} to shavit-misc, which would get "name" without colors or just "display" from shavit-chat.cfg and show it on score board.

Current setup of the clantag from shavit-misc:

`// Custom clantag for players.`
`// 0 - Disabled`
`// {styletag} - style tag.`
`// {style} - style name.`
`// {time} - formatted time.`
`// {tr} - first letter of track.`
`// {rank} - player rank.`
`// -`
`// Default: "{tr}{styletag} :: {time}"`
`shavit_misc_clantag "{tr}{styletag} :: {time}"`

**Comment by rtldg** [comment]
Added `{cr}` to `shavit_misc_clantag` in https://github.com/shavitush/bhoptimer/commit/720ddeed1dacab3b39bde2ff926450a7ba81423b
