### ISSUE TITLE
Server Crash on Server Record being set

### ISSUE THREAD

**Issue by scrotumtotum** [shavitush/bhoptimer#936]
Hello, I am new to CSS servers but whenever a new record is set using the zone's on the server it crashes the server.

**Comment by kidfearless** [comment]
Any error logs, or an accelerator link?

**Comment by scrotumtotum** [comment]
Uh I going to be honest just started hosting a server today, I assume accelerator is some sort of error log program for servers, I will try to install that. An update to the issue though, I installed the latest version of bhoptimer because I was using an older version. The issue now is that when using the timer commands to create a zone of any sort whether it be start/end or main/bonus after hitting use to set the 2nd coordinate of the zone it doesn't give the prompt to finalize the zone meaning the next time I use the timer commands to set say an end zone it gets rid of the initial zone because there was no prompt to finalize it.

**Comment by kidfearless** [comment]
Without any error logs, I'd only be able to guess what your issue is. If you're crashing install [accelerator](https://forums.alliedmods.net/showthread.php?t=277703). Otherwise please post the error logs in your addons/sourcemod/logs folder.

**Comment by scrotumtotum** [comment]
[errors_20200710.log](https://github.com/shavitush/bhoptimer/files/4906264/errors_20200710.log)
This is the error log in my folder, I hope it helps, if not I am trying to install accelerator.

**Comment by scrotumtotum** [comment]
I installed accelerator but I still have the above issue where zones cannot be created which is preventing me from setting a new record to crash the server.

**Comment by kidfearless** [comment]
> Exception reported: MySQL is the only supported database engine for shavit-rankings.
You'll need to set up a mysql database if you want to use shavit rankings.

And i'm not sure what the trikz guys were thinking. But they've created an infinite loop by trying to finish each others runs when the other finishes.

**Comment by kidfearless** [comment]
Also make sure that you copied over the configs for shavit-sounds. If you don't want any sounds just leave the plugin off the server.

**Comment by scrotumtotum** [comment]
Ok so I just have to create a MySQL database, do you know any fix for the zone issue? What do you mean by copied over the configs? I copied all of the sounds from the bhoptimer sounds folder into the CSS server's sounds folder but I don't know where the configs would be?

**Comment by kidfearless** [comment]
I'd recommend using [releases](https://github.com/shavitush/bhoptimer/releases/) if you're new to server hosting. If you look at our [wiki](https://github.com/shavitush/bhoptimer/wiki/2.5.-Configuration:-Sounds) you can see what I mean by configuring sounds. Leaving the config empty will result in an exception.

Switching to a mysql database will most likely fix the zones not saving issue. The SQLite support in the timer is sparse at best.

**Comment by scrotumtotum** [comment]
Thank you, I will update when I have a MySQL database set up :)

**Comment by scrotumtotum** [comment]
How can I check if I have the MySQL Database up and running?

**Comment by scrotumtotum** [comment]
I believe I have the MySQL Database running and I am still having the issue with zones where they cannot be created.

**Comment by scrotumtotum** [comment]
This is my error logs now.
[errors_20200711.log](https://github.com/shavitush/bhoptimer/files/4906480/errors_20200711.log)

**Comment by kidfearless** [comment]
I haven't ever had to set up MySQL for a game server before so I'm not able to help you much now. You're missing your translation files still, re-read the wiki on the installation process for the timer.
shavit-core isn't able to be loaded cause of the following error: Timer startup failed. Reason: [2059]: Authentication plugin 'caching_sha2_password' cannot be loaded: The specified module could not be found.

**Comment by Nairdaa** [comment]
> 
> 
> How can I check if I have the MySQL Database up and running?

> mysql -v
in console

**Comment by scrotumtotum** [comment]
Ok, since I want to rule out it being an issue with bhoptimer, I am going to reinstall the plugin twice, the first time I will use the ZIP in releases, the second time I will use the source code from releases and if neither of those work I will use bhopmaster zip.

**Comment by Nairdaa** [comment]
Sourcecode won't work, you need to compile it first and I guess you've no idea how.

**Comment by scrotumtotum** [comment]
With the compiler provided with sourcemod yes? If so, then I have got it to work, and for an update when using the sourcecode, the confirmation menu now pops up when creating the start and end zones but, they disappear the moment you confirm if this is intended either way when you go to make the end zone and finalize the confirmation for that as well the zones do not reappear.

**Comment by Nairdaa** [comment]
That means you don't have a working database.

**Comment by scrotumtotum** [comment]
L 07/11/2020 - 07:55:09: [shavit-zones.smx] Timer (zone refresh) SQL query failed. Reason: no such column: flags

**Comment by scrotumtotum** [comment]
The previous error is on server launch, I get the below error when zones are attempted to be made.

L 07/11/2020 - 07:56:10: [shavit-zones.smx] Timer (zone insert) SQL query failed. Reason: table mapzones has no column named flags

**Comment by kidfearless** [comment]
> L 07/11/2020 - 07:55:09: [shavit-zones.smx] Timer (zone refresh) SQL query failed. Reason: no such column: flags

> - this is fine. the error happens because the zones plugin has no way of knowing if the migration has happened already or not. it should go away right after finishing the migration

**Comment by kidfearless** [comment]
If the problem persists though let us know.

**Comment by scrotumtotum** [comment]
Yea, everytime someone tries to make a new zone this appears in console. 

L 07/11/2020 - 07:56:10: [shavit-zones.smx] Timer (zone insert) SQL query failed. Reason: table mapzones has no column named flags

**Comment by kidfearless** [comment]
Make sure that the user you gave to the timer has permission to alter the database.

**Comment by scrotumtotum** [comment]
If I had to guess this means that I installed the MySQL Database wrong most likely which is gonna be real tough for me since I have no idea how to install it. May as well just say what my setup is since I am almost certain at this point that I am missing something big. I have literally no experience with this so any insight is helpful honestly. I have a MySQL database hosted through AWS and I am connected to it through MySQL Workbench, after that I went to database.cfg and put in the relevant information to change the "default" to "MySQL" that is about all I know how to do, if there is some tutorial I could follow for missing steps that would be great. 

> Make sure that the user you gave to the timer has permission to alter the database.

Not sure if this is really proof but said user deleted a replay that was stored as a test. This replay was stored on my PC though.

This MySQL thing has really been a learning process and while I have a database up and I can connect to it I have no clue what to do after that really.

**Comment by Nairdaa** [comment]
https://github.com/shavitush/bhoptimer/wiki/2.1.-Configuration:-Database

**Comment by scrotumtotum** [comment]
Now when I connect to the server I cannot move and I get this error repeated in console. 

L 07/11/2020 - 08:18:16: [SM] Blaming: shavit-hud.smx
L 07/11/2020 - 08:18:16: [SM] Call stack trace:
L 07/11/2020 - 08:18:16: [SM]   [0] Shavit_InsideZone
L 07/11/2020 - 08:18:16: [SM]   [1] Line 1387, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::UpdateMainHUD
L 07/11/2020 - 08:18:16: [SM]   [2] Line 878, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::TriggerHUDUpdate
L 07/11/2020 - 08:18:16: [SM]   [3] Line 870, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::Cron
L 07/11/2020 - 08:18:16: [SM]   [4] Line 770, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::OnGameFrame
L 07/11/2020 - 08:18:16: [SM] Exception reported: Native is not bound

**Comment by scrotumtotum** [comment]
Also there are no longer timer settings in the admin menu.

**Comment by Nairdaa** [comment]
Are you compiling it with SM 1.11?

**Comment by scrotumtotum** [comment]
I am using the latest stable build 1.10

**Comment by scrotumtotum** [comment]
This is what I added to my database.cfg file, changed nothing else in it.

	"shavit"
	{
		"driver"	"mysql"
		"host"		"[MYSQLDOMAIN]"
		"database"	"bhoptimer"
		"user"		"shavit"
		"pass"		"123_My_Safe_Password_#@!"
	}

This might not be an issue but the default in the database.cfg is this for me since I changed it.

	"default"
	{
		"driver"			"mysql"
		"host"				"[MYSQLDOMAIN]"
		"database"			"[DBNAME]"
		"user"				"[MASTERUSER]"
		"pass"				"[MASTERPASS]"
		//"timeout"			"0"
		//"port"			"0"
	}
Everything in brackets is information that I removed as it is somewhat personal.

**Comment by Nairdaa** [comment]
> "[MYSQLDOMAIN]"


I that an IP or actual domain? Linux somehow fucks up and you gotta use the ip instead of domain name.

**Comment by scrotumtotum** [comment]
I am using windows and it is a website.

**Comment by Nairdaa** [comment]
It could also be that the mysql host that you're trying to connect to denies external connections due to security reasons.

**Comment by scrotumtotum** [comment]
I looked through the settings on the page hosting the database and that does not seem to be an issue this is what it had to say about public access.

EC2 instances and devices outside of the VPC hosting the DB instance will connect to the DB instances. You must also select one or more VPC security groups that specify which EC2 instances and devices can connect to the DB instance.

**Comment by Nairdaa** [comment]
I don't know then. Shit host XD

**Comment by scrotumtotum** [comment]
I just checked and adding the below text to the databases.cfg breaks the game whether or not the databases is default or not. What I mean by that is that me editing the "default" has no effect on the error.

"shavit"
{
	"driver"	"mysql"
	"host"		"[MYSQLDOMAIN]"
	"database"	"bhoptimer"
	"user"		"shavit"
	"pass"		"123_My_Safe_Password_#@!"
}

This results in this:

L 07/11/2020 - 08:18:16: [SM] Blaming: shavit-hud.smx
L 07/11/2020 - 08:18:16: [SM] Call stack trace:
L 07/11/2020 - 08:18:16: [SM] [0] Shavit_InsideZone
L 07/11/2020 - 08:18:16: [SM] [1] Line 1387, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::UpdateMainHUD
L 07/11/2020 - 08:18:16: [SM] [2] Line 878, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::TriggerHUDUpdate
L 07/11/2020 - 08:18:16: [SM] [3] Line 870, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::Cron
L 07/11/2020 - 08:18:16: [SM] [4] Line 770, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::OnGameFrame
L 07/11/2020 - 08:18:16: [SM] Exception reported: Native is not bound

If it really is a MySQL error then I will have to learn how to set it up properly as I suspect I have messed up something. Not 100% on this but my host is AWS which is an amazon service, while it is free I think it is more likely the problem is on my side.

**Comment by Nairdaa** [comment]
It's not a MySQL error. Can you check if all the plugins are loaded fine?

> rcon sm plugins list

**Comment by Nairdaa** [comment]
It looks like some of the timer's dependencies are not loading fine.

**Comment by scrotumtotum** [comment]
[SM] Listing 35 plugins:
  01 "Admin File Reader" (1.10.0.6490) by AlliedModders LLC
  02 "SQL Admins (Prefetch)" (1.10.0.6490) by AlliedModders LLC
  03 "Admin Help" (1.10.0.6490) by AlliedModders LLC
  04 "Admin Menu" (1.10.0.6490) by AlliedModders LLC
  05 "Anti-Flash" (1.2) by FrozDark (HLModders LLC)
  06 "Anti-Flood" (1.10.0.6490) by AlliedModders LLC
  07 "Basic Ban Commands" (1.10.0.6490) by AlliedModders LLC
  08 "Basic Chat" (1.10.0.6490) by AlliedModders LLC
  09 "Basic Comm Control" (1.10.0.6490) by AlliedModders LLC
  10 "Basic Commands" (1.10.0.6490) by AlliedModders LLC
  11 "Basic Info Triggers" (1.10.0.6490) by AlliedModders LLC
  12 "Basic Votes" (1.10.0.6490) by AlliedModders LLC
  13 "Client Preferences" (1.10.0.6490) by AlliedModders LLC
  14 "cPMod" (2.1.0) by byaaaaah
  15 "CSS Anti Team Flash" (1.2.3) by Twisted|Panda (Orig: SAMURAI16/Kigen)
  16 "Fun Commands" (1.10.0.6490) by AlliedModders LLC
  17 "Fun Votes" (1.10.0.6490) by AlliedModders LLC
  18 "Nextmap" (1.10.0.6490) by AlliedModders LLC
  19 "Player Commands" (1.10.0.6490) by AlliedModders LLC
  20 "Reserved Slots" (1.10.0.6490) by AlliedModders LLC
  21 <Error> "[shavit] Chat Processor" (2.5.7a) by shavit
  22 <Error> "[shavit] Core" (2.5.7a) by shavit
  23 "[shavit] HUD" (2.5.7a) by shavit
  24 "[shavit] Miscellaneous" (2.5.7a) by shavit
  25 <Error> "[shavit] Rankings" (2.5.7a) by shavit
  26 <Error> "[shavit] Replay Bot" (2.5.7a) by shavit
  27 <Failed> "[shavit] Sounds" (2.5.7a) by shavit
  28 <Error> "[shavit] Player Stats" (2.5.7a) by shavit
  29 <Error> "[shavit] Dynamic Timelimits" (2.5.7a) by shavit
  30 <Failed> "[shavit] World Records" (2.5.7a) by shavit
  31 <Failed> "[shavit] Map Zones" (2.5.7a) by shavit
  32 "Sound Commands" (1.10.0.6490) by AlliedModders LLC
  33 "SQL Admin Manager" (1.10.0.6490) by AlliedModders LLC
  34 "Trikz (Redux)" (1.8.0) by shavit
  35 "Player Whitelist" (1.1) by Stevo.TVR
Errors:
shavit-chat.smx ([shavit] Chat Processor): Error detected in plugin startup (see error logs)
shavit-core.smx ([shavit] Core): Error detected in plugin startup (see error logs)
shavit-rankings.smx ([shavit] Rankings): Error detected in plugin startup (see error logs)
shavit-replay.smx ([shavit] Replay Bot): Error detected in plugin startup (see error logs)
shavit-sounds.smx ([shavit] Sounds): shavit-wr is required for the plugin to work.
shavit-stats.smx ([shavit] Player Stats): Error detected in plugin startup (see error logs)
shavit-timelimit.smx ([shavit] Dynamic Timelimits): Error detected in plugin startup (see error logs)
shavit-wr.smx ([shavit] World Records): Native "Shavit_LogMessage" was not found
shavit-zones.smx ([shavit] Map Zones): Native "Shavit_LogMessage" was not found

**Comment by Nairdaa** [comment]
Check error logs why exactly it doesnt load

sob., 11 lip 2020, 18:02 użytkownik scrotumtotum <notifications@github.com>
napisał:

**Comment by scrotumtotum** [comment]
My error logs are just this over and over again.

L 07/11/2020 - 08:18:16: [SM] Blaming: shavit-hud.smx
L 07/11/2020 - 08:18:16: [SM] Call stack trace:
L 07/11/2020 - 08:18:16: [SM] [0] Shavit_InsideZone
L 07/11/2020 - 08:18:16: [SM] [1] Line 1387, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::UpdateMainHUD
L 07/11/2020 - 08:18:16: [SM] [2] Line 878, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::TriggerHUDUpdate
L 07/11/2020 - 08:18:16: [SM] [3] Line 870, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::Cron
L 07/11/2020 - 08:18:16: [SM] [4] Line 770, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::OnGameFrame
L 07/11/2020 - 08:18:16: [SM] Exception reported: Native is not bound

**Comment by Nairdaa** [comment]
There must be a reason why the plugins didnt load on server lauch. Check
console log

sob., 11 lip 2020, 18:08 użytkownik scrotumtotum <notifications@github.com>
napisał:

**Comment by Nairdaa** [comment]
Ill be back home in 5 mins, I can try via teamviewer

sob., 11 lip 2020, 18:10 użytkownik Adrian Grzechowiak <voytassss@gmail.com>
napisał:

**Comment by scrotumtotum** [comment]
Nevermind I have found other things that I will post,
L 07/11/2020 - 09:09:31: [SM] Blaming: shavit-hud.smx
L 07/11/2020 - 09:09:31: [SM] Call stack trace:
L 07/11/2020 - 09:09:31: [SM]   [0] Shavit_InsideZone
L 07/11/2020 - 09:09:31: [SM]   [1] Line 1387, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::UpdateMainHUD
L 07/11/2020 - 09:09:31: [SM]   [2] Line 878, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::TriggerHUDUpdate
L 07/11/2020 - 09:09:31: [SM]   [3] Line 870, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::Cron
L 07/11/2020 - 09:09:31: [SM]   [4] Line 770, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-hud.sp::OnGameFrame
L 07/11/2020 - 09:09:31: [SM] Exception reported: Native is not bound
L 07/11/2020 - 09:09:31: [SM] Blaming: shavit-misc.smx
L 07/11/2020 - 09:09:31: [SM] Call stack trace:
L 07/11/2020 - 09:09:31: [SM]   [0] Shavit_GetClientPB
L 07/11/2020 - 09:09:31: [SM]   [1] Line 884, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-misc.sp::UpdateScoreboard
L 07/11/2020 - 09:09:31: [SM]   [2] Line 815, C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\scripting\shavit-misc.sp::Timer_Scoreboard
L 07/11/2020 - 09:09:31: [SM] Exception reported: Native is not bound

The txt is too big to attach.

**Comment by Nairdaa** [comment]
Pome me in DM on shavit's discord.

**Comment by kidfearless** [comment]
Issue was with his databases.cfg. Thanks @Nairdaa for helping resolve this.

**Comment by scrotumtotum** [comment]
Zones can now be opened which is great but now setting a server record crashes the server.

L 07/11/2020 - 09:30:16: Info (map "de_kombu") (file "C:\Users\Dido Admin\Desktop\CSSSERVER\steamapps\common\Counter-Strike Source Dedicated Server\cstrike\addons\sourcemod\logs\errors_20200711.log")
L 07/11/2020 - 09:30:16: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 07/11/2020 - 09:30:16: [SM] Blaming: cPMod.smx
L 07/11/2020 - 09:30:16: [SM] Call stack trace:
L 07/11/2020 - 09:30:16: [SM]   [0] SQL_TQuery
L 07/11/2020 - 09:30:16: [SM]   [1] Line 666, cPMod/sql.sp::db_selectMapStartStop
L 07/11/2020 - 09:30:16: [SM]   [2] Line 530, C:\Users\rivu\Documents\cPMod\sourcemod\scripting\cPMod.sp::OnMapStart
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:16: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:17: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 09:30:29: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 07/11/2020 - 09:30:29: [SM] Blaming: cPMod.smx
L 07/11/2020 - 09:30:29: [SM] Call stack trace:
L 07/11/2020 - 09:30:29: [SM]   [0] SQL_TQuery
L 07/11/2020 - 09:30:29: [SM]   [1] Line 734, cPMod/sql.sp::db_selectPlayerCheckpoint
L 07/11/2020 - 09:30:29: [SM]   [2] Line 742, C:\Users\rivu\Documents\cPMod\sourcemod\scripting\cPMod.sp::OnClientPostAdminCheck
L 07/11/2020 - 09:52:56: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 07/11/2020 - 09:52:56: [SM] Blaming: cPMod.smx
L 07/11/2020 - 09:52:56: [SM] Call stack trace:
L 07/11/2020 - 09:52:56: [SM]   [0] SQL_TQuery
L 07/11/2020 - 09:52:56: [SM]   [1] Line 734, cPMod/sql.sp::db_selectPlayerCheckpoint
L 07/11/2020 - 09:52:56: [SM]   [2] Line 742, C:\Users\rivu\Documents\cPMod\sourcemod\scripting\cPMod.sp::OnClientPostAdminCheck
L 07/11/2020 - 09:53:19: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist

**Comment by Nairdaa** [comment]
Ill tell you what query to run on mysql to fix it. Walking doggo atm.

sob., 11 lip 2020, 18:58 użytkownik scrotumtotum <notifications@github.com>
napisał:

**Comment by scrotumtotum** [comment]
Tried to relaunch server (did it through console so that might be the issue but here is the accelerator link) https://crash.limetech.org/2qile76lcvrw

And here is the console as that was happening:

L 07/11/2020 - 10:00:59: [shavit-rankings.smx] Timer (rankings, CREATE GetWeightedPoints) error! Reason: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
L 07/11/2020 - 10:00:59: [shavit-rankings.smx] Timer (rankings, CREATE GetRecordPoints) error! Reason: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
L 07/11/2020 - 10:01:00: "Normal - 0.000<3><BOT><CT>" changed name to "!replay"
L 07/11/2020 - 10:01:00: server_cvar: "mp_timelimit" "60"
L 07/11/2020 - 10:01:00: server_cvar: "mp_roundtime" "60"
Setting CBaseEntity to non-brush model models/props/cs_office/vending_machine.mdl
Setting CBaseEntity to non-brush model models/props/cs_office/vending_machine.mdl
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: FUNCTION totumdb.GetRecordPoints does not exist
L 07/11/2020 - 10:01:00: [shavit-rankings.smx] Timer (rankings, update all points) error! Reason: FUNCTION totumdb.GetWeightedPoints does not exist
Setting CBaseEntity to non-brush model models/props/cs_office/vending_machine.mdl
Setting CBaseEntity to non-brush model models/props/cs_office/vending_machine.mdl
L 07/11/2020 - 10:01:04: World triggered "Round_Start"
L 07/11/2020 - 10:01:07: [CRASH] Accelerator uploaded crash dump: Crash ID: 2QIL-E76L-CVRW
Accelerator upload thread finished. (0 skipped, 1 uploaded, 0 failed)
Accelerator upload thread terminated. (canceled = false)

**Comment by scrotumtotum** [comment]
Alright, it is all good

**Comment by kidfearless** [comment]
make sure your database user can create functions
