### ISSUE TITLE
Can't load the plugin

### ISSUE THREAD

**Issue by kaan36875** [shavitush/bhoptimer#937]
I download all files on my server but plugins don't load. I have sourcemod 1.11 .

**Comment by Nairdaa** [comment]
Thank you for your exhaustive statement. Wypierdalaj.

**Comment by kaan36875** [comment]
https://pastebin.com/qerRCrJD

**Comment by kaan36875** [comment]
> Thank you for your exhaustive statement. Wypierdalaj.

I found this https://pastebin.com/qerRCrJD

**Comment by kidfearless** [comment]
> [SM] Exception reported: Cannot open "configs/shavit-prefix.txt". Make sure this file exists and that the server has read permissions to it.

Seems pretty self explanatory. Be sure to read the GitHub wiki on installing the timer

**Comment by Nairdaa** [comment]
i'm sorry what's "ohp_shavit-core.smx"?
