### ISSUE TITLE
Godmode is not working. Is there a way to block team?

### ISSUE THREAD

**Issue by kaan36875** [shavitush/bhoptimer#940]
shavit_misc_godmode "2" not working. So is there way to block team by maps.

**Comment by someunknownguy** [comment]
you can force mp_humanteam to the team you wish, however i found that removing that -> https://prnt.sc/tktkia
and replacing it with `return Plugin_Handled;` makes it so you can no longer bypass map's limitations on teams (so on gamemodes like mg you can only join the team with pre-existing spawn locations). If you're having problems with maps where the mapper didn't think to limit teams you might just want to enable true godmode?

**Comment by kidfearless** [comment]
You aren't by chance unloading the timer on certain maps are you?

**Comment by rtldg** [comment]
Blocking team damage by map or whatever you're trying to do is something a different plugin should do.
