### ISSUE TITLE
Points recalculation error for big databases

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#942]
Hello,

as long sm_recalcall works just fine on small MySQL databases, unfortunately it doesn't work on big ones anymore.

- Started recalculating points for all maps. Check console for output.

About 2 mins later:
L 07/26/2020 - 15:01:29: [shavit-rankings.smx] Timer (rankings) error! Recalculation failed. Reason: Lost connection to MySQL server during query

**Comment by Nairdaa** [comment]
Btw, I've had that since months.

**Comment by Nairdaa** [comment]
> - Started recalculating points for all maps. Check console for output.

rcon from "148.251.11.171:41272": command "sm_recalcall"

L 07/26/2020 - 15:07:02: [shavit-rankings.smx] Timer (rankings, recalculate map points) error! Reason: Lock wait timeout exceeded; try restarting transaction

**Comment by Nairdaa** [comment]
THANK YOU CARNIFEX

L 10/11/2020 - 00:13:36: [shavit-rankings.smx] Timer (rankings) error! Recalculation failed. Reason: Lock wait timeout exceeded; try restarting transaction


Okay, now I'm absolutely clueless. Changed sm's core cfg SlowScriptTimeout setting to 0, changed session timeout to 999999999 and it's still fucky.

**Comment by Nairdaa** [comment]
Solved and fixed by @rtldg

**Comment by sneak-it** [comment]
Was the solution to this PRd somewhere, or was this just a personal setup issue?

**Comment by rtldg** [comment]
Two things affected this:
- Some random change to the config in databases.cfg which stopped the connection timing out to the MySQL server. Something to do with swapping 127.0.0.1 & localhost as the host and hardcoding the port. IDK it didn't make sense how it fixed the timeout problem. @Nairdaa can you post whatever is your current db config for that (excluding password and such xd)?
- And a test branch I made to have the recalculating use a separate query for each style so hopefully it wouldn't timeout.
The branch is https://github.com/rtldg/bhoptimer/commits/split-recalcs but I kind of forgot about it so I'll see about making sure it's right and doing a PR soon

**Comment by Nairdaa** [comment]
Separate query for each style + actually setting the port to 3306 in the db cfg (even tho it's fucking default) for shavit's timer is what fixed it.

Don't ask me why setting the port fixed it. Probably SM stuff, just like localhost vs 127.0.0.1 not working on linux somehow.


> 	{
> 		"driver"			"mysql"
> 		"host"				"127.0.0.1"
> 		"database"			"db_name"
> 		"user"				"db_user"
> 		"pass"				"db_pass"
> 		"port"				"3306"
> 	}

**Comment by Nairdaa** [comment]
Oh, also, setting timeout on the db at like 20 minutes, or 60 minutes, would eventually result with "L 07/26/2020 - 15:01:29: [shavit-rankings.smx] Timer (rankings) error! Recalculation failed. Reason: Lost connection to MySQL server during query" anyway.

Hardsetting the port + the above dividing each style in recalc into separate queries is what fixed it for linux. Probably works just fine on windows.

**Comment by rtldg** [comment]
this should be fine now with https://github.com/shavitush/bhoptimer/commit/dc9f39bdf31413a0084b0184e1488a6de1ae9fe4 / in very_good_yes / whenever there's a new release
