### ISSUE TITLE
[Suggestion] Dynamic HUD Channels

### ISSUE THREAD

**Issue by cytrus224** [shavitush/bhoptimer#943]
https://github.com/Vauff/DynamicChannels
![image](https://user-images.githubusercontent.com/17723060/88577766-d56a7280-d047-11ea-8f1c-5c741f74353b.png)

**Comment by rtldg** [comment]
Should be fine with https://github.com/shavitush/bhoptimer/commit/0caa746290355da811f3b2629799b35f38377798
Using plugin channel 5
