### ISSUE TITLE
Different Prespeeds for Different Styles

### ISSUE THREAD

**Issue by 1Noxstar** [shavitush/bhoptimer#954]
Allowing different styles to use different shavit_misc_prespeed settings. Not sure if it's possible but preferably a cvar in shavit-styles.cfg in the configs folder.

```
// Stop prespeeding in the start zone?
// 0 - Disabled, fully allow prespeeding.
// 1 - Limit relatively to prestrafelimit.
// 2 - Block bunnyhopping in startzone.
// 3 - Limit to prestrafelimit and block bunnyhopping.
// 4 - Limit to prestrafelimit but allow prespeeding. Combine with shavit_core_nozaxisspeed 1 for SourceCode timer's behavior.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "4.000000"
shavit_misc_prespeed "1"
```

**Comment by vv1sh** [comment]
How to let the speed of the empty hand, gun speed, according to the AD (AS) speed is different

**Comment by Nairdaa** [comment]
:thonk:

**Comment by NukoOoOoOoO** [comment]
@vv1sh 不会用英语说的话用中文讲。你是要没武器时的速度和有武器的不一样吗

**Comment by vv1sh** [comment]
> @vv1sh不会用英语说的话用中文讲。你是要没武器时的速度和有武器的不一样吗
好的哥，空手速度应该快一些，不知道咋改，还有地速拉不了

**Comment by NukoOoOoOoO** [comment]
要拉地速得装[这个插件](https://forums.alliedmods.net/showthread.php?t=255298), 然后把 sv_friction 和 sv_accelerate 的值分别改成4 和 5,同时 shavit_misc_staticprestrafe 的值要为 1

**Comment by rtldg** [comment]
I added some style settings to allow for different prespeed settings on different styles. https://github.com/shavitush/bhoptimer/commit/396f2017c5beef679938a0fc0512d2b50637e58a
Check out `prespeed_type`, `blockprejump`, `nozaxisspeed`, and `restrictnoclip` in [configs/shavit-styles.cfg](https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/configs/shavit-styles.cfg)
