### ISSUE TITLE
Replay bot don't die

### ISSUE THREAD

**Issue by kaan36875** [shavitush/bhoptimer#959]
Is there way disable replay bot's godmode?

**Comment by deadw1nter** [comment]
remove both of these lines
https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/shavit-replay.sp#L1530
https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/shavit-replay.sp#L1742

**Comment by kaan36875** [comment]
It worked. Thanks.

**Comment by rtldg** [comment]
> remove both of these lines https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/shavit-replay.sp#L1530 https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/shavit-replay.sp#L1742

github has a [bug](https://github.community/t/unable-to-edit-or-unhide-comment-by-closed-acc-on-issue/162575/6) that doesn't let me edit comments by deleted users so here's permalinks to those

https://github.com/shavitush/bhoptimer/blob/7567cde52df2adf0461984db72fb60531c331f8e/addons/sourcemod/scripting/shavit-replay.sp#L1530
https://github.com/shavitush/bhoptimer/blob/7567cde52df2adf0461984db72fb60531c331f8e/addons/sourcemod/scripting/shavit-replay.sp#L1742
