### ISSUE TITLE
[ Request ] map zone beams

### ISSUE THREAD

**Issue by Nairdaa** [shavitush/bhoptimer#978]
https://github.com/shavitush/bhoptimer/blob/very_good_yes/addons/sourcemod/configs/shavit-zones.cfg

Please make it so that you can define a zone beam material for different zones. I'm currently using "ULTIMA" custom material for zones (start/end) but creating a custom zone like freestyle makes it look ultra gay.

![image](https://user-images.githubusercontent.com/38843773/97096984-2fd99600-166c-11eb-89df-96265fa049fe.png)

Something like

```
		"Freestyle"
		{
			"visible"	"1"
			
			"red"		"25"
			"green"		"25"
			"blue"		"255"
			
			"alpha"		"195"
			"width"		"0.5"

			"custom_sprite" "0"
		}
```

And that way drawing the default shavit's one instead. Hope I made it all clear ;p

**Comment by Nairdaa** [comment]
Parsing is fucked on git, can't help it.

**Comment by Nairdaa** [comment]
fucking misclicked

**Comment by Nairdaa** [comment]
Why did it get closed without response?

**Comment by kidfearless** [comment]
Thought this was an old one that was accidentally reopened

**Comment by rtldg** [comment]
you can use `"beam" "somethingelse.vmt"` (or `"vanilla_sprite" "1"` for non-custom beams) now with https://github.com/shavitush/bhoptimer/commit/f9825f8ca112229f3bbb8762c2fe4fa908f7f79a
minimal testing went into that so let me know if things break :sunglasses:
