### ISSUE TITLE
Invalid parameter number: 3

### ISSUE THREAD

**Issue by Septembers** [shavitush/bhoptimer#981]
Hello, i am using version 2.5.7a
does my error come from shavit-zones or ssj?
L 10/31/2020 - 19:07:36: [SM] Exception reported: Invalid parameter number: 3
L 10/31/2020 - 19:07:36: [SM] Blaming: shavit/shavit-zones.smx
L 10/31/2020 - 19:07:36: [SM] Call stack trace:
L 10/31/2020 - 19:07:36: [SM]   [0] GetNativeCell
L 10/31/2020 - 19:07:36: [SM]   [1] Line 466, C:\Users\September\Desktop\COMPILE 1.10\shavit-zones.sp::Native_InsideZone
L 10/31/2020 - 19:07:36: [SM]   [3] Shavit_InsideZone
L 10/31/2020 - 19:07:36: [SM]   [4] Line 412, C:\Users\September-PC\Desktop\COMPILE 1.10\ssj.sp::OnPlayerRunCmd

how can this be fixed?

**Comment by Nairdaa** [comment]
upload that ssj.sp here

**Comment by kidfearless** [comment]
This error is a safety check added for differing versions of the includes. Recompile the plugin using includes from the version of the timer that you are using and it should resolve itself.
