### ISSUE TITLE
I have a bag when open Check Points Menu

### ISSUE THREAD

**Issue by sojio12** [shavitush/bhoptimer#985]
L 11/12/2020 - 20:33:14: [SM] Exception reported: Invalid Handle 0 (error: 4)
L 11/12/2020 - 20:33:14: [SM] Blaming: shavit-misc.smx
L 11/12/2020 - 20:33:14: [SM] Call stack trace:
L 11/12/2020 - 20:33:14: [SM] [0] ArrayList.Length.get
L 11/12/2020 - 20:33:14: [SM] [1] Line 1966, shavit-misc.sp::OpenNormalCPMenu
L 11/12/2020 - 20:33:14: [SM] [2] Line 1814, shavit-misc.sp::OpenCheckpointsMenu
L 11/12/2020 - 20:33:14: [SM] [3] Line 470, shavit-misc.sp::Shavit_OnStyleChanged
L 11/12/2020 - 20:33:14: [SM] [5] Call_Finish
L 11/12/2020 - 20:33:14: [SM] [6] Line 1199, shavit-core.sp::CallOnStyleChanged
L 11/12/2020 - 20:33:14: [SM] [7] Line 2154, shavit-core.sp::OnClientCookiesCached
L 11/12/2020 - 20:33:14: [SM] [8] Line 2183, shavit-core.sp::OnClientPutInServer
L 11/12/2020 - 20:39:12: Error log file session closed.

I am using a version of very_good_yes 2.6.0

**Comment by deadw1nter** [comment]
It seems like the arraylist isn't initialized, make sure you are running on a dedicated server, not listening one.

**Comment by kidfearless** [comment]
Are you unloading and reloading the timer while the server is running?

**Comment by GAMMACASE** [comment]
Happened to me right now on map change.
