### ISSUE TITLE
[question] Unreal style removed shotgun or is it a bug?

### ISSUE THREAD

**Issue by SueKabliat** [shavitush/bhoptimer#991]
note: I'm not the server hoster or owner so I'm not 100% sure if the required questions I answered are accurate but I think it should be right

**The game your server is running?**
CS:GO

**Are you using the latest Steam version of the game?**
Yes

**What's the operating system of your game server?**
Linux

**Are you running the latest stable builds of SourceMod?**
Yes

**What behavior were you expecting, and what's the actual behavior?**
Basically, the server just updated the timer after almost a year of no updates. In the old version, when playing UNREAL style, there was a mag7 that you could shoot to get a boost (worked with glock too). In the new update, the mag7 is no longer present and the glock doesnt give a boost anymore. Double jumping and double tapping w still works. 

Was wondering, was the shotgun boost feature removed or is it a server side bug? Thanks in advance 👍

**Comment by kidfearless** [comment]
There's been a lot of changes to the API in both the past year and since the unreal style was written. More than likely it's crashing right now and need to be recompiled to use the latest version of the timer

**Comment by rtldg** [comment]
Can't help if you're not the server owner with logs/errors. I have unreal working for the timer over here https://github.com/rtldg/unrealphys
As long as `/cstrike/cfg/sourcemod/unrealphys.cfg` (with `unrealphys_modified 1`) & `/cstrike/addons/sourcemod/configs/gunjump.cfg` are there it should work the same.
Tell the server owner to make an issue in https://github.com/rtldg/unrealphys if they need help with it
