### ISSUE TITLE
[CS:GO] Exception reported: Native is not bound

### ISSUE THREAD

**Issue by HybridVenom** [shavitush/bhoptimer#992]
Installed from source, using the latest commit and cant find anyone with the same problem. The server is a completely fresh one.

Latest CS:GO Steam version, Windows 10, latest STABLE builds of SourceMod and Metamod.

Expected behaviour: No exception on startup.
Shown behaviour: Exception spam causing high sv rate (i.e making it unplayable).

Currently using:
- Shavit (latest commit)
- DHooks 2.2
- MySQL as database driver

So far I've tried using `sqlite` and `mysql` as database drivers, none of them work.

This is the exception printed in the console:
```
L 12/05/2020 - 18:21:31: [SM] Exception reported: Native is not bound
L 12/05/2020 - 18:21:31: [SM] Blaming: shavit-hud.smx
L 12/05/2020 - 18:21:31: [SM] Call stack trace:
L 12/05/2020 - 18:21:31: [SM]   [0] Shavit_InsideZone
L 12/05/2020 - 18:21:31: [SM]   [1] Line 1427, C:\csgo-server\csgo\addons\sourcemod\scripting\shavit-hud.sp::UpdateMainHUD
L 12/05/2020 - 18:21:31: [SM]   [2] Line 918, C:\csgo-server\csgo\addons\sourcemod\scripting\shavit-hud.sp::TriggerHUDUpdate
L 12/05/2020 - 18:21:31: [SM]   [3] Line 910, C:\csgo-server\csgo\addons\sourcemod\scripting\shavit-hud.sp::Cron
L 12/05/2020 - 18:21:31: [SM]   [4] Line 810, C:\csgo-server\csgo\addons\sourcemod\scripting\shavit-hud.sp::OnGameFrame
```
[Latest .log file](https://github.com/shavitush/bhoptimer/files/5647535/l192_168_001_046_27015_202012051821_000.log)

Have I possibly done something wrong?

**Comment by HybridVenom** [comment]
Would like to add that none of the commands mentioned in the alliedmods thread work as if `shavit-core.smx`, `shavit-zones.smx`, etc., never loads.

**Comment by kidfearless** [comment]
> L 12/05/2020 - 18:18:11: [SM] Unable to load plugin "shavit-core.smx": Required extension "dhooks" file("dhooks.ext") not running
L 12/05/2020 - 18:18:11: [SM] Exception reported: MySQL is the only supported database engine for shavit-rankings.
L 12/05/2020 - 18:18:11: [SM] Blaming: shavit-rankings.smx
L 12/05/2020 - 18:18:11: [SM] Call stack trace:
L 12/05/2020 - 18:18:11: [SM]   [0] SetFailState
L 12/05/2020 - 18:18:11: [SM]   [1] Line 217, C:\csgo-server\csgo\addons\sourcemod\scripting\shavit-rankings.sp::SQL_DBConnect
L 12/05/2020 - 18:18:11: [SM]   [2] Line 167, C:\csgo-server\csgo\addons\sourcemod\scripting\shavit-rankings.sp::OnPluginStart

dhooks wasn't loaded and so shavit-core couldn't be loaded. Try using this version of dhooks
https://github.com/peace-maker/DHooks2/releases

**Comment by HybridVenom** [comment]
Got it working :)

Changed back to running `sqlite` and switching to [DHooks2](https://github.com/peace-maker/DHooks2/releases) for SourceMod 1.10!

Damn you're fast at responding, didnt even get to close the thread and comment ^^

Great plugin btw!
