### ISSUE TITLE
Use velocity on practice is missing in CSGO

### ISSUE THREAD

**Issue by GAMMACASE** [shavitush/bhoptimer#994]
``Use velocity`` button on practice checkpoint menu is missing due to recently added ``Delete current checkpoint`` button as CSGO only supports 9 keys. (The position of ``Delete current checkpoint`` was changed by me intentionally, doesn't have anything to do with this issue tho)
![image](https://user-images.githubusercontent.com/31375974/101302424-9e556a80-384c-11eb-842f-f89ee2489a95.png)

**Comment by Nairdaa** [comment]
Uninstall CSGO and problem is solved.

**Comment by Nairdaa** [comment]
https://github.com/shavitush/bhoptimer/pull/995/files

**Comment by GAMMACASE** [comment]
This wont do anything.

**Comment by kidfearless** [comment]
fixed in #995
