### ISSUE TITLE
Issue with points

### ISSUE THREAD

**Issue by Nikolaj304** [shavitush/bhoptimer#999]
I've been noticing an issue with the points system. When I complete maps, and look at the amount of points I got from them by doing !top, it's different from what I actually get.
I just completed a map and saw I got 169 points from it, but my score went from 7516 to 7533, which I cant understand.

**Comment by GAMMACASE** [comment]
Comments in here describes the ranking system pretty well https://github.com/shavitush/bhoptimer/blob/master/addons/sourcemod/scripting/shavit-rankings.sp#L21-L31

**Comment by kidfearless** [comment]
It's definitely intentional so that top players are the ones with the most records and not the most times. If you'd like your points to match up like that you can change `shavit_rankings_weighting` to 1.
